"use strict";

window.arrLang = window.arrLang || {};
window.arrLang["en"] = {
    'nav-link-01': 'What is #MetaHash?',
    'nav-link-02': 'Buy #MHC',
    'nav-link-03': '<a href="https://static.metahash.org/docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper link -link-white"><img src="img/icon_file.svg" class="icon_file"> White Paper</a>',
    'nav-link-04': '<a href="https://static.metahash.org/docs/MetaHash_OnePager_EN.pdf" target="_blank" class="download-one-pager link -link-white"><img src="img/icon_file.svg" class="icon_file"> One-Pager</a>',
    'nav-link-05': 'FAQ',
    'nav-link-06': 'Support',
    'nav-link-07': 'Contact us',

    'promo-nav-download': '<a href="https://github.com/metahashorg/YellowPaper/raw/master/MetaHash_YellowPaper_EN.pdf">Download Yellow Paper</a>',

    'promo-01': 'fast',
    'promo-02': 'validation rate <b>under 3 seconds</b>. Performance is <b>over 50,000 TPS</b>',
    'promo-03': 'secure',
    'promo-04': 'protected by <b>5 different consensus algorithms</b>',
    'promo-05': 'decentralized',
    'promo-06': '<b>anyone can add transaction nodes</b> to the #MetaHash network',


    'descr-01': 'based on Blockchain 2.0',
    'descr-02': '<span class="cripto-title -title-part01 --eng">crypto</span><span class="cripto-title -title-part02 --eng">currency</span>',
    'descr-03': 'and decentralized ecosystem',
    'descr-04': 'based on Blockchain 2.0',


    'promo-appint-01': '<span class="part-name">for&nbsp;</span>storage',
    'promo-appint-03': 'of any information in Blockchain with <b>4k crypto protection</b> and <b>multi-signature</b>',
    'promo-appint-04': '<a href="#private-round" class="btn -default">ICO Round A<i class="icon icon_link"></i></a>',
    'promo-appint-05': 'transactions<span class="part-name">&nbsp;</span>',
    'promo-appint-06': '<b>up to 3 seconds to approve</b> inside the #MetaHash network and outside it',
    'promo-appint-07': '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">Download White Paper<i class="icon icon_dowload"></i></a>',
    'promo-appint-08': 'exchange<span class="part-name">&nbsp;of any asset</span>',
    'promo-appint-10': '<b>all digital assets</b> in the #MetaGate wallet use the <b>ERC20 token</b> in all exchange services',
    'promo-appint-11': '<a href="docs/MetaHash_OnePager_EN.pdf" target="_blank" class="download-one-pager btn -download">Download One-Pager<i class="icon icon_dowload"></i></a>',
    'promo-appint-12': '<a href="#private-round" class="btn -default -mega" >ICO Round A</a>',
    'promo-appint-13': '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">White Paper</a>',
    'promo-appint-14': '<a href="docs/MetaHash_OnePager_EN.pdf" target="_blank" class="download-one-pager btn -download float-right">One-Pager</a>',
    'promo-appint-15': 'Download #MetaGate client',

    'whatis-01': 'What is #MetaHash?',
    'whatis-02': '#MetaHash is a next-generation network based on the Blockchain 2.0 technology for sharing digital assets and a platform for creating and managing decentralized apps and services in real-time',
    'whatis-03': 'Four components of the system:',
    'whatis-04': '#TraceChain',
    'whatis-05': 'The fastest and most secure Blockchain',
    'whatis-06': 'More than five <b>billion transactions per day</b>, no more than three seconds to validate a transaction',
    'whatis-07': 'About #TraceChain',
    'whatis-08': '#MetaApps',
    'whatis-09': 'New generation of Smart Contracts',
    'whatis-10': '<b>Decentralized real-time applications</b> that are operated like regular web services and developed with the help of any programming language including C ++, PHP, Solidity and others',
    'whatis-11': 'About #MetaApps',
    'whatis-12': '#MetaGate',
    'whatis-13': 'Decentralized Internet',
    'whatis-14': "Decentralized apps directory and a <b>multi-asset wallet</b> that won't overload your computer",
    'whatis-15': 'About #MetaGate',
    'whatis-16': '#MetaHashCoin',
    'whatis-17': '#MetaHash network exchange asset',
    'whatis-18': '<b>#MetaHashCoin</b> is used to ensure the reliability of the network, exchange services and regulate its self-financing and development',
    'whatis-19': 'About #MHC',


    'tracechain-01': '#TraceChain',
    'tracechain-02': 'Fast and secure Blockchain 2.0',
    'tracechain-03': 'More than',
    'tracechain-04': '100,000',
    'tracechain-05': 'transactions per second on each node',
    'tracechain-06': '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download lang" >Download White Paper<i class="icon icon_dowload"></i></a>',
    'tracechain-07': 'to approve a transaction',
    'tracechain-08': 'transactions per day',
    'tracechain-09': 'stages of consensus for verification',
    'tracechain-10': '#MetaHash block anchors <span class="blue">in Bitcoin and Ethereum networks</span>',
    'tracechain-11': '<img class="tracechain-svg" src="img/graphical/tracechain-en.svg" alt="">',


    'speed-work-01': 'Unprecedented speed and decentralization of the #TraceChain network make #MetaHash the flagship of Blockchain',
    'speed-work-02': 'Complete any amount of transactions in the <b>#MetaHash</b> network',
    'speed-work-03': 'Transaction cost is lower than in any regular Blockchain',
    'speed-work-04': 'Reasonable data storage cost with <b>#TraceChain</b> for decentralized projects',
    'speed-work-05': 'Any asset can be tokenized into <b>#MetaHashCoin</b> to circulate in #MetaHash, Ethereum and other networks',


    'speeds-01': 'How did we attain such swiftness?',
    'speeds-02': 'Transactions begin at the outer radius and then run into the core network using the fastest route.',
    'speeds-03': 'Each stage approves a transaction on its way to the core.',
    'speeds-04': 'The fastest nodes of the core network synchronize transactions between themselves.',
    'speeds-05': 'Core network returns the balance of the wallets to the network, which verifies the correctness of the calculations.',
    'speeds-06': 'Backup data goes into the classic Blockchain, verifying network integrity.',
    'speeds-07': 'Anchors (hash from the longest chain of blocks) are stored on the Bitcoin, Ethereum and other networks.',
    'speeds-08': 'You cannot corrupt or modify the information stored in #MetaHash. To do so, it would be necessary to successfully attack the #MetaHash network as well as Bitcoin, Ethereum and other networks.',
    'speeds-09': 'Check our White Paper for more technical details',
    'speeds-10': '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">Download White Paper<i class="icon icon_dowload"></i></a>',


    'metaapps-01': '#MetaApps',
    'metaapps-02': 'Cloud service for smart real-time applications',
    'metaapps-03': '#MetaApps is an evolution of Smart Contracts and can be used to decentralize any service. These are independent programs that can exist forever and do not belong to anyone. They work exactly as programmed and cannot be tampered with by third parties.',
    'metaapps-04': '#MetaApps advantages',
    'metaapps-05': 'Run in real-time',
    'metaapps-06': 'As fast as regular web services and applications',
    'metaapps-07': 'Any GUI design',
    'metaapps-08': 'Can look like ordinary applications or webpages',
    'metaapps-09': 'Security',
    'metaapps-10': "No one can change the application's behavior bypassing the update rules",
    'metaapps-11': 'Program and operation system’s image uploads onto the network and starts automatically on numerous computers.',
    'metaapps-12': 'Are created in any programming language including C ++ PHP, Solidity and others.',
    'metaapps-13': 'Full support of Smart Contracts functionality, can work with any Blockchain or just with data from the internet.',


    'metagate-01': '#MetaGate',
    'metagate-02': 'Gateway to the decentralized internet',
    'metagate-03': '#MetaGate is an open source program, so all developers can embed parts of its code into their applications and browsers.',
    'metagate-04': 'Multi-asset wallet',
    'metagate-05': 'The wallet supports "light mode" without downloading the entire Blockchain. Data comes from different sources of the decentralized network and is checked by the user. Private keys from all Blockchains used will be stored only by the user.',
    'metagate-06': 'Applications Catalog',
    'metagate-07': 'Catalog of decentralized applications and the browser to work with them. Any decentralized application built on <b>#MetaHash</b> can be accessed, not only by the standard internet domain, but also via <b>#MetaGate</b> or allocated to a separate program.',
    'metagate-08': '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">Download White Paper<i class="icon icon_dowload"></i></a>',
    'metagate-download-button': 'Download #Metahash',
    'metagate-download-button2': 'Download #MetaGate',

    'metahashcoin-01': '#MetaHashCoin (#MHC)',
    'metahashcoin-02': '#MetaHash financial model',
    'metahashcoin-03': '#MetaHash is a self-financing system with self-development process embedded in its genetic code.',
    'metahashcoin-04': '#MetaHashCoin is used for payment:',
    'metahashcoin-05': 'Transactions',
    'metahashcoin-06': 'Instant and reliable transactions of any assets at an reasonable fixed price.',
    'metahashcoin-07': 'Data storage',
    'metahashcoin-08': 'For applications that need to store data, but lack the speed and volume of data in conventional Blockchain systems.',
    'metahashcoin-09': 'Operation of application',
    'metahashcoin-10': 'Any decentralized application or Smart Contract requires resources for deployment, including the <b>#MetaHash</b> network itself.',
    'metahashcoin-11': 'Other services',
    'metahashcoin-12': 'Payment for public addresses, listing in <b>#MetaApps</b>, advertising in <b>#MetaGate</b> and other sources.',
    'metahashcoin-13': '<a href="#private-round" class="btn -default btn-mobile">Buy #MHC<i class="icon icon_link"></i></a>',


    'minig-01': 'Mining / forging of #MHC',
    'minig-02': 'Servers',
    'minig-03': 'Used for the operation of the transaction network, free resources used for the operation of decentralized applications.',
    'minig-04': '#MetaGate wallets',
    'minig-05': 'In Full mode, nodes are used as a data storage and Torrent Nodes.',
    'minig-06': '#MetaHashCoins',
    'minig-07': 'Strengthen the security of consensus on the hybrid voting model for PoW + PoS components.',
    'minig-08': '#MHC received from the sale of services are used for:',
    'minig-09': 'training developers who build their projects on #MetaHash',
    'minig-10': 'improvement of project quality',
    'minig-11': 'promotion of #MetaHash',
    'minig-12': 'payments to owners of #MetaHashCoins for consensus support',
    'minig-13': 'payments to the owners of servers and computers',


    'compare-01': '#MetaHash advantages',
    'compare-02': 'After searching for and failing to find any projects working on creating a fully decentralized and synchronized circuit capable of quickly processing the amount of data necessary for the world, we decided to make #MetaHash.',
    'compare-03': 'Comparison table of the main Blockchain systems',
    'compare-04': 'Transaction <br />approval time',
    'compare-05': 'Transactions per second (TPS)',
    'compare-06': 'The level of<br />decentra&shy;lization',
    'compare-07': 'Bitcoin',
    'compare-08': '10 minutes',
    'compare-09': 'up to 12',
    'compare-10': 'high',
    'compare-11': 'Ethereum',
    'compare-12': '15 seconds',
    'compare-13': 'up to 30',
    'compare-14': 'high',
    'compare-15': 'Plasma',
    'compare-16': '15 seconds',
    'compare-17': 'up to 30',
    'compare-18': 'high',
    'compare-19': 'EOS',
    'compare-20': '5 seconds',
    'compare-21': 'from 1,000 to millions',
    'compare-22': 'minimal',
    'compare-23': '#MetaHash',
    'compare-24': 'up to 3 seconds',
    'compare-25': 'from 50,000 to millions',
    'compare-26': 'high',
    'compare-27': '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">Download White Paper<i class="icon icon_dowload"></i></a>',


    'timemap-01': 'Roadmap',
    'timemap-02': 'The technical part of the project was based on the achievements of AdSniper, created in 2012 through 2017 in the field of advertising technologies.',
    'timemap-03': "We received a lot of requests from different companies for the application of Blockchain technology and came to understanding that current technologies cannot satisfy requests for such types of systems. So in 2016 we've started developing our own protocol #TraceChain.",
    'timemap-04': 'In 2017, we created alpha and beta versions of #TraceChain protocol and joined forces with the strongest companies and people in the fields of international marketing and business development.',
    'timemap-05': '2012-2016',
    'timemap-06': 'A network library for receiving signals, working on C++ and capable of simultaneously receiving and sending more than 100,000 requests per second to one inexpensive standard server',
    'timemap-07': 'A network library for synchronizing signals within a cluster that manages gigantic data flows between cluster machines.',
    'timemap-08': 'A machine learning system that decides in 40 milliseconds to respond to a signal taking into account multifactorial interrelationships.',
    'timemap-09': 'Own analogue of Hadoop’s for similar systems in C ++ for distributed processing of large data.',
    'timemap-11': '2017',
    'timemap-12': 'Development of #TraceChain protocol (Alpha version)',
    'timemap-13': 'Development of #TraceChain protocol (Beta version)',
    'timemap-14': '<b>AdNow</b> team joins us',
    'timemap-15': '<b>Agranovsky IT</b> team joins us',
    'timemap-16': 'Formation of <b>Business Development team</b>',
    'timemap-17': 'Formation of <b>Operational Team</b>',
    'timemap-18': '2018',


    'timemap-19': '#MetaHash website official launch',
    'timemap-20': 'Start of the Operational Team office construction',
    'timemap-21': 'Onboarding of experts and advisors',
    'timemap-22': 'Development of #MetaGate (v.1.0). Multi-asset wallet featuring the ability to transfer #MetaHashCoins between wallets on multiple servers that stores data on transactions between crypto wallets.',
    'timemap-23': 'Development of #TraceChain (v.1.0)',
    'timemap-23a': 'Development of #TraceChain (v.2.0). #TraceChain data download API',
    'timemap-24': 'Development of #MetaICO (v.1.0). The ICO interface on the #MetaHash platform that accepts assets from various blockchains (Bitcoin and Ethereum), distributes tokens in the #MetaHash network and carries out multichain transactions, including ERC20 in the Ethereum network',
    'timemap-25': 'Development of #MetaChains (v.1.0). Converting #MetaHashCoins to ERC20 and withdrawing them to the Ethereum network so that #MHC holders can choose which network to use and automatically convert ERC20 tokens into #MetaHashCoins',

    'timemap-26': 'Development of #MetaApps (v.1.0). Application Platform',
    'timemap-27': 'Testnet data download API',
    'timemap-28': 'Opening of the Operational Team office',


    'timemap-29': 'ICO Round A scheduled start',
    'timemap-30': 'Development of #MetaChains (v.2.0). API featuring transaction history and balance  of wallets associated with different blockchain platforms. Decentralized application containing information about transactions in the Ethereum and Bitcoin networks which is necessary to provide blockchain interoperability in #MetaApps',
    'timemap-31': 'Release of <b>#MetaGate (v.2.0)</b>. Encrypted messenger for public notifications and messaging between wallets',
    'timemap-32': 'Release of <b>#TraceChain (v.3.0)</b>. Peer nodes that connect to TestNet to be installed on any server',
    'timemap-33': '#TraceChain (v.4.0). Network core performance testing service (1,000,000+ transactions per second)',
    'timemap-34': '#MetaICO (v.2.0). Interface for creating tokens inside the network #MetaHash',
    'timemap-35': '#MetaICO (v.3.0). Release of ICO project platform at #MetaHash.',
    'timemap-36': '#TraceChain (v.4.0). Voting functions in the #MetaHash network',
    'timemap-37': '#TraceChain (v.5.0). AI managing the routing of signals between nodes for providing maximum speed of #MetaHash block creation and bandwidth and 100 test nodes in different geographical locations for testing node interaction',

    'timemap-38': '#MetaICO (v.4.0). Release of the #MetaToken application, tokenization of ETH, ERC20, Bitcoin to #MetaHashCoin for use in the #MetaHash network',
    'timemap-39': '#TraceChain (v.6.0). #MetaStorage, service for decentralized applications',
    'timemap-40': '#MetaApps (v.2.0). The platform for self-deployment of third-party decentralized applications',
    'timemap-41': '#MetaGate (v.3.0). Final release of #MetaGate wallet for Mac/Win/Unix/Android/iOS with #MetaApps catalogue',


    'timemap-42': '<b>#TraceChain (v.7.0). Start of forging </b>',
    'timemap-43': '<b>ICO Round B start or conclusion of the Listing Agreement with the duly organized and regulated cryptoexchange</b>',
    'timemap-44': 'Further plan announcement',


    'timemap-45': 'Extensive security testing',
    'timemap-46': 'Source code release upon the completion of testing',
    'timemap-47': 'Launch of a fully decentralized system',

    'timemap-100': 'Show more',
    'timemap-101': 'Hide events',
    'timemap-102': 'Other events',


    'teambanner-01': 'Our team',
    'teambanner-02': '#MetaHash is an open-team structured project, which welcomes all people and companies.',
    'teambanner-03': 'If you believe you can be of help and want to join the team, please <a class="team-write" href="mailto:hello@metahash.org">contact us</a>.',
    'teambanner-04': '<a href="#private-round" class="btn -default">ICO Round A<i class="icon icon_link"></i></a>',
    'teambanner-05': 'If you believe you can be of help and want to join the team, please <a href="mailto:hello@metahash.org">contact us</a>.',
    'teambanner-06': 'ICO Round A',
    'teambanner-07': '<img src="img/graphical/People_EN@3x.svg" alt="">',

    'team-hidden-01': 'In the interests of the project, names of the rest of the team are disclosed',

    'team-dev-01': 'Gleb Nikitin',
    'team-dev-02': 'Oleg Romanenko',
    'team-dev-03': 'CSA, The architect of real-time services at AdSniper and system analyst of AlfaBank online banking system. Creator of highload network library capable of serving over 1 million request per second on 1 node.',
    'team-dev-04': 'Mikhail Zarutskiy',
    'team-dev-05': 'CTO, Head of AI, Big Data and real time services teams to create Razoom AI capable of handling millions of requests in real time combining neural networks calculations with other machine learning algorithms.',
    'team-dev-06': 'Sergey Raylyan',
    'team-dev-07': "CIO, plans and coordinates implementation of dozens of different technologies and interfaces forming AdSniper's technology stack.",
    'team-dev-08': '29 employees AdSniper <i class="icon icon_link"></i>',
    'team-dev-09': "Over the past 10 years, the company has created highly loaded advertising networks. The company's own large data processor incorporates servicing petabytes of data, fast NoSQL and SQL databases, artificial intelligence systems and C ++ libraries for highly loaded advertising services, processing requests for advertising from the entire internet.",
    'team-key-staff': 'Key staff',


    'team-mark-01': 'Vladimir Bashkin',
    'team-mark-02': 'Ad network with more than a billion impressions per day. One of the strongest teams in the world for buying advertising on all advertising networks with its own staff of translators and advertising specialists in local markets.',
    'team-mark-03': '89 employees AdNow <i class="icon icon_link"></i>',
    'team-mark-04': 'Artem Kravchenko',
    'team-mark-05': 'Event Director - PR-Director. CEO of AdDays Digital Events. Event Director in Bitcomo Affiliate Network',
    'team-mark-06': 'Daria Baranova',
    'team-mark-07': 'Affiliate Director - Publisher Sales Director of AdNow. Managing Director of Moscow Office',
    'team-mark-08': 'Pham Thành Trung',
    'team-mark-09': "Head of Advertiser's Department - Head of Sales Department in Asian Region of AdNow. Sales and Business Development Manager of AdNow",


    'team-fin-01': 'Anton Agranovsky',
    'team-fin-02': 'Agranovsky IT - investment company, invests in IT startups and accompanies the company growth from the idea to IPO. The Founder Anton Agronovsky is an investor, expert, opinion leader in the field of establishment and development of IT companies. Board member of Plastic Media and SMX Communications. In 2008-2017 -  the founder and president of Destiny Development, one of the first gaming companies on the Russian internet market known both for its own developments and localizations. <br />&nbsp;<br /><a href="https://goo.gl/fJVjfK" class="link -link-small" target="_blank">Forbes magazine contributor</a>',
    'team-fin-03': '11 employees Agranovsky IT <i class="icon icon_link"></i>',
    'team-fin-04': 'Gennady Yakunin',
    'team-fin-05': 'CEO - Organisation of accounting in holding companies. More than 10 years of experience in IT and gaming projects',
    'team-fin-06': 'Svetlana Rudenok',
    'team-fin-07': 'Deputy CEO - Expert in risk evaluation, more than 10 years of experience in audit of new and active projects in IT and gaming industries',
    'team-fin-08': 'Andrey Korostelev',
    'team-fin-09': 'CFO - More than 10 years of experience in financial management of IT and gaming projects. Active supporter of social and charity projects',


    'team-oper-01': 'Dmitry Ushakov',
    'team-oper-02': '<span style="color:#ffffff;">COO, General PM</span><br/>Over 11 years of experience in operational management of multi-user projects for Game Insight and other IT startups',
    'team-oper-03': 'Michaił Iwanow',
    'team-oper-04': '<span style="color:#ffffff;">Art Director</span><br/>More than 16 years of experience in visual and product design. Worked on various projects for RUSNANO, Sony, Canon, Nikon and more',
    'team-oper-05': 'Zhibo Fan',
    'team-oper-06': '<span style="color:#ffffff;">Asia BD Partner</span><br/>Founder of the Game.ru game platform and the INFIPLAY game publisher',
    'team-oper-07': 'Alexander Zhigarenko',
    'team-oper-08': '<span style="color:#ffffff;">CBDO Russia, CIS</span><br/>Over 10 years of publishing, operation and business development experience for Destiny.Games and in game industry',
    'team-oper-09': 'Eugenia Sigacheva',
    'team-oper-10': '<span style="color:#ffffff;">Public Affairs Partner</span><br/>More than 18 years in international Marketing & PR, also IT&Innovations. Eugenia is a part of International team of the well known robot Sophia and CEO&Founder of the IHEART Platform.',
    'team-oper-11': 'Andrey Akimov',
    'team-oper-12': '<span style="color:#ffffff;">Chief Communication Officer</span><br/>More than 15 years in marketing and PR in gaming, entertainment, and IT business. Former head of PR and marketing at My.com, Mail.Ru Group, Game Insight, and other companies.',
    'team-oper-00': '17 employees Operational Team <i class="icon icon_link"></i>',


    'legal-title': 'Legal Department',
    //'legal-02' : 'Anastasia Pichugina',
    //'legal-03' : 'ANP Law Managing Partner',
    //'legal-04' : 'Ekaterina Myznikova',
    //'legal-05' : 'Senior Lawyer - Head of the practice of Blockchain projects. Successfully accompanies several ICO projects, a participant and speaker of profile conferences, webinars.',
    //'legal-06' : 'Maxim Mekhriakov',
    //'legal-07' : 'Senior Lawyer - Head of Commercial Practice within the ANP Law specialising in legal support of commercial and investment transactions.',
    //'legal-08' : 'Anna Shevchenko',
    //'legal-09' : 'Lawyer - Legal support for Russian and foreign companies in the field of intellectual property rights, including registration of trademarks and patents.',
    //'legal-10' : 'Experts in International and Russian law. Our lawyers graduated from the most prestigious law schools in Russia and abroad. Managing partner Anastasia has a unique experience and knowledge in Russian and foreign law, is a trusted legal representative of several foreign companies from the IT, FMCG market. Anastasia successfully represented foreign companies in Russian courts.',
    //'legal-11' : '<a href="docs/MetaHash_LegalOpinion_EN.pdf" target="_blank">Download Legal Opinion #MetaHashCoin<i class="icon icon_link"></i></a>',


    //'legal-14' : 'Maria Agranovskaya',
    //'legal-15' : 'Chief Legal Coordinator <a href="https://www.facebook.com/magranovskaya" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a> <a href="https://www.linkedin.com/in/maria-agranovskaya-151334/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
    //'legal-16' : '<span>Attorney at Law with 20+ years of experience. Started working with cryptocurrency issues back in 2010. MGIMO MID of Russia (International Law), studied in Germany and Holland. 8,5 years - running a multifamily office, worked on various cross-border transactions, investments, asset management, deal and corporate structuring in various jurisdictions, M&A, international taxation and other matters.</span><span>Areas: fintech, finance, telecom, banking, energy, pharmaceuticals, real estate and other sectors.</span><span>2007: setup of GRAD Attorney Bar (managing partner,  30+ Russian and foreign lawyers)</span><span>Substantially engaged in blockchain technology, ICO (TGE) related projects, trading and finance regulations, funds and financial activity.</span><span>Speaks English, German, French, Italian, </span>',

    'legal-more': 'Show more',
    'legal-less': 'Show less',
    'legal-17': 'Andrey Mironov <a href="http://www.linkedin.com/in/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a> <a href="https://www.facebook.com/" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
    'legal-18': 'Chief of Legal Department',
    'legal-19': 'Graduated MGIMO in 2000 at the international law faculty. Legal practice in the field of new technologies, media and intellectual property for more than 15 years.',
    'legal-19a': 'He worked at the Art. Lebedev Studio, Odnoklassniki, the Russian office of Myspace, on the channels MTV, Discovery, Amedia and the online cinema Amediateka. Helped to develop the EKSMO publishing house, the Fox TV channel. Expert at the Russian Association of Electronic Communications (RAEC).<br>Secondary Education: Consultant Psychologist',
    'legal-20': 'Maria Agranovskaya',
    'legal-21': 'Chief Legal Coordinator',
    'legal-22': 'Attorney at Law with 20+ years of experience. Started working with cryptocurrency issues back in 2010.',
    'legal-22a': 'MGIMO MID of Russia (International Law), studied in Germany and Holland. 8,5 years - running a multifamily office, worked on various cross-border transactions, investments, asset management, deal and corporate structuring in various jurisdictions, M&A, international taxation and other matters. Areas: fintech, finance, telecom, banking, energy, pharmaceuticals, real estate and other sectors. 2007: setup of GRAD Attorney Bar (managing partner,  30+ Russian and foreign lawyers). Substantially engaged in blockchain technology, ICO (TGE) related projects, trading and finance regulations, funds and financial activity. Speaks English, German, French, Italian,  Spanish.',
    'legal-23': 'Katya Fisher',
    'legal-24': 'Partner, Principal at The Law Office of Katya Yoffe PLLC',
    'legal-25': 'Katya Yoffe (née Fisher) is an attorney focusing on general corporate law, cross-border transactions and business immigration.',
    'legal-25a': 'Katya represents various prominent companies and startups doing business in the United States as well as celebrity and HNW individuals. Katya has been selected to Super Lawyers as a “Rising Star” in 2014, 2015, 2016, 2017 and 2018. <br>Katya is a graduate of New York University, the Benjamin N. Cardozo School of Law and a former Howard M. Squadron Fellow in International Media Law & Policy at the University of Oxford and Center for Global Communication Studies, University of Pennsylvania. She is admitted to practice in New York and before the United States Tax Court.',
    'legal-26': 'Anastasia Pichugina',
    'legal-27': 'ANP Law Managing Partner ',
    'legal-28': 'Managing partner Anastasia has a unique experience and knowledge in Russian and foreign law, is a trusted legal representative of several foreign companies.',
    'legal-29': 'Ekaterina Myznikova',
    'legal-30': 'Senior Lawyer',
    'legal-31': 'Head of the practice of Blockchain projects. Successfully accompanies several ICO projects, a participant and speaker of profile conferences, webinars.',
    'legal-32': 'International Legal Support',
    'legal-33': 'Daniel G. Viola',
    'legal-34': 'Partner, Head of Regulatory and Compliance Group at Sadis & Goldberg LLP',
    'legal-35': 'Oliver Ciric',
    'legal-36': 'Partner at TA Advisory',
    'legal-37': 'Daniel G. Viola is a partner of <span class="ilegal-white">Sadis & Goldberg LLP</span> and the Head of its Regulatory and Compliance Group.  Mr. Viola has been active in the Blockchain and Virtual Currency verticals since 2014. He also served as a Senior Compliance Examiner for the <span class="ilegal-white">Northeast Regional Office of the SEC,</span> where he worked from 1992 through 1996',
    'legal-37a': 'During his tenure at the SEC, Mr. Viola worked on several compliance inspection projects and enforcement actions involving examinations of registered investment advisers, ensuring compliance with federal and state securities laws. Mr. Viola’s examination experience includes financial statement, performance advertising, and disclosure document reviews, as well as, analysis of investment adviser and hedge fund issues arising under ERISA and blue-sky laws. In late 2006 Mr.  Viola founded his own law firm and eventually merged it into Sadis & Goldberg’s law practice.',
    'legal-38': 'Experience in international jurisprudence for more than 20 years. Oliver graduated from Boston University of Law in 2006, majoring in banking and finance law, and the Geneva University of Law in 1998, specializing in "License and Law".',
    'legal-38a': 'Previous work experience:  Nationale Suisse Assurances, Matile Brosset Stickel-Cicurel & Gianninazzi, Poncet Turrettini Amaudruz Neyroud & Partners, <span class="ilegal-white">Akin Gump Strauss Hauer & Feld LLP</span> (formerly Hogan & Hartson LLP).Since June 2017 he has been a partner at <span class="ilegal-white">TA Advisory</span>. Mr. Ciric provides legal support for blockchain projects, and also advises on cooperation <span class="ilegal-white">with FINMA.</span><br>Languages: German, English, French, Portuguese, Russian, Serbian.',
    'legal-39': '<span class="ilegal-white-02">KPMG AG, Switzerland,</span> served as exclusive legal advisor to #MetaHash and its management in the evaluation of regulatory, tax and legal aspects in respect of the White Paper, which is released in preparation of a Coin offering (ICO)',
    'legal-40': '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">Download White Paper<i class="icon icon_dowload"></i></a>',
    'legal-41': 'Martin Hess',
    'legal-42': 'Partner at Wenger & Vieli AG',
    'legal-43': 'Martin Hess specializes in financial services and capital markets law, FinTech and the digitization of financial services. He is recognized by the Swiss Stock Exchange as an issuer representative. Martin Hess advises Swiss and foreign clients and represents them vis-à-vis supervisory authorities and in court.',
    'legal-43a': 'He is involved in the legal design of trading venues for digital assets, payment systems and securities settlement systems as well as central counterparties. He advises and represents clients on Initial Coin Offerings / Token Generating Events. Since 2001 Partner at Wenger & Vieli Ltd',


    'private-01': 'Private Round',
    'private-form': '<input type="hidden" name="form_subject" value="Private Round Application">',
    'private-03': 'days',
    'private-04': 'Private Round ends in',
    'private-05': 'Private Round',
    'private-06': 'The purpose of the Private Round is to verify the idea before the public launch',
    'private-07': 'We hope to meet experts who are ready to participate in the discussion of the project before its public launch and, possibly, join the #MetaHashTeam.',
    'private-08': '#MetaHash undertakes to inform all Private Round participants about terms of participation, their rights and obligations in connection with participation.',
    'private-09': 'Private Round participants will be able to decide whether to remain in the project after the ICO.',
    'private-10': 'Send an application to participate in the Private Round',
    'private-11': 'We are not interested in the amount, but rather in your expertise. We want experts from different fields to participate in the Private Round.',
    'private-12': 'Describe your expertise in cryptocurrencies. Are you ready to participate in discussion about the project?',
    'private-13': 'Apply <i class="icon icon_link"></i>',
    'private-14': 'Terms of Use',
    'private-15': 'Privacy Policy',
    'private-16': 'Private Round terms:',
    'private-17': 'Do you want to participate in the Private Round or join the #MetaHashTeam?',
    'private-18': 'Participation in the Private Round is public - the name or company name of the participant will be published',
    'private-19': 'Private Round volume - <b>1,840 ETH</b>',
    'private-20': 'The value of the #MHC - <b>0.001 ETH</b>',
    'private-21': 'The volume of the Private Round is not enough to satisfy the requests of all comers',
    'private-22': 'You can fill the application form before the end of the Private Round',
    'private-23': 'At the end of the Private Round, the current #MetaHash team will decide on quotas for each of those wishing to participate',
    'private-24': 'After the completion of the Private Round and the distribution of tasks between the current and new team members, the ICO Round A will start',
    'private-25': 'Private Round Application',
    'private-26': 'Enter your name',
    'private-27': 'Enter your e-mail',
    'private-28': 'Desired amount of participation (ETH)',
    'private-29': 'Additional information about yourself',


    'timer-day-1': 'days',
    'timer-day-2': 'days',
    'timer-day-3': 'days',
    'timer-hour-1': 'hour',
    'timer-hour-2': 'hours',
    'timer-hour-3': 'hours',
    'timer-minute-1': 'minute',
    'timer-minute-2': 'minutes',
    'timer-minute-3': 'minutes',
    'timer-second-1': 'second',
    'timer-second-2': 'seconds',
    'timer-second-3': 'seconds',


    'form-sent-01': 'Thank you!',
    'form-sent-02': 'Your information has been submitted successfully.',


    'faq-01': 'F.A.Q.',
    'faq-02-00': 'About #MetaHash',
    'faq-02-01': 'Are you a legal entity?',
    'faq-02-02': 'The process of registering a legal entity has been initialized in Switzerland. It generally takes time to come to agreement with the Swiss government.',
    'faq-02-03': 'Where can I examine the MVP and Open source code of #MetaHash?',
    'faq-02-04': '#TraceChain centrilized network is currently active with a multi-asset wallet. The source codes of #TraceChain protocol will be released after a public security bounty program for hackers is passed and the patent is obtained.',
    'faq-02-05': 'What is the general aim of the product itself and the token?',
    'faq-02-06': '#MetaHashCoin is used to exchange for: transactions, data storage, app functions. You can also excange #MHC to add a public address, to make your app listed in #MetaApp directory, to purchace ads in #MetaGate adnetwork and much more.',
    'faq-02-07': 'What are the speed capacities of your Blockchain? How can you reach such a result?',
    'faq-02-08': 'Please check our <a href="docs/MetaHash_WhitePaper_EN.pdf" class="download-white-paper link -link-small" target="_blank">White Paper</a> to learn more about our Blockchain capacities.',
    'faq-02-09': 'Is your coin mineable? Are there any benefits for the miners?',
    'faq-02-10': 'Read the <a href="docs/MetaHash_WhitePaper_EN.pdf" class="download-white-paper link -link-small" target="_blank">White Paper</a> for more details about mining.',
    'faq-02-11': 'What proof system do you use, POW or POS?',
    'faq-02-12': '#MetaHash uses a hybrid consensus algorithm. This is a multiPOS system including the vote results from separate network nodes.',


    'faq-03-00': 'ICO Round A / Round B and buying #MHC',
    'faq-03-01': 'What payment methods do you accept?',
    'faq-03-02': 'We accept ETH only. Other digital assets need to be exchanged to ETH first.',
    'faq-03-03': '',
    'faq-03-04': '',
    'faq-03-05': 'Can I participate from an exchange platform?',
    'faq-03-06': 'Yes, you can. But we accept ETH only.',
    'faq-03-07': '',
    'faq-03-08': '',
    'faq-03-09': 'When do the ICO Round A / ICO Round A rounds finish?',
    'faq-03-10': 'ICO Round A round lasts until the targeted amount is reached. ICO Round B starts after the MVP is released',
    'faq-03-11': 'What are the special terms of the #MHC multi-asset wallet?',
    'faq-03-12': '#MetaGate multi-asset wallet is an open source code product. Its usage is financed from payments for ads shown and the subscriptions for ads blocking',


    'faq-04-00': '#MetaHashCoin and Prospects',
    'faq-04-01': 'What are the general differences between #MetaHash and any other Blockchain provider?',
    'faq-04-02': 'All of the existing competitors are either slow or centralized. The next generation of Blockchains must be swift, totally decentralized and have cheap transactions as well. There is no existing project (except for #MetaHash) which covers all these requirements.',
    'faq-04-03': 'Is #MHC ERC20 emited though the ETH Smart Contract?',
    'faq-04-04': '#MHC is a separate independent coin that is operated in a separate chain. Nevertheless, some mirror contracts in Ethereum and #MetaHash exist. These mirror contracts allow for the tokenizing procedure of ERC20 tokens in both directions.',
    'faq-04-05': 'What is the total supply in tokens?',
    'faq-04-06': '92,000,000 #MHC will be released over a term of 10 years. 46,000,000 #MHC will be released in the first year.',
    'faq-04-07': 'What exchange platforms will trade the #MetaHashCoins?',
    'faq-04-08': 'Coin availability on exchange platforms will be announced through the all official #MetaHash public channels. We are not allowed to share such information in advance.',
    'faq-04-09': 'What will the initial price of the #MHC be after the ICO once it reaches the open market? And after one year?',
    'faq-04-10': 'The cost of #MetaHashCoin is determined by market necessities. #MHC is used to pay for the following services: transactions, data storage, app functioning and so on. These factors will influence the cost of #MHC.',
    'faq-04-11': 'When does the token sale start/end?',
    'faq-04-12': 'We plan to finish ICO Round A by the end of 2018. Official ICO Round B will start in Q4 of 2018 or in Q1 of 2019.',


    'faq-05-00': '#MHC Sale Process',
    'faq-05-01': 'Is there a minumum limit to participate in #MetaHash?',
    'faq-05-02': 'We do not set any minimum limits. You can have as many tokens as you wish.',
    'faq-05-03': 'When will the tokens be provided to participants?',
    'faq-05-04': '#MetaHash TestNet coins or their ERC20 substitute are provided when the ICO is finished',
    'faq-05-05': 'What will you do with the unsold coins?',
    'faq-05-06': 'All the assets unsold will remain at #MetaHash Company',
    'faq-05-07': 'I transferred 0.07 ETH to my #MetaHash wallet. How many tokens will I receive?',
    'faq-05-08': 'You can use our internal calculator.',
    'faq-05-09': 'How can I purchase #MHC if I have no cryptocurrency assets?',
    'faq-05-10': 'You can not: you have to convert your money into ETH or BTC. You can use any exchange platform you like.',



    'faq-06-00': 'Other Questions',
    'faq-06-01': 'I am a Chinese or Korean citizen, is it legal to participate in the #MetaHash ICO crowdsale?',
    'faq-06-02': 'Every nationality except: United States, Singapore, Socialist Republic of Vietnam, People’s Republic of China or resident of a country where American embargoes and sanctions are in force, namely Iran, North Korea, Syria, Sudan, or Cuba. More information in our Terms of Token Sale.',
    'faq-06-03': 'So in a nutshell, what is #TraceChain?',
    'faq-06-04': '#TraceChain is the next generation of Blockchain systems. The solution is based on an autonomous self-studying routing algorythm. It starts its functioning at a speed of 50,000 transactions per second (basic speed of a 100 Mb/s channel) and increases by adding reasonable numbers of high speed channels. These channels form the core of #MetaHash network and make its work stable.',
    'faq-06-05': 'Hard cap / soft cap?',
    'faq-06-06': 'Soft cap is reached through Founders and Private round. Hard cap is not determined.',
    'faq-06-07': 'I deposited 0.0067769 BTC/ETH, when will it be converted into #MHC tokens?',
    'faq-06-08': "The tokens are provided to you after six confirmations on the Ethereum network and #MetaChains nodes are received. We usually give 6 hours to validate the transactions from ETH and BTC networks. Please don't worry if you haven't receive your coins in 6 hours. Send us a report and we will resolve your issue. Your deposit is a transaction in itself. If the transaction took place, your coins will be sent to you.",
    'faq-06-09': 'What are the official dates of Private round, ICO rounds and so on?',
    'faq-06-10': 'The official dates of ICO Round A and ICO Round B are not yet determined. They will be announced through our public channels soon. Stay tuned, and you will be the first to know.',
    'faq-06-11': 'Is #MetaHash a BTC or ETH fork ?',
    'faq-06-12': '#MetaHash is not a fork. This is an independent blockchain provider that is much faster and more secure.',


    'support-01': 'Any questions? Contact us!',
    'support-02': 'Send Message',
    'support-03': 'User question',
    'support-04': 'Enter your name',
    'support-05': 'Enter your e-mail',
    'support-06': 'Your question',


    'prefooter-01': 'Join the ride!',
    'prefooter-02': '#MetaHashTeam',
    'prefooter-03': '<a href="#private-round" class="btn -default">Buy #MHC<i class="icon icon_link"></i></a>',
    'prefooter-03': '<a href="#private-round" class="btn -default">Buy #MHC<i class="icon icon_link"></i></a>',
    'prefooter-04': '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">Download White Paper<i class="icon icon_dowload"></i></a>',
    'prefooter-05': '<a href="docs/MetaHash_OnePager_EN.pdf" target="_blank" class="download-one-pager btn -download">Download One-Pager<i class="icon icon_dowload"></i></a>',
    'prefooter-06': 'Take part in ICO Round A',
    'prefooter-07': '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">White Paper</a>',
    'prefooter-08': '<a href="docs/MetaHash_OnePager_EN.pdf" target="_blank" class="download-one-pager btn -download float-right">One-Pager</a>',


    'footer-01': 'What is #MetaHash?',
    'footer-02': 'Buy #MetaHashCoin (#MHC)',
    'footer-03': '<a href="https://static.metahash.org/docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper link -footer-link">White Paper</a>',
    'footer-04': '<a href="https://static.metahash.org/docs/MetaHash_OnePager_EN.pdf" target="_blank" class="download-one-pager link -footer-link">One-Pager</a>',
    'footer-05': 'FAQ',
    'footer-06': '<a href="https://static.metahash.org/docs/MetaHash_TermsOfUse_EN.pdf" target="_blank" class="link -footer-link">Terms of Use</a>',
    'footer-07': '<a href="https://static.metahash.org/docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank" class="link -footer-link">Privacy Policy</a>',
    'footer-08': '<a href="https://static.metahash.org/docs/MetaHash_AntiSpam_EN.pdf" target="_blank" class="link -footer-link">Anti-Spam Policy</a>',
    'footer-09': 'Advisor Agreement',
    'footer-10': '<a href="https://static.metahash.org/docs/MetaHash_RiskDisclosureStatement_EN.pdf" target="_blank" class="link -footer-link">Risk Disclosure Agreement</a>',
    'footer-11': 'Social networks and messengers',
    'footer-12': 'Forums',
    'footer-13': 'Feedback at <a href="mailto:hello@metahash.org" class="link -link-small">hello@metahash.org</a>',
    'footer-14': 'Support at <a href="mailto:support@metahash.org" class="link -link-small">support@metahash.org</a>',
    'footer-15': 'Press enquiries <a href="mailto:support@metahash.org" class="link -link-small">press@metahash.org</a>',
    'footer-16': 'Press office <a class="link -link-small">+7 926 671-67-08</a>',


    'mobile-menu-01': '<span><a href="#whatis" class="link -link-white">What is #MetaHash?</a></span>',
    'mobile-menu-02': '<a href="#private-round" class="link -link-white">Buy #MetaHashCoin (#MHC)</a>',
    'mobile-menu-03': '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper link -link-white">Download White Paper</a>',
    'mobile-menu-04': '<a href="docs/MetaHash_OnePager_EN.pdf" target="_blank" class="download-one-pager link -link-white">Download One-Pager</a>',
    'mobile-menu-05': '<a href="#faq" class="link -link-white">F.A.Q.</a>',
    'mobile-menu-06': '<a href="#support" class="link -link-white">Support</a>',
    'mobile-menu-07': '<a href="#support" class="link -link-white">Contacts</a>',

    'new-mobile-menu-01': '<a href="#whatis" class="link -link-white --offcan">What is #MetaHash?</a>',
    'new-mobile-menu-02': '<a href="#tracechain" class="link -link-white --offcan">#TraceChain</a>',
    'new-mobile-menu-03': '<a href="#metaapps" class="link -link-white --offcan">#MetaApps</a>',
    'new-mobile-menu-04': '<a href="#metagate" class="link -link-white --offcan">#MetaGate</a>',
    'new-mobile-menu-05': '<a href="#timemap" class="link -link-white --offcan">Roadmap</a>',
    'new-mobile-menu-06': '<a href="#advisors-and-consultants" class="link -link-white --offcan">Advisors & Consultants</a>',
    'new-mobile-menu-07': '<a href="#teambanner" class="link -link-white --offcan">The Team</a>',
    'new-mobile-menu-08': '<a href="#ico" class="link -link-white --offcan">ICO Round A</a>',
    'new-mobile-menu-09': '<a href="#faq" class="link -link-white --offcan">F.A.Q.</a>',
    'new-mobile-menu-10': '<a href="#support" class="link -link-white --offcan">Contact Us</a>',



    'promo-soc-01': '<a href="https://t.me/metahash_ENG" class="footer-social-button link-soc -tooltype" data-event="org_tg" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
    'promo-soc-02': '<a href="https://www.facebook.com/MetaHash/" class="footer-social-button link-soc -tooltype" data-event="org_fb" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
    'promo-soc-03': '<a href="https://vk.com/metahash" class="footer-social-button link-soc -tooltype" data-event="org_vk" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
    'promo-soc-04': '<a href="https://twitter.com/themetahash" class="footer-social-button link-soc -tooltype" data-event="org_twitter" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
    'promo-soc-05': '<a href="https://instagram.com/themetahash" class="footer-social-button link-soc -tooltype" data-event="org_instagram" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
    'promo-soc-06': '<a href="https://www.youtube.com/channel/UCIkBIrd1q7JkLLj43KgG8zA" class="footer-social-button link-soc -tooltype" data-event="org_youtube" target="_blank"><span class="soc-tooltype">youtube.com</span><span class="icon -icon-big icon_youtube"></span></a>',
    'promo-soc-07': '<a href="#" class="footer-social-button link-soc -tooltype" data-event="org_wechat"><span class="soc-tooltype">ID:MetaHash</span><span class="icon -icon-big icon_wechat"></span></a>',
    'promo-soc-08': '<a href="https://open.kakao.com/o/gY5dUgG" class="footer-social-button link-soc -tooltype" data-event="org_kakao" target="_blank"><span class="soc-tooltype">talk.com</span><span class="icon -icon-big icon_talk"></span></a>',
    'promo-soc-09': '<a href="https://github.com/metahashorg" class="footer-social-button link-soc -tooltype" data-event="org_github" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
    'promo-soc-10': '<a href="https://www.reddit.com/user/MetaHash/" class="footer-social-button link-soc -tooltype" data-event="org_reddit" target="_blank"><span class="soc-tooltype">reddit.com</span><span class="icon -icon-big icon_reddit"></span></a>',
    'promo-soc-11': '<a href="https://www.linkedin.com/company/27209614/" class="footer-social-button link-soc -tooltype" data-event="org_linkedin" target="_blank"><span class="soc-tooltype">linkedin.com</span><span class="icon -icon-big icon_in"></span></a>',
    'promo-soc-12': '<a href="https://medium.com/@themetahash" class="footer-social-button link-soc -tooltype" data-event="org_medium" target="_blank"><span class="soc-tooltype">medium.com</span><span class="icon -icon-big icon_medium"></span></a>',
    'promo-soc-13': '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="footer-social-button link-soc" data-event="org_bitsmedia" target="_blank"><span class="icon -icon-big --icon-forum icon_bitsmedia"></span></a>',
    'promo-soc-14': '<a href="https://bitcointalk.org/index.php?action=profile;u=1253602" class="footer-social-button link-soc" data-event="org_bitcointalk" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',

    'promo-soc-mobile-01': '<a href="https://t.me/metahash_ENG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
    'promo-soc-mobile-02': '<a href="https://www.facebook.com/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
    'promo-soc-mobile-03': '<a href="https://vk.com/metahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
    'promo-soc-mobile-04': '<a href="https://twitter.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
    'promo-soc-mobile-05': '<a href="https://instagram.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
    'promo-soc-mobile-06': '<a href="https://github.com/metahashorg" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
    'promo-soc-mobile-07': '<a href="https://www.linkedin.com/company/27209614/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">linkedin.com</span><span class="icon -icon-big icon_in"></span></a>',
    'promo-soc-mobile-08': '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="link-soc"><span class="icon -icon-big --icon-forum icon_bitsmedia" target="_blank"></span></a>',
    'promo-soc-mobile-09': '<a href="https://bitcointalk.org/index.php?action=profile;u=1253602" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',
    'promo-soc-mobile-10': '<a href="https://www.youtube.com/channel/UCIkBIrd1q7JkLLj43KgG8zA" class="link-soc" target="_blank"><span class="icon -icon-big icon_youtube"></span></a>',
    'promo-soc-mobile-11': '<a href="https://medium.com/@themetahash" class="link-soc" target="_blank"><span class="icon -icon-big icon_medium"></span></a>',




    'tg_button': '<a href="https://t.me/metahash_ENG" class="footer-social-button" data-event="org_tg" target="_blank"><img class="telega-svg" style="margin-bottom: 40px;" src="img/telegram.svg" alt=""></a>',



    'private-close-01': 'Private Round is closed',
    'private-close-02': 'Finished after being over 20x oversubscribed.',
    'private-close-03': 'We want to thank all participants and invite everyone to join us for the ICO Round A.',
    'private-close-04': 'ICO Round A',
    'private-close-05': 'scheduled month of start',
    'private-close-06': 'ICO Round A coming soon',
    'private-close-07': 'don’t miss the start, apply now<br class="mobile-br"> to participate or join our team',
    'private-close-08': 'Apply now <i class="icon icon_link"></i>',
    'private-close-09': 'Keep up with us:',
    'private-close-10': 'ICO Round A features:',
    'private-close-11': '<b class="mob-bold">9,200,000 #MHC</b> will be distributed during ICO Round A',
    'private-close-12': '#MHC value for ICO Round A is <b class="mob-bold">0.0125 ETH</b>',
    'private-close-13': 'Orders <b class="mob-bold">under 50 ETH</b> (4,000 #MHC) are filled from general limited pool renewed every 4 hours. <b class="mob-bold">First come first served</b>',
    'private-close-14': 'To keep space for small buyers, <b class="mob-bold">orders over 50 ETH</b> are filled from separate reserved pool instantly',
    'private-close-15': '04/2018',
    'private-close-16': 'enter your e-mail',
    'private-close-17': 'can be changed according<br> to White Paper',
    // 'private-close-18' : '<input id="private-close__terms-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__terms-check">I agree to </label><a href="docs/MetaHash_TermsOfUse_EN.pdf" target="_blank">Terms of Use</a>',
    // 'private-close-19' : '<input id="private-close__policy-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__policy-check">I agree to </label><a href="docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank">Privacy Policy</a> ',


    'private-close-18': 'I agree to ',
    'private-close-19': 'I agree to ',
    'private-close-25': '<a href="docs/MetaHash_TermsOfUse_EN.pdf"  target="_blank">Terms of Use</a>',
    'private-close-26': '<a href="docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank">Privacy Policy</a>',



    'private-close-20': 'Application submitted',
    'private-close-21': ', thank you for your interest in <b>#MetaHash</b> project. We will keep you informed about the <b>ICO Round A start date</b>.',
    'private-close-22': 'Dont miss a thing!',
    'private-close-23': '<a href="https://t.me/metahash_ENG" target="_blank"  class="private-close__modal-content_tg-link" >Join our Telegram Channel<br> and stay updated</a>',
    'private-close-24': '<a href="https://t.me/metahash_ENG" target="_blank" class="support-window__social-block_soc-link support-window__social-block_soc-link_tg"><img class="support-window__social-block_soc-img" src="img/popup/sub-tg.png" alt=""><span class="flag"><img class="support-window__social-block_flag-img" src="img/icons/flag-eng.png"></span></a>',









    'modal-sub-name': 'Peter',
    'modal-sub-metalang': '#MetaHash<br class="mobile-br">  English (British)',
    'modal-sub-subtit': 'Subscribe to #MetaHash news digest<br class="mobile-br"> about crypto-currencies, mining and blockchain',
    'modal-sub-subbtn': 'Subscribe',
    'modal-sub-talk': '<a class="sub-hr-text" href="https://t.me/metahash_ENG" target="_blank"><b>We speak English!</b><br> Join our Telegram chat and feel free to ask any question to #MetaHash team </a>',
    'modal-sub-tw': '<a href="https://twitter.com/themetahash" class="sub-hr-text" target="_blank">Follow the news and the development of the project on Twitter</a>',
    'modal-sub-img': '<img src="img/popup/support_people/RU and EN - Peter.png" class="" alt="">',
    'modal-sub-soc-tg': '<a href="https://t.me/metahash_ENG" target="_blank" class="support-window__social-block_soc-link support-window__social-block_soc-link_tg"><img class="support-window__social-block_soc-img" src="img/popup/sub-tg.png" alt=""><span class="flag"><img class="support-window__social-block_flag-img" src="img/icons/flag-eng.png"></span></a>',
    'modal-sub-soc-tw': '<a href="https://twitter.com/themetahash" target="_blank" class="support-window__social-block_soc-link support-window__social-block_soc-link_tw"><img class="support-window__social-block_soc-img" src="img/popup/sub-tw.png" alt=""><span class="flag"><img class="support-window__social-block_flag-img" src="img/icons/flag-eng.png"></span>',
    'modal-sub-enter': '<input type="text" class="modal__sub-inp" placeholder="Enter e-mail">',


    'attention-01': '<span class="mobtext">Dear users!</span> As a result of numerous consultations with lawyers and preparation of documents for the SEC and FINMA regulators, the project team have made the following decisions:',
    'attention-03': '1. To rename the ICO rounds for ICO Round A and ICO Round B;',
    'attention-04': '2. To revise financial terms of the two expected ICO rounds in order to extend the competitive advantage over projects with unreasonably high capitalizations;',
    'attention-05': '3. To change the distribution schedule of fees to comply with FINMA rules, where the team is replaced by the Authors and combined with the Advisors of the project. Authors royalties extend beyond both rounds of the ICO;',
    'attention-06': '4. Open in April a test entry for TestNet #TraceChain and download the #MetaGate working client before the start of ICO Round A, so that the working product is available <span>before the start of the crowdsale.</span>',
    'attention-07': '<span class="mobtext">For more details,</span>  see our White Paper',
    'attention-08': '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">Download White Paper<i class="icon icon_dowload"></i></a>',
    "promo-nav-heading": "MetaHash repositories",
    "promo-nav-link-1": "General repositories",
    "promo-nav-link-2": "MetaHash services",
    "promo-nav-link-3": "Scripts and applications allowing to generate address<br>and perform transaction in Metahash network",
    "promo-nav-link-4": "Libraries on generating unique identification icons<br>for each Metahash address",
    "promo-nav-link-5": "About Metahash network",
    "promo-nav-link-6": "Examples of using v8 library",
    "promo-nav-link-7": "Other repositories",
    "promo-content-description-1-1": "This repository contains the source code of MetaHash wallet in C++,<br>as well as wallet application releases developed for various operating systems: <a href=\"https://github.com/metahashorg/metagate/releases\">https://github.com/metahashorg/metagate/releases</a>",
    "promo-content-description-1-2": "See our wiki page for more information about Metahash wallet: <a href=\"https://github.com/metahashorg/MetaHash/wiki/MetaHash-Wallet\">https://github.com/metahashorg/MetaHash/wiki/MetaHash-Wallet</a>",
    "promo-content-description-2-1": "This repository contains driver for PHP7 to support multiple databases.<br>Currently only Redis DB is supported",
    "promo-content-description-3-1": "Source code of the driver for PHP including all features for generating a wallet. Library from the <a href=\"https://github.com/metahashorg/cpplib_open_ssl_decor\">cpplib_open_ssl_decor</a> repository written in С++ is used",
    "promo-content-description-3-2": "Library containing all features for generating a wallet.<br>Library is written in C++",
    "promo-content-description-3-3": "Python language",
    "promo-content-description-3-4": "See our wiki page for more information <a href=\"https://github.com/metahashorg/MetaHash/wiki/Address-Bash-example\">https://github.com/metahashorg/MetaHash/wiki/Address-Bash-example</a>",
    "promo-content-description-3-5": "Shell scripts<br>See our wiki page for more information <a href=\"https://github.com/metahashorg/MetaHash/wiki/Address-Python-example\">https://github.com/metahashorg/MetaHash/wiki/Address-Python-example</a>",
    "promo-content-description-3-6": "Source code written in PHP language<br><a href=\"http://developers.metahash.org\">http://developers.metahash.org</a>",
    "promo-content-description-3-7": "C++ language",
    "promo-content-description-3-8": "Repository is empty",
    "promo-content-description-3-9": "This repository supports the same features for generating address<br>and verification signature in PHP",
    "promo-content-description-4-1": "Python language",
    "promo-content-description-4-2": "See our wiki page for more information <br><a href=\"https://github.com/metahashorg/MetaHash/wiki/Python-iconhas\">https://github.com/metahashorg/MetaHash/wiki/Python-iconhas</a>",
    "promo-content-description-4-3": "JavaScript language",
    "promo-content-description-4-4": "See our wiki page for more information <br><a href=\"https://github.com/metahashorg/MetaHash/wiki/JavaScript-iconhash\">https://github.com/metahashorg/MetaHash/wiki/JavaScript-iconhash</a>",
    "promo-content-description-5-1": "This repository contains code of this website",
    "promo-content-description-5-2": "This repository contains wiki pages for general repositories  <br><a href=\"https://github.com/metahashorg/MetaHash/wiki\">https://github.com/metahashorg/MetaHash/wiki</a>",
    "promo-content-description-5-3": "This repository contains Yellow Paper of Metahash network",
    "promo-content-description-6-1": "This repository contains examples of solving tasks in C++ using v8 library",
    "promo-content-description-6-2": "This repository is used for saving compilation result and implementing<br>contracts on v8 server. JavaScript language",
    "promo-content-description-7-1": "HTML language",
    "promo-content-description-7-2": "PHP language",
    "promo-content-description-7-3": "Python language. Repository is empty",
    "promo-content-heading-1": "General<br>repositories",
    "promo-content-heading-2": "MetaHash<br>services",
    "promo-content-heading-3": "Scripts and applications allowing to<br>generate address and perform<br>transaction in Metahash network",
    "promo-content-heading-4": "Libraries on generating unique<br>identification icons for each<br>Metahash address",
    "promo-content-heading-5": "About Metahash<br>network",
    "promo-content-heading-6": "Examples of using<br>v8 library",
    "promo-content-heading-7": "Other<br>repositories",
    "legal-14": "",
    "legal-15": "",
    "legal-16": ""

};
