window.arrLang = window.arrLang || {};
window.arrLang["es"] = {
    'nav-link-01' : '¿Qué es #MetaHash?',
      'nav-link-02' : 'Comprar #MHC',
      'nav-link-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -link-white"><img src="img/icon_file.svg" class="icon_file"> Libro Blanco</a>',
      'nav-link-04' : '<a href="docs/MetaHash_OnePager_ES.pdf" target="_blank" class="link -link-white"><img src="img/icon_file.svg" class="icon_file"> Memorándum de una página</a>',
      'nav-link-05' : 'Preguntas frecuentes',
      'nav-link-06' : 'Soporte técnico',
	  'nav-link-07' : 'Ponte en contacto con nosotros',

      'promo-01' : 'rápido',
      'promo-02' : 'tasa de validación <b>inferior a 3 segundos</b>. Rendimiento <b>superior a 50,000 TPS</b>.',
      'promo-03' : 'seguro',
      'promo-04' : 'protegido por <b>5 algoritmos de consenso diferentes</b>',
      'promo-05' : 'descentralizado',
      'promo-06' : '<b>cualquier persona puede añadir nodos</b> de transacción a la red #MetaHash',


      'descr-01' : 'basada en Blockchain 2.0',
      'descr-02' : '<span class="cripto-title -title-part01 --eng">cripto</span><span class="cripto-title -title-part02 --eng">moneda</span>',
      'descr-03' : 'and decentralized ecosystem',
      'descr-04' : 'basada en Blockchain 2.0',


      'promo-appint-01' : '<span class="part-name">para&nbsp;</span>almacenamiento',
      'promo-appint-03' : 'de cualquier información en Blockchain con protección criptográfica <b>4k</b> y <b>multifirma</b>',
      'promo-appint-04' : '<a href="#private-round" class="btn -default">Ronda A del ICO<i class="icon icon_link"></i></a>',
      'promo-appint-05' : 'transacciones<span class="part-name">&nbsp;</span>',
      'promo-appint-06' : '<b>hasta un máximo de 3 segundos para aprobar</b> dentro de la red #MetaHash y fuera de ella',
      'promo-appint-07' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Descargar el Libro Blanco<i class="icon icon_dowload"></i></a>',
      'promo-appint-08' : 'intercambio<span class="part-name">&nbsp;de cualquier activo</span>',
      'promo-appint-10' : '<b>todos los activos digitales</b> de la cartera #MetaGate utilizan <b>el token ERC20</b> en todos los servicios de intercambio',
      'promo-appint-11' : '<a href="docs/MetaHash_OnePager_ES.pdf" target="_blank" class="btn -download">Descargar memorándum de una página<i class="icon icon_dowload"></i></a>',
      'promo-appint-12' : '<a href="#private-round" class="btn -default -mega" >Ronda A del ICO</a>',
      'promo-appint-13' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Libro Blanco</a>',
      'promo-appint-14' : '<a href="docs/MetaHash_OnePager_ES.pdf" target="_blank" class="btn -download float-right">Memorándum de una página</a>',
      'promo-appint-15' : 'Download #MetaGate client',

      'whatis-01' : '¿Qué es #MetaHash?',
      'whatis-02' : '#MetaHash es una red de próxima generación basada en la tecnología Blockchain 2.0 para compartir activos digitales, así como una plataforma para crear y gestionar aplicaciones y servicios descentralizados en tiempo real',
      'whatis-03' : 'Cuatro componentes del sistema:',
      'whatis-04' : '#TraceChain',
      'whatis-05' : 'El Blockchain más rápido y seguro',
      'whatis-06' : 'Más de cinco  <b>mil millones de transacciones al día</b>, no más de tres segundos para validar una transacción',
      'whatis-07' : 'Sobre #TraceChain',
      'whatis-08' : '#MetaApps',
      'whatis-09' : 'Nueva generación de Smart Contracts',
      'whatis-10' : '<b>Aplicaciones descentralizadas en tiempo real</b> que se operan como servicios web regulares y se desarrollan con la ayuda de cualquier lenguaje de programación, incluidos C++, PHP y Solidity, entre otros',
      'whatis-11' : 'Sobre #MetaApps',
      'whatis-12' : '#MetaGate',
      'whatis-13' : 'Internet descentralizado',
      'whatis-14' : 'Directorio de aplicaciones descentralizadas y <b>una cartera de múltiples activos</b> que no sobrecargará tu ordenador',
      'whatis-15' : 'Sobre #MetaGate',
      'whatis-16' : '#MetaHashCoin',
      'whatis-17' : 'Activo de intercambio de la red #MetaHash',
      'whatis-18' : '<b>#MetaHashCoin</b> se utiliza para garantizar la fiabilidad de la red, intercambiar servicios y regular su autofinanciación y desarrollo',
      'whatis-19' : 'Sobre #MHC',


      'tracechain-01' : '#TraceChain',
      'tracechain-02' : 'Blockchain 2.0 rápido y seguro',
      'tracechain-03' : 'Mas de',
      'tracechain-04' : '100.000',
      'tracechain-05' : 'transacciones por segundo en cada nodo',
      'tracechain-06' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download lang" >Descarga el Libro Blanco<i class="icon icon_dowload"></i></a>',
  //  'tracechain-07' : 'to approve a transaction',
  //  'tracechain-08' : 'transactions per day',
  //  'tracechain-09' : 'stages of consensus for verification',
  //  'tracechain-10' : 'Los anclajes de bloques #MetaHash <span class="blue">en redes Bitcoin y Ethereum</span>',
      'tracechain-11' : '<img class="tracechain-svg" src="img/graphical/tracechain-es.svg" alt="">',


      'speed-work-01' : 'La velocidad sin precedentes y la descentralización de la red #TraceChain convierten a #MetaHash en el buque insignia de Blockchain',
      'speed-work-02' : 'Completa la cantidad de transacciones que quieras en la red <b>#MetaHash</b>',
      'speed-work-03' : 'El coste por transacción es menor que en cualquier Blockchain normal',
      'speed-work-04' : 'Coste de almacenamiento de datos razonable con <b>#TraceChain</b> para proyectos descentralizados',
      'speed-work-05' : 'Cualquier activo puede ser tokenizado en <b>#MetaHashCoin</b> para que circule en #MetaHash, Ethereum y otras redes',


      'speeds-01' : '¿Cómo hemos conseguido esta rapidez?',
      'speeds-02' : 'Las transacciones comienzan en el radio exterior y luego se ejecutan en la red central utilizando la ruta más rápida.',
      'speeds-03' : 'Cada etapa aprueba una transacción en su camino hacia el núcleo.',
      'speeds-04' : 'Los nodos más rápidos de la red central sincronizan las transacciones entre ellos.',
      'speeds-05' : 'La red central devuelve el saldo de las carteras a la red, lo cual verifica la exactitud de los cálculos.',
      'speeds-06' : 'Los datos de respaldo van al clásico Blockchain, verificando la integridad de la red.',
      'speeds-07' : 'Los anclajes (hash del bloque más largo) se almacenan en Bitcoin, Ethereum y otras redes.',
      'speeds-08' : 'No se puede dañar ni modificar la información almacenada en #MetaHash. Para hacerlo, sería necesario atacar con éxito la red #MetaHash, Bitcoin y Ethereum y otras redes.',
      'speeds-09' : 'Consulta nuestro Libro Blanco para obtener más información técnica',
      'speeds-10' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Descarga el Libro Blanco<i class="icon icon_dowload"></i></a>',


      'metaapps-01' : '#MetaApps',
      'metaapps-02' : 'Servicio en la nube para aplicaciones inteligentes en tiempo real',
      'metaapps-03' : '#MetaApps es una evolución de Smart Contracts y se puede usar para descentralizar cualquier servicio. Se trata de programas independientes que pueden existir para siempre y no pertenecen a nadie. Funcionan exactamente como se programaron y no pueden ser manipulados por terceros.',
      'metaapps-04' : 'Ventajas de #MetaApps',
      'metaapps-05' : 'Ejecución en tiempo real',
      'metaapps-06' : 'Tan rápido como los servicios web y las aplicaciones normales',
      'metaapps-07' : 'Cualquier diseño de interfaz gráfica de usuario (GUI)',
      'metaapps-08' : 'Puede tener la apariencia típica de aplicaciones o páginas web normales ',
      'metaapps-09' : 'Seguridad',
      'metaapps-10' : "Nadie puede cambiar el comportamiento de la aplicación eludiendo las reglas de actualización",
      'metaapps-11' : 'La imagen del sistema operativo y del programa se carga en la red y se inicia automáticamente en múltiples ordenadores.',
      'metaapps-12' : 'Se crea en cualquier lenguaje de programación, incluidos C++, PHP y Solidity, entre otros.',
      'metaapps-13' : 'Soporte completo de la funcionalidad Smart Contracts, funciona con cualquier Blockchain o simplemente con datos de Internet.',


      'metagate-01' : '#MetaGate',
      'metagate-02' : 'Portal de acceso al Internet descentralizado',
      'metagate-03' : '#MetaGate es un programa de código abierto, por lo que todos los desarrolladores pueden incorporar partes de su código en sus aplicaciones y navegadores.',
      'metagate-04' : 'Cartera multiactivos',
      'metagate-05' : 'La cartera es compatible con el "modo light" sin descargar todo el Blockchain. Los datos proceden de diferentes fuentes de la red descentralizada y son verificados por el usuario. Las claves privadas de todos los Blockchains utilizados serán almacenados únicamente por el usuario.',
      'metagate-06' : 'Catálogo de aplicaciones',
      'metagate-07' : 'Catálogo de aplicaciones descentralizadas y el navegador para trabajar con ellas. Se puede acceder a cualquier aplicación descentralizada creada en #MetaHash, no solo por el dominio de Internet estándar, sino también a través de #MetaGate o asignado a un programa independiente.',
      'metagate-08' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Descarga el Libro Blanco<i class="icon icon_dowload"></i></a>',
	  'metagate-download-button' : 'Download #Metahash',

      'metahashcoin-01' : '#MetaHashCoin (#MHC)',
      'metahashcoin-02' : 'Modelo financiero #MetaHash',
      'metahashcoin-03' : '#MetaHash es un sistema de autofinanciamiento con proceso de autodesarrollo integrado en su código genético.',
      'metahashcoin-04' : '#MetaHashCoin se utiliza para el pago:',
      'metahashcoin-05' : 'Transacciones',
      'metahashcoin-06' : 'Transacciones instantáneas y fiables de cualquier activo a un precio fijo razonable.',
      'metahashcoin-07' : 'Almacenamiento de datos',
      'metahashcoin-08' : 'Para aplicaciones que necesitan almacenar datos, pero que carecen de velocidad y volumen de datos en los sistemas Blockchain convencionales.',
      'metahashcoin-09' : 'Funcionamiento de la aplicación',
      'metahashcoin-10' : 'Cualquier aplicación descentralizada o Smart Contract requiere recursos para su implementación, incluida la propia red <b>#MetaHash</b>.',
      'metahashcoin-11' : 'Otros servicios',
      'metahashcoin-12' : 'Pago de direcciones públicas, listado en <b>#MetaApps</b>, publicidad en <b>#MetaGate</b> y otras fuentes.',
      'metahashcoin-13' : '<a href="#private-round" class="btn -default btn-mobile">Comprar #MHC<i class="icon icon_link"></i></a>',


      'minig-01' : 'Minería / forjado de #MHC',
      'minig-02' : 'Servidores',
      'minig-03' : 'Utilizado para el funcionamiento de la red de transacciones, recursos gratuitos utilizados para la operación de aplicaciones descentralizadas.',
      'minig-04' : 'Carteras #MetaGate',
      'minig-05' : 'En el modo Completo, los nodos se utilizan como almacenamiento de datos y Nodos de Torrente.',
      'minig-06' : '#MetaHashCoins',
      'minig-07' : 'Fortalecen la seguridad del consenso sobre el modelo de votación híbrido para los componentes PoW + PoS.',
      'minig-08' : 'Las #MHC recibidas de la venta de servicios se utilizan para:',
      'minig-09' : 'la formación de los desarrolladores que crean sus proyectos en #MetaHash',
      'minig-10' : 'la mejora de la calidad del proyecto',
      'minig-11' : 'la promoción de #MetaHash',
      'minig-12' : 'pagar a los propietarios de #MetaHashCoins para apoyo de consenso',
      'minig-13' : 'pagar a los propietarios de los servidores y los ordenadores',


      'compare-00' : 'Proyecto',
	  'compare-01' : 'Ventajas de #MetaHash',
      'compare-02' : 'Después de buscar y no encontrar ningún proyecto que trabajase en la creación de un circuito totalmente descentralizado y sincronizado capaz de procesar rápidamente la cantidad de datos necesarios para el mundo, decidimos crear #MetaHash.',
      'compare-03' : 'Tabla comparativa de los principales sistemas Blockchain',
      'compare-04' : 'Tiempo de aprobación <br />de transacciones',
      'compare-05' : 'Transacciones por segundo (TPS)',
      'compare-06' : 'Tiempo de aprobación<br />de transacciones',
      'compare-07' : 'Bitcoin',
      'compare-08' : '10 minutos',
      'compare-09' : 'hasta 12',
      'compare-10' : 'alto',
      'compare-11' : 'Ethereum',
      'compare-12' : '15 segundos',
      'compare-13' : 'hasta 30',
      'compare-14' : 'alto',
  //    'compare-15' : 'Plasma',
  //    'compare-16' : '15 segundos',
  //    'compare-17' : 'hasta 30',
  //    'compare-18' : 'alto',
      'compare-19' : 'EOS',
      'compare-20' : '5 segundos',
      'compare-21' : 'de 1.000 a millones',
      'compare-22' : 'mínimo',
      'compare-23' : '#MetaHash',
      'compare-24' : 'hasta 3 segundos',
      'compare-25' : 'de 50.000 a millones',
      'compare-26' : 'alto',
      'compare-27' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Descarga el Libro Blanco<i class="icon icon_dowload"></i></a>',


      'timemap-01' : 'Mapa de ruta',
      'timemap-02' : 'La parte técnica del proyecto se basó en los logros de AdSniper, que se creóo entre 2012 y 2017 en el campo de las tecnologías publicitarias.',
      'timemap-03' : "Recibimos muchas solicitudes de diferentes empresas para la aplicación de tecnología Blockchain y llegamos a la conclusión de que las tecnologías actuales no podían satisfacer las solicitudes de dichos tipos de sistemas. Entonces, en 2016, comenzamos a desarrollar nuestro propio protocolo #TraceChain.",
      'timemap-04' : 'En 2017, creamos las versiones alfa y beta del protocolo #TraceChain y unimos fuerzas con las empresas y las personas más sólidas de los campos del marketing internacional y el desarrollo empresarial.',
      'timemap-05' : '2012-2016',
      'timemap-06' : 'A network library for receiving signals, working on C++ and capable of simultaneously receiving and sending more than 100,000 requests per second to one inexpensive standard server',
      'timemap-07' : 'A network library for synchronizing signals within a cluster that manages gigantic data flows between cluster machines.',
      'timemap-08' : 'A machine learning system that decides in 40 milliseconds to respond to a signal taking into account multifactorial interrelationships.',
      'timemap-09' : 'Own analogue of Hadoop’s for similar systems in C ++ for distributed processing of large data.',
      'timemap-11' : '2017',
      'timemap-12' : 'Development of #TraceChain protocol (Alpha version)',
      'timemap-13' : 'Development of #TraceChain protocol (Beta version)',
      'timemap-14' : '<b>AdNow</b> team joins us',
      'timemap-15' : '<b>Agranovsky IT</b> team joins us',
      'timemap-16' : 'Formation of <b>Business Development team</b>',
      'timemap-17' : 'Formation of <b>Operational Team</b>',
      'timemap-18' : '2018',


      'timemap-19' : '#MetaHash website official launch',
      'timemap-20' : 'Start of the Operational Team office construction',
      'timemap-21' : 'Onboarding of experts and advisors',
      'timemap-22' : 'Development of #MetaGate (v.1.0). Multi-asset wallet featuring the ability to transfer #MetaHashCoins between wallets on multiple servers that stores data on transactions between crypto wallets.',
      'timemap-23' : 'Development of #TraceChain (v.1.0)',
      'timemap-23a': 'Development of #TraceChain (v.2.0). #TraceChain data download API',
      'timemap-24' : 'Development of #MetaICO (v.1.0). The ICO interface on the #MetaHash platform that accepts assets from various blockchains (Bitcoin and Ethereum), distributes tokens in the #MetaHash network and carries out multichain transactions, including ERC20 in the Ethereum network',
      'timemap-25' : 'Development of #MetaChains (v.1.0). Converting #MetaHashCoins to ERC20 and withdrawing them to the Ethereum network so that #MHC holders can choose which network to use and automatically convert ERC20 tokens into #MetaHashCoins',

      'timemap-26' : 'Development of #MetaApps (v.1.0). Application Platform',
      'timemap-27' : 'Testnet data download API',
      'timemap-28' : 'Opening of the Operational Team office',


      'timemap-29' : 'ICO Round A scheduled start',
      'timemap-30' : 'Development of #MetaChains (v.2.0). API featuring transaction history and balance  of wallets associated with different blockchain platforms. Decentralized application containing information about transactions in the Ethereum and Bitcoin networks which is necessary to provide blockchain interoperability in #MetaApps',
      'timemap-31' : 'Release of <b>#MetaGate (v.2.0)</b>. Encrypted messenger for public notifications and messaging between wallets',
      'timemap-32' : 'Release of <b>#TraceChain (v.3.0)</b>. Peer nodes that connect to TestNet to be installed on any server',
      'timemap-33' : '#TraceChain (v.4.0). Network core performance testing service (1,000,000+ transactions per second)',
      'timemap-34' : '#MetaICO (v.2.0). Interface for creating tokens inside the network #MetaHash',
      'timemap-35' : '#MetaICO (v.3.0). Release of ICO project platform at #MetaHash.',
      'timemap-36' : '#TraceChain (v.4.0). Voting functions in the #MetaHash network',
      'timemap-37' : '#TraceChain (v.5.0). AI managing the routing of signals between nodes for providing maximum speed of #MetaHash block creation and bandwidth and 100 test nodes in different geographical locations for testing node interaction',

      'timemap-38' : '#MetaICO (v.4.0). Release of the #MetaToken application, tokenization of ETH, ERC20, Bitcoin to #MetaHashCoin for use in the #MetaHash network',
      'timemap-39' : '#TraceChain (v.6.0). #MetaStorage, service for decentralized applications',
      'timemap-40' : '#MetaApps (v.2.0). The platform for self-deployment of third-party decentralized applications',
      'timemap-41' : '#MetaGate (v.3.0). Final release of #MetaGate wallet for Mac/Win/Unix/Android/iOS with #MetaApps catalogue',


      'timemap-42' : '<b>#TraceChain (v.7.0). Start of forging </b>',
      'timemap-43' : '<b>Inicio de la Ronda B del ICO o conclusión del Acuerdo de inclusión en el listado con el criptointercambio debidamente organizado y regulado</b>',
      'timemap-44' : 'Anuncio de plan adicional',


      'timemap-45' : 'Extensive security testing',
      'timemap-46' : 'Source code release upon the completion of testing',
      'timemap-47' : 'Launch of a fully decentralized system',
      
      'timemap-100' : 'Leer más',
	  'timemap-101' : 'Ocultar eventos',
	  'timemap-102' : 'Otros eventos',


      'teambanner-01' : 'Nuestro equipo',
      'teambanner-02' : '#MetaHash es un proyecto estructurado de equipo abierto, que da la bienvenida a todo tipo de personas y empresas.',
      'teambanner-03' : 'Si crees que puedes ser de ayuda y quieres unirte al equipo, <a class="team-write" href="mailto:hello@metahash.org">solicita participar</a> en la Ronda privada con un mínimo de 1.0 ETH.',
      'teambanner-04' : '<a href="#private-round" class="btn -default">Ronda A del ICO<i class="icon icon_link"></i></a>',
      'teambanner-05' : 'If you believe you can be of help and want to join the team, please <a href="mailto:hello@metahash.org">contact us</a>.',
      'teambanner-06' : 'Ronda A del ICO',
      'teambanner-07' : '<img src="img/graphical/People_ES@3x.svg" alt="">',

      'team-hidden-01' : 'A beneficio del proyecto, se revelan los nombres del resto de integrantes del equipo',

      'team-dev-00' : 'Desarrollo',
	  'team-dev-01' : 'Gleb Nikitin',
	  'team-dev-01a' : 'Cofundador, Socio, CRO <a href="http://www.facebook.com/glebnikitin" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="https://www.linkedin.com/in/glebnikitin/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
      'team-dev-02' : 'Oleg Romanenko',
      'team-dev-03' : 'CSA, arquitecto de servicios en tiempo real en AdSniper y analista de sistemas del sistema bancario en línea de AlfaBank. Creador de una biblioteca de red de alta carga capaz de servir más de 1 millón de solicitudes por segundo en 1 nodo.',
      'team-dev-04' : 'Mikhail Zarutskiy',
      'team-dev-05' : 'CTO, Director de AI, Big Data y equipos de servicios en tiempo real para crear Razoom AI capaz de gestionar millones de solicitudes en tiempo real combinando cálculos de redes neuronales con otros algoritmos de aprendizaje automático.',
      'team-dev-06' : 'Sergey Raylyan',
      'team-dev-07' : "CIO, planifica y coordina la implementación de docenas de tecnologías e interfaces diferentes que forman la pila tecnológica de AdSniper.",
      'team-dev-08' : '29 empleados AdSniper <i class="icon icon_link"></i>',
      'team-dev-09' : "En los últimos 10 años, la empresa ha creado redes de publicidad de alta carga. El gran procesador de datos propiedad de la compañía incorpora servicio de petabytes de datos, bases de datos rápidas NoSQL y SQL, sistemas de inteligencia artificial y bibliotecas C++ para servicios publicitarios de alta carga, procesando solicitudes de publicidad desde Internet.",
      'team-key-staff' : 'Personal clave',


      'team-mark-00' : 'Márketing',
	  'team-mark-01' : 'Vladimir Bashkin',
	  'team-mark-01a' : 'CEO de AdNow, CMO <a href="http://www.facebook.com/vladimir.bashkin" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="http://www.linkedin.com/in/vladimir-bashkin-18877678/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
      'team-mark-02' : 'Red publicitaria con más de mil millones de impresiones al día. Uno de los equipos más fuertes del mundo para comprar publicidad en todas las redes de publicidad con su propio personal de traductores y especialistas en publicidad en los mercados locales.',
      'team-mark-03' : '89 empleados AdNow <i class="icon icon_link"></i>',
      'team-mark-04' : 'Artem Kravchenko',
      'team-mark-05' : 'Director de eventos - Director de RR.PP.. CEO de AdDays Digital Events. Director de eventos en Bitcomo Affiliate Network',
      'team-mark-06' : 'Daria Baranova',
      'team-mark-07' : 'Director de afiliados - Director de ventas editoriales de AdNow. Director Gerente de la Oficina de Moscú',
      'team-mark-08' : 'Pham Thành Trung',
      'team-mark-09' : "Jefe del Departamento de anunciantes: Jefe del Departamento de ventas en la región asiática de AdNow. Gerente de Ventas y Desarrollo empresarial de AdNow",


      'team-fin-00' : 'Desarrollo empresarial',
	  'team-fin-01' : 'Anton Agranovsky',
	  'team-fin-01a' : 'Cofundador, Socio, CBDO <a href="https://www.facebook.com/aagranovsky" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="https://www.linkedin.com/in/anton-agranovsky-57427a15a/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
      'team-fin-02' : 'Agranovsky IT - empresa de inversión, invierte en nuevas empresas de TI y acompaña el crecimiento de la empresa desde que nace la idea hasta su salida a bolsa. Su fundador, Anton Agronovsky, es inversor, experto, líder de opinión en el campo del establecimiento y desarrollo de empresas de TI. Miembro de la junta de Plastic Media y SMX Communications. En 2008-2017: fundador y presidente de Destiny Development, una de las primeras empresas de juegos en el mercado ruso de Internet, conocida tanto por sus propios desarrollos como por sus localizaciones. <br />&nbsp;<br /><a href="https://goo.gl/fJVjfK" class="link -link-small" target="_blank">Colaborador de la revista Forbes</a>',
      'team-fin-03' : '11 empleados Agranovsky IT <i class="icon icon_link"></i>',
      'team-fin-04' : 'Gennady Yakunin',
      'team-fin-05' : 'CEO - Organización de contabilidad en holdings. Más de 10 años de experiencia en proyectos de TI y juegos',
      'team-fin-06' : 'Svetlana Rudenok',
      'team-fin-07' : 'Directora General adjunta - Experta en Evaluación de riesgos, más de 10 años de experiencia en la auditoría de proyectos nuevos y activos en las industrias de TI y juegos',
      'team-fin-08' : 'Andrey Korostelev',
      'team-fin-09' : 'Director Financiero - Más de 10 años de experiencia en gestión financiera de proyectos de TI y juegos. Defensor activo de proyectos sociales y de caridad',


      'team-oper-00t' : 'Equipo operacional',
	  'team-oper-01' : 'Dmitry Ushakov',
      'team-oper-02' : '<span style="color:#ffffff;">COO, General PM</span><br/>Más de 11 años de experiencia en gestión operativa de proyectos multiusuario para Game Insight y otras startups de TI',
      'team-oper-03' : 'Michaił Iwanow',
      'team-oper-04' : '<span style="color:#ffffff;">Director artístico</span><br/>Con más de 16 años de experiencia en diseño visual y de productos. Ha trabajado en proyectos para RUSNANO, Sony, Canon y Nikon, entre otras compañías',
      'team-oper-05' : 'Zhibo Fan',
      'team-oper-06' : '<span style="color:#ffffff;">CBDO para Asia, MENA</span><br/>Fundador de la plataforma de juegos Game.ru y editor de juegos en INFIPLAY',
      'team-oper-07' : 'Alexander Zhigarenko',
      'team-oper-08' : '<span style="color:#ffffff;">CBDO para Rusia, CIS</span><br/>Más de 10 años de experiencia editorial, operativa y de desarrollo comercial para Destiny.Games y en la industria de los videojuegos',
      'team-oper-09' : 'Eugenia Sigacheva',
      'team-oper-10' : '<span style="color:#ffffff;">Socia de Asuntos Públicos</span><br/>más de 18 años de experiencia en Marketing Internacional y Relaciones Públicas, así como en Tecnologías de la Información e Innovaciones. Eugenia es parte del equipo internacional del conocido robot Sophia y CEO y fundadora de la Plataforma IHEART.',
      'team-oper-11' : 'Andrey Akimov',
      'team-oper-12' : '<span style="color:#ffffff;">Chief Communication Officer</span><br/>More than 15 years in marketing and PR in gaming, entertainment, and IT business. Former head of PR and marketing at My.com, Mail.Ru Group, Game Insight, and other companies.',
      'team-oper-00' : '17 empleados Equipo operativo <i class="icon icon_link"></i>',


      //'legal-01' : 'Apoyo jurídico',
      //'legal-02' : 'Anastasia Pichugina',
      //'legal-03' : 'Socia Directora de ANP Law  <a href="https://www.facebook.com/people/Anastasia-Pichugina/1520204010" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
      //'legal-04' : 'Ekaterina Myznikova',
      //'legal-05' : 'Abogada experimentada - Jefa de la práctica de proyectos Blockchain. Ha acompañado con éxito varios proyectos ICO, ha sido participante y oradora en conferencias y seminarios web de alto nivel.',
      //'legal-06' : 'Maxim Mekhriakov',
      //'legal-07' : 'Abogado experimentado - Jefe de Práctica Comercial dentro de la ANP Law, especializado en apoyo jurídico de transacciones comerciales y de inversión.',
      //'legal-08' : 'Anna Shevchenko',
      //'legal-09' : 'Abogada - Apoyo jurídico para empresas rusas y extranjeras en el campo de los derechos de propiedad intelectual, incluido el registro de marcas comerciales y patentes.',
      //'legal-10a' : 'ANP Law Firm',
	  //'legal-10' : 'Expertos en derecho internacional y ruso. Nuestros abogados se graduaron en las facultades de derecho más prestigiosas de Rusia y del extranjero. La Socia Gerente, Anastasia, cuenta con una experiencia única, así como profundos conocimientos en derecho ruso y extranjero, es la representante legal de confianza de varias compañías extranjeras del mercado de IT y FMCG. Anastasia ha representado exitosamente a varias compañías extranjeras ante los tribunales rusos.',
      //'legal-11' : '<a href="docs/MetaHash_LegalOpinion_ES.pdf" target="_blank">Descargar Opinión legal #MetaHashCoin<i class="icon icon_link"></i></a>',
      'legal-title' : 'Legal Department',

    //'legal-14' : 'Maria Agranovskaya',
    //'legal-15' : 'Chief Legal Coordinator <a href="https://www.facebook.com/magranovskaya" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a> <a href="https://www.linkedin.com/in/maria-agranovskaya-151334/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
    //'legal-16' : '<span>Attorney at Law with 20+ years of experience. Started working with cryptocurrency issues back in 2010. MGIMO MID of Russia (International Law), studied in Germany and Holland. 8,5 years - running a multifamily office, worked on various cross-border transactions, investments, asset management, deal and corporate structuring in various jurisdictions, M&A, international taxation and other matters.</span><span>Areas: fintech, finance, telecom, banking, energy, pharmaceuticals, real estate and other sectors.</span><span>2007: setup of GRAD Attorney Bar (managing partner,  30+ Russian and foreign lawyers)</span><span>Substantially engaged in blockchain technology, ICO (TGE) related projects, trading and finance regulations, funds and financial activity.</span><span>Speaks English, German, French, Italian, </span>',
	 
	  'legal-more' : 'Leer más',
	  'legal-less' : 'Ocultar eventos',
	  'legal-17' : 'Andrey Mironov <a href="http://www.linkedin.com/in/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a> <a href="https://www.facebook.com/" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
	  'legal-18' : 'Chief of Legal Department',
	  'legal-19' : 'Graduated MGIMO in 2000 at the international law faculty. Legal practice in the field of new technologies, media and intellectual property for more than 15 years.',
	  'legal-19a' : 'He worked at the Art. Lebedev Studio, Odnoklassniki, the Russian office of Myspace, on the channels MTV, Discovery, Amedia and the online cinema Amediateka. Helped to develop the EKSMO publishing house, the Fox TV channel. Expert at the Russian Association of Electronic Communications (RAEC).<br>Secondary Education: Consultant Psychologist',
	  'legal-20' : 'Maria Agranovskaya',
	  'legal-21' : 'Chief Legal Coordinator',
	  'legal-22' : 'Attorney at Law with 20+ years of experience. Started working with cryptocurrency issues back in 2010.',
	  'legal-22a' : 'MGIMO MID of Russia (International Law), studied in Germany and Holland. 8,5 years - running a multifamily office, worked on various cross-border transactions, investments, asset management, deal and corporate structuring in various jurisdictions, M&A, international taxation and other matters. Areas: fintech, finance, telecom, banking, energy, pharmaceuticals, real estate and other sectors. 2007: setup of GRAD Attorney Bar (managing partner,  30+ Russian and foreign lawyers). Substantially engaged in blockchain technology, ICO (TGE) related projects, trading and finance regulations, funds and financial activity. Speaks English, German, French, Italian,  Spanish.',
	  'legal-23' : 'Katya Fisher',
	  'legal-24' : 'Partner, Principal at The Law Office of Katya Yoffe PLLC',
	  'legal-25' : 'Katya Yoffe (née Fisher) is an attorney focusing on general corporate law, cross-border transactions and business immigration.',
	  'legal-25a' : 'Katya represents various prominent companies and startups doing business in the United States as well as celebrity and HNW individuals. Katya has been selected to Super Lawyers as a “Rising Star” in 2014, 2015, 2016, 2017 and 2018. <br>Katya is a graduate of New York University, the Benjamin N. Cardozo School of Law and a former Howard M. Squadron Fellow in International Media Law & Policy at the University of Oxford and Center for Global Communication Studies, University of Pennsylvania. She is admitted to practice in New York and before the United States Tax Court.',
	  'legal-26' : 'Anastasia Pichugina',
	  'legal-27' : 'ANP Law Managing Partner ',
	  'legal-28' : 'Managing partner Anastasia has a unique experience and knowledge in Russian and foreign law, is a trusted legal representative of several foreign companies.',
	  'legal-29' : 'Ekaterina Myznikova',
	  'legal-30' : 'Abogada experimentada',
	  'legal-31' : 'Jefa de la práctica de proyectos Blockchain. Ha acompañado con éxito varios proyectos ICO, ha sido participante y oradora en conferencias y seminarios web de alto nivel.',
	  'legal-32' : 'International Legal Support',
	  'legal-33' : 'Daniel G. Viola',
	  'legal-34' : 'Partner, Head of Regulatory and Compliance Group at Sadis & Goldberg LLP',
	  'legal-35' : 'Oliver Ciric',
	  'legal-36' : 'Partner at TA Advisory',
	  'legal-37' : 'Daniel G. Viola is a partner of <span class="ilegal-white">Sadis & Goldberg LLP</span> and the Head of its Regulatory and Compliance Group.  Mr. Viola has been active in the Blockchain and Virtual Currency verticals since 2014. He also served as a Senior Compliance Examiner for the <span class="ilegal-white">Northeast Regional Office of the SEC,</span> where he worked from 1992 through 1996',
	  'legal-37a' : 'During his tenure at the SEC, Mr. Viola worked on several compliance inspection projects and enforcement actions involving examinations of registered investment advisers, ensuring compliance with federal and state securities laws. Mr. Viola’s examination experience includes financial statement, performance advertising, and disclosure document reviews, as well as, analysis of investment adviser and hedge fund issues arising under ERISA and blue-sky laws. In late 2006 Mr.  Viola founded his own law firm and eventually merged it into Sadis & Goldberg’s law practice.',
	  'legal-38' : 'Experience in international jurisprudence for more than 20 years. Oliver graduated from Boston University of Law in 2006, majoring in banking and finance law, and the Geneva University of Law in 1998, specializing in "License and Law". Previous work experience:  Nationale Suisse Assurances, Matile Brosset Stickel-Cicurel & Gianninazzi, Poncet Turrettini Amaudruz Neyroud & Partners, <span class="ilegal-white">Akin Gump Strauss Hauer & Feld LLP</span> (formerly Hogan & Hartson LLP).',
	  'legal-38a' : 'Since June 2017 he has been a partner at <span class="ilegal-white">TA Advisory</span>. Mr. Ciric provides legal support for blockchain projects, and also advises on cooperation <span class="ilegal-white">with FINMA.</span><br>Languages: German, English, French, Portuguese, Russian, Serbian.',
	  'legal-39' : '<span class="ilegal-white-02">KPMG AG, Switzerland,</span> served as exclusive legal advisor to #MetaHash and its management in the evaluation of regulatory, tax and legal aspects in respect of the White Paper, which is released in preparation of a Coin offering (ICO)',
	  'legal-40' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">Libro Blanco<i class="icon icon_dowload"></i></a>',
	  'legal-41' : 'Martin Hess',
      'legal-42' : 'Partner at Wenger & Vieli AG',
	  'legal-43' : 'Martin Hess specializes in financial services and capital markets law, FinTech and the digitization of financial services. He is recognized by the Swiss Stock Exchange as an issuer representative. Martin Hess advises Swiss and foreign clients and represents them vis-à-vis supervisory authorities and in court.',
	  'legal-43a' : 'He is involved in the legal design of trading venues for digital assets, payment systems and securities settlement systems as well as central counterparties. He advises and represents clients on Initial Coin Offerings / Token Generating Events. Since 2001 Partner at Wenger & Vieli Ltd',


  //   'private-01' : 'Private Round',
   //   'private-form' : '<input type="hidden" name="form_subject" value="Private Round Application">',
   //   'private-03' : 'days',
   //   'private-04' : 'Private Round ends in',
   //   'private-05' : 'Private Round',
   //   'private-06' : 'The purpose of the Private Round is to verify the idea before the public launch',
   //   'private-07' : 'We hope to meet experts who are ready to participate in the discussion of the project before its public launch and, possibly, join the #MetaHashTeam.',
   //   'private-08' : '#MetaHash undertakes to inform all Private Round participants about terms of participation, their rights and obligations in connection with participation.',
   //   'private-09' : 'Private Round participants will be able to decide whether to remain in the project after the ICO.',
   //   'private-10' : 'Send an application to participate in the Private Round',
   //   'private-11' : 'We are not interested in the amount, but rather in your expertise. We want experts from different fields to participate in the Private Round.',
   //   'private-12' : 'Describe your expertise in cryptocurrencies. Are you ready to participate in discussion about the project?',
   //   'private-13' : 'Apply <i class="icon icon_link"></i>',
   //   'private-14' : 'Terms of Use',
   //   'private-15' : 'Privacy Policy',
   //   'private-16' : 'Private Round terms:',
   //   'private-17' : 'Do you want to participate in the Private Round or join the #MetaHashTeam?',
   //   'private-18' : 'Participation in the Private Round is public - the name or company name of the participant will be published',
   //   'private-19' : 'Private Round volume - <b>1,840 ETH</b>',
   //   'private-20' : 'The value of the #MHC - <b>0.001 ETH</b>',
   //   'private-21' : 'The volume of the Private Round is not enough to satisfy the requests of all comers',
   //   'private-22' : 'You can fill the application form before the end of the Private Round',
   //   'private-23' : 'At the end of the Private Round, the current #MetaHash team will decide on quotas for each of those wishing to participate',
   //   'private-24' : 'After the completion of the Private Round and the distribution of tasks between the current and new team members, the Ronda A del ICO will start',
   //   'private-25' : 'Private Round Application',
      'private-26' : 'Introduce tu nombre',
      'private-27' : 'Introduce tu correo electrónico',
   //   'private-28' : 'Desired amount of participation (ETH)',
   //   'private-29' : 'Additional information about yourself',


   //   'timer-day-1' : 'days',
   //   'timer-day-2' : 'days',
   //   'timer-day-3' : 'days',
   //   'timer-hour-1' : 'hour',
   //   'timer-hour-2' : 'hours',
   //   'timer-hour-3' : 'hours',
   //   'timer-minute-1' : 'minute',
   //   'timer-minute-2' : 'minutes',
   //   'timer-minute-3' : 'minutes',
   //   'timer-second-1' : 'second',
   //   'timer-second-2' : 'seconds',
   //   'timer-second-3' : 'seconds',


      'form-sent-01' : '¡Gracias!',
      'form-sent-02' : 'Tu información se ha enviado correctamente.',


      'faq-01' : 'PREGUNTAS FRECUENTES',
      'faq-02-00' : 'Sobre #MetaHash',
      'faq-02-01' : '¿Eres una entidad jurídica?',
      'faq-02-02' : 'El proceso de registro de una entidad jurídica se ha iniciado en Suiza. Por lo general, requiere tiempo llegar a un acuerdo con el gobierno suizo.',
      'faq-02-03' : '¿Dónde puedo consultar el MVP y el código de fuente abierta de #MetaHash?',
      'faq-02-04' : 'La red centralizada de #TraceChain está activa actualmente con una cartera de activos múltiples. Los códigos fuente del protocolo #TraceChain se lanzarán cuando se haya aprobado un programa de recompensas de seguridad pública para hackers y se obtenga la patente.',
      'faq-02-05' : '¿Cuál es el objetivo general del producto en sí y del token?',
      'faq-02-06' : '#MetaHashCoin se usa para intercambiarse por: transacciones, almacenamiento de datos, funciones de aplicaciones. También puede intercambiar #MHC para añadir una dirección pública, para que tu aplicación aparezca en el directorio de #MetaApp, para comprar anuncios en #MetaGate adnetwork y mucho más.',
      'faq-02-07' : '¿Cuáles son las capacidades de velocidad de vuestro Blockchain? ¿Cómo se puede conseguir un resultado así?',
      'faq-02-08' : 'Échale un vistazo a nuestro <a href="docs/MetaHash_WhitePaper_EN.pdf" class="link -link-small" target="_blank">Libro Blanco</a> obtener más información sobre las capacidades de nuestro Blockchain.',
      'faq-02-09' : '¿Vuestra moneda es explotable? ¿Existe algún beneficio para los mineros?',
      'faq-02-10' : 'Consulte el <a href="docs/MetaHash_WhitePaper_EN.pdf" class="link -link-small" target="_blank">Libro Blanco</a> obtener más detalles sobre la minería.',
      'faq-02-11' : '¿Qué sistema de prueba utilizáis: POW o POS?',
      'faq-02-12' : '#MetaHash usa un algoritmo de consenso híbrido. Se trata de un sistema multiPOS que incluye resultados de votación de nodos de red independientes.',


      'faq-03-00' : 'Ronda A/Ronda B del ICO y compra de #MHC',
      'faq-03-01' : '¿Qué métodos de pago aceptáis?',
      'faq-03-02' : 'Aceptamos solo ETH. El resto de activos digitales se deben cambiar a ETH.',
      'faq-03-03' : '',
      'faq-03-04' : '',
      'faq-03-05' : '¿Puedo participar desde una plataforma de intercambio?',
      'faq-03-06' : 'Sí. Pero solo aceptamos ETH.',
      'faq-03-07' : '',
      'faq-03-08' : '',
      'faq-03-09' : '¿Cuándo terminan las rondas pre ICO/ICO?',
      'faq-03-10' : 'La Ronda A del ICO durará hasta que se alcance la cantidad objetivo. La Ronda B del ICO comenzará después de que se lance el MVP',
      'faq-03-11' : '¿Cuáles son los términos especiales de la cartera de activos múltiples de #MHC?',
      'faq-03-12' : 'La cartera de activos múltiples de #MetaGate es un producto de código abierto. Su uso se financia con los pagos de los anuncios que se muestran y las suscripciones para el bloqueo de anuncios.',


      'faq-04-00' : '#MetaHashCoin y sus perspectivas',
      'faq-04-01' : '¿Cuáles son las principales diferencias entre #MetaHash y cualquier otro proveedor de Blockchain?',
      'faq-04-02' : 'Todos los competidores existentes son lentos o están centralizados. La próxima generación de Blockchains debe ser rápida, totalmente descentralizada y ofrecer transacciones económicas. No hay ningún proyecto existente (excepto #MetaHash) que cubra todos estos requisitos.',
      'faq-04-03' : '¿Se emite #MHC ERC20 a través del Smart Contract de ETH?',
      'faq-04-04' : '#MHC es una moneda independiente que se opera en una cadena independiente. Sin embargo, existen algunos contratos espejo en Ethereum y #MetaHash. Estos contratos espejo permiten el procedimiento de tokenización de tokens ERC20 en ambas direcciones.',
      'faq-04-05' : '¿Cuál es el suministro total en tokens?',
      'faq-04-06' : '92.000.000 de #MHC se lanzarán en un plazo de 10 años. 46.000.000 de #MHC se lanzarán durante el primer año.',
      'faq-04-07' : '¿Qué plataformas de intercambio comercializarán las #MetaHashCoins?',
      'faq-04-08' : 'La disponibilidad de la moneda en las plataformas de intercambio se anunciará a través de todos los canales públicos oficiales de #MetaHash. No se nos permite compartir dicha información por adelantado.',
      'faq-04-09' : '¿Cuál será el precio inicial de #MHC después del ICO una vez que llegue al mercado abierto? ¿Y después de un año?',
      'faq-04-10' : 'El coste de la #MetaHashCoin se determina por las necesidades del mercado. La #MHC se utiliza para pagar los siguientes servicios: transacciones, almacenamiento de datos, funcionamiento de la aplicación, etc. Estos factores influirán en el coste de la #MHC.',
      'faq-04-11' : '¿Cuándo comienza/finaliza la venta de tokens?',
      'faq-04-12' : 'Creemos que la Ronda A del ICO terminará a finales del 2018. La Ronda B oficial del ICO comenzará en el cuarto trimestre del 2018 o en el primer trimestre del 2019.',


      'faq-05-00' : 'Proceso de venta de #MHC',
      'faq-05-01' : '¿Hay un límite mínimo para participar en #MetaHash?',
      'faq-05-02' : 'No establecemos ningún límite mínimo. Puedes tener tantos tokens como quieras.',
      'faq-05-03' : '¿Cuándo se entregarán los tokens a los participantes?',
      'faq-05-04' : 'Las monedas #MetaHash TestNet o su sustituto ERC20 se proporcionarán cuando se complete la Ronda B del ICO',
      'faq-05-05' : '¿Qué haréis con las monedas que no se vendan?',
      'faq-05-06' : 'Todos los activos no vendidos permanecerán en #MetaHash Company',
      'faq-05-07' : 'Transferí 0.07 ETH a mi cartera de #MetaHash. ¿Cuántos tokens recibiré?',
      'faq-05-08' : 'Puedes usar nuestra calculadora interna.',
      'faq-05-09' : '¿Cómo puedo comprar #MHC si no tengo activos de criptomonedas?',
      'faq-05-10' : 'No puedes: tiene que convertir tu dinero en ETH o BTC. Puedes usar cualquier plataforma de intercambio.',



      'faq-06-00' : 'Otras preguntas',
      'faq-06-01' : 'Soy ciudadano chino o coreano, ¿es legal participar en el crowdsale #MetaHash ICO?',
      'faq-06-02' : 'Pueden participar todas las nacionalidades excepto Estados Unidos, Singapur, República Socialista de Vietnam, República Popular de China o los residentes de un país donde estén vigentes embargos y sanciones estadounidenses (a saber, Irán, Corea del Norte, Siria, Sudán o Cuba). Encontrarás más información en nuestros Términos de venta de tokens.',
      'faq-06-03' : 'Entonces, en pocas palabras, ¿qué es #TraceChain?',
      'faq-06-04' : '#TraceChain es la próxima generación de sistemas Blockchain. La solución se basa en un algoritmo de enrutamiento de autoaprendizaje autónomo. Comienza a funcionar a una velocidad de 50.000 transacciones por segundo (velocidad básica de un canal de 100 Mb/s) y aumenta añadiendo un número razonable de canales de alta velocidad. Estos canales forman el núcleo de la red #MetaHash y hacen que su funcionamiento sea estable.',
      'faq-06-05' : '¿Hard cap/soft cap?',
      'faq-06-06' : 'La soft cap se alcanza a través de los Fundadores y la Ronda privada. La hard cap no está determinada.',
      'faq-06-07' : 'He depositado 0.0067769 BTC/ETH, ¿cuándo se convertirán en tokens #MHC?',
      'faq-06-08' : "Los tokens se te proporcionarán después de seis confirmaciones en la red de Ethereum y recibirás nodos #MetaChains. Por lo general, te damos 6 horas para validar las transacciones de las redes ETH y BTC. Por favor, no te preocupes si no has recibido tus monedas en 6 horas. Envíanos un mensaje y resolveremos tu problema. Tu depósito es una transacción en sí misma. Si has realizado la transacción, te enviaremos tus monedas.",
      'faq-06-09' : '¿Cuáles son las fechas oficiales de la Ronda privada, la Ronda A y la Ronda B del ICO?',
      'faq-06-10' : 'Las fechas oficiales de los períodos de la Ronda A y de la Ronda B del ICO aún no se han determinado. Se anunciarán próximamente a través de nuestros canales públicos. Permaneced atentos y seréis los primeros en saberlo.',
      'faq-06-11' : '¿#MetaHash es una bifurcación de BTC o ETH?',
      'faq-06-12' : '#MetaHash no es una bifurcación. Se trata de un proveedor de blockchain independiente que es mucho más rápido y más seguro.',


      'support-01' : '¿Tienes alguna pregunta? ¡Ponte en contacto con nosotros!',
      'support-02' : 'Enviar',
      'support-03' : 'User question',
      'support-04' : 'Introduce tu nombre',
      'support-05' : 'Introduce tu correo electrónico',
      'support-06' : 'Tu pregunta',


      'prefooter-01' : '¡Únete al viaje!',
      'prefooter-02' : '#MetaHashTeam',
      'prefooter-03' : '<a href="#private-round" class="btn -default">Comprar #MHC<i class="icon icon_link"></i></a>',
      'prefooter-04' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Descarga el Libro Blanco<i class="icon icon_dowload"></i></a>',
      'prefooter-05' : '<a href="docs/MetaHash_OnePager_ES.pdf" target="_blank" class="btn -download">Descarga el Memorandum de una página<i class="icon icon_dowload"></i></a>',
      'prefooter-06' : 'Participe en Ronda A del ICO',
      'prefooter-07' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Libro Blanco</a>',
      'prefooter-08' : '<a href="docs/MetaHash_OnePager_ES.pdf" target="_blank" class="btn -download float-right">Memorándum de una página</a>',


      'footer-01' : '¿Qué es #MetaHash?',
      'footer-02' : 'Comprar #MetaHashCoin (#MHC)',
      'footer-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -footer-link">Libro Blanco</a>',
      'footer-04' : '<a href="docs/MetaHash_OnePager_ES.pdf" target="_blank" class="link -footer-link">Memorándum de una página</a>',
      'footer-05' : 'Preguntas frecuentes',
      'footer-06' : '<a href="docs/MetaHash_TermsOfUse_EN.pdf" target="_blank" class="link -footer-link">Términos de Uso</a>',
      'footer-07' : '<a href="docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank" class="link -footer-link">Política de privacidad</a>',
      'footer-08' : '<a href="docs/MetaHash_AntiSpam_EN.pdf" target="_blank" class="link -footer-link">Política antispam</a>',
      'footer-09' : 'Acuerdo de asesores',
      'footer-10' : '<a href="docs/MetaHash_RiskDisclosureStatement_EN.pdf" target="_blank" class="link -footer-link">Acuerdo de divulgación de riesgos</a>',
      'footer-11' : 'Redes sociales y servicios de mensajería',
      'footer-12' : 'Foros',
      'footer-13' : 'Soporte técnico en <a href="mailto:hello@metahash.org" class="link -link-small">hello@metahash.org</a>',
      'footer-14' : 'Comentarios en <a href="mailto:support@metahash.org" class="link -link-small">support@metahash.org</a>',
      'footer-15' : 'Consultas de prensa <a href="mailto:support@metahash.org" class="link -link-small">press@metahash.org</a>',
      'footer-16' : 'Oficina de prensa <a class="link -link-small">+7 926 671-67-08</a>',
	  'copyright' : 'Copyright © 2017-2018 #MetaHash. Todos los derechos reservados',

      'mobile-menu-01' : '<a href="#whatis" class="link -link-white">¿Qué es #MetaHash?</a>',
      'mobile-menu-02' : '<a href="#private-round" class="link -link-white">Comprar #MetaHashCoin (#MHC)</a>',
      'mobile-menu-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -link-white">Descarga el Libro Blanco</a>',
      'mobile-menu-04' : '<a href="docs/MetaHash_OnePager_ES.pdf" target="_blank" class="link -link-white">Descarga el Memorandum de una página</a>',
      'mobile-menu-05' : '<a href="#faq" class="link -link-white">PREGUNTAS FRECUENTES</a>',
      'mobile-menu-06' : '<a href="#support" class="link -link-white">Soporte técnico</a>',
      'mobile-menu-07' : '<a href="#support" class="link -link-white">Contactos</a>',
	  
	  'new-mobile-menu-01' : '<a href="#whatis" class="link -link-white --offcan">¿Qué es #MetaHash?</a>',
	  'new-mobile-menu-02' : '<a href="#tracechain" class="link -link-white --offcan">#TraceChain</a>',
	  'new-mobile-menu-03' : '<a href="#metaapps" class="link -link-white --offcan">#MetaApps</a>',
	  'new-mobile-menu-04' : '<a href="#metagate" class="link -link-white --offcan">#MetaGate</a>',
	  'new-mobile-menu-05' : '<a href="#timemap" class="link -link-white --offcan">Roadmap</a>',
	  'new-mobile-menu-06' : '<a href="#advisors-and-consultants" class="link -link-white --offcan">Advisors & Consultants</a>',
	  'new-mobile-menu-07' : '<a href="#teambanner" class="link -link-white --offcan">The Team</a>',
	  'new-mobile-menu-08' : '<a href="#ico" class="link -link-white --offcan">Inicio de la Ronda A del ICO</a>',
	  'new-mobile-menu-09' : '<a href="#faq" class="link -link-white --offcan">PREGUNTAS FRECUENTES</a>',
	  'new-mobile-menu-10' : '<a href="#support" class="link -link-white --offcan">Ponte en contacto con nosotros</a>',

      'promo-soc-01' : '<a href="https://t.me/metahash_ENG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
      'promo-soc-02' : '<a href="https://www.facebook.com/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
      'promo-soc-03' : '<a href="https://vk.com/metahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
      'promo-soc-04' : '<a href="https://twitter.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
      'promo-soc-05' : '<a href="https://instagram.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
      'promo-soc-06' : '<a href="https://www.youtube.com/channel/UCIkBIrd1q7JkLLj43KgG8zA" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">youtube.com</span><span class="icon -icon-big icon_youtube"></span></a>',
      'promo-soc-07' : '<a href="#" class="link-soc -tooltype"><span class="soc-tooltype">ID:MetaHash</span><span class="icon -icon-big icon_wechat"></span></a>',
      'promo-soc-08' : '<a href="https://open.kakao.com/o/gY5dUgG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">talk.com</span><span class="icon -icon-big icon_talk"></span></a>',
      'promo-soc-09' : '<a href="https://github.com/metahashorg" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
      'promo-soc-10' : '<a href="https://www.reddit.com/user/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">reddit.com</span><span class="icon -icon-big icon_reddit"></span></a>',
      'promo-soc-11' : '<a href="https://www.linkedin.com/company/27209614/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">in.com</span><span class="icon -icon-big icon_in"></span></a>',
      'promo-soc-12' : '<a href="https://medium.com/@themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">medium.com</span><span class="icon -icon-big icon_medium"></span></a>',
      'promo-soc-13' : '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitsmedia"></span></a>',
      'promo-soc-14' : '<a href="https://bitcointalk.org/index.php?action=profile;u=1253602" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',


      'promo-soc-mobile-01' : '<a href="https://t.me/metahash_ENG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
      'promo-soc-mobile-02' : '<a href="https://www.facebook.com/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
      'promo-soc-mobile-03' : '<a href="https://vk.com/metahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
      'promo-soc-mobile-04' : '<a href="https://twitter.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
      'promo-soc-mobile-05' : '<a href="https://instagram.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
      'promo-soc-mobile-06' : '<a href="https://github.com/metahashorg" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
      'promo-soc-mobile-07' : '<a href="https://www.linkedin.com/company/27209614/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">in.com</span><span class="icon -icon-big icon_in"></span></a>',
      'promo-soc-mobile-08' : '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="link-soc"><span class="icon -icon-big --icon-forum icon_bitsmedia" target="_blank"></span></a>',
      'promo-soc-mobile-09' : '<a href="https://bitcointalk.org/index.php?action=profile;u=1253602" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',

      'tg_button' : '<a href="https://t.me/metahash_ENG" target="_blank"><img class="telega-svg" style="margin-bottom: 40px;" src="img/telegram.svg" alt=""></a>',



      'private-close-01' : 'La Ronda privada está cerrada',
      'private-close-02' : 'Se ha dado por finalizada después de que se inscribiesen 20 veces más el número de participantes admitidos.',
      'private-close-03' : 'Queremos darle las gracias a todos los participantes e invitar a todo el mundo a unirse a nosotros en la Ronda A del ICO.',
      'private-close-04' : 'Inicio de la Ronda A del ICO',
      'private-close-05' : 'mes programado de inicio',
      'private-close-06' : 'La Ronda A del ICO tendrá lugar próximamente',
      'private-close-07' : 'no te pierdas el comienzo,<br class="mobile-br">regístrate ya',
      'private-close-08' : 'Registrarse ahora <i class="icon icon_link"></i>',
      'private-close-09' : 'Mantente informado de todas las novedades:',
      'private-close-10' : 'Características de la Ronda A del ICO:',
      'private-close-11' : '<b class="mob-bold">9.200.000 #MHC</b> se distribuirán durante la Ronda A del ICO',
      'private-close-12' : 'El valor de #MHC para la Ronda A del ICO es de <b class="mob-bold">0,0125 ETH</b>',
      'private-close-13' : 'Los pedidos <b class="mob-bold">inferiores a 50 ETH</b> (12.500 #MHC) se completan con un grupo limitado general que se renueva cada 4 horas. <b class="mob-bold">Se asignan por orden de llegada</b>',
      'private-close-14' : 'Para mantener el espacio para los pequeños compradores, <b class="mob-bold">los pedidos superiores a 50 ETH</b> se completan con un grupo reservado al instante',
      'private-close-15' : '04/2018',
      'private-close-16' : 'Introduce tu correo electrónico',
      'private-close-17' : 'puede modificarse de acuerdo<br> con el Libro Blanco', 
      // 'private-close-18' : '<input id="private-close__terms-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__terms-check">I agree to </label><a href="docs/MetaHash_TermsOfUse_ES.pdf" target="_blank">Terms of Use</a>',
      // 'private-close-19' : '<input id="private-close__policy-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__policy-check">I agree to </label><a href="docs/MetaHash_PrivacyPolicy_ES.pdf" target="_blank">Privacy Policy</a> ',
      

      'private-close-18' : 'Acepto ',
      'private-close-19' : 'Acepto ',
      'private-close-25' : '<a href="docs/MetaHash_TermsOfUse_ES.pdf"  target="_blank">Términos de uso</a>',
      'private-close-26' : '<a href="docs/MetaHash_PrivacyPolicy_ES.pdf" target="_blank">Política de privacidad</a>',



      'private-close-20' : 'La Ronda privada está cerrada',
      'private-close-21' : ', thank you for your interest in <b>#MetaHash</b> project. We will keep you informed Sobre the <b>ICO Round A Start date</b>.',
      'private-close-22' : 'Dont miss a thing!',
      'private-close-23' : '<a href="https://t.me/metahash_ENG" target="_blank"  class="private-close__modal-content_tg-link" >Join our Telegram Channel<br> and stay updated</a>',
      'private-close-24' : '<a href="https://t.me/metahash_ENG" target="_blank" class="support-window__social-block_soc-link support-window__social-block_soc-link_tg"><img class="support-window__social-block_soc-img" src="img/popup/sub-tg.png" alt=""><span class="flag"><img class="support-window__social-block_flag-img" src="img/icons/flag-eng.png"></span></a>',


};