window.arrLang = window.arrLang || {};
window.arrLang["tr"] = {
    'nav-link-01' : '#MetaHash nedir?',
      'nav-link-02' : '#MHC satın alın',
      'nav-link-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -link-white"><img src="img/icon_file.svg" class="icon_file"> Tanıtım Dosyası</a>',
      'nav-link-04' : '<a href="docs/MetaHash_OnePager_TR.pdf" target="_blank" class="link -link-white"><img src="img/icon_file.svg" class="icon_file"> Tek Sayfalık Tanıtım</a>',
      'nav-link-05' : 'Sıkça Sorulan Sorular',
      'nav-link-06' : 'Destek',
	  'nav-link-07' : 'Bizimle iletişime geçin',

      'promo-01' : 'hızlı',
      'promo-02' : "<b>3 saniyenin</b> altında doğrulama. <b>50.000'in üzerinde TPS</b> (saniye başına işlem) performansı",
      'promo-03' : 'güvenli',
      'promo-04' : '<b>5 farklı konsensüs algoritması</b> ile korunur',
      'promo-05' : 'dağıtık',
      'promo-06' : '#MetaHash ağına <b>herkes işlem düğümü ekleyebilir</b>',


      'descr-01' : 'Blockchain 2.0 tabanlı',
      'descr-02' : '<span class="cripto-title -title-part01 --eng">kripto</span><span class="cripto-title -title-part02 --eng">para birimi</span>',
      'descr-03' : 'and decentralized ecosystem',
      'descr-04' : 'Blockchain 2.0 tabanlı',


      'promo-appint-01' : '<span class="part-name">depolama&nbsp;</span>için',
      'promo-appint-03' : 'her tür verinin <b>4k kripto koruma</b> ve <b>çoklu-imza</b> ile blok zincirinde saklanması',
      'promo-appint-04' : '<a href="#private-round" class="btn -default">ICO Raunt A<i class="icon icon_link"></i></a>',
      'promo-appint-05' : 'işlemler<span class="part-name">&nbsp;</span>',
      'promo-appint-06' : '#MetaHash içinde ve dışında en <b>fazla 3 saniyede onaylama</b>',
      'promo-appint-07' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Tanıtım Dosyası indir<i class="icon icon_dowload"></i></a>',
      'promo-appint-08' : 'her türlü varlığın takası',
      'promo-appint-10' : "#MetaGate cüzdanında yer alan <b>tüm dijital varlıklar</b> alım satım hizmetleri için <b>ERC20 token’i</b> kullanır",
      'promo-appint-11' : '<a href="docs/MetaHash_OnePager_TR.pdf" target="_blank" class="btn -download">Tek Sayfalık Tanıtım İndir<i class="icon icon_dowload"></i></a>',
      'promo-appint-12' : '<a href="#private-round" class="btn -default -mega" >ICO Raunt A</a>',
      'promo-appint-13' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Tanıtım Dosyası</a>',
      'promo-appint-14' : '<a href="docs/MetaHash_OnePager_TR.pdf" target="_blank" class="btn -download float-right">Tek Sayfalık Tanıtım</a>',
      'promo-appint-15' : 'Download #MetaGate client',

      'whatis-01' : '#MetaHash nedir?',
      'whatis-02' : '#MetaHash, dijital varlıkların paylaşıldığı Blockchain 2.0 teknolojisi tabanlı yeni nesil bir ağ ve dağıtık uygulamaların ve hizmetlerin gerçek zamanlı oluşturulduğu bir platformdur.',
      'whatis-03' : 'Sistemin dört bileşeni:',
      'whatis-04' : '#TraceChain',
      'whatis-05' : 'En hızlı ve en güvenli Blockchain',
      'whatis-06' : 'Günde beş <b>milyardan fazla işlem</b> ve her işlemin üç saniyeye kadar doğrulanması',
      'whatis-07' : '#TraceChain Hakkında',
      'whatis-08' : '#MetaApps',
      'whatis-09' : 'Yeni nesil Akıllı Sözleşmeler (Smart Contract)',
      'whatis-10' : 'Normal web hizmetleri gibi çalışan ve C++, PHP, Solidity ve benzeri herhangi bir programlama diliyle yazılmış dağıtık gerçek zamanlı uygulamalar',
      'whatis-11' : '#MetaApps hakkında',
      'whatis-12' : '#MetaGate',
      'whatis-13' : 'Dağıtık İnternet',
      'whatis-14' : 'Bilgisayarınızda aşırı yüklemeye sebep olmayacak dağıtık uygulamalar klasörü ve birden çok varlığa dayalı cüzdan',
      'whatis-15' : '#MetaGate hakkında',
      'whatis-16' : '#MetaHashCoin',
      'whatis-17' : '#MetaHash ağı takas varlığı',
      'whatis-18' : '<b>#MetaHashCoin</b>, ağın güvenilirliğini, alım satım hizmetlerini ve kendi kendini finans etmesi ile gelişimini garantilemek için kullanılır.',
      'whatis-19' : '#MHC hakkında',


      'tracechain-01' : '#TraceChain',
      'tracechain-02' : 'Hızlı ve güvenli Blockchain 2.0',
      'tracechain-03' : 'Her bir düğümde saniye başına işlem adedi',
      'tracechain-04' : '100.000',
      'tracechain-05' : '100.000’DEN FAZLA',
      'tracechain-06' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download lang" >Tanıtım Dosyası indir<i class="icon icon_dowload"></i></a>',
 //   'tracechain-07' : 'to approve a transaction',
 //   'tracechain-08' : 'transactions per day',
 //   'tracechain-09' : 'stages of consensus for verification',
 //   'tracechain-10' : '#MetaHash block anchors <span class="blue">in Bitcoin and Ethereum networks</span>',
      'tracechain-11' : '<img class="tracechain-svg" src="img/graphical/tracechain-tr.svg" alt="">',


      'speed-work-01' : 'Eşi benzeri görülmemiş hıza sahip ve dağıtık #TraceChain ağı, #MetaHash’i Blockchain’in amiral gemisi yapıyor.',
      'speed-work-02' : 'Her miktarda işlemi <b>#MetaHash</b> ağı içerisinde tamamlayın.',
      'speed-work-03' : 'İşlem maliyeti her tür Blockchain’inkinden daha düşük',
      'speed-work-04' : 'Dağıtık projeler için <b>#TraceChain</b> ile cazip veri depolama maliyeti',
      'speed-work-05' : 'Her türlü varlık <b>#MetaHashCoin</b> içinde token’leştirilerek #MetaHash, Ethereum ve diğer ağlarda sürüme sokulabilir',


      'speeds-01' : 'Bu sürati nasıl elde ettik?',
      'speeds-02' : 'İşlemler dış radyanda başlayıp sonra en kısa yoldan ağın merkezine ilerliyorlar.',
      'speeds-03' : 'Her bir aşama çekirdeğe ilerlerken bir işlemi onaylıyor.',
      'speeds-04' : 'Çekirdek ağın en hızlı düğümü, işlemleri kendi aralarında senkronize ediyor.',
      'speeds-05' : 'Çekirdek ağ, cüzdanların bakiyelerini, hesaplamaların doğruluğunu onaylayan ağa geri gönderiyor.',
      'speeds-06' : 'Yedek veri, ağ bütünlüğünü doğrulayan klasik blok zincire dâhil ediliyor.',
      'speeds-07' : 'Çapalar (anchor – en uzun bloktan olan hash), Bitcoin, Ethereum ve diğer ağlarda depolanıyor.',
      'speeds-08' : '#MetaHash üzerinde kayıtlı bilgiyi bozamazsınız veya modifiye edemezsiniz. Bunu yapabilmek için #MetaHash ağına ve aynı zamanda Bitcoin, Ethereum ve diğer ağlara yapılacak saldırının başarılı olması gerekir.',
      'speeds-09' : "Daha geniş teknik bilgi için White Paper'ı (Tanıtım Dosyası) inceleyiniz.",
      'speeds-10' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Tanıtım Dosyası indir<i class="icon icon_dowload"></i></a>',


      'metaapps-01' : '#MetaApps',
      'metaapps-02' : 'Gerçek zamanlı akıllı uygulamalar için bulut hizmeti',
      'metaapps-03' : '#MetaApps, Akıllı Sözleşmelerin evrim geçirmiş halidir ve her türü hizmeti, âdem-i merkeziyetçi yönetim yapısına dönüştürmekte kullanılır. Bunlar varlıklarını sonsuza kadar sürdürebilen bağımsız programlardır ve kimsenin malı değillerdir. Tam tamına programlandıkları gibi çalışırlar ve üçüncü taraflar tarafından kurcalanmaları mümkün değildir.',
      'metaapps-04' : '#MetaApps avantajları',
      'metaapps-05' : 'Gerçek zamanlı çalışırlar',
      'metaapps-06' : 'Normal web hizmetleri ve uygulamaları kadar hızlıdırlar',
      'metaapps-07' : 'Her türlü GUI’ya (grafik kullanıcı arayüzü) uyumludur',
      'metaapps-08' : 'Görüntüleri sıradan uygulamalara veya web sayfalarına benzeyebilir',
      'metaapps-09' : 'Güvenlik',
      'metaapps-10' : "Hiç kimse güncelleme kurallarını aşarak uygulamanın davranışını değiştiremez",
      'metaapps-11' : 'Programlar ve işletim sisteminin ağ üzerine görsel yüklemeleri çok sayıda bilgisayarda otomatik başlar.',
      'metaapps-12' : 'C++, PHP, Solidity ve diğerleri dâhil her türlü yazılım diliyle yaratılabilir.',
      'metaapps-13' : 'Akıllı Sözleşmelerin işlevselliğinin tam desteği mevcuttur, tüm blok zincirler veya internetten veriyle çalışır.',


      'metagate-01' : '#MetaGate',
      'metagate-02' : 'Dağıtık internet ağ geçidi',
      'metagate-03' : '#MetaGate, açık kaynak bir programdır, dolayısıyla geliştiriciler kodunun istedikleri kısımlarını kendi uygulamalarına veya tarayıcılarına gömebilirler.',
      'metagate-04' : 'Çoklu varlık cüzdanı',
      'metagate-05' : 'Bu cüzdan, blok zincirinin tamamının indirilmesine ihtiyaç duymayan “hafif kip” (light mode) desteği verir. Veri, dağıtık ağın farklı kaynaklarından gelir ve kullanıcı tarafından kontrol edilir. Kullanılan her türlü blok zincir özel anahtarları sadece kullanıcı tarafından saklanır.',
      'metagate-06' : 'Uygulama kataloğu',
      'metagate-07' : 'Dağıtık uygulamalar ve bunlarla çalışan tarayıcıların kataloğu. <b>#MetaHash</b> üzerinde inşa edilen tüm dağıtık uygulamalara sadece standart internet alanlarınca değil aynı zamanda <b>#MetaGate</b> aracılığıyla veya atanmış ayrı programlar tarafından da erişilebilir.',
      'metagate-08' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Tanıtım Dosyası indir<i class="icon icon_dowload"></i></a>',
	  'metagate-download-button' : 'Download #Metahash',

      'metahashcoin-01' : '#MetaHashCoin (#MHC)',
      'metahashcoin-02' : '#MetaHash finans modeli',
      'metahashcoin-03' : '#MetaHash, kodunun genetik yapısına kendi kendini geliştirme işlemi gömülmüş, bir kendi kendini finanse eden sistemidir.',
      'metahashcoin-04' : '#MetaHashCoin ödeme için kullanılır:',
      'metahashcoin-05' : 'İşlemler',
      'metahashcoin-06' : 'Uygun sabit bir fiyata her türlü varlığa ait anında ve güvenilir işlemleri.',
      'metahashcoin-07' : 'Veri depolama',
      'metahashcoin-08' : 'Veri depolama ihtiyacı olan ama geleneksel blok zincir sistemlerinin hızına ve veri hacmine sahip olmayan uygulamalar için.',
      'metahashcoin-09' : 'Uygulamanın işletimi',
      'metahashcoin-10' : 'Her dağıtık uygulamanın veya Akıllı Sözleşmenin dağıtım için <b>#MetaHash</b> ağının kendisi dahil kaynaklara ihtiyacı vardır.',
      'metahashcoin-11' : 'Diğer hizmetler',
      'metahashcoin-12' : 'Ortak adresler, <b>#MetaApps</b>’te listelenme, #<b>#MetaGate</b>’te reklam ve diğer kaynakların ödemesi.',
      'metahashcoin-13' : '<a href="#private-round" class="btn -default btn-mobile">#MHC satın al<i class="icon icon_link"></i></a>',


      'minig-01' : '#MHC madenciliği / dövmeciliği',
      'minig-02' : 'Sunucular',
      'minig-03' : 'İşlem ağının işletimi için kullanılır, ücretsiz kaynaklar dağıtık uygulamaların işletimi için kullanılır.',
      'minig-04' : '#MetaGate cüzdanları',
      'minig-05' : 'Düğümler, “Full” kipinde veri depolama ve Torrent Düğümleri için kullanılır.',
      'minig-06' : '#MetaHashCoins',
      'minig-07' : 'PoW + PoS parçaları için melez seçim modelinin konsensüs güvenliğini güçlendirir.',
      'minig-08' : 'hizmet satışından elde edilen #MHC şunlar için kullanılır:',
      'minig-09' : '#MetaHash üzerinde kendi projelerini oluşturan geliştiricilerin eğitimi',
      'minig-10' : 'proje kalitesinin artırılması',
      'minig-11' : '#MetaHash tanıtımı',
      'minig-12' : 'konsensüs desteği için #MetaHashCoins sahiplerine ödeme',
      'minig-13' : 'sunucuların ve bilgisayarların sahiplerine ödeme',


      'compare-00' : ' ',
	  'compare-01' : '#MetaHash avantajları',
      'compare-02' : 'Tamamen dağıtık ve dünyanın ihtiyaç duyduğu veri miktarını hızlı işleyebilecek senkronize devre kapasitesi yaratmak üzerine çalışan proje arayışlarımızın sonuçsuz kalması üzerine #MetaHash’i yapma kararı aldık.',
      'compare-03' : 'Ana Blok zinciri sistemlerinin karşılaştırma tablosu',
      'compare-04' : 'İşlem<br />onay süresi',
      'compare-05' : 'Saniye başına işlem (TPS)',
      'compare-06' : 'Dağıtık<br />yapı seviyesi',
      'compare-07' : 'Bitcoin',
      'compare-08' : '10 dakika',
      'compare-09' : '12’ye kadar',
      'compare-10' : 'yüksek',
      'compare-11' : 'Ethereum',
      'compare-12' : '15 saniye',
      'compare-13' : '30’a kadar',
      'compare-14' : 'yüksek',
  //    'compare-15' : 'Plasma',
  //    'compare-16' : '15 seconds',
  //    'compare-17' : 'up to 30',
  //    'compare-18' : 'high',
      'compare-19' : 'EOS',
      'compare-20' : '5 saniye',
      'compare-21' : '1.000 ila milyonlar arasında',
      'compare-22' : 'minimum',
      'compare-23' : '#MetaHash',
      'compare-24' : '3 saniyeye kadar',
      'compare-25' : '50.000 ile milyonlar arasında',
      'compare-26' : 'yüksek',
      'compare-27' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Tanıtım Dosyası indir<i class="icon icon_dowload"></i></a>',


      'timemap-01' : 'Yol haritası',
      'timemap-02' : 'Projenin teknik kısmı, reklam teknolojileri alanında 2012’de yaratılan AdSniper’ın 2017 yılına kadar elde ettiği başarıları temel aldı.',
      'timemap-03' : "Blok zincir teknolojinin uygulanması ile ilgili farklı şirketlerden çok adette talep aldık ve mevcut teknolojilerin bu tür sistemlere yönelik talepleri karşılayamadığını fark ettik. Sonuç olarak 2016’da kendi protokolümüz #TraceChain için düğmeye bastık.",
      'timemap-04' : '2017’de #TraceChain protokolünün alfa ve beta sürümlerini çıkarttık ve uluslararası pazarlama ve iş geliştirme alanlarındaki en güçlü kuruluşlar ve kişilerle kuvvetlerimizi birleştirdik.',
      'timemap-05' : '2012-2016',
      'timemap-06' : 'A network library for receiving signals, working on C++ and capable of simultaneously receiving and sending more than 100,000 requests per second to one inexpensive standard server',
      'timemap-07' : 'A network library for synchronizing signals within a cluster that manages gigantic data flows between cluster machines.',
      'timemap-08' : 'A machine learning system that decides in 40 milliseconds to respond to a signal taking into account multifactorial interrelationships.',
      'timemap-09' : 'Own analogue of Hadoop’s for similar systems in C ++ for distributed processing of large data.',
      'timemap-11' : '2017',
      'timemap-12' : 'Development of #TraceChain protocol (Alpha version)',
      'timemap-13' : 'Development of #TraceChain protocol (Beta version)',
      'timemap-14' : '<b>AdNow</b> team joins us',
      'timemap-15' : '<b>Agranovsky IT</b> team joins us',
      'timemap-16' : 'Formation of <b>Business Development team</b>',
      'timemap-17' : 'Formation of <b>Operational Team</b>',
      'timemap-18' : '2018',


      'timemap-19' : '#MetaHash website official launch',
      'timemap-20' : 'Start of the Operational Team office construction',
      'timemap-21' : 'Onboarding of experts and advisors',
      'timemap-22' : 'Development of #MetaGate (v.1.0). Multi-asset wallet featuring the ability to transfer #MetaHashCoins between wallets on multiple servers that stores data on transactions between crypto wallets.',
      'timemap-23' : 'Development of #TraceChain (v.1.0)',
      'timemap-23a': 'Development of #TraceChain (v.2.0). #TraceChain data download API',
      'timemap-24' : 'Development of #MetaICO (v.1.0). The ICO interface on the #MetaHash platform that accepts assets from various blockchains (Bitcoin and Ethereum), distributes tokens in the #MetaHash network and carries out multichain transactions, including ERC20 in the Ethereum network',
      'timemap-25' : 'Development of #MetaChains (v.1.0). Converting #MetaHashCoins to ERC20 and withdrawing them to the Ethereum network so that #MHC holders can choose which network to use and automatically convert ERC20 tokens into #MetaHashCoins',

      'timemap-26' : 'Development of #MetaApps (v.1.0). Application Platform',
      'timemap-27' : 'Testnet data download API',
      'timemap-28' : 'Opening of the Operational Team office',


      'timemap-29' : 'ICO Round A scheduled start',
      'timemap-30' : 'Development of #MetaChains (v.2.0). API featuring transaction history and balance  of wallets associated with different blockchain platforms. Decentralized application containing information about transactions in the Ethereum and Bitcoin networks which is necessary to provide blockchain interoperability in #MetaApps',
      'timemap-31' : 'Release of <b>#MetaGate (v.2.0)</b>. Encrypted messenger for public notifications and messaging between wallets',
      'timemap-32' : 'Release of <b>#TraceChain (v.3.0)</b>. Peer nodes that connect to TestNet to be installed on any server',
      'timemap-33' : '#TraceChain (v.4.0). Network core performance testing service (1,000,000+ transactions per second)',
      'timemap-34' : '#MetaICO (v.2.0). Interface for creating tokens inside the network #MetaHash',
      'timemap-35' : '#MetaICO (v.3.0). Release of ICO project platform at #MetaHash.',
      'timemap-36' : '#TraceChain (v.4.0). Voting functions in the #MetaHash network',
      'timemap-37' : '#TraceChain (v.5.0). AI managing the routing of signals between nodes for providing maximum speed of #MetaHash block creation and bandwidth and 100 test nodes in different geographical locations for testing node interaction',

      'timemap-38' : '#MetaICO (v.4.0). Release of the #MetaToken application, tokenization of ETH, ERC20, Bitcoin to #MetaHashCoin for use in the #MetaHash network',
      'timemap-39' : '#TraceChain (v.6.0). #MetaStorage, service for decentralized applications',
      'timemap-40' : '#MetaApps (v.2.0). The platform for self-deployment of third-party decentralized applications',
      'timemap-41' : '#MetaGate (v.3.0). Final release of #MetaGate wallet for Mac/Win/Unix/Android/iOS with #MetaApps catalogue',


      'timemap-42' : '<b>#TraceChain (v.7.0). Start of forging </b>',
      'timemap-43' : "<b>ICO Raunt B başlangıcı veya usulünce kurulmuş ve denetlenen kripto borsasında Kotasyon Sözleşmesi'nin tamamlanması</b>",
      'timemap-44' : 'İlave plan anonsu',


      'timemap-45' : 'Kapsamlı güvenlik testi',
      'timemap-46' : 'Testin tamamlanmasını takiben kaynak kodun açıklanması',
      'timemap-47' : 'Tamamen dağıtık sistemin lansmanı',
      
      'timemap-100' : 'Daha geniş bilgi',
	  'timemap-101' : 'Etkinlikleri gizle',
	  'timemap-102' : 'Diğer etkinlikler',


      'teambanner-01' : 'Ekibimiz',
      'teambanner-02' : '#MetaHash, açık ekip yapısına sahip bir projedir, herkesi ve her şirketi kabul eder.',
      'teambanner-03' : 'Yardımcı olabileceğinizi düşünüyorsanız ve ekibe katılmak istiyorsanız, lütfen <a class="team-write" href="mailto:hello@metahash.org">bizimle iletişime geçiniz</a>.',
      'teambanner-04' : '<a href="#private-round" class="btn -default">ICO Raunt A<i class="icon icon_link"></i></a>',
      'teambanner-05' : 'Yardımcı olabileceğinizi düşünüyorsanız ve ekibe katılmak istiyorsanız, lütfen <a href="mailto:hello@metahash.org">bizimle iletişime geçiniz</a>.',
      'teambanner-06' : 'ICO Raunt A',
      'teambanner-07' : '<img src="img/graphical/People_TR@3x.svg" alt="">',

      'team-hidden-01' : 'Projenin çıkarları için, diğer ekip üyelerinin adları açıklanır',

      'team-dev-00' : 'Geliştirme',
	  'team-dev-01' : 'Gleb Nikitin',
	  'team-dev-01a' : 'Eş-Kurucu, Ortak, CRO <a href="http://www.facebook.com/glebnikitin" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="https://www.linkedin.com/in/glebnikitin/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
      'team-dev-02' : 'Oleg Romanenko',
      'team-dev-03' : 'CSA – AdSniper’ın gerçek zamanlı hizmetlerinin mimarı ve AlfaBank online bankacılık sisteminin sistem analisti. 1 düğüm üzerinde saniyede 1 milyondan fazla isteği cevaplama kapasitesine sahip çok yük ağ kitaplığının yaratıcısı.',
      'team-dev-04' : 'Mikhail Zarutskiy',
      'team-dev-05' : 'CTO - Nöral ağlar hesaplamalarını diğer makine öğrenimi algoritmaları ile birleştirerek milyonlarca isteği gerçek zamanlı işleme kapasitesine sahip Razoom’u yaratan AI (Yapay Zekâ), Big Data ve gerçek zamanlı hizmetler ekiplerinin başı.',
      'team-dev-06' : 'Sergey Raylyan',
      'team-dev-07' : "CIO – AdSniper’ın teknoloji çatısını oluşturan düzinelerce farklı teknolojileri ve arayüzleri planlar ve koordine eder.",
      'team-dev-08' : 'AdSniper – Personel Sayısı: 29 <i class="icon icon_link"></i>',
      'team-dev-09' : "Firma, son 10 yıl içinde çok yüklü reklam ağları kurmuştur. Firmanın kendisine ait büyük veri işlemcisiyle çok yüklü reklam hizmetleri ve internetin genelinden gelen reklam isteklerinin işlemi için petabayt boyutunda veri, hızlı NoSQL ve SQL veri tabanları, yapay zekâ sistemleri ve C++ kitaplıkları hizmetlerini bünyesinde toplar.",
      'team-key-staff' : 'Kilit yöneticiler',


      'team-mark-00' : 'Pazarlama',
	  'team-mark-01' : 'Vladimir Bashkin',
	  'team-mark-01a' : 'CEO AdNow, CMO <a href="http://www.facebook.com/vladimir.bashkin" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="http://www.linkedin.com/in/vladimir-bashkin-18877678/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
      'team-mark-02' : 'Günde bir milyardan fazla gösterime sahip bir reklam ağıdır. Yerel pazarlarda bulundurduğu kendi çevirmenleri ve reklam uzmanlarıyla tüm reklam ağlarında reklam satın alan dünyadaki en güçlü ekiplerden bir tanesidir.',
      'team-mark-03' : 'AdNow – Personel Sayısı: 89 <i class="icon icon_link"></i>',
      'team-mark-04' : 'Artem Kravchenko',
      'team-mark-05' : 'Etkinlik Direktörü – PR – Direktör. AdDays Dijital Events’te CEO. Bitcomo Affiliate Network’te Etkinlik Direktörü',
      'team-mark-06' : 'Daria Baranova',
      'team-mark-07' : 'Ortaklık Direktörü – AdNow’ın Yayıncı Satış Direktörü. Moskova Ofisinin Genel Müdürü',
      'team-mark-08' : 'Pham Thành Trung',
      'team-mark-09' : "Reklamveren Departmanı Başkanı – AdNow Asya Bölgesi Satış Departmanı Başkanı. AdNow’ın Satış ve İş Geliştirme Müdürü",


      'team-fin-00' : 'İş Geliştirme',
	  'team-fin-01' : 'Anton Agranovsky',
	  'team-fin-01a' : 'Eş-Kurucu, Ortak, CBDO <a href="https://www.facebook.com/aagranovsky" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="https://www.linkedin.com/in/anton-agranovsky-57427a15a/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
      'team-fin-02' : 'Agranovsky IT – Bilişim teknolojileri sektöründeki yeni girişim şirketlerine yatırım yapan ve fikir aşamasından halka arza kadar büyümesine eşlik eden bir yatırım firmasıdır. Kurucusu Anton Agronovsky, bilişim teknolojisi şirketlerinin kurulması ve geliştirilmesi alanında yatırımcı, uzman ve kanaat önderi olarak bilinir. Plastic Media ve SMX Communications şirketlerinin yönetim kurulu üyesidir. 2008-2017 yılları arasında Rusya internet pazarında kendi geliştirmeleri ve yerelleştirmeleriyle bilinen ilk oyun şirketlerinden biri olan Destiny Development firmasının kurucusu ve başkanı görevinde bulunmuştur.<br />&nbsp;<br /><a href="https://goo.gl/fJVjfK" class="link -link-small" target="_blank">Forbes dergisine katkıda bulunur</a>',
      'team-fin-03' : 'Agranovsky IT – Personel Sayısı: 11 <i class="icon icon_link"></i>',
      'team-fin-04' : 'Gennady Yakunin',
      'team-fin-05' : 'CEO – Holding şirketlerinde muhasebe organizasyonları yapmıştır. IT ve oyun projeleri alanında 10 yıldan fazla deneyim sahibidir.',
      'team-fin-06' : 'Svetlana Rudenok',
      'team-fin-07' : 'Yardımcı CEO – Risk değerlendirme uzmanıdır, IT ve oyun endüstrilerinde yeni ve aktif projelerin denetiminde 10 yıldan fazla deneyime sahiptir.',
      'team-fin-08' : 'Andrey Korostelev',
      'team-fin-09' : 'CFO – IT ve oyun projelerinde 10 yıldan fazla finans yönetimi deneyimine sahiptir. Sosyal ve yardım projelerinin aktif destekçisidir.',


      'team-oper-00t' : 'Operasyon Ekibi',
	  'team-oper-01' : 'Dmitry Ushakov',
      'team-oper-02' : '<span style="color:#ffffff;">COO, General PM</span><br/>Game Insight ve diğer bilişim teknolojisi girişimci şirketlerin çok kullanıcılı projelerinin operasyon yönetimi alanında 11 yıldan fazla deneyime sahiptir.',
      'team-oper-03' : 'Michaił Iwanow',
      'team-oper-04' : '<span style="color:#ffffff;">Sanat Yönetmenidir</span><br/>Görsel ve ürün tasarımı alanında 16 yıldan fazla deneyime sahip. RUSNANO, Sony, Canon, Nikon ve diğer birçok firmanın projelerinde çalışmıştır.',
      'team-oper-05' : 'Zhibo Fan',
      'team-oper-06' : '<span style="color:#ffffff;">CBDO Asya, Ortadoğu ve Kuzey Afrika</span><br/>Oyun platformu Game.ru ve oyun yayıncısı INFIPLAY şirketlerinin kurucusudur.',
      'team-oper-07' : 'Alexander Zhigarenko',
      'team-oper-08' : '<span style="color:#ffffff;">CBDO Rusya, Bağımsız Devletler Topluluğu</span><br/>Oyun endüstrisinde ve Destiny.Games’de yayıncılık, operasyon ve iş geliştirme alanlarında 10 yıldan fazla deneyime sahiptir.',
      'team-oper-09' : 'Eugenia Sigacheva',
      'team-oper-10' : '<span style="color:#ffffff;">Public Affairs Partner</span><br/>More than 18 years in international Marketing & PR, also IT&Innovations. Eugenia is a part of International team of the well known robot Sophia and CEO&Founder of the IHEART Platform.',
      'team-oper-00' : 'Operasyon Ekibi Personel Sayısı: 17 <i class="icon icon_link"></i>',


      //'legal-01' : 'Hukuk Desteği',
      //'legal-02' : 'Anastasia Pichugina',
      //'legal-03' : 'ANP Kanun Genel Müdürü <a href="https://www.facebook.com/people/Anastasia-Pichugina/1520204010" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
      //'legal-04' : 'Ekaterina Myznikova',
      //'legal-05' : 'Kıdemli Avukat – Blok zincir uygulamaları başkanıdır. Çok sayıda ICO projesine başarıyla eşlik etmiştir ve yüksek profilli konferanslarda, web seminerlerinde konuşmacılık yapmıştır.',
      //'legal-06' : 'Maxim Mekhriakov',
      //'legal-07' : 'Kıdemli Avukat – ANP Law hukuk ofisinde Ticari Uygulamalar Başkanı görevinde bulunmuştur, ticari ve yatırım işlemleri hukuk desteği alanında uzmandır.',
      //'legal-08' : 'Anna Shevchenko',
      //'legal-09' : 'Avukat – Rus ve yabancı şirketlere, marka ve patent tescili dâhil fikri mülkiyet alanında hukuk desteği verir.',
      //'legal-10a' : 'ANP Law Firm',
	  //'legal-10' : 'Uluslararası ve Rusya hukuku alanlarında uzmanlaşmıştır. Bünyemizdeki avukatlar Rusya’nın ve diğer ülkelerin en saygın hukuk fakültelerinde eğitim almışlardır. Rus ve yabancı hukuk alanında özgün deneyim ve bilgi sahibi olan Genel Müdürümüz Anastasia, bileşim teknolojileri ve hızlı tüketim ürünleri piyasalarında faaliyet gösteren bir dizi uluslararası firmanın hukuk temsilcisidir. Anastasia, uluslararası firmaları Rus mahkemelerinde başarıyla temsil etmiştir.',
      //'legal-11' : '<a href="docs/MetaHash_LegalOpinion_EN.pdf" target="_blank">Hukuki Mütalaa İndir #MetaHashCoin<i class="icon icon_link"></i></a>',
      'legal-title' : 'Legal Department',
      'legal-more' : 'Daha geniş bilgi',
	  'legal-less' : 'Etkinlikleri gizle',
	  'legal-17' : 'Andrey Mironov <a href="http://www.linkedin.com/in/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a> <a href="https://www.facebook.com/" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
	  'legal-18' : 'Chief of Legal Department',
	  'legal-19' : 'Graduated MGIMO in 2000 at the international law faculty. Legal practice in the field of new technologies, media and intellectual property for more than 15 years.',
	  'legal-19a' : 'He worked at the Art. Lebedev Studio, Odnoklassniki, the Russian office of Myspace, on the channels MTV, Discovery, Amedia and the online cinema Amediateka. Helped to develop the EKSMO publishing house, the Fox TV channel. Expert at the Russian Association of Electronic Communications (RAEC).<br>Secondary Education: Consultant Psychologist',
	  'legal-20' : 'Maria Agranovskaya',
	  'legal-21' : 'Chief Legal Coordinator',
	  'legal-22' : 'Attorney at Law with 20+ years of experience. Started working with cryptocurrency issues back in 2010.',
	  'legal-22a' : 'MGIMO MID of Russia (International Law), studied in Germany and Holland. 8,5 years - running a multifamily office, worked on various cross-border transactions, investments, asset management, deal and corporate structuring in various jurisdictions, M&A, international taxation and other matters. Areas: fintech, finance, telecom, banking, energy, pharmaceuticals, real estate and other sectors. 2007: setup of GRAD Attorney Bar (managing partner,  30+ Russian and foreign lawyers). Substantially engaged in blockchain technology, ICO (TGE) related projects, trading and finance regulations, funds and financial activity. Speaks English, German, French, Italian,  Spanish.',
	  'legal-23' : 'Katya Fisher',
	  'legal-24' : 'Partner, Principal at The Law Office of Katya Yoffe PLLC',
	  'legal-25' : 'Katya Yoffe (née Fisher) is an attorney focusing on general corporate law, cross-border transactions and business immigration.',
	  'legal-25a' : 'Katya represents various prominent companies and startups doing business in the United States as well as celebrity and HNW individuals. Katya has been selected to Super Lawyers as a “Rising Star” in 2014, 2015, 2016, 2017 and 2018. <br>Katya is a graduate of New York University, the Benjamin N. Cardozo School of Law and a former Howard M. Squadron Fellow in International Media Law & Policy at the University of Oxford and Center for Global Communication Studies, University of Pennsylvania. She is admitted to practice in New York and before the United States Tax Court.',
	  'legal-26' : 'Anastasia Pichugina',
	  'legal-27' : 'ANP Law Managing Partner ',
	  'legal-28' : 'Managing partner Anastasia has a unique experience and knowledge in Russian and foreign law, is a trusted legal representative of several foreign companies.',
	  'legal-29' : 'Ekaterina Myznikova',
	  'legal-30' : 'Kıdemli Avukat',
	  'legal-31' : 'Blok zincir uygulamaları başkanıdır. Çok sayıda ICO projesine başarıyla eşlik etmiştir ve yüksek profilli konferanslarda, web seminerlerinde konuşmacılık yapmıştır.',
	  'legal-32' : 'International Legal Support',
	  'legal-33' : 'Daniel G. Viola',
	  'legal-34' : 'Partner, Head of Regulatory and Compliance Group at Sadis & Goldberg LLP',
	  'legal-35' : 'Oliver Ciric',
	  'legal-36' : 'Partner at TA Advisory',
	  'legal-37' : 'Daniel G. Viola is a partner of <span class="ilegal-white">Sadis & Goldberg LLP</span> and the Head of its Regulatory and Compliance Group.  Mr. Viola has been active in the Blockchain and Virtual Currency verticals since 2014. He also served as a Senior Compliance Examiner for the <span class="ilegal-white">Northeast Regional Office of the SEC,</span> where he worked from 1992 through 1996',
	  'legal-37a' : 'During his tenure at the SEC, Mr. Viola worked on several compliance inspection projects and enforcement actions involving examinations of registered investment advisers, ensuring compliance with federal and state securities laws. Mr. Viola’s examination experience includes financial statement, performance advertising, and disclosure document reviews, as well as, analysis of investment adviser and hedge fund issues arising under ERISA and blue-sky laws. In late 2006 Mr.  Viola founded his own law firm and eventually merged it into Sadis & Goldberg’s law practice.',
	  'legal-38' : 'Experience in international jurisprudence for more than 20 years. Oliver graduated from Boston University of Law in 2006, majoring in banking and finance law, and the Geneva University of Law in 1998, specializing in "License and Law". Previous work experience:  Nationale Suisse Assurances, Matile Brosset Stickel-Cicurel & Gianninazzi, Poncet Turrettini Amaudruz Neyroud & Partners, <span class="ilegal-white">Akin Gump Strauss Hauer & Feld LLP</span> (formerly Hogan & Hartson LLP).',
	  'legal-38a' : 'Since June 2017 he has been a partner at <span class="ilegal-white">TA Advisory</span>. Mr. Ciric provides legal support for blockchain projects, and also advises on cooperation <span class="ilegal-white">with FINMA.</span><br>Languages: German, English, French, Portuguese, Russian, Serbian.',
	  'legal-39' : '<span class="ilegal-white-02">KPMG AG, Switzerland,</span> served as exclusive legal advisor to #MetaHash and its management in the evaluation of regulatory, tax and legal aspects in respect of the White Paper, which is released in preparation of a Coin offering (ICO)',
	  'legal-40' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">Tanıtım Dosyası<i class="icon icon_dowload"></i></a>',
	  'legal-41' : 'Martin Hess',
      'legal-42' : 'Partner at Wenger & Vieli AG',
	  'legal-43' : 'Martin Hess specializes in financial services and capital markets law, FinTech and the digitization of financial services. He is recognized by the Swiss Stock Exchange as an issuer representative. Martin Hess advises Swiss and foreign clients and represents them vis-à-vis supervisory authorities and in court.',
	  'legal-43a' : 'He is involved in the legal design of trading venues for digital assets, payment systems and securities settlement systems as well as central counterparties. He advises and represents clients on Initial Coin Offerings / Token Generating Events. Since 2001 Partner at Wenger & Vieli Ltd',


   //   'private-01' : 'Private Round',
   //   'private-form' : '<input type="hidden" name="form_subject" value="Private Round Application">',
   //   'private-03' : 'days',
   //   'private-04' : 'Private Round ends in',
   //   'private-05' : 'Private Round',
   //   'private-06' : 'The purpose of the Private Round is to verify the idea before the public launch',
   //   'private-07' : 'We hope to meet experts who are ready to participate in the discussion of the project before its public launch and, possibly, join the #MetaHashTeam.',
   //   'private-08' : '#MetaHash undertakes to inform all Private Round participants about terms of participation, their rights and obligations in connection with participation.',
   //   'private-09' : 'Private Round participants will be able to decide whether to remain in the project after the ICO.',
   //   'private-10' : 'Send an application to participate in the Private Round',
   //   'private-11' : 'We are not interested in the amount, but rather in your expertise. We want experts from different fields to participate in the Private Round.',
   //   'private-12' : 'Describe your expertise in cryptocurrencies. Are you ready to participate in discussion about the project?',
   //   'private-13' : 'Apply <i class="icon icon_link"></i>',
   //   'private-14' : 'Terms of Use',
   //   'private-15' : 'Privacy Policy',
   //   'private-16' : 'Private Round terms:',
   //   'private-17' : 'Do you want to participate in the Private Round or join the #MetaHashTeam?',
   //   'private-18' : 'Participation in the Private Round is public - the name or company name of the participant will be published',
   //   'private-19' : 'Private Round volume - <b>1,840 ETH</b>',
   //   'private-20' : 'The value of the #MHC - <b>0.001 ETH</b>',
   //   'private-21' : 'The volume of the Private Round is not enough to satisfy the requests of all comers',
   //   'private-22' : 'You can fill the application form before the end of the Private Round',
   //   'private-23' : 'At the end of the Private Round, the current #MetaHash team will decide on quotas for each of those wishing to participate',
   //   'private-24' : 'After the completion of the Private Round and the distribution of tasks between the current and new team members, the Pre-ICO will start',
   //   'private-25' : 'Private Round Application',
      'private-26' : 'Adınız, soyadınız',
      'private-27' : 'E-posta adresiniz',
   //   'private-28' : 'Desired amount of participation (ETH)',
   //   'private-29' : 'Additional information about yourself',


   //   'timer-day-1' : 'days',
   //   'timer-day-2' : 'days',
   //   'timer-day-3' : 'days',
   //   'timer-hour-1' : 'hour',
   //   'timer-hour-2' : 'hours',
   //   'timer-hour-3' : 'hours',
   //   'timer-minute-1' : 'minute',
   //   'timer-minute-2' : 'minutes',
   //   'timer-minute-3' : 'minutes',
   //   'timer-second-1' : 'second',
   //   'timer-second-2' : 'seconds',
   //   'timer-second-3' : 'seconds',


      'form-sent-01' : 'Teşekkür ederiz!',
      'form-sent-02' : 'Bilginiz başarıyla iletilmiştir.',


      'faq-01' : 'Sıkça Sorulan Sorular',
      'faq-02-00' : '#MetaHash Hakkında',
      'faq-02-01' : 'Yasal tüzel bir yapı mısınız?',
      'faq-02-02' : 'Oluşumun yasal kayıt süreci İsviçre’de başlatılmıştır. İsviçre hükümeti ile mutabakata varmak genellikle zaman alır.',
      'faq-02-03' : '#MetaHash’e ait MVP ve açık kaynak kodunu nerede inceleyebilirim?',
      'faq-02-04' : 'Merkezi #TraceChain ağı şu anda çoklu-varlıklı cüzdan ile aktif durumdadır. #TraceChain protokolünün kaynak kodu, korsanlara karşı kamu için primle güvenliği koruma programı geçtikten ve patentler alındıktan sonra açıklanacaktır.',
      'faq-02-05' : 'Projenin kendisinin ve token’in ana amacı nedir?',
      'faq-02-06' : '#MetaHashCoin şunlara karşılık kullanılır: İşlemler, veri depolaması, uygulama fonksiyonları. #MHC ayrıca ortak adres eklemek, uygulamanızı #MetaApp klasöründe yayınlatmak, #MetaGate reklam ağına reklam vermek ve çok daha fazlası için de kullanılabilir.',
      'faq-02-07' : 'Blok zincirin hız kapasitesi nedir? Bu hıza nasıl ulaşabiliyorsunuz?',
      'faq-02-08' : 'Blok zincirimizin kapasiteleri hakkında daha geniş bilgi sahibi olmak için lütfen <a href="docs/MetaHash_WhitePaper_EN.pdf" class="link -link-small" target="_blank">Tanıtım Dosyamızı (White Paper)</a> inceleyiniz.',
      'faq-02-09' : 'Para biriminizin madenciliği yapılabiliyor mu? Madenciler için bir fayda sağlıyor mu?',
      'faq-02-10' : 'Madencilik konusunda daha geniş bilgi için lütfen <a href="docs/MetaHash_WhitePaper_EN.pdf" class="link -link-small" target="_blank">Tanıtım Dosyası</a> okuyunuz.',
      'faq-02-11' : 'Hangi kanıt sistemini kullanıyorsunuz; POW mu yoksa POS mu?',
      'faq-02-12' : '#MetaHash melez bir konsensüs algoritması kullanır. Bu, farklı ağ düğümlerinden seçim sonuçlarını içeren çoklu-POS sistemidir.',


      'faq-03-00' : 'ICO Raunt A / Raunt B ve #MHC satın alımı',
      'faq-03-01' : 'Hangi ödeme yöntemlerini kabul ediyorsunuz?',
      'faq-03-02' : 'Sadece ETH kabul ediyoruz. Diğer dijital varlıklar önce ETH’ye çevrilmelidir.',
      'faq-03-03' : '',
      'faq-03-04' : '',
      'faq-03-05' : 'Bir borsa platformu üzerinden katılabilir miyim?',
      'faq-03-06' : 'Evet, katılabilirsiniz. Fakat sadece ETH kabul ediyoruz.',
      'faq-03-07' : '',
      'faq-03-08' : '',
      'faq-03-09' : 'ICO Raunt A / Raunt B ne zaman tamamlanacak?',
      'faq-03-10' : 'ICO Raunt A hedeflenen miktara ulaşılıncaya kadar devam edecek. ICO Raunt B, MVP yayınlandıktan sonra başlayacak.',
      'faq-03-11' : '#MHC çoklu varlığa dayalı cüzdanın özel koşulları nelerdir?',
      'faq-03-12' : '#MetaGate çoklu varlığa dayalı cüzdan, bir açık kaynaklı kod ürünüdür. Gösterilen reklamların ve reklam engelleme aboneliklerinin geliri ile finanse edilir.',


      'faq-04-00' : '#MetaHashCoin ve Beklentiler',
      'faq-04-01' : '#MetaHash ile diğer herhangi bir blok zincir tedarikçisi arasındaki temel farklar nelerdir?',
      'faq-04-02' : 'Bütün mevcut rakipler ya daha yavaşlar ya da merkezi yapıya sahipler. Yeni nesil blok zincirler süratli olmak, tamamen dağıtık olmak ve ucuz işlem sunmak zorunda. Bütün bu şartları sağlayan (#MetaHash hariç) bir proje mevcut değil.',
      'faq-04-03' : '#MHC ERC20, tedavüle ETH Akıllı Sözleşme aracılığı ile mi çıkıyor?',
      'faq-04-04' : '#MHC, farklı bir zincirde faaliyet gösteren ayrı, bağımsız bir para birimidir. Yine de Ethereum ve #MetaHash içinde bazı ayna sözleşmeler bulunmaktadır. Bu ayna sözleşmeler ERC20 token’lerini her iki yönde token’leştirme işlemine izin vermektedir.',
      'faq-04-05' : 'Toplam token arzı nedir?',
      'faq-04-06' : 'Gelecek 10 yıl içerisinde 92 milyon #MHC tedavüle girecek. Bunun 46 milyonu ilk yıl içinde gerçekleşecek.',
      'faq-04-07' : 'Hangi borsa platformları #MetaHashCoins alım satımı yapacaklar?',
      'faq-04-08' : 'Borsa platformlarındaki müsait miktarlar #MetaHash’in resmi kamu kanallarından duyurulacak. Bu bilgiyi önceden paylaşmaya iznimiz bulunmuyor.',
      'faq-04-09' : 'ICO açık pazara çıktıktan sonra #MHC’nin ilk fiyatı ne olacak? Fiyat bir yıl sonra ne olacak?',
      'faq-04-10' : '#MetaHashCoin’in değeri pazar gereklilikleri tarafından belirlenecek. #MHC şu hizmetlerin ödemesinde kullanılır: işlemler, veri depolama, uygulama fonksiyonları, vb. Bu faktörler #MHC’nin fiyatını etkileyecek.',
      'faq-04-11' : 'Token satışı ne zaman başlayacak/bitecek?',
      'faq-04-12' : "ICO Raunt A döneminin 2018 sonu itibarıyla tamamlanmasını planlıyoruz. Resmi ICO Raunt B ise 2018'in son veya 2019'un ilk çeyreğinde başlayacak.",


      'faq-05-00' : '#MHC Satış Süreci',
      'faq-05-01' : '#MetaHash katılımı için bir alt sınır var mı?',
      'faq-05-02' : 'Bizim tarafımızdan getirilmiş bir alt sınır yok. Dilediğiniz adette token sahibi olabilirsiniz.',
      'faq-05-03' : 'Token’ler ne zaman katılımcılara temin edilecek?',
      'faq-05-04' : "#MetaHash TestNet coin'leri veya ERC20 cinsinden karşılıkları ICO Raunt B tamamlandığında temin edilecektir.",
      'faq-05-05' : 'Satılmayan kripto paraları ne yapacaksınız?',
      'faq-05-06' : 'Satılmayan tüm varlıklar #MetaHash Şirketi bünyesinde kalacak.',
      'faq-05-07' : '#MetaHash cüzdanıma 0,07 ETH transfer ettim. Kaç token alacağım?',
      'faq-05-08' : 'Dahili hesap makinemizi kullanabilirsiniz.',
      'faq-05-09' : 'Herhangi bir kripto para birimi varlığına sahip değilsem nasıl #MHC satın alabilirim?',
      'faq-05-10' : 'Alamazsınız. Paranızı ETH veya BTC’ye çevirmeniz gerekir. Dilediğiniz herhangi bir borsa platformunu kullanabilirsiniz.',



      'faq-06-00' : 'Diğer Sorular',
      'faq-06-01' : 'Ben Çin veya Kore vatandaşıyım, #MetaHash ICO kitle satışına (crowdsale) katılmam yasa dışı mı?',
      'faq-06-02' : 'Şu ülkeler hariç her ülke vatandaşı katılabilir: Birleşik Devletler, Singapur, Sosyalist Vietnam Cumhuriyeti, Çin Halk Cumhuriyeti veya Amerikan ambargo veya yaptırımların geçerli olduğu İran, Kuzey Kore, Suriye, Sudan veya Küba. Daha geniş bilgi Token Satış Koşullarında mevcuttur.',
      'faq-06-03' : 'Çok kısaca, #TraceChain nedir?',
      'faq-06-04' : '#TraceChain, yeni nesil Blok zincir sistemidir. Otomatik, kendi kendine çalışan yönlendirme tabanlı bir çözümdür. Çalışmaya saniyede 50.000 işlem hızıyla başlar (temel 100 Mb/s kanal hızı) ve makul adette yüksek hızlı kanallar ekleyerek süratini artırır. Bu kanallar #MetaHash ağının özünü oluşturur ve istikrarlı çalışmasını sağlar.',
      'faq-06-05' : 'Maksimum yatırım miktarı mı (hard cap), minimum yatırım miktarı mı (soft cap)?',
      'faq-06-06' : '“Soft cap” kurucular ve Özel Raunt aracılığıyla sağlanmıştır. Belirlenmiş “hard cap” yoktur.',
      'faq-06-07' : 'Ben, 0,0067769 BTC/ETH yatırdım; ne zaman #MHC token’ine çevrilecek?',
      'faq-06-08' : "Ethereum ağı üzerinden altı konfirmasyon ve #MetaChains düğümleri ulaştıktan sonra token’leriniz verilir. İşlemin ETH ve BTC ağlarından onaylanmasına biz genellikle 6 saat veriyoruz. Eğer 6 saat sonunda kripto paralarınızı almamışsanız lütfen endişelenmeyin. Durumu bize iletirseniz, sorun çözülecektir. Yatırdığınız tutar kendi başına bir işlemdir. Eğer işlem gerçekleştiyse, kripto paralarınız size gönderilir.",
      'faq-06-09' : 'Özel Raunt, ICO Raunt A/B ve benzerlerinin resmi tarihleri nedir?',
      'faq-06-10' : 'ICO Raunt A ve ICO Raunt B dönemlerinin resmi tarihleri henüz belirlenmedi. Çok yakında kamuya açık kanallarımızdan duyurulacaklar. Bizi izlemeye devam edin ve ilk öğrenen siz olun.',
      'faq-06-11' : '#MetaHash, BTC veya ETH çatallaşması mı (Fork)?',
      'faq-06-12' : '#MetaHash bir çatallaşma değildir. Bu, daha hızlı ve daha güvenli bir bağımsız blok zincir sağlayıcısıdır.',


      'support-01' : 'Sorunuz mu var? Bizimle iletişime geçin!',
      'support-02' : 'Gönder',
      'support-03' : 'User question',
      'support-04' : 'Adınız, Soyadınız',
      'support-05' : 'E-posta adresiniz',
      'support-06' : 'Sorunuz',


      'prefooter-01' : 'Yolculuğa sen de katıl!',
      'prefooter-02' : '#MetaHashTeam',
      'prefooter-03' : '<a href="#private-round" class="btn -default">#MHC Satın Al<i class="icon icon_link"></i></a>',
      'prefooter-04' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Tanıtım Dosyası İndir<i class="icon icon_dowload"></i></a>',
      'prefooter-05' : '<a href="docs/MetaHash_OnePager_TR.pdf" target="_blank" class="btn -download">Tek Sayfalık Tanıtım İndir<i class="icon icon_dowload"></i></a>',
      'prefooter-06' : "ICO Raunt A'ya katılın",
      'prefooter-07' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Tanıtım Dosyası</a>',
      'prefooter-08' : '<a href="docs/MetaHash_OnePager_TR.pdf" target="_blank" class="btn -download float-right">Tek Sayfalık Tanıtım</a>',


      'footer-01' : '#MetaHash nedir?',
      'footer-02' : '#MetaHashCoin (#MHC) Satın Al',
      'footer-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -footer-link">Tanıtım Dosyası</a>',
      'footer-04' : '<a href="docs/MetaHash_OnePager_TR.pdf" target="_blank" class="link -footer-link">Tek Sayfalık Tanıtım</a>',
      'footer-05' : 'Sıkça Sorulan Sorular',
      'footer-06' : '<a href="docs/MetaHash_TermsOfUse_CN.pdf" target="_blank" class="link -footer-link">Kullanım Koşulları</a>',
      'footer-07' : '<a href="docs/MetaHash_PrivacyPolicy_CN.pdf" target="_blank" class="link -footer-link">Gizlilik Politikası</a>',
      'footer-08' : '<a href="docs/MetaHash_AntiSpam_EN.pdf" target="_blank" class="link -footer-link">İstenmeyen Mesaj Politikası</a>',
      'footer-09' : 'Danışman Sözleşmesi',
      'footer-10' : '<a href="docs/MetaHash_RiskDisclosureStatement_EN.pdf" target="_blank" class="link -footer-link">Risk Açıklama Anlaşması</a>',
	  'footer-11' : 'Sosyal ağlar ve mesajlaşma uygulamaları',
      'footer-12' : 'Forumlar',
      'footer-13' : 'İletişim için: <a href="mailto:hello@metahash.org" class="link -link-small">hello@metahash.org</a>',
      'footer-14' : 'Destek için: <a href="mailto:support@metahash.org" class="link -link-small">support@metahash.org</a>',
      'footer-15' : 'Basın soruları <a href="mailto:support@metahash.org" class="link -link-small">press@metahash.org</a>',
      'footer-16' : 'Basın odası <a class="link -link-small">+7 926 671-67-08</a>',
	  'copyright' : 'Telif Hakkı © 2017-2018 #MetaHash. Tüm Hakları Saklıdır',

      'mobile-menu-01' : '<a href="#whatis" class="link -link-white">#MetaHash nedir?</a>',
      'mobile-menu-02' : '<a href="#private-round" class="link -link-white">#MetaHashCoin (#MHC) Satın Al</a>',
      'mobile-menu-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -link-white">Tanıtım Dosyası İndir</a>',
      'mobile-menu-04' : '<a href="docs/MetaHash_OnePager_TR.pdf" target="_blank" class="link -link-white">Tek Sayfalık Tanıtım İndir</a>',
      'mobile-menu-05' : '<a href="#faq" class="link -link-white">Sıkça Sorulan Sorular</a>',
      'mobile-menu-06' : '<a href="#support" class="link -link-white">Destek</a>',
      'mobile-menu-07' : '<a href="#support" class="link -link-white">İletişim</a>',
	  
	  'new-mobile-menu-01' : '<a href="#whatis" class="link -link-white --offcan">#MetaHash nedir?</a>',
	  'new-mobile-menu-02' : '<a href="#tracechain" class="link -link-white --offcan">#TraceChain</a>',
	  'new-mobile-menu-03' : '<a href="#metaapps" class="link -link-white --offcan">#MetaApps</a>',
	  'new-mobile-menu-04' : '<a href="#metagate" class="link -link-white --offcan">#MetaGate</a>',
	  'new-mobile-menu-05' : '<a href="#timemap" class="link -link-white --offcan">Roadmap</a>',
	  'new-mobile-menu-06' : '<a href="#advisors-and-consultants" class="link -link-white --offcan">Advisors & Consultants</a>',
	  'new-mobile-menu-07' : '<a href="#teambanner" class="link -link-white --offcan">The Team</a>',
	  'new-mobile-menu-08' : '<a href="#ico" class="link -link-white --offcan">ICO Raunt A Başlangıcı</a>',
	  'new-mobile-menu-09' : '<a href="#faq" class="link -link-white --offcan">Sıkça Sorulan Sorular</a>',
	  'new-mobile-menu-10' : '<a href="#support" class="link -link-white --offcan">Bizimle iletişime geçin</a>',

      'promo-soc-01' : '<a href="https://t.me/metahash_ENG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
      'promo-soc-02' : '<a href="https://www.facebook.com/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
      'promo-soc-03' : '<a href="https://vk.com/metahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
      'promo-soc-04' : '<a href="https://twitter.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
      'promo-soc-05' : '<a href="https://instagram.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
      'promo-soc-06' : '<a href="https://www.youtube.com/channel/UCIkBIrd1q7JkLLj43KgG8zA" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">youtube.com</span><span class="icon -icon-big icon_youtube"></span></a>',
      'promo-soc-07' : '<a href="#" class="link-soc -tooltype"><span class="soc-tooltype">ID:MetaHash</span><span class="icon -icon-big icon_wechat"></span></a>',
      'promo-soc-08' : '<a href="https://open.kakao.com/o/gY5dUgG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">talk.com</span><span class="icon -icon-big icon_talk"></span></a>',
      'promo-soc-09' : '<a href="https://github.com/metahashorg" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
      'promo-soc-10' : '<a href="https://www.reddit.com/user/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">reddit.com</span><span class="icon -icon-big icon_reddit"></span></a>',
      'promo-soc-11' : '<a href="https://www.linkedin.com/company/27209614/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">in.com</span><span class="icon -icon-big icon_in"></span></a>',
      'promo-soc-12' : '<a href="https://medium.com/@themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">medium.com</span><span class="icon -icon-big icon_medium"></span></a>',
      'promo-soc-13' : '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitsmedia"></span></a>',
      'promo-soc-14' : '<a href="https://bitcointalk.org/index.php?action=profile;u=1253602" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',


      'promo-soc-mobile-01' : '<a href="https://t.me/metahash_ENG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
      'promo-soc-mobile-02' : '<a href="https://www.facebook.com/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
      'promo-soc-mobile-03' : '<a href="https://vk.com/metahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
      'promo-soc-mobile-04' : '<a href="https://twitter.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
      'promo-soc-mobile-05' : '<a href="https://instagram.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
      'promo-soc-mobile-06' : '<a href="https://github.com/metahashorg" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
      'promo-soc-mobile-07' : '<a href="https://www.linkedin.com/company/27209614/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">in.com</span><span class="icon -icon-big icon_in"></span></a>',
      'promo-soc-mobile-08' : '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="link-soc"><span class="icon -icon-big --icon-forum icon_bitsmedia" target="_blank"></span></a>',
      'promo-soc-mobile-09' : '<a href="https://bitcointalk.org/index.php?action=profile;u=1253602" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',

      'tg_button' : '<a href="https://t.me/metahash_ENG" target="_blank"><img class="telega-svg" style="margin-bottom: 40px;" src="img/telegram.svg" alt=""></a>',



      'private-close-01' : 'Özel Raunt tamamlanmıştır.',
      'private-close-02' : 'Beklenenden 20 kat fazla kayıt ile sona ermiştir.',
      'private-close-03' : "Tüm katılımcılara teşekkür eder, herkesi ICO Raunt A için bize katılmaya davet ederiz.",
      'private-close-04' : 'ICO Raunt A',
      'private-close-05' : 'Başlangıcın planlandığı ay',
      'private-close-06' : 'ICO Raunt A çok yakında',
      'private-close-07' : 'Başlangıcı<br class="mobile-br">kaçırmayın ve',
      'private-close-08' : 'Başvur <i class="icon icon_link"></i>',
      'private-close-09' : 'Bizi takipte kalın:',
      'private-close-10' : 'ICO Raunt A özellikleri:',
      'private-close-11' : 'ICO Raunt A süresince <b class="mob-bold">9.200.000 #MHC</b> dağıtılacaktır.',
      'private-close-12' : 'ICO Raunt A için #MHC değeri <b class="mob-bold">0.0125 ETH</b> olarak belirlenmiştir.',
      'private-close-13' : "<b class='mob-bold'>'50 ETH</b> (12.500 #MHC) altındaki siparişler her 4 saatte bir yenilenecek limitli genel havuzdan karşılanacaktır. <b class='mob-bold'>''İlk gelene ilk hizmet'' esası uygulanacaktır.</b>",
      'private-close-14' : 'Küçük alıcılara <b class="mob-bold">imkan vermek için 50 ETH</b> üzeri siparişler ayrı rezerve havuzdan anında karşılanacaktır.',
      'private-close-15' : '04/2018',
      'private-close-16' : 'E-posta adresiniz',
      'private-close-17' : "White Paper'a (Tanıtım Dosyası)<br>bağlı olarak değişebilir", 
      // 'private-close-18' : '<input id="private-close__terms-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__terms-check">I agree to </label><a href="docs/MetaHash_TermsOfUse_EN.pdf" target="_blank">Terms of Use</a>',
      // 'private-close-19' : '<input id="private-close__policy-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__policy-check">I agree to </label><a href="docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank">Privacy Policy</a> ',
      

      'private-close-18' : 'Kabul ediyorum ',
      'private-close-19' : 'Kabul ediyorum ',
      'private-close-25' : '<a href="docs/MetaHash_TermsOfUse_EN.pdf"  target="_blank">Kullanım Koşulları</a>',
      'private-close-26' : '<a href="docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank">Gizlilik Politikası</a>',



      'private-close-20' : 'Application submitted',
      'private-close-21' : ', thank you for your interest in <b>#MetaHash</b> project. We will keep you informed about the <b>ICO Round A Start date</b>.',
      'private-close-22' : 'Dont miss a thing!',
      'private-close-23' : '<a href="https://t.me/metahash_ENG" target="_blank"  class="private-close__modal-content_tg-link" >Join our Telegram Channel<br> and stay updated</a>',
      'private-close-24' : '<a href="https://t.me/metahash_ENG" target="_blank" class="support-window__social-block_soc-link support-window__social-block_soc-link_tg"><img class="support-window__social-block_soc-img" src="img/popup/sub-tg.png" alt=""><span class="flag"><img class="support-window__social-block_flag-img" src="img/icons/flag-eng.png"></span></a>',


};