window.arrLang = window.arrLang || {};
window.arrLang["ko"] = {
    'nav-link-01' : '#MetaHash는 무엇입니까?',
    'nav-link-02' : '#MHC 구매하기',
    'nav-link-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -link-white"><img src="img/icon_file.svg" class="icon_file"> 백서</a>',
    'nav-link-04' : '<a href="docs/MetaHash_OnePager_KO.pdf" target="_blank" class="link -link-white"><img src="img/icon_file.svg" class="icon_file"> 원페이저</a>',
    'nav-link-05' : '자주 하는 질문',
    'nav-link-06' : '지원',
	'nav-link-07' : '연락주십시오',


    'promo-01' : '삐른 속도',
    'promo-02' : '3초 이하의 인증 속도. 50,000 TPS 이상의 작업 수행 능력',
    'promo-03' : '안정성',
    'promo-04' : '5개의 다른 의견 일치 알고리즘에 의한 보호',
    'promo-05' : '분산화',
    'promo-06' : '누구나 #MetaHash 네트워크에 거래 노드 추가 가능',


    'descr-01' : '블록체인 2.0 기반',
    'descr-02' : '<span class="cripto-title -title-part01 --eng">암호</span><span class="cripto-title -title-part02 --eng">화폐</span>',
    'descr-03' : 'and decentralized ecosystem',
	'descr-04' : '블록체인 2.0 기반',


    'promo-appint-01' : '저장소',
    'promo-appint-03' : '블록체인 내 어떠한 정보든 4k 암호 보호와 다중서명',
    'promo-appint-04' : '<a href="#private-round" class="btn -default">ICO 라운드 A<i class="icon icon_link"></i></a>',
    'promo-appint-05' : '거래<span class="part-name">&nbsp;</span>',
    'promo-appint-06' : '#MetaHash 네트워크 안팎에서 승인까지 최대 3초',
    'promo-appint-07' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">백서 다운로드<i class="icon icon_dowload"></i></a>',
    'promo-appint-08' : '모든 자산<span class="part-name">&nbsp;거래</span>',
    'promo-appint-10' : '#MetaGate 지갑 안의 모든 디지털 자산은 모든 거래 서비스에 ERC20 토큰을 사용합니다',
    'promo-appint-11' : '<a href="docs/MetaHash_OnePager_KO.pdf" target="_blank" class="btn -download">원페이저 다운로드<i class="icon icon_dowload"></i></a>',
    'promo-appint-12' : '<a href="#private-round" class="btn -default -mega" >ICO 라운드 A</a>',
    'promo-appint-13' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">백서</a>',
    'promo-appint-14' : '<a href="docs/MetaHash_OnePager_KO.pdf" target="_blank" class="btn -download float-right">원페이저</a>',
    'promo-appint-15' : 'Download #MetaGate client',

    'whatis-01' : '#MetaHash는 무엇입니까?',
    'whatis-02' : '#MetaHash는 디지털 자산 공유를 위한 블록체인 2.0 기술 기반의 차세대 네트워크이고, 실시간으로 분산화 앱과 서비스를 창출하고 관리할 수 있는 플랫폼입니다',
    'whatis-03' : '시스템의 4가지 구성 요소',
    'whatis-04' : '#TraceChain',
    'whatis-05' : '가장 빠르고 안전한 블록체인',
    'whatis-06' : '하루 50억 건 이상의 거래, 거래 인증에 3초 미만 소요',
    'whatis-07' : '#TraceChain 소개',
    'whatis-08' : '#MetaApps',
    'whatis-09' : '스마트 컨트랙트의 새로운 세대',
    'whatis-10' : '일반 웹 서비스처럼 작동하고 C++, PHP, Solidity 등을 포함한 프로그래밍 언어의 도움으로 개발된 분산화 실시간 애플리케이션',
    'whatis-11' : '#MetaApps 소개',
    'whatis-12' : '#MetaGate',
    'whatis-13' : '분산화 인터넷',
    'whatis-14' : '컴퓨터에 과부하를 주지 않는 분산화 앱 디렉토리 및 다중 자산 지갑',
    'whatis-15' : '#MetaGate 소개',
    'whatis-16' : '#MetaHashCoin',
    'whatis-17' : '#MetaHash 네트워크 거래 자산',
    'whatis-18' : '#MetaHashCoin은 네트워크의 신뢰도를 확인하고, 서비스를 거래하고, 자기금융 및 개발을 규제하는 데에 사용합니다',
    'whatis-19' : '#MHC 소개',


    'tracechain-01' : '#TraceChain',
    'tracechain-02' : '빠르고 안전한 블록체인 2.0',
    'tracechain-03' : '각 노드마다 초당 거래량',
    'tracechain-04' : '100,000',
    'tracechain-05' : '이상',
    'tracechain-06' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download lang" >백서 다운로드<i class="icon icon_dowload"></i></a>',
    //   'tracechain-07' : 'to approve a transaction',
    //   'tracechain-08' : 'transactions per day',
    //   'tracechain-09' : 'stages of consensus for verification',
    'tracechain-10' : '비트코인과 이더리움 네트워크 내의 #MetaHash 블록 앵커',
    'tracechain-11' : '<img class="tracechain-svg" src="img/graphical/tracechain-ko.svg" alt="">',


    'speed-work-01' : '#TraceChain 네트워크의 전례 없는 속도와 분산화가 #MetaHash를 블록체인의 주력 상품으로 만듭니다',
    'speed-work-02' : '아무리 많은 거래량도 #MetaHash 네트워크에서 완성하십시오',
    'speed-work-03' : '거래수수료가 어떠한 일반 블록체인보다 저렴합니다',
    'speed-work-04' : '분산화 프로젝트를 위한 #TraceChain의 합리적인 데이터 저장 비용',
    'speed-work-05' : '어떤 자산이라도 #MetaHashCoin으로 토큰화할 수 있고, #MetaHash와 이더리움, 다른 네트워크에서 유통시킬 수 있습니다',


    'speeds-01' : '어떻게 그러한 신속함을 이루어 냈습니까?',
    'speeds-02' : '거래는 외부 구역에서 시작되어 더 빠른 경로를 사용해 코어 네트워크로 들어옵니다.',
    'speeds-03' : '각 단계가 코어로 향하는 거래를 승인합니다.',
    'speeds-04' : '코어 네트워크의 가장 빠른 노드가 거래를 동기화합니다.',
    'speeds-05' : '코어 네트워크는 네트워크에 지갑의 잔고를 반환하고, 계산이 정확한지 판별합니다.',
    'speeds-06' : '백업 데이터는 클래식 블록체인으로 가서 네트워크 무결성을 확인합니다.',
    'speeds-07' : '앵커(가장 긴 블록에서 나온 해시)는 비트코인, 이더리움 및 기타 네트워크에 보관됩니다.',
    'speeds-08' : '#MetaHash에 저장된 정보를 손상시키거나 수정할 수 없습니다. 그렇게 하려면 비트코인, 이더리움, 기타 네트워크뿐만 아니라 #MetaHash 네트워크에 대한 공격에 성공해야 합니다.',
    'speeds-09' : '더 자세한 기술적 정보는 백서에서 확인하십시오',
    'speeds-10' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">백서 다운로드<i class="icon icon_dowload"></i></a>',


    'metaapps-01' : '#MetaApps',
    'metaapps-02' : '스마트한 실시간 애플리케이션을 위한 클라우드 서비스',
    'metaapps-03' : '#MetaApps는 스마트 컨트랙트의 진화이고, 모든 서비스 분산화에 사용할 수 있습니다. 이것은 영원히 지속적이며 누구에게도 속하지 않는 독립적인 프로그램입니다. 프로그램된 대로만 정확히 작동하며, 제3자가 간섭할 수 없습니다.',
    'metaapps-04' : '#MetaApps 이점',
    'metaapps-05' : '실시간 작동',
    'metaapps-06' : '일반 웹서비스와 애플리케이션만큼 빠름',
    'metaapps-07' : '일반적 GUI 디자인',
    'metaapps-08' : '평범한 애플리케이션이나 웹페이지처럼 보임',
    'metaapps-09' : '보안',
    'metaapps-10' : "누구도 업데이트 규정을 벗어나 애플리케이션 작동을 변경할 수 없습니다.",
    'metaapps-11' : '프로그램과 구동 시스템의 이미지는 네트워크에 업로드되고 수많은 컴퓨터에서 자동적으로 시작합니다.',
    'metaapps-12' : 'C++, PHP, Solidity 등을 포함한 프로그래밍 언어로 만들어졌습니다. ',
    'metaapps-13' : '스마트 컨트랙트 기능을 완벽하게 지원하고 모든 블록체인 또는 인터넷의 데이터만으로도 작동할 수 있습니다.',


    'metagate-01' : '#MetaGate',
    'metagate-02' : '분산화 인터넷으로 가는 관문',
    'metagate-03' : '#MetaGate는 오픈 소스 프로그램으로 모든 개발자들은 자신의 애플리케이션과 브라우저에 맞게 코드의 일부분을 포함시킬 수 있습니다.',
    'metagate-04' : '다중 자산 지갑',
    'metagate-05' : '지갑은 전체 블록체인을 다운로드할 필요 없이 "라이트 모드"를 지원합니다. 데이터는 분산화 네트워크의 다양한 소스로부터 오고 사용자들이 확인합니다. 사용된 모든 블록체인의 개인 보안 키는 사용자에 의해서만 저장됩니다.',
    'metagate-06' : '애플리케이션 카탈로그',
    'metagate-07' : '분산화 애플리케이션 카탈로그 및 함께 작동하는 브라우저. <b>#MetaHash</b> 기반의 모든 분산화 애플리케이션은 표준 인터넷 도메인뿐만 아니라, <b>#MetaGate</b>을 통해서도 접근할 수 있고, 별도의 프로그램에 할당할 수도 있습니다. ',
    'metagate-08' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">백서 다운로드<i class="icon icon_dowload"></i></a>',
	'metagate-download-button' : 'Download #Metahash',

    'metahashcoin-01' : '#MetaHashCoin (#MHC)',
    'metahashcoin-02' : '#MetaHash 재정 모델',
    'metahashcoin-03' : '#MetaHash는 개발 코드에 자기발전 프로세스가 내장된 자기 재정 시스템입니다.',
    'metahashcoin-04' : '#MetaHashCoin은 비용 지불에 사용됩니다:',
    'metahashcoin-05' : '거래',
    'metahashcoin-06' : '합리적인 고정가격으로 모든 자산의 즉각적이고 신뢰할 수 있는 거래',
    'metahashcoin-07' : '데이터 보관',
    'metahashcoin-08' : '데이터 저장이 필요한 애플리케이션이지만, 전통적 블록체인에서는 속도와 데이터 양이 부족한 경우',
    'metahashcoin-09' : '애플리케이션 구동',
    'metahashcoin-10' : '모든 분산화 애플리케이션 또는 스마트 컨트랙트가 <b>#MetaHash</b> 네트워크를 포함해 배치에 필요한 리소스를 요구합니다.',
    'metahashcoin-11' : '기타 서비스',
    'metahashcoin-12' : '공개 연설, <b>#MetaApps</b> 내 리스팅, <b>#MetaGate</b> 내 또는 다른 소스에서의 광고에 대한 지불.',
    'metahashcoin-13' : '<a href="#private-round" class="btn -default btn-mobile">#MHC 구매하기<i class="icon icon_link"></i></a>',


    'minig-01' : '#MHC 채굴/포징하기',
    'minig-02' : '서버',
    'minig-03' : '거래 네트워크의 작동에 사용되며, 분산화 애플리케이션의 작동에 사용되는 무료 리소스',
    'minig-04' : '#MetaGate 지갑',
    'minig-05' : '전체 모드에서 노드는 데이터 저장과 토렌트 노드로 사용됩니다',
    'minig-06' : '#MetaHashCoins',
    'minig-07' : 'PoW + PoS 요소를 위한 하이브리드 투표 모델 기반에 대한 합의 보안을 강화합니다.',
    'minig-08' : '서비스 판매로 생기는 #MHC는 다음에 사용됩니다:',
    'minig-09' : '#MetaHash에 프로젝트를 만드는 개발자들을 훈련',
    'minig-10' : '프로젝트의 품질 향상',
    'minig-11' : '#MetaHash 홍보',
    'minig-12' : '컨센서스 지원을 위한 #MetaHashCoins 소유주에게 지불',
    'minig-13' : '서버와 컴퓨터 소유주에게 지불',


    'compare-00' : '프로젝트',
    'compare-01' : '#MetaHash 이점',
    'compare-02' : '전세계에 필요한 양의 데이터를 빠르게 처리할 수 있는 완전히 분산화되고 동기화된 순환 시스템을 만드는 프로젝트를 찾아보고 실패한 끝에 #MetaHash를 만들기로 결정했습니다.',
    'compare-03' : '주요 블록체인 시스템의 비교표',
    'compare-04' : '거래<br />승인 시간',
    'compare-05' : '초당 거래량 (TPS)',
    'compare-06' : '분산화<br />정도',
    'compare-07' : '비트코인',
    'compare-08' : '10분',
    'compare-09' : '최대 12건',
    'compare-10' : '높음',
    'compare-11' : '이더리움',
    'compare-12' : '15초',
    'compare-13' : '최대 30건',
    'compare-14' : '높음',
    //  'compare-15' : 'Plasma',
    //  'compare-16' : '15 seconds',
    //  'compare-17' : 'up to 30',
    //  'compare-18' : 'high',
    'compare-19' : 'EOS',
    'compare-20' : '5초',
    'compare-21' : '1,000에서 수백만 건',
    'compare-22' : '최소',
    'compare-23' : '#MetaHash',
    'compare-24' : '최대 3초',
    'compare-25' : '50,000에서 수백만 건',
    'compare-26' : '높음',
    'compare-27' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">백서 다운로드<i class="icon icon_dowload"></i></a>',


    'timemap-01' : '로드맵',
    'timemap-02' : '프로젝트의 기술적 부분은 AdSniper가 2012년에 만들어 2017년까지 광고 기술 분야에서 이룩한 업적을 기반으로 합니다.',
    'timemap-03' : "다른 회사들로부터 블록체인 기술 적용에 대한 많은 요청을 받았고 현존하는 기술은 이러한 종류의 시스템에 대한 요구를 충족시킬 수 없다는 결론을 내렸습니다. 따라서 2016년에 우리의 독자적 프로토콜인 #TraceChain의 개발을 시작했습니다.",
    'timemap-04' : '2017년에 #TraceChain의 알파 및 베타 버전을 만들었고, 국제 마케팅 및 사업 개발 분야의 최강으로 꼽히는 회사와 인재들과 함께 하게 되었습니다.',
      'timemap-05' : '2012-2016',
      'timemap-06' : 'A network library for receiving signals, working on C++ and capable of simultaneously receiving and sending more than 100,000 requests per second to one inexpensive standard server',
      'timemap-07' : 'A network library for synchronizing signals within a cluster that manages gigantic data flows between cluster machines.',
      'timemap-08' : 'A machine learning system that decides in 40 milliseconds to respond to a signal taking into account multifactorial interrelationships.',
      'timemap-09' : 'Own analogue of Hadoop’s for similar systems in C ++ for distributed processing of large data.',
      'timemap-11' : '2017',
      'timemap-12' : 'Development of #TraceChain protocol (Alpha version)',
      'timemap-13' : 'Development of #TraceChain protocol (Beta version)',
      'timemap-14' : '<b>AdNow</b> team joins us',
      'timemap-15' : '<b>Agranovsky IT</b> team joins us',
      'timemap-16' : 'Formation of <b>Business Development team</b>',
      'timemap-17' : 'Formation of <b>Operational Team</b>',
      'timemap-18' : '2018',


      'timemap-19' : '#MetaHash website official launch',
      'timemap-20' : 'Start of the Operational Team office construction',
      'timemap-21' : 'Onboarding of experts and advisors',
      'timemap-22' : 'Development of #MetaGate (v.1.0). Multi-asset wallet featuring the ability to transfer #MetaHashCoins between wallets on multiple servers that stores data on transactions between crypto wallets.',
      'timemap-23' : 'Development of #TraceChain (v.1.0)',
      'timemap-23a': 'Development of #TraceChain (v.2.0). #TraceChain data download API',
      'timemap-24' : 'Development of #MetaICO (v.1.0). The ICO interface on the #MetaHash platform that accepts assets from various blockchains (Bitcoin and Ethereum), distributes tokens in the #MetaHash network and carries out multichain transactions, including ERC20 in the Ethereum network',
      'timemap-25' : 'Development of #MetaChains (v.1.0). Converting #MetaHashCoins to ERC20 and withdrawing them to the Ethereum network so that #MHC holders can choose which network to use and automatically convert ERC20 tokens into #MetaHashCoins',

      'timemap-26' : 'Development of #MetaApps (v.1.0). Application Platform',
      'timemap-27' : 'Testnet data download API',
      'timemap-28' : 'Opening of the Operational Team office',


      'timemap-29' : 'ICO Round A scheduled start',
      'timemap-30' : 'Development of #MetaChains (v.2.0). API featuring transaction history and balance  of wallets associated with different blockchain platforms. Decentralized application containing information about transactions in the Ethereum and Bitcoin networks which is necessary to provide blockchain interoperability in #MetaApps',
      'timemap-31' : 'Release of <b>#MetaGate (v.2.0)</b>. Encrypted messenger for public notifications and messaging between wallets',
      'timemap-32' : 'Release of <b>#TraceChain (v.3.0)</b>. Peer nodes that connect to TestNet to be installed on any server',
      'timemap-33' : '#TraceChain (v.4.0). Network core performance testing service (1,000,000+ transactions per second)',
      'timemap-34' : '#MetaICO (v.2.0). Interface for creating tokens inside the network #MetaHash',
      'timemap-35' : '#MetaICO (v.3.0). Release of ICO project platform at #MetaHash.',
      'timemap-36' : '#TraceChain (v.4.0). Voting functions in the #MetaHash network',
      'timemap-37' : '#TraceChain (v.5.0). AI managing the routing of signals between nodes for providing maximum speed of #MetaHash block creation and bandwidth and 100 test nodes in different geographical locations for testing node interaction',

      'timemap-38' : '#MetaICO (v.4.0). Release of the #MetaToken application, tokenization of ETH, ERC20, Bitcoin to #MetaHashCoin for use in the #MetaHash network',
      'timemap-39' : '#TraceChain (v.6.0). #MetaStorage, service for decentralized applications',
      'timemap-40' : '#MetaApps (v.2.0). The platform for self-deployment of third-party decentralized applications',
      'timemap-41' : '#MetaGate (v.3.0). Final release of #MetaGate wallet for Mac/Win/Unix/Android/iOS with #MetaApps catalogue',


    'timemap-42' : '<b>#TraceChain (v.7.0). Start of forging </b>',
    'timemap-43' : '<b>ICO 라운드 B 시작 또는 정식으로 조직되고 규제된 암호화폐 교환소와의 리스팅 협약 종료</b>',
    'timemap-44' : '향후 계획 발표',


    'timemap-45' : '광범위한 보안 테스트',
    'timemap-46' : '테스트 완료 시점에 소스 코드 공개',
    'timemap-47' : '완전히 분산화된 시스템의 출시',

    'timemap-100' : '자세히 보기',
    'timemap-101' : '이벤트 숨기기',
    'timemap-102' : '다른 이벤트',


    'teambanner-01' : '우리 팀',
    'teambanner-02' : '#MetaHash는 오픈 팀 구성 프로젝트로서 모든 사람, 모든 회사를 환영합니다.',
    'teambanner-03' : '우리에게 도움이 될 거라고 생각하고, 우리 팀과 함께 하기를 원하시면 <a class="team-write" href="mailto:hello@metahash.org">연락 바랍니다</a>.',
    'teambanner-04' : '<a href="#private-round" class="btn -default">ICO 라운드 A<i class="icon icon_link"></i></a>',
    'teambanner-05' : '우리에게 도움이 될 거라고 생각하고, 우리 팀과 함께 하기를 원하시면 <a href="mailto:hello@metahash.org">연락 바랍니다</a>.',
    'teambanner-06' : 'ICO 라운드 A',
    'teambanner-07' : '<img src="img/graphical/People_KO@3x.svg" alt="">',

    'team-hidden-01' : '프로젝트의 이익을 위해, 나머지 팀원의 이름이 공개됩니다.',

    'team-dev-00' : '개발',
    'team-dev-01' : 'Gleb Nikitin',
    'team-dev-01a' : '공동 설립자, 파트너, CRO <a href="http://www.facebook.com/glebnikitin" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="https://www.linkedin.com/in/glebnikitin/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
    'team-dev-02' : 'Oleg Romanenko',
    'team-dev-03' : 'CSA, AdSniper의 실시간 서비스 설계자 및 AlfaBank 온라인 뱅킹 시스템의 시스템 분석가. 1노드 당 초당 백만건 이상의 요청 수행이 가능한 과부하 네트워크 라이브러리의 개발자.',
    'team-dev-04' : 'Mikhail Zarutskiy',
    'team-dev-05' : 'CTO, AI, 빅데이터와 실시간 서비스팀의 수장으로 신경망 연산과 다른 머신 학습 알고리즘을 결합하여 수백만 건의 요청을 실시간으로 처리할 수 있는 Razoom AI 개발.',
    'team-dev-06' : 'Sergey Raylyan',
    'team-dev-07' : "CIO, AdSniper의 기술 보고를 형성하는 수십 개의 다양한 기술과 인터페이스 구현을 계획하고 조정.",
    'team-dev-08' : '29의 직원을 둔 AdSniper <i class="icon icon_link"></i>',
    'team-dev-09' : "지난 10년 간, 당사는 고부하 광고 네트워크를 만들어 냈습니다. 당사의 거대한 데이터 프로세서는 페타바이트의 데이터 제공, 빠른 NoSQL과 SQL 데이터베이스, 인공지능 시스템, 고부하 광고 서비스를 위한 C++ 라이브러리를 통합하여 전 인터넷 상의 광고 요청을 처리합니다.",
    'team-key-staff' : '주요 스태프',


    'team-mark-00' : '마케팅',
    'team-mark-01' : 'Vladimir Bashkin',
    'team-mark-01a' : 'CEO AdNow, CMO <a href="http://www.facebook.com/vladimir.bashkin" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="http://www.linkedin.com/in/vladimir-bashkin-18877678/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
    'team-mark-02' : '매일 10억 건 이상의 노출이 이루어지는 광고 네트워크. 현지 시장에서 번역 스태프와 광고 전문가를 보유한 모든 광고 네트워크에서 광고를 구매하는 세계의 최고 강팀 중 하나.',
    'team-mark-03' : '89명의 직원을 둔 AdNow <i class="icon icon_link"></i>',
    'team-mark-04' : 'Artem Kravchenko',
    'team-mark-05' : '이벤트 디렉트 - PR-디렉터. AdDays Digital Events의 CEO. Bitcomo Affiliate Network의 이벤트 디렉터',
    'team-mark-06' : 'Daria Baranova',
    'team-mark-07' : '연계 디렉터 - AdNow의 게시자 판매 디렉터. 모스크바 사무실 관리 디렉터',
    'team-mark-08' : 'Pham Thành Trung',
    'team-mark-09' : "광고부 책임자 - AdNow 아시아 지역 판매부 책임자. AdNow의 판매 및 사업부 관리자",


    'team-fin-00' : '사업 개발',
    'team-fin-01' : 'Anton Agranovsky',
    'team-fin-01a' : '공동 설립자, 파트너 <a href="https://www.facebook.com/aagranovsky" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="https://www.linkedin.com/in/anton-agranovsky-57427a15a/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
    'team-fin-02' : 'Agranovsky IT - 투자 회사, 스타트업에 투자하고 아이디어에서 IPO까지 회사 성장의 동반자. 창립자 Anton Agronovsky 는 IT 회사 설립 및 개발 분야의 투자자, 전문가, 오피니언 리더입니다. Plastic Media와 SMX Communications의 이사회 구성원. 2008-2017년 - Destiny Development의 설립자 및 회장, 러시아 인터넷 시장에서 최초의 게임 회사 중 하나로 개발 및 현지화 분야에서 잘 알려져 있습니다. <br />&nbsp;<br /><a href="https://goo.gl/fJVjfK" class="link -link-small" target="_blank">Forbes지 기고자</a>',
    'team-fin-03' : '11명의 직원을 둔 Agranovsky IT <i class="icon icon_link"></i>',
    'team-fin-04' : 'Gennady Yakunin',
    'team-fin-05' : 'CEO - 지주회사 내 회계 조직. IT와 게임 프로젝트에서 10년 이상의 경험 보유',
    'team-fin-06' : 'Svetlana Rudenok',
    'team-fin-07' : '부CEO - 위험평가 전문가. IT와 게임 산업에서 신규 및 기존 프로젝트의 회계 감사에 10년 이상의 경험 보유',
    'team-fin-08' : 'Andrey Korostelev',
    'team-fin-09' : 'CFO - IT와 게임 프로젝트의 재무 관리에서 10년 이상의 경험 보유. 사회 자선 프로젝트를 적극적으로 지원',


    'team-oper-00t' : '운영팀',
    'team-oper-01' : 'Dmitry Ushakov',
    'team-oper-02' : '<span style="color:#ffffff;">COO, 제너럴 PM</span><br/>Game Insight와 기타 IT 스타트업을 위한 다중 사용자 프로젝트 운영관리에서 11년 이상의 경험',
    'team-oper-03' : 'Michaił Iwanow',
    'team-oper-04' : '<span style="color:#ffffff;">아트 디렉터</span><br/>시각 및 제품 디자인에 16년 이상의 경험을 가진. RUSNANO, Sony, Canon, Nikon 및 기타 회사들의 프로젝트에 참여',
    'team-oper-05' : 'Zhibo Fan',
    'team-oper-06' : '<span style="color:#ffffff;">CBDO 아시아, MENA</span><br/>Game.ru 게임 플랫폼의 설립자이자 INFIPLAY 게임 출판인',
    'team-oper-07' : 'Alexander Zhigarenko',
    'team-oper-08' : '<span style="color:#ffffff;">CBDO 러시아, CIS</span><br/>Destiny.Games과 게임 산업에서 출판, 운영 및 사업개발에 10년 이상의 경험',
    'team-oper-09' : 'Eugenia Sigacheva',
    'team-oper-10' : '<span style="color:#ffffff;">대중 업무 파트너</span><br/>18년 이상 국제 마케팅과 광고 및 IT와 혁신 분야 경력. 잘 알려진 로봇 소피아의 국제팀 일원이자 IHEART 플랫폼의 CEO 및 창립자.',
    'team-oper-11' : 'Andrey Akimov',
    'team-oper-12' : '<span style="color:#ffffff;">Chief Communication Officer</span><br/>More than 15 years in marketing and PR in gaming, entertainment, and IT business. Former head of PR and marketing at My.com, Mail.Ru Group, Game Insight, and other companies.',
    'team-oper-00' : '17명의 직원을 둔 운영팀 <i class="icon icon_link"></i>',


    //'legal-01' : '법률 지원',
    //'legal-02' : 'Anastasia Pichugina',
    //'legal-03' : 'ANP 법률 관리 파트너 <a href="https://www.facebook.com/people/Anastasia-Pichugina/1520204010" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
    //'legal-04' : 'Ekaterina Myznikova',
    //'legal-05' : '선임 변호사 - 블록체인 프로젝트 실무 책임자. 다수의 ICO 프로젝트를 성공적으로 수행했고, 프로필 회담 및 온라인 회의의 참가자 및 연사.',
    //'legal-06' : 'Maxim Mekhriakov',
    //'legal-07' : '선임 변호사 - ANP 법률 내의 상업 실무 책임자로 상업과 투자 거래의 법률 지원에 특화',
    //'legal-08' : 'Anna Shevchenko',
    //'legal-09' : '변호사 - 러시아 및 외국계 기업의 상표 및 특허 등록을 포함한 지적재산권 분야에서 법률 지원',
    //'legal-10a' : 'ANP Law Firm',
    //'legal-10' : '국제법 및 러시아법 전문가. 당사 변호사는 매우 명망있는 러시아 및 외국 법대를 졸업하였습니다. 매니징 파트너 Anastasia는 러시아와 외국 법에 독특한 경험과 지식을 가지고 있으며, IT, FMCG 시장의 여러 기업들의 신뢰를 받는 법적 대표입니다. Anastasia는 러시아 법정에서 성공적으로 외국 기업들을 대표했습니다. ',
    //'legal-11' : '<a href="docs/MetaHash_LegalOpinion_EN.pdf" target="_blank">법적견해서 다운로드하기 #MetaHashCoin<i class="icon icon_link"></i></a>',
    //'legal-title' : 'Legal Department',
    //'legal-14' : 'Maria Agranovskaya',
    //'legal-15' : 'Chief Legal Coordinator <a href="https://www.facebook.com/magranovskaya" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a> <a href="https://www.linkedin.com/in/maria-agranovskaya-151334/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
    //'legal-16' : '<span>Attorney at Law with 20+ years of experience. Started working with cryptocurrency issues back in 2010. MGIMO MID of Russia (International Law), studied in Germany and Holland. 8,5 years - running a multifamily office, worked on various cross-border transactions, investments, asset management, deal and corporate structuring in various jurisdictions, M&A, international taxation and other matters.</span><span>Areas: fintech, finance, telecom, banking, energy, pharmaceuticals, real estate and other sectors.</span><span>2007: setup of GRAD Attorney Bar (managing partner,  30+ Russian and foreign lawyers)</span><span>Substantially engaged in blockchain technology, ICO (TGE) related projects, trading and finance regulations, funds and financial activity.</span><span>Speaks English, German, French, Italian, </span>',
	 
	  'legal-more' : '더 읽어보기',
	  'legal-less' : '이벤트 숨기기',
	  'legal-17' : 'Andrey Mironov <a href="http://www.linkedin.com/in/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a> <a href="https://www.facebook.com/" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
	  'legal-18' : 'Chief of Legal Department',
	  'legal-19' : 'Graduated MGIMO in 2000 at the international law faculty. Legal practice in the field of new technologies, media and intellectual property for more than 15 years.',
	  'legal-19a' : 'He worked at the Art. Lebedev Studio, Odnoklassniki, the Russian office of Myspace, on the channels MTV, Discovery, Amedia and the online cinema Amediateka. Helped to develop the EKSMO publishing house, the Fox TV channel. Expert at the Russian Association of Electronic Communications (RAEC).<br>Secondary Education: Consultant Psychologist',
	  'legal-20' : 'Maria Agranovskaya',
	  'legal-21' : 'Chief Legal Coordinator',
	  'legal-22' : 'Attorney at Law with 20+ years of experience. Started working with cryptocurrency issues back in 2010.',
	  'legal-22a' : 'MGIMO MID of Russia (International Law), studied in Germany and Holland. 8,5 years - running a multifamily office, worked on various cross-border transactions, investments, asset management, deal and corporate structuring in various jurisdictions, M&A, international taxation and other matters. Areas: fintech, finance, telecom, banking, energy, pharmaceuticals, real estate and other sectors. 2007: setup of GRAD Attorney Bar (managing partner,  30+ Russian and foreign lawyers). Substantially engaged in blockchain technology, ICO (TGE) related projects, trading and finance regulations, funds and financial activity. Speaks English, German, French, Italian,  Spanish.',
	  'legal-23' : 'Katya Fisher',
	  'legal-24' : 'Partner, Principal at The Law Office of Katya Yoffe PLLC',
	  'legal-25' : 'Katya Yoffe (née Fisher) is an attorney focusing on general corporate law, cross-border transactions and business immigration.',
	  'legal-25a' : 'Katya represents various prominent companies and startups doing business in the United States as well as celebrity and HNW individuals. Katya has been selected to Super Lawyers as a “Rising Star” in 2014, 2015, 2016, 2017 and 2018. <br>Katya is a graduate of New York University, the Benjamin N. Cardozo School of Law and a former Howard M. Squadron Fellow in International Media Law & Policy at the University of Oxford and Center for Global Communication Studies, University of Pennsylvania. She is admitted to practice in New York and before the United States Tax Court.',
	  'legal-26' : 'Anastasia Pichugina',
	  'legal-27' : 'ANP Law Managing Partner ',
	  'legal-28' : 'Managing partner Anastasia has a unique experience and knowledge in Russian and foreign law, is a trusted legal representative of several foreign companies.',
	  'legal-29' : 'Ekaterina Myznikova',
	  'legal-30' : '선임 변호사',
	  'legal-31' : '블록체인 프로젝트 실무 책임자. 다수의 ICO 프로젝트를 성공적으로 수행했고, 프로필 회담 및 온라인 회의의 참가자 및 연사.',
	  'legal-32' : 'International Legal Support',
	  'legal-33' : 'Daniel G. Viola',
	  'legal-34' : 'Partner, Head of Regulatory and Compliance Group at Sadis & Goldberg LLP',
	  'legal-35' : 'Oliver Ciric',
	  'legal-36' : 'Partner at TA Advisory',
	  'legal-37' : 'Daniel G. Viola is a partner of <span class="ilegal-white">Sadis & Goldberg LLP</span> and the Head of its Regulatory and Compliance Group.  Mr. Viola has been active in the Blockchain and Virtual Currency verticals since 2014. He also served as a Senior Compliance Examiner for the <span class="ilegal-white">Northeast Regional Office of the SEC,</span> where he worked from 1992 through 1996',
	  'legal-37a' : 'During his tenure at the SEC, Mr. Viola worked on several compliance inspection projects and enforcement actions involving examinations of registered investment advisers, ensuring compliance with federal and state securities laws. Mr. Viola’s examination experience includes financial statement, performance advertising, and disclosure document reviews, as well as, analysis of investment adviser and hedge fund issues arising under ERISA and blue-sky laws. In late 2006 Mr.  Viola founded his own law firm and eventually merged it into Sadis & Goldberg’s law practice.',
	  'legal-38' : 'Experience in international jurisprudence for more than 20 years. Oliver graduated from Boston University of Law in 2006, majoring in banking and finance law, and the Geneva University of Law in 1998, specializing in "License and Law". Previous work experience:  Nationale Suisse Assurances, Matile Brosset Stickel-Cicurel & Gianninazzi, Poncet Turrettini Amaudruz Neyroud & Partners, <span class="ilegal-white">Akin Gump Strauss Hauer & Feld LLP</span> (formerly Hogan & Hartson LLP).',
	  'legal-38a' : 'Since June 2017 he has been a partner at <span class="ilegal-white">TA Advisory</span>. Mr. Ciric provides legal support for blockchain projects, and also advises on cooperation <span class="ilegal-white">with FINMA.</span><br>Languages: German, English, French, Portuguese, Russian, Serbian.',
	  'legal-39' : '<span class="ilegal-white-02">KPMG AG, Switzerland,</span> served as advisor to #MetaHash in the evaluation of the Swiss regulatory, tax and legal aspects in respect of the Initial Coin offering (ICO)',
	  'legal-40' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">ICO 라운드 A<i class="icon icon_dowload"></i></a>',
	  'legal-41' : 'Martin Hess',
      'legal-42' : 'Partner at Wenger & Vieli AG',
	  'legal-43' : 'Martin Hess specializes in financial services and capital markets law, FinTech and the digitization of financial services. He is recognized by the Swiss Stock Exchange as an issuer representative. Martin Hess advises Swiss and foreign clients and represents them vis-à-vis supervisory authorities and in court.',
	  'legal-43a' : 'He is involved in the legal design of trading venues for digital assets, payment systems and securities settlement systems as well as central counterparties. He advises and represents clients on Initial Coin Offerings / Token Generating Events. Since 2001 Partner at Wenger & Vieli Ltd',


    //   'private-01' : 'Private Round',
    //   'private-form' : '<input type="hidden" name="form_subject" value="Private Round Application">',
    //   'private-03' : 'days',
    //   'private-04' : 'Private Round ends in',
    //   'private-05' : 'Private Round',
    //   'private-06' : 'The purpose of the Private Round is to verify the idea before the public launch',
    //   'private-07' : 'We hope to meet experts who are ready to participate in the discussion of the project before its public launch and, possibly, join the #MetaHashTeam.',
    //   'private-08' : '#MetaHash undertakes to inform all Private Round participants about terms of participation, their rights and obligations in connection with participation.',
    //   'private-09' : 'Private Round participants will be able to decide whether to remain in the project after the ICO.',
    //   'private-10' : 'Send an application to participate in the Private Round',
    //   'private-11' : 'We are not interested in the amount, but rather in your expertise. We want experts from different fields to participate in the Private Round.',
    //   'private-12' : 'Describe your expertise in cryptocurrencies. Are you ready to participate in discussion about the project?',
    //   'private-13' : 'Apply <i class="icon icon_link"></i>',
    //   'private-14' : 'Terms of Use',
    //   'private-15' : 'Privacy Policy',
    //   'private-16' : 'Private Round terms:',
    //   'private-17' : 'Do you want to participate in the Private Round or join the #MetaHashTeam?',
    //   'private-18' : 'Participation in the Private Round is public - the name or company name of the participant will be published',
    //   'private-19' : 'Private Round volume - <b>1,840 ETH</b>',
    //   'private-20' : 'The value of the #MHC - <b>0.001 ETH</b>',
    //   'private-21' : 'The volume of the Private Round is not enough to satisfy the requests of all comers',
    //   'private-22' : 'You can fill the application form before the end of the Private Round',
    //   'private-23' : 'At the end of the Private Round, the current #MetaHash team will decide on quotas for each of those wishing to participate',
    //   'private-24' : 'After the completion of the Private Round and the distribution of tasks between the current and new team members, the ICO 라운드 A will start',
    //   'private-25' : 'Private Round Application',
    'private-26' : '이름 입력하기',
    'private-27' : '이메일 입력하기',
    //   'private-28' : 'Desired amount of participation (ETH)',
    //   'private-29' : 'Additional information about yourself',


    //   'timer-day-1' : 'days',
    //   'timer-day-2' : 'days',
    //   'timer-day-3' : 'days',
    //   'timer-hour-1' : 'hour',
    //   'timer-hour-2' : 'hours',
    //   'timer-hour-3' : 'hours',
    //   'timer-minute-1' : 'minute',
    //   'timer-minute-2' : 'minutes',
    //   'timer-minute-3' : 'minutes',
    //   'timer-second-1' : 'second',
    //   'timer-second-2' : 'seconds',
    //   'timer-second-3' : 'seconds',


    'form-sent-01' : '감사합니다!',
    'form-sent-02' : '귀하의 정보가 성공적으로 제출되었습니다.',


    'faq-01' : '자주 묻는 질문',
    'faq-02-00' : '#MetaHash에 대하여',
    'faq-02-01' : '법인입니까?',
    'faq-02-02' : '법인 등록 절차가 스위스에서 시작되었습니다. 스위스 정부에서 승인해 주기까지 일반적으로 어느 정도의 시간이 소요됩니다.',
    'faq-02-03' : 'MVP 및 #MetaHash의 오픈 소스 코드를 어디에서 검토할 수 있습니까?',
    'faq-02-04' : '#TraceChain 중앙 집중식 네트워크는 현재 다중 자산 지갑과 함께 활성화되어 있습니다. #TraceChain 프로토콜의 소스 코드는 해커에 대한 공공 보안 보상금 정책이 통과되고 특허 취득 후 공개될 것입니다.',
    'faq-02-05' : '제품과 토큰의 일반적 목표는 무엇입니까?',
    'faq-02-06' : '#MetaHashCoin은 거래, 데이터 저장, 앱 기능을 교환하는 데에 사용됩니다. 또한 #MHC를 공개 주소를 추가하고, #MetaApp 디렉토리 리스트에 앱을 등록하고, #MetaGate 광고 네트워크에서 광고를 구매하는 등 훨씬 많은 곳에 사용할 수 있습니다.',
    'faq-02-07' : '블록체인의 속도 용량은 얼마입니까? 어떻게 그런 결과를 이룰 수 있습니까?',
    'faq-02-08' : '우리의 블록체인 용량에 대해 <a href="docs/MetaHash_WhitePaper_EN.pdf" class="link -link-small" target="_blank">백서</a>에서 더 알아보시기 바랍니다.',
    'faq-02-09' : '코인은 채굴이 가능합니까? 채굴자들에게는 어떤 이점이 있습니까?',
    'faq-02-10' : '채굴에 대해 <a href="docs/MetaHash_WhitePaper_EN.pdf" class="link -link-small" target="_blank">백서</a>에서 더 알아보시기 바랍니다.',
    'faq-02-11' : 'POW나 POS 중 어떤 인증 시스템을 사용하십니까?',
    'faq-02-12' : '#MetaHash는 하이브리드 컨센서스 알고리즘을 사용합니다. 이것은 별개의 네트워크 노드에서 투표 결과를 포함하는 멀티 POS 시스템입니다.',


    'faq-03-00' : 'ICO 라운드 A / 라운드 B와 #MHC 구매',
    'faq-03-01' : '어떤 지불 수단을 허용합니까?',
    'faq-03-02' : 'ETH만 받습니다. 다른 디지털 자산은 ETH로 먼저 교환해야 합니다. ',
    'faq-03-03' : '',
    'faq-03-04' : '',
    'faq-03-05' : '거래 플랫폼에서 참가할 수 있습니까?',
    'faq-03-06' : '네, 가능합니다. 하지만 ETH만 수용합니다.',
    'faq-03-07' : '',
    'faq-03-08' : '',
    'faq-03-09' : 'ICO 라운드 A / 라운드 B는 언제 종료됩니까?',
    'faq-03-10' : 'ICO 라운드 A는 목표량에 도달할 때까지 계속됩니다. ICO 라운드 B는 MVP가 출시된 후 시작합니다.',
    'faq-03-11' : '#MHC 다중 자산 지갑의 특별한 점은 무엇입니까?',
    'faq-03-12' : '#MetaGate 다중 자산 지갑은 오픈 소스 코드 제품입니다. 광고 게재 수익과 광고 차단을 위한 구독으로 사용을 재정적으로 지원합니다.',


    'faq-04-00' : '#MetaHashCoin과 전망',
    'faq-04-01' : '#MetaHash와 다른 블록체인 제공자들 간의 일반적 차이는 무엇입니까?',
    'faq-04-02' : '모든 현존하는 경쟁자들은 느리거나 중앙집중형입니다. 차세대 블록체인은 반드시 신속하고 완전히 분산화되어야 하며, 거래도 저렴해야 합니다. (#MetaHash 제외) 현존하는 프로젝트는 이 모든 요구사항을 수용하지 못합니다.',
    'faq-04-03' : 'ETH 스마트 컨트랙트임에도 불구하고 #MHC ERC20는 발행됩니까?',
    'faq-04-04' : '#MHC는 별개의 독자적 코인으로 별개의 체인에서 운영됩니다. 하지만, 이더리움과 #MetaHash 내에 일부 미러 컨트랙트가 존재합니다. 이 미러 컨트랙트는 양방향에서 ERC20 토큰의 토큰화 절차를 허용합니다.',
    'faq-04-05' : '토큰으로 총 공급량은 얼마입니까?',
    'faq-04-06' : '10년 간에 걸쳐 92,000,000 #MHC가 발행될 것입니다. 첫해에는 46,000,000 #MHC가 발행될 것입니다.',
    'faq-04-07' : '#MetaHashCoins는 어떤 거래 플랫폼에서 거래됩니까?',
    'faq-04-08' : '거래 플랫폼 상의 코인 이용가능성이 모든 공식적인 #MetaHash 공공 채널을 통해서 발표될 것입니다. 그러한 정보를 선공개할 수는 없습니다.',
    'faq-04-09' : '일단 공개 시장에 도달하면 ICO 후에 #MHC의 초기 가격은 얼마가 될 것입니까? 1년 후는 어떠합니까?',
    'faq-04-10' : '#MetaHashCoin의 가격은 시작 필요에 의해 결정됩니다. #MHC는 거래, 데이터 저장, 앱 기능 등을 지불하는 데에 사용됩니다. 이러한 요인이 #MHC의 가격에 영향을 줄 것입니다.',
    'faq-04-11' : '토큰 판매는 언제 시작/종료합니까?',
    'faq-04-12' : 'ICO 라운드 A를 2018년 말까지 종료할 계획입니다. 공식 ICO 라운드 B는 2018년 4/4분기 또는 2019년 1/4분기에 시작할 것입니다. ',


    'faq-05-00' : '#MHC 판매 과정',
    'faq-05-01' : '#MetaHash에 참가하기 위한 최소 한도가 있습니까?',
    'faq-05-02' : '최소 한도를 정하지는 않습니다. 원하는 만큼 토큰을 가질 수 있습니다.',
    'faq-05-03' : '참가자들에게 토큰이 언제 제공됩니까?',
    'faq-05-04' : '#MetaHash ICO Round B가 종료되면 TestNet 코인 또는 ERC20 대체물이 제공됩니다',
    'faq-05-05' : '판매되지 않은 코인은 어떻게 합니까?',
    'faq-05-06' : '판매되지 않은 모든 자산은 #MetaHash 사에 남게 됩니다.',
    'faq-05-07' : '0.07 ETH을 #MetaHash 지갑으로 전송했습니다. 얼마만큼의 토큰을 받을 수 있습니까?',
    'faq-05-08' : '우리가 제공하는 내부 계산기를 사용하시기 바랍니다.',
    'faq-05-09' : '암호화폐 자산이 없으면 어떻게 #MHC를 구매할 수 있습니까?',
    'faq-05-10' : '구매할 수 없습니다. 돈을 ETH나 BTC로 환전해야 합니다. 원하시는 어떤 거래 플랫폼이든 사용하실 수 있습니다.',



    'faq-06-00' : '기타 질문',
    'faq-06-01' : '저는 중국 또는 한국 국민인데, #MetaHash ICO 크라우드 세일에 참가하는 것이 합법입니까?',
    'faq-06-02' : '다음을 제외한 모든 국적에서 가능합니다: 미국, 싱가포르, 베트남사회주의공화국, 중화인민공화국 또는 미국령 금수조치와 제제가 시행되는 국가의 거주자, 즉 이란, 북한, 시리아, 수단, 또는 쿠바. 자세한 정보는 토큰판매규정에서 확인하십시오.',
    'faq-06-03' : '간단히 말해서, #TraceChain은 무엇입니까?',
    'faq-06-04' : '#TraceChain은 차세대 블록체인 시스템입니다. 이 솔루션은 자율 자기학습 라우팅 알고리즘에 기반합니다. 초당 50,000건의 거래 속도로 작동을 시작해서 (기본 100Mb/S 채널 속도) 합리적인 고속 채널의 수가 더해짐에 따라 증가합니다. 이 채널이 #MetaHash 네트워크의 중심을 형성하고 작동을 안정시킵니다.',
    'faq-06-05' : '하드캡 / 소프트캡?',
    'faq-06-06' : '소프트캡은 창립자와 프라이빗 라운드를 통해 도달합니다. 하드캡은 결정되지 않았습니다.',
    'faq-06-07' : '0.0067769 BTC/ETH을 입금했는데, 언제 #MHC tokens으로 환전됩니까?',
    'faq-06-08' : "토큰은 이더리움 네트워크에서 6건의 확정 후에 제공되고, #MetaChains 노드를 받게 됩니다. ETH와 BTC 네트워크로부터 거래를 승인하기 위해서는 일반적으로 6시간이 걸립니다. 6시간 후에 코인을 받지 못하더라도 걱정하지 마십시오. 우리에게 상황을 알려주시면, 문제를 해결해 드리겠습니다. 예치금이 거래나 마찬가지입니다. 거래가 발생하면 코인을 받게 됩니다.",
    'faq-06-09' : '프라이빗 라운드, ICO 라운드 A/B 등의 공식 일자는 언제입니까?',
    'faq-06-10' : 'ICO 라운드 A와 ICO 라운드 B 기간은 아직 정해지지 않았습니다. 우리 공식 채널을 통해 곧 발표될 것입니다. 계속 주목하셔서 가장 빠르게 소식을 받으시기 바랍니다. ',
    'faq-06-11' : '#MetaHash는 BTC 또는 ETH 포크입니까?',
    'faq-06-12' : '#MetaHash는 포크가 아닙니다. 훨씬 빠르고 더욱 안전한 독립 블록체인 제공자입니다.',


    'support-01' : '질문이 있습니까? 연락주십시오!',
    'support-02' : '제출하기',
    'support-03' : 'User question',
    'support-04' : '이름을 입력하세요',
    'support-05' : '이메일을 입력하세요',
    'support-06' : '질문',


    'prefooter-01' : '탑승하십시오!',
    'prefooter-02' : '#MetaHashTeam',
    'prefooter-03' : '<a href="#private-round" class="btn -default">#MHC 구매하기<i class="icon icon_link"></i></a>',
    'prefooter-04' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">백서 다운로드<i class="icon icon_dowload"></i></a>',
    'prefooter-05' : '<a href="docs/MetaHash_OnePager_KO.pdf" target="_blank" class="btn -download">원페이저 다운로드<i class="icon icon_dowload"></i></a>',
    'prefooter-06' : 'ICO 라운드 A에 참여하십시오.',
    'prefooter-07' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">백서</a>',
    'prefooter-08' : '<a href="docs/MetaHash_OnePager_KO.pdf" target="_blank" class="btn -download float-right">원페이저</a>',


    'footer-01' : '#MetaHash는 무엇입니까?',
    'footer-02' : '#MetaHashCoin (#MHC) 구매하기',
    'footer-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -footer-link">백서</a>',
    'footer-04' : '<a href="docs/MetaHash_OnePager_KO.pdf" target="_blank" class="link -footer-link">원페이저</a>',
    'footer-05' : '자주 묻는 질문',
    'footer-06' : '<a href="docs/MetaHash_TermsOfUse_KO.pdf" target="_blank" class="link -footer-link">이용약관</a>',
    'footer-07' : '<a href="docs/MetaHash_PrivacyPolicy_KO.pdf" target="_blank" class="link -footer-link">개인정보보호정책</a>',
    'footer-08' : '<a href="docs/MetaHash_AntiSpam_EN.pdf" target="_blank" class="link -footer-link">안티 스팸 정책</a>',
    'footer-09' : '고문 동의',
    'footer-10' : '<a href="docs/MetaHash_RiskDisclosureStatement_EN.pdf" target="_blank" class="link -footer-link">위험 공시 동의</a>',
    'footer-11' : '소셜 네트워크 및 메신저',
    'footer-12' : '포럼',
    'footer-13' : '<a href="mailto:hello@metahash.org" class="link -link-small">hello@metahash.org</a> 피드백 보내기',
    'footer-14' : '<a href="mailto:support@metahash.org" class="link -link-small">support@metahash.org</a> 지원하기',
    'footer-15' : '<a href="mailto:support@metahash.org" class="link -link-small">press@metahash.org</a> 언론 문의',
    'footer-16' : '<a class="link -link-small">+7 926 671-67-08</a> 홍보 담당 부서',
    'copyright' : '저작권 © 2017-2018 #MetaHash. 판권소유',


    'mobile-menu-01' : '<a href="#whatis" class="link -link-white">#MetaHash는 무엇입니까?</a>',
    'mobile-menu-02' : '<a href="#private-round" class="link -link-white">#MetaHashCoin (#MHC) 구매하기</a>',
    'mobile-menu-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -link-white">백서 다운로드</a>',
    'mobile-menu-04' : '<a href="docs/MetaHash_OnePager_KO.pdf" target="_blank" class="link -link-white">원페이저 다운로드</a>',
    'mobile-menu-05' : '<a href="#faq" class="link -link-white">자주 묻는 질문</a>',
    'mobile-menu-06' : '<a href="#support" class="link -link-white">지원</a>',
    'mobile-menu-07' : '<a href="#support" class="link -link-white">연락</a>',

	'new-mobile-menu-01' : '<a href="#whatis" class="link -link-white --offcan">#MetaHash는 무엇입니까?</a>',
	'new-mobile-menu-02' : '<a href="#tracechain" class="link -link-white --offcan">#TraceChain</a>',
	'new-mobile-menu-03' : '<a href="#metaapps" class="link -link-white --offcan">#MetaApps</a>',
	'new-mobile-menu-04' : '<a href="#metagate" class="link -link-white --offcan">#MetaGate</a>',
	'new-mobile-menu-05' : '<a href="#timemap" class="link -link-white --offcan">Roadmap</a>',
    'new-mobile-menu-06' : '<a href="#advisors-and-consultants" class="link -link-white --offcan">Advisors & Consultants</a>',
	'new-mobile-menu-07' : '<a href="#teambanner" class="link -link-white --offcan">The Team</a>',
	'new-mobile-menu-08' : '<a href="#ico" class="link -link-white --offcan">ICO 라운드 A</a>',
	'new-mobile-menu-09' : '<a href="#faq" class="link -link-white --offcan">자주 묻는 질문</a>',
	'new-mobile-menu-10' : '<a href="#support" class="link -link-white --offcan">연락주십시오</a>',
	  
    'promo-soc-01' : '<a href="https://t.me/metahash_ENG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
    'promo-soc-02' : '<a href="https://www.facebook.com/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
    'promo-soc-03' : '<a href="https://vk.com/metahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
    'promo-soc-04' : '<a href="https://twitter.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
    'promo-soc-05' : '<a href="https://instagram.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
    'promo-soc-06' : '<a href="https://www.youtube.com/channel/UCIkBIrd1q7JkLLj43KgG8zA" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">youtube.com</span><span class="icon -icon-big icon_youtube"></span></a>',
    'promo-soc-07' : '<a href="#" class="link-soc -tooltype"><span class="soc-tooltype">ID:MetaHash</span><span class="icon -icon-big icon_wechat"></span></a>',
    'promo-soc-08' : '<a href="https://open.kakao.com/o/gY5dUgG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">talk.com</span><span class="icon -icon-big icon_talk"></span></a>',
    'promo-soc-09' : '<a href="https://github.com/metahashorg" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
    'promo-soc-10' : '<a href="https://www.reddit.com/user/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">reddit.com</span><span class="icon -icon-big icon_reddit"></span></a>',
    'promo-soc-11' : '<a href="https://www.linkedin.com/company/27209614/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">in.com</span><span class="icon -icon-big icon_in"></span></a>',
    'promo-soc-12' : '<a href="https://medium.com/@themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">medium.com</span><span class="icon -icon-big icon_medium"></span></a>',
    'promo-soc-13' : '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitsmedia"></span></a>',
    'promo-soc-14' : '<a href="https://bitcointalk.org/index.php?action=profile;u=1253602" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',


    'promo-soc-mobile-01' : '<a href="https://t.me/metahash_ENG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
    'promo-soc-mobile-02' : '<a href="https://www.facebook.com/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
    'promo-soc-mobile-03' : '<a href="https://vk.com/metahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
    'promo-soc-mobile-04' : '<a href="https://twitter.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
    'promo-soc-mobile-05' : '<a href="https://instagram.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
    'promo-soc-mobile-06' : '<a href="https://github.com/metahashorg" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
    'promo-soc-mobile-07' : '<a href="https://www.linkedin.com/company/27209614/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">in.com</span><span class="icon -icon-big icon_in"></span></a>',
    'promo-soc-mobile-08' : '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="link-soc"><span class="icon -icon-big --icon-forum icon_bitsmedia" target="_blank"></span></a>',
    'promo-soc-mobile-09' : '<a href="https://bitcointalk.org/index.php?action=profile;u=1253602" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',

    'tg_button' : '<a href="https://t.me/metahash_ENG" target="_blank"><img class="telega-svg" style="margin-bottom: 40px;" src="img/telegram.svg" alt=""></a>',



    'private-close-01' : '프라이빗 라운드 종료',
    'private-close-02' : '20배 이상의 초과 구독 후 마감',
    'private-close-03' : '모든 참가자에게 감사하며, ICO 라운드 A에 함께 하시도록 모두를 초대합니다.',
    'private-close-04' : 'ICO 라운드 A',
    'private-close-05' : '시작이 예정된 달',
    'private-close-06' : 'ICO 라운드 A가 곧 시작됩니다.',
    'private-close-07' : '시작을 놓치지 마시고 지금 신청하셔서<br class="mobile-br"> 참가하거나 또는 팀에 가입하세요',
    'private-close-08' : '지금 접수하기 <i class="icon icon_link"></i>',
    'private-close-09' : '우리와 함께 하십시오:',
    'private-close-10' : 'ICO 라운드 A 특징:',
    'private-close-11' : 'ICO 라운드 A 동안 <b class="mob-bold">9,200,000 #MHC</b>가 분배됩니다',
    'private-close-12' : 'ICO 라운드 A 동안의 #MHC 가치는 <b class="mob-bold">0.0125 ETH</b>입니다.',
    'private-close-13' : '<b class="mob-bold">50 ETH</b> (12,500 #MHC) 미만의 주문은 4시간 마다 갱신되는 일반 제한 풀로부터 채워집니다. <b class="mob-bold">선착순입니다</b>',
    'private-close-14' : '소규모 바이어를 위한 공간을 확보하기 위해, <b class="mob-bold">50 ETH</b> 이상의 주문은 별도의 예약된 풀에서 즉시 채워집니다',
    'private-close-15' : '2018/04',
    'private-close-16' : '이메일 입력',
    'private-close-17' : '백서에 따라 수정될<br>수 있음',
    // 'private-close-18' : '<input id="private-close__terms-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__terms-check">I agree to </label><a href="docs/MetaHash_TermsOfUse_EN.pdf" target="_blank">Terms of Use</a>',
    // 'private-close-19' : '<input id="private-close__policy-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__policy-check">I agree to </label><a href="docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank">Privacy Policy</a> ',


    'private-close-18' : '동의합니다 ',
    'private-close-19' : '동의합니다 ',
    'private-close-25' : '<a href="docs/MetaHash_TermsOfUse_EN.pdf"  target="_blank">이용약관</a>',
    'private-close-26' : '<a href="docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank">개인정보보호정책</a>',



    'private-close-20' : 'Application submitted',
    'private-close-21' : ', thank you for your interest in <b>#MetaHash</b> project. We will keep you informed about the <b>ICO 라운드 A start date</b>.',
    'private-close-22' : 'Dont miss a thing!',
    'private-close-23' : '<a href="https://t.me/metahash_ENG" target="_blank"  class="private-close__modal-content_tg-link" >Join our Telegram Channel<br> and stay updated</a>',
    'private-close-24' : '<a href="https://t.me/metahash_ENG" target="_blank" class="support-window__social-block_soc-link support-window__social-block_soc-link_tg"><img class="support-window__social-block_soc-img" src="img/popup/sub-tg.png" alt=""><span class="flag"><img class="support-window__social-block_flag-img" src="img/icons/flag-eng.png"></span></a>',

};