window.arrLang = window.arrLang || {};
window.arrLang["pt"] = {
    'nav-link-01' : 'O que é #MetaHash?',
      'nav-link-02' : 'Comprar #MHC',
      'nav-link-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -link-white"><img src="img/icon_file.svg" class="icon_file"> Artigo Técnico</a>',
      'nav-link-04' : '<a href="docs/MetaHash_OnePager_PT.pdf" target="_blank" class="link -link-white"><img src="img/icon_file.svg" class="icon_file"> Sumário</a>',
      'nav-link-05' : 'FAQ',
      'nav-link-06' : 'Suporte',
	  'nav-link-07' : 'Contacte-nos',

      'promo-01' : 'rápido',
      'promo-02' : 'velocidade de validação <b>inferior a 3 segundos</b>. Desempenho <b>superior a 50 000 TPS</b>',
      'promo-03' : 'seguro',
      'promo-04' : 'protegido por <b>5 algoritmos de consenso diferentes</b>',
      'promo-05' : 'descentralizado',
      'promo-06' : '<b>qualquer pessoa pode adicionar nós de transação</b> à rede #MetaHash',


      'descr-01' : 'baseada no Blockchain 2.0',
      'descr-02' : '<span class="cripto-title -title-part01 --eng">cripto</span><span class="cripto-title -title-part02 --eng">moeda</span>',
      'descr-03' : 'and decentralized ecosystem',
      'descr-04' : 'baseada no Blockchain 2.0',


      'promo-appint-01' : '<span class="part-name">para&nbsp;</span>armazenamento',
      'promo-appint-03' : 'de qualquer informação no Blockchain com  <b>proteção criptográfica 4k</b> e <b>multiassinatura</b>',
      'promo-appint-04' : '<a href="#private-round" class="btn -default">Ronda A da ICO<i class="icon icon_link"></i></a>',
      'promo-appint-05' : 'transações<span class="part-name">&nbsp;</span>',
      'promo-appint-06' : '<b>até 3 segundos para aprovar</b> dentro da rede #MetaHash e fora dela',
      'promo-appint-07' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Transferir Artigo Técnico<i class="icon icon_dowload"></i></a>',
      'promo-appint-08' : 'troca <span class="part-name">&nbsp;de qualquer ativo</span>',
      'promo-appint-10' : '<b>todos os ativos digitais</b> na carteira #MetaGate usam o <b>token ERC20</b> em todos os serviços de câmbio',
      'promo-appint-11' : '<a href="docs/MetaHash_OnePager_PT.pdf" target="_blank" class="btn -download">Transferir Sumário<i class="icon icon_dowload"></i></a>',
      'promo-appint-12' : '<a href="#private-round" class="btn -default -mega" >Ronda A da ICO</a>',
      'promo-appint-13' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Artigo Técnico</a>',
      'promo-appint-14' : '<a href="docs/MetaHash_OnePager_PT.pdf" target="_blank" class="btn -download float-right">Sumário</a>',
      'promo-appint-15' : 'Download #MetaGate client',

      'whatis-01' : 'O que é #MetaHash?',
      'whatis-02' : '#MetaHash é uma rede de nova geração baseada na tecnologia Blockchain 2.0 para partilha de ativos digitais e uma plataforma de criação e gestão de aplicações e serviços descentralizados em tempo real',
      'whatis-03' : 'Quatro componentes do sistema:',
      'whatis-04' : '#TraceChain',
      'whatis-05' : 'O Blockchain mais rápido e seguro',
      'whatis-06' : 'Mais de cinco <b>mil milhões de transações por dia</b>, não mais de três segundos para validar uma transação',
      'whatis-07' : 'Sobre #TraceChain',
      'whatis-08' : '#MetaApps',
      'whatis-09' : 'Nova geração de Contratos Inteligentes',
      'whatis-10' : '<b>Aplicações descentralizadas em tempo real</b> que são operadas como serviços web normais e desenvolvidas com recurso a qualquer linguagem de programação, incluindo C ++, PHP, Solidity e outros',
      'whatis-11' : 'Sobre #MetaApps',
      'whatis-12' : '#MetaGate',
      'whatis-13' : 'Internet Descentralizada',
      'whatis-14' : 'Diretório de aplicações descentralizadas e <b>carteira multiativos</b> que não irá sobrecarregar o seu computador',
      'whatis-15' : 'Sobre #MetaGate',
      'whatis-16' : '#MetaHashCoin',
      'whatis-17' : 'Ativo de bolsa da rede #MetaHash',
      'whatis-18' : '<b>#MetaHashCoin</b> é usada para garantir a fiabilidade da rede, dos serviços de intercâmbio e regular o seu autofinanciamento e desenvolvimento',
      'whatis-19' : 'Sobre #MHC',


      'tracechain-01' : '#TraceChain',
      'tracechain-02' : 'Blockchain 2.0 rápido e seguro',
      'tracechain-03' : 'MAIS DE',
      'tracechain-04' : '100 000',
      'tracechain-05' : 'transações por segundo em cada nó',
      'tracechain-06' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download lang" >Transferir Artigo Técnico<i class="icon icon_dowload"></i></a>',
 //   'tracechain-07' : 'to approve a transaction',
 //   'tracechain-08' : 'transactions per day',
 //   'tracechain-09' : 'stages of consensus for verification',
 //   'tracechain-10' : '#MetaHash block anchors <span class="blue">in Bitcoin and Ethereum networks</span>',
      'tracechain-11' : '<img class="tracechain-svg" src="img/graphical/tracechain-pt.svg" alt="">',


      'speed-work-01' : 'Uma velocidade sem precedentes e a descentralização da rede #TraceChain tornam #MetaHash numa referência de Blockchain',
      'speed-work-02' : 'Conclua qualquer quantidade de transações na rede <b>#MetaHash</b>',
      'speed-work-03' : 'O custo da transação é mais baixo do que em qualquer Blockchain normal',
      'speed-work-04' : 'Custos razoáveis de armazenamento de dados com <b>#TraceChain</b> para projetos descentralizados',
      'speed-work-05' : 'Qualquer ativo pode ser transformado em <b>#MetaHashCoin</b> via token para circular nas redes #MetaHash, Ethereum e outras',


      'speeds-01' : 'Como atingimos tal rapidez?',
      'speeds-02' : 'As transações começam no raio externo e depois são executadas no sentido do núcleo da rede usando a rota mais rápida.',
      'speeds-03' : 'Cada fase aprova uma transação a caminho do núcleo.',
      'speeds-04' : 'Os nós mais rápidos da rede nuclear sincronizam as transações entre si.',
      'speeds-05' : 'A rede nuclear devolve o saldo das carteiras à rede, que verifica a correção dos cálculos.',
      'speeds-06' : 'Os dados de apoio vão para o clássico Blockchain, verificando a integridade da rede.',
      'speeds-07' : 'As âncoras (hash do bloco mais longo) são guardadas nas redes Bitcoin, Ethereum e outras redes.',
      'speeds-08' : 'Não conseguirá corromper ou modificar a informação guardada em #MetaHash. Para o fazer, seria necessário conseguir atacar de forma bem-sucedida a rede #MetaHash, assim como as redes Bitcoin, Ethereum e outras.',
      'speeds-09' : 'Consulte o nosso Artigo Técnico para mais detalhes técnicos',
      'speeds-10' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Transferir Artigo Técnico<i class="icon icon_dowload"></i></a>',


      'metaapps-01' : '#MetaApps',
      'metaapps-02' : 'Serviço na nuvem para aplicações inteligentes em tempo real',
      'metaapps-03' : '#MetaApps é uma evolução dos Contratos Inteligentes e pode ser usada para descentralizar qualquer serviço. São programas independentes que podem existir para sempre e não pertencem a ninguém. Funcionam exatamente como programados e não podem ser adulterados por terceiros.',
      'metaapps-04' : 'Vantagens de #MetaApps',
      'metaapps-05' : 'Funcionamento em tempo real',
      'metaapps-06' : 'Tão rápido como os serviços e aplicações web normais',
      'metaapps-07' : 'Qualquer design GUI',
      'metaapps-08' : 'Podem parecer aplicações ou páginas web normais',
      'metaapps-09' : 'Segurança',
      'metaapps-10' : "Ninguém pode alterar o comportamento das aplicações contornando as regras de atualização",
      'metaapps-11' : 'A imagem do programa e do sistema operativo é carregada para a rede e inicia automaticamente em diversos computadores.',
      'metaapps-12' : 'Criado em qualquer linguagem de programação, incluindo C++, Solidity e outros.',
      'metaapps-13' : 'Suporte completo da funcionalidade de Contratos Inteligentes, pode trabalhar com qualquer Blockchain ou apenas com dados da internet.',


      'metagate-01' : '#MetaGate',
      'metagate-02' : 'Portal de ligação à internet descentralizada',
      'metagate-03' : '#MetaGate é um programa de código aberto, por isso todos os desenvolvedores podem integrar partes do seu código nas suas aplicações e nos seus navegadores.',
      'metagate-04' : 'Carteira multiativos',
      'metagate-05' : 'A carteira suporta "modo light" sem transferir todo o Blockchain. Os dados vêm de diferentes fontes da rede descentralizada e são verificados pelo utilizador. As chaves privadas de todos os Blockchains usados serão armazenadas apenas pelo utilizador.',
      'metagate-06' : 'Catálogo de aplicações',
      'metagate-07' : 'Catálogo de aplicações descentralizadas e navegador para trabalhar com as mesmas. Qualquer aplicação descentralizada incorporada em <b>#MetaHash</b> pode ser acedida, não apenas pelo domínio de internet padrão, mas também através de <b>#MetaGate</b> ou pode ser alocada a um programa separado.',
      'metagate-08' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Transferir Artigo Técnico<i class="icon icon_dowload"></i></a>',
	  'metagate-download-button' : 'Download #Metahash',

      'metahashcoin-01' : '#MetaHashCoin (#MHC)',
      'metahashcoin-02' : 'Modelo financeiro #MetaHash',
      'metahashcoin-03' : '#MetaHash é um sistema de autofinanciamento com um processo de autodesenvolvimento integrado no seu código genético.',
      'metahashcoin-04' : '#MetaHashCoin é usado para pagamento:',
      'metahashcoin-05' : 'Transações',
      'metahashcoin-06' : 'Transações imediatas e fiáveis de quaisquer ativos a um preço fixo razoável.',
      'metahashcoin-07' : 'Armazenamento de dados',
      'metahashcoin-08' : 'Para aplicações que necessitem de armazenar dados, mas que não tenham a velocidade e volume de dados dos sistemas Blockchain convencionais.',
      'metahashcoin-09' : 'Funcionamento da aplicação',
      'metahashcoin-10' : 'Qualquer aplicação descentralizada ou Contrato Inteligente requer recursos para implementação, incluindo a própria rede <b>#MetaHash</b>.',
      'metahashcoin-11' : 'Outros serviços',
      'metahashcoin-12' : 'Pagamento de endereços públicos, listagem em  <b>#MetaApps</b>, publicitação em <b>#MetaGate</b> e outras fontes.',
      'metahashcoin-13' : '<a href="#private-round" class="btn -default btn-mobile">Comprar #MHC<i class="icon icon_link"></i></a>',


      'minig-01' : 'Mineração / forjamento de #MHC',
      'minig-02' : 'Servidores',
      'minig-03' : 'Usados para o funcionamento da rede de transações, recursos livres usados para o funcionamento das aplicações descentralizadas.',
      'minig-04' : 'Carteiras #MetaGate',
      'minig-05' : 'Em Modo completo, os nós são usados como armazenamento de dados e Nós de Torrent.',
      'minig-06' : '#MetaHashCoins',
      'minig-07' : 'Fortalecer a segurança do consenso no modelo de votação híbrida para componentes PoW + PoS.',
      'minig-08' : '#MHC recebidas da venda de serviços são usadas para:',
      'minig-09' : 'formação de desenvolvedores que criem os seus projetos em #MetaHash',
      'minig-10' : 'melhoria da qualidade dos projetos',
      'minig-11' : 'promoção de #MetaHash',
      'minig-12' : 'pagamentos a proprietários de #MetaHashCoins para suporte de consenso',
      'minig-13' : 'pagamentos aos proprietários de servidores e computadores',


      'compare-00' : ' ',
	  'compare-01' : 'Vantagens #MetaHash',
      'compare-02' : 'Após termos procurado e não termos encontrado nenhum projeto que trabalhasse na criação de um circuito totalmente descentralizado e sincronizado capaz de processar rapidamente a quantidade de dados necessária a nível mundial, decidimos criar a #MetaHash.',
      'compare-03' : 'Tabela de comparação dos principais sistemas Blockchain',
      'compare-04' : 'Tempo de aprovação <br />da transação',
      'compare-05' : 'Transações por segundo (TPS)',
      'compare-06' : 'Nível <br />de descentralização',
      'compare-07' : 'Bitcoin',
      'compare-08' : '10 minutos',
      'compare-09' : 'até 12',
      'compare-10' : 'elevado',
      'compare-11' : 'Ethereum',
      'compare-12' : '15 segundos',
      'compare-13' : 'até 30',
      'compare-14' : 'elevado',
  //    'compare-15' : 'Plasma',
  //    'compare-16' : '15 seconds',
  //    'compare-17' : 'up to 30',
  //    'compare-18' : 'high',
      'compare-19' : 'EOS',
      'compare-20' : '5 segundos',
      'compare-21' : 'entre 1000 e milhões',
      'compare-22' : 'mínimo',
      'compare-23' : '#MetaHash',
      'compare-24' : 'até 3 segundos',
      'compare-25' : 'entre 50 000 e milhões',
      'compare-26' : 'elevado',
      'compare-27' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Transferir Artigo Técnico<i class="icon icon_dowload"></i></a>',


      'timemap-01' : 'Roteiro',
      'timemap-02' : 'A parte técnica do projeto foi baseada nas conquistas de AdSniper, criado em 2012 até 2017 na área das tecnologias publicitárias.',
      'timemap-03' : "Recebemos imensos pedidos de diferentes empresas para a aplicação de tecnologia Blockchain e chegámos à conclusão de que as tecnologias atuais não conseguem satisfazer pedidos para esses tipos de sistemas. Por isso, em 2016 começámos a desenvolver o nosso próprio protocolo #TraceChain.",
      'timemap-04' : 'Em 2017, criámos versões alfa e beta do protocolo #TraceChain e unimos forças com as pessoas e empresas mais fortes nas áreas de marketing internacional e desenvolvimento de negócios.',
      'timemap-05' : '2012-2016',
      'timemap-06' : 'A network library for receiving signals, working on C++ and capable of simultaneously receiving and sending more than 100,000 requests per second to one inexpensive standard server',
      'timemap-07' : 'A network library for synchronizing signals within a cluster that manages gigantic data flows between cluster machines.',
      'timemap-08' : 'A machine learning system that decides in 40 milliseconds to respond to a signal taking into account multifactorial interrelationships.',
      'timemap-09' : 'Own analogue of Hadoop’s for similar systems in C ++ for distributed processing of large data.',
      'timemap-11' : '2017',
      'timemap-12' : 'Development of #TraceChain protocol (Alpha version)',
      'timemap-13' : 'Development of #TraceChain protocol (Beta version)',
      'timemap-14' : '<b>AdNow</b> team joins us',
      'timemap-15' : '<b>Agranovsky IT</b> team joins us',
      'timemap-16' : 'Formation of <b>Business Development team</b>',
      'timemap-17' : 'Formation of <b>Operational Team</b>',
      'timemap-18' : '2018',


      'timemap-19' : '#MetaHash website official launch',
      'timemap-20' : 'Start of the Operational Team office construction',
      'timemap-21' : 'Onboarding of experts and advisors',
      'timemap-22' : 'Development of #MetaGate (v.1.0). Multi-asset wallet featuring the ability to transfer #MetaHashCoins between wallets on multiple servers that stores data on transactions between crypto wallets.',
      'timemap-23' : 'Development of #TraceChain (v.1.0)',
      'timemap-23a': 'Development of #TraceChain (v.2.0). #TraceChain data download API',
      'timemap-24' : 'Development of #MetaICO (v.1.0). The ICO interface on the #MetaHash platform that accepts assets from various blockchains (Bitcoin and Ethereum), distributes tokens in the #MetaHash network and carries out multichain transactions, including ERC20 in the Ethereum network',
      'timemap-25' : 'Development of #MetaChains (v.1.0). Converting #MetaHashCoins to ERC20 and withdrawing them to the Ethereum network so that #MHC holders can choose which network to use and automatically convert ERC20 tokens into #MetaHashCoins',

      'timemap-26' : 'Development of #MetaApps (v.1.0). Application Platform',
      'timemap-27' : 'Testnet data download API',
      'timemap-28' : 'Opening of the Operational Team office',


      'timemap-29' : 'ICO Round A scheduled start',
      'timemap-30' : 'Development of #MetaChains (v.2.0). API featuring transaction history and balance  of wallets associated with different blockchain platforms. Decentralized application containing information about transactions in the Ethereum and Bitcoin networks which is necessary to provide blockchain interoperability in #MetaApps',
      'timemap-31' : 'Release of <b>#MetaGate (v.2.0)</b>. Encrypted messenger for public notifications and messaging between wallets',
      'timemap-32' : 'Release of <b>#TraceChain (v.3.0)</b>. Peer nodes that connect to TestNet to be installed on any server',
      'timemap-33' : '#TraceChain (v.4.0). Network core performance testing service (1,000,000+ transactions per second)',
      'timemap-34' : '#MetaICO (v.2.0). Interface for creating tokens inside the network #MetaHash',
      'timemap-35' : '#MetaICO (v.3.0). Release of ICO project platform at #MetaHash.',
      'timemap-36' : '#TraceChain (v.4.0). Voting functions in the #MetaHash network',
      'timemap-37' : '#TraceChain (v.5.0). AI managing the routing of signals between nodes for providing maximum speed of #MetaHash block creation and bandwidth and 100 test nodes in different geographical locations for testing node interaction',

      'timemap-38' : '#MetaICO (v.4.0). Release of the #MetaToken application, tokenization of ETH, ERC20, Bitcoin to #MetaHashCoin for use in the #MetaHash network',
      'timemap-39' : '#TraceChain (v.6.0). #MetaStorage, service for decentralized applications',
      'timemap-40' : '#MetaApps (v.2.0). The platform for self-deployment of third-party decentralized applications',
      'timemap-41' : '#MetaGate (v.3.0). Final release of #MetaGate wallet for Mac/Win/Unix/Android/iOS with #MetaApps catalogue',


      'timemap-42' : '<b>#TraceChain (v.7.0). Start of forging </b>',
      'timemap-43' : '<b>Início da Ronda B da ICO ou conclusão do Acordo de Participação com a bolsa de criptomoeda devidamente organizada e regulada</b>',
      'timemap-44' : 'Comunicação de plano',


      'timemap-45' : 'Testes de segurança exaustivos',
      'timemap-46' : 'Publicação do código fonte após conclusão dos testes',
      'timemap-47' : 'Lançamento de um sistema totalmente descentralizado',
      
      'timemap-100' : 'Ler mais',
	  'timemap-101' : 'Ocultar Eventos',
	  'timemap-102' : 'Outros eventos',


      'teambanner-01' : 'A nossa equipa',
      'teambanner-02' : '#MetaHash é um projeto estruturado com uma equipa aberta, que acolhe todas as pessoas e empresas.',
      'teambanner-03' : 'Se acha que pode ser útil e quiser juntar-se à equipa, entre em <a class="team-write" href="mailto:hello@metahash.org">contacto connosco</a>.',
      'teambanner-04' : '<a href="#private-round" class="btn -default">Ronda A da ICO<i class="icon icon_link"></i></a>',
      'teambanner-05' : 'Se acha que pode ser útil e quiser juntar-se à equipa, entre em <a href="mailto:hello@metahash.org">contacto connosco</a>.',
      'teambanner-06' : 'Ronda A da ICO',
      'teambanner-07' : '<img src="img/graphical/People_PT@3x.svg" alt="">',

      'team-hidden-01' : 'No interesse do próprio projeto, os nomes dos restantes membros da equipa são apresentados',

      'team-dev-00' : 'Desenvolvimento',
	  'team-dev-01' : 'Gleb Nikitin',
	  'team-dev-01a' : 'Cofundador, Sócio, CRO <a href="http://www.facebook.com/glebnikitin" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="https://www.linkedin.com/in/glebnikitin/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
      'team-dev-02' : 'Oleg Romanenko',
      'team-dev-03' : 'Agente de Atendimento ao Cliente, O arquiteto dos serviços em tempo real da AdSniper e analista de sistemas do sistema bancário online AlfaBank. Criador da biblioteca de rede de alta capacidade capaz de servir mais de 1 milhão de pedidos por segundo em 1 nó.',
      'team-dev-04' : 'Mikhail Zarutskiy',
      'team-dev-05' : 'Diretor de Tecnologia, Diretor de IA, Big Data e das equipas de serviços em tempo real para a criação da IA Razoom, capaz de lidar com milhões de pedidos em tempo real, combinando cálculos de redes neurais com outros algoritmos de aprendizagem automática.',
      'team-dev-06' : 'Sergey Raylyan',
      'team-dev-07' : "Diretor de Informática, planeia e coordena a implementação de dezenas de diferentes tecnologias e interfaces que formam o stack tecnológico da AdSniper.",
      'team-dev-08' : '29 colaboradores AdSniper <i class="icon icon_link"></i>',
      'team-dev-09' : "Ao longo dos últimos 10 anos, a empresa criou redes publicitárias de elevada procura. O grande processador de dados próprio da empresa incorpora a manutenção de petabytes de dados, bases de dados rápidas NoSQL e SQL, sistemas de inteligência artificial e bibliotecas C ++ para serviços publicitários de elevada capacidade, processando pedidos de publicidade de toda a internet.",
      'team-key-staff' : 'Principais elementos da equipa',


      'team-mark-00' : 'Marketing',
	  'team-mark-01' : 'Vladimir Bashkin',
	  'team-mark-01a' : 'Presidente Executivo AdNow, CMO <a href="http://www.facebook.com/vladimir.bashkin" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="http://www.linkedin.com/in/vladimir-bashkin-18877678/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
      'team-mark-02' : 'Rede publicitária com mais de mil milhões de impressões por dia. Uma das equipas mais fortes do mundo para compra de publicidade em todas as redes publicitárias com a sua própria equipa de tradutores e especialistas publicitários nos mercados locais.',
      'team-mark-03' : '89 colaboradores <i class="icon icon_link"></i>',
      'team-mark-04' : 'Artem Kravchenko',
      'team-mark-05' : 'Diretor de Eventos - Diretor de RP. Presidente Executivo da AdDays Digital Events. Diretor de Eventos na Rede de Afiliados Bitcomo',
      'team-mark-06' : 'Daria Baranova',
      'team-mark-07' : 'Diretora de Afiliados - Diretora Comercial de Publicação da AdNow. Diretora Executiva do Escritório de Moscovo',
      'team-mark-08' : 'Pham Thành Trung',
      'team-mark-09' : "Diretor do Departamento de Anunciantes - Diretor do Departamento Comercial da AdNow na Região Asiática. Gestor Comercial e de Desenvolvimento de Negócios da AdNow",


      'team-fin-00' : 'Desenvolvimento de Negócio',
	  'team-fin-01' : 'Anton Agranovsky',
	  'team-fin-01a' : 'Cofundador, Sócio, Diretor de Desenvolvimento Comercial <a href="https://www.facebook.com/aagranovsky" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="https://www.linkedin.com/in/anton-agranovsky-57427a15a/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
      'team-fin-02' : 'Agranovsky IT - empresa de investimento, investe em startups de TI e acompanha o crescimento das empresas desde a ideia até à OPI. O Fundador Anton Agronovsky é um investidor, especialista, líder de opiniões na área do estabelecimento e desenvolvimento de empresas de TI. Membro do conselho da Plastic Media e da SMX Communications. Em 2008-2017 - fundador e presidente da Destiny Development, uma das primeiras empresas de jogos no mercado de internet Russo conhecida pelos seus próprios desenvolvimentos e localizações. <br />&nbsp;<br /><a href="https://goo.gl/fJVjfK" class="link -link-small" target="_blank">Consultor da revista Forbes</a>',
      'team-fin-03' : '11 colaboradores na Agranovsky IT <i class="icon icon_link"></i>',
      'team-fin-04' : 'Gennady Yakunin',
      'team-fin-05' : 'Presidente Executivo - Organização de contabilidade em empresas participantes. Mais de 10 anos de experiência em TI e projetos de jogos.',
      'team-fin-06' : 'Svetlana Rudenok',
      'team-fin-07' : 'Presidente Executiva Adjunta - Especialista em avaliação de risco, mais de 10 anos de experiência em auditoria de projetos novos e ativos nas industrias de TI e jogos.',
      'team-fin-08' : 'Andrey Korostelev',
      'team-fin-09' : 'Diretor Financeiro - Mais de 10 anos de experiência em gestão financeira de projetos de TI e de jogos. Apoiante ativo de projetos sociais e de caridade.',


      'team-oper-00t' : 'Equipa Operacional',
	  'team-oper-01' : 'Dmitry Ushakov',
      'team-oper-02' : '<span style="color:#ffffff;">Diretor de Operações, Gestor Geral de Projeto</span><br/>Mais de 11 anos de experiência em gestão operacional de projetos multiutilizador para a Game Insight e outras startups de TI.',
      'team-oper-03' : 'Michaił Iwanow',
      'team-oper-04' : '<span style="color:#ffffff;">Diretor Artístico</span><br/>com mais de 16 anos de experiência em design visual e de produto. Trabalhou em projetos para a RUSNANO, Sony, Canon, Nikon e outras empresas.',
      'team-oper-05' : 'Zhibo Fan',
      'team-oper-06' : '<span style="color:#ffffff;">Diretor de Desenvolvimento Comercial Ásia, MENA</span><br/>Fundador da plataforma de jogos Game.ru e editor de jogos INFIPLAY.',
      'team-oper-07' : 'Alexander Zhigarenko',
      'team-oper-08' : '<span style="color:#ffffff;">Diretor de Desenvolvimento Comercial Rússia, CIS</span><br/>Mais de 10 anos de experiência em publicação, operação e desenvolvimento de negócio para a Destiny Games e na indústria de jogos.',
      'team-oper-09' : 'Eugenia Sigacheva',
      'team-oper-10' : '<span style="color:#ffffff;">Public Affairs Partner</span><br/>More than 18 years in international Marketing & PR, also IT&Innovations. Eugenia is a part of International team of the well known robot Sophia and CEO&Founder of the IHEART Platform.',
      'team-oper-11' : 'Andrey Akimov',
      'team-oper-12' : '<span style="color:#ffffff;">Chief Communication Officer</span><br/>More than 15 years in marketing and PR in gaming, entertainment, and IT business. Former head of PR and marketing at My.com, Mail.Ru Group, Game Insight, and other companies.',
      'team-oper-00' : '17 colaboradores na Equipa Operacional <i class="icon icon_link"></i>',


      //'legal-01' : 'Suporte Legal',
      //'legal-02' : 'Anastasia Pichugina',
      //'legal-03' : 'Sócia Administradora da ANP Law <a href="https://www.facebook.com/people/Anastasia-Pichugina/1520204010" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
      //'legal-04' : 'Ekaterina Myznikova',
      //'legal-05' : 'Advogada Sénior - Responsável de projetos Blockchain. Acompanha de forma bem-sucedida vários projetos ICO, é participante e oradora em importantes conferências e webinars.',
      //'legal-06' : 'Maxim Mekhriakov',
      //'legal-07' : 'Advogado Sénior - Responsável pela Prática Comercial na ANP Law, especializando-se no suporte legal de transações comerciais e de investimento.',
      //'legal-08' : 'Anna Shevchenko',
      //'legal-09' : 'Advogada - Suporte legal de empresas Russas e estrangeiras na área dos direitos e propriedade intelectual, incluindo registo de marcas e patentes.',
      //'legal-10a' : 'Firma jurídica ANP Law',
	  //'legal-10' : 'Especialistas em lei Russa e Internacional. Os nossos advogados licenciaram-se nas escolas de direito mais prestigiadas da Rússia e do exterior. A sócia administradora Anastasia tem uma experiência e conhecimento únicos em direito Russo e estrangeiro, sendo representante legal de confiança de várias empresas estrangeiras dos mercados de IT e FMCG. Anastasia representou ainda com sucesso empresas estrangeiras em tribunais Russos.',
      //'legal-11' : '<a href="docs/MetaHash_LegalOpinion_EN.pdf" target="_blank">Transferir Parecer Jurídico #MetaHashCoin<i class="icon icon_link"></i></a>',
      'legal-title' : 'Legal Department',

    //'legal-14' : 'Maria Agranovskaya',
    //'legal-15' : 'Chief Legal Coordinator <a href="https://www.facebook.com/magranovskaya" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a> <a href="https://www.linkedin.com/in/maria-agranovskaya-151334/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
    //'legal-16' : '<span>Attorney at Law with 20+ years of experience. Started working with cryptocurrency issues back in 2010. MGIMO MID of Russia (International Law), studied in Germany and Holland. 8,5 years - running a multifamily office, worked on various cross-border transactions, investments, asset management, deal and corporate structuring in various jurisdictions, M&A, international taxation and other matters.</span><span>Areas: fintech, finance, telecom, banking, energy, pharmaceuticals, real estate and other sectors.</span><span>2007: setup of GRAD Attorney Bar (managing partner,  30+ Russian and foreign lawyers)</span><span>Substantially engaged in blockchain technology, ICO (TGE) related projects, trading and finance regulations, funds and financial activity.</span><span>Speaks English, German, French, Italian, </span>',
	 
	  'legal-more' : 'Ler mais',
	  'legal-less' : 'Ocultar Eventos',
	  'legal-17' : 'Andrey Mironov <a href="http://www.linkedin.com/in/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a> <a href="https://www.facebook.com/" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
	  'legal-18' : 'Chief of Legal Department',
	  'legal-19' : 'Graduated MGIMO in 2000 at the international law faculty. Legal practice in the field of new technologies, media and intellectual property for more than 15 years.',
	  'legal-19a' : 'He worked at the Art. Lebedev Studio, Odnoklassniki, the Russian office of Myspace, on the channels MTV, Discovery, Amedia and the online cinema Amediateka. Helped to develop the EKSMO publishing house, the Fox TV channel. Expert at the Russian Association of Electronic Communications (RAEC).<br>Secondary Education: Consultant Psychologist',
	  'legal-20' : 'Maria Agranovskaya',
	  'legal-21' : 'Chief Legal Coordinator',
	  'legal-22' : 'Attorney at Law with 20+ years of experience. Started working with cryptocurrency issues back in 2010.',
	  'legal-22a' : 'MGIMO MID of Russia (International Law), studied in Germany and Holland. 8,5 years - running a multifamily office, worked on various cross-border transactions, investments, asset management, deal and corporate structuring in various jurisdictions, M&A, international taxation and other matters. Areas: fintech, finance, telecom, banking, energy, pharmaceuticals, real estate and other sectors. 2007: setup of GRAD Attorney Bar (managing partner,  30+ Russian and foreign lawyers). Substantially engaged in blockchain technology, ICO (TGE) related projects, trading and finance regulations, funds and financial activity. Speaks English, German, French, Italian,  Spanish.',
	  'legal-23' : 'Katya Fisher',
	  'legal-24' : 'Partner, Principal at The Law Office of Katya Yoffe PLLC',
	  'legal-25' : 'Katya Yoffe (née Fisher) is an attorney focusing on general corporate law, cross-border transactions and business immigration.',
	  'legal-25a' : 'Katya represents various prominent companies and startups doing business in the United States as well as celebrity and HNW individuals. Katya has been selected to Super Lawyers as a “Rising Star” in 2014, 2015, 2016, 2017 and 2018. <br>Katya is a graduate of New York University, the Benjamin N. Cardozo School of Law and a former Howard M. Squadron Fellow in International Media Law & Policy at the University of Oxford and Center for Global Communication Studies, University of Pennsylvania. She is admitted to practice in New York and before the United States Tax Court.',
	  'legal-26' : 'Anastasia Pichugina',
	  'legal-27' : 'ANP Law Managing Partner ',
	  'legal-28' : 'Managing partner Anastasia has a unique experience and knowledge in Russian and foreign law, is a trusted legal representative of several foreign companies.',
	  'legal-29' : 'Ekaterina Myznikova',
	  'legal-30' : 'Advogada Sénior',
	  'legal-31' : 'Responsável de projetos Blockchain. Acompanha de forma bem-sucedida vários projetos ICO, é participante e oradora em importantes conferências e webinars.',
	  'legal-32' : 'International Legal Support',
	  'legal-33' : 'Daniel G. Viola',
	  'legal-34' : 'Partner, Head of Regulatory and Compliance Group at Sadis & Goldberg LLP',
	  'legal-35' : 'Oliver Ciric',
	  'legal-36' : 'Partner at TA Advisory',
	  'legal-37' : 'Daniel G. Viola is a partner of <span class="ilegal-white">Sadis & Goldberg LLP</span> and the Head of its Regulatory and Compliance Group.  Mr. Viola has been active in the Blockchain and Virtual Currency verticals since 2014. He also served as a Senior Compliance Examiner for the <span class="ilegal-white">Northeast Regional Office of the SEC,</span> where he worked from 1992 through 1996',
	  'legal-37a' : 'During his tenure at the SEC, Mr. Viola worked on several compliance inspection projects and enforcement actions involving examinations of registered investment advisers, ensuring compliance with federal and state securities laws. Mr. Viola’s examination experience includes financial statement, performance advertising, and disclosure document reviews, as well as, analysis of investment adviser and hedge fund issues arising under ERISA and blue-sky laws. In late 2006 Mr.  Viola founded his own law firm and eventually merged it into Sadis & Goldberg’s law practice.',
	  'legal-38' : 'Experience in international jurisprudence for more than 20 years. Oliver graduated from Boston University of Law in 2006, majoring in banking and finance law, and the Geneva University of Law in 1998, specializing in "License and Law". Previous work experience:  Nationale Suisse Assurances, Matile Brosset Stickel-Cicurel & Gianninazzi, Poncet Turrettini Amaudruz Neyroud & Partners, <span class="ilegal-white">Akin Gump Strauss Hauer & Feld LLP</span> (formerly Hogan & Hartson LLP).',
	  'legal-38a' : 'Since June 2017 he has been a partner at <span class="ilegal-white">TA Advisory</span>. Mr. Ciric provides legal support for blockchain projects, and also advises on cooperation <span class="ilegal-white">with FINMA.</span><br>Languages: German, English, French, Portuguese, Russian, Serbian.',
	  'legal-39' : '<span class="ilegal-white-02">KPMG AG, Switzerland,</span> served as exclusive legal advisor to #MetaHash and its management in the evaluation of regulatory, tax and legal aspects in respect of the White Paper, which is released in preparation of a Coin offering (ICO)',
	  'legal-40' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">Transferir Artigo Técnico<i class="icon icon_dowload"></i></a>',
	  'legal-41' : 'Martin Hess',
      'legal-42' : 'Partner at Wenger & Vieli AG',
	  'legal-43' : 'Martin Hess specializes in financial services and capital markets law, FinTech and the digitization of financial services. He is recognized by the Swiss Stock Exchange as an issuer representative. Martin Hess advises Swiss and foreign clients and represents them vis-à-vis supervisory authorities and in court.',
	  'legal-43a' : 'He is involved in the legal design of trading venues for digital assets, payment systems and securities settlement systems as well as central counterparties. He advises and represents clients on Initial Coin Offerings / Token Generating Events. Since 2001 Partner at Wenger & Vieli Ltd',


   //   'private-01' : 'Private Round',
   //   'private-form' : '<input type="hidden" name="form_subject" value="Private Round Application">',
   //   'private-03' : 'days',
   //   'private-04' : 'Private Round ends in',
   //   'private-05' : 'Private Round',
   //   'private-06' : 'The purpose of the Private Round is to verify the idea before the public launch',
   //   'private-07' : 'We hope to meet experts who are ready to participate in the discussion of the project before its public launch and, possibly, join the #MetaHashTeam.',
   //   'private-08' : '#MetaHash undertakes to inform all Private Round participants about terms of participation, their rights and obligations in connection with participation.',
   //   'private-09' : 'Private Round participants will be able to decide whether to remain in the project after the ICO.',
   //   'private-10' : 'Send an application to participate in the Private Round',
   //   'private-11' : 'We are not interested in the amount, but rather in your expertise. We want experts from different fields to participate in the Private Round.',
   //   'private-12' : 'Describe your expertise in cryptocurrencies. Are you ready to participate in discussion about the project?',
   //   'private-13' : 'Apply <i class="icon icon_link"></i>',
   //   'private-14' : 'Terms of Use',
   //   'private-15' : 'Privacy Policy',
   //   'private-16' : 'Private Round terms:',
   //   'private-17' : 'Do you want to participate in the Private Round or join the #MetaHashTeam?',
   //   'private-18' : 'Participation in the Private Round is public - the name or company name of the participant will be published',
   //   'private-19' : 'Private Round volume - <b>1,840 ETH</b>',
   //   'private-20' : 'The value of the #MHC - <b>0.001 ETH</b>',
   //   'private-21' : 'The volume of the Private Round is not enough to satisfy the requests of all comers',
   //   'private-22' : 'You can fill the application form before the end of the Private Round',
   //   'private-23' : 'At the end of the Private Round, the current #MetaHash team will decide on quotas for each of those wishing to participate',
   //   'private-24' : 'After the completion of the Private Round and the distribution of tasks between the current and new team members, the Pre-ICO will start',
   //   'private-25' : 'Private Round Application',
        'private-26' : 'Insira o seu nome',
        'private-27' : 'Insira o seu e-mail',
   //   'private-28' : 'Desired amount of participation (ETH)',
   //   'private-29' : 'Additional information about yourself',


   //   'timer-day-1' : 'days',
   //   'timer-day-2' : 'days',
   //   'timer-day-3' : 'days',
   //   'timer-hour-1' : 'hour',
   //   'timer-hour-2' : 'hours',
   //   'timer-hour-3' : 'hours',
   //   'timer-minute-1' : 'minute',
   //   'timer-minute-2' : 'minutes',
   //   'timer-minute-3' : 'minutes',
   //   'timer-second-1' : 'second',
   //   'timer-second-2' : 'seconds',
   //   'timer-second-3' : 'seconds',


      'form-sent-01' : 'Obrigado!',
      'form-sent-02' : 'A sua informação foi submetida com sucesso.',


      'faq-01' : 'F.A.Q.',
      'faq-02-00' : 'Sobre #MetaHash',
      'faq-02-01' : 'É uma entidade legal?',
      'faq-02-02' : 'O processo de registo de entidade legal foi iniciado na Suíça. Normalmente, demora algum tempo a chegar a um acordo com o governo Suíço.',
      'faq-02-03' : 'Onde posso examinar o MVP e Código de fonte aberta de #MetaHash?',
      'faq-02-04' : 'A rede centralizada #TraceChain está atualmente ativa com uma carteira multiativos. Os códigos-fonte do protocolo #TraceChain serão lançados após um programa de recompensa de segurança pública para hackers ser aprovado e a patente ser obtida.',
      'faq-02-05' : 'Qual o objetivo geral do token e do produto em si?',
      'faq-02-06' : '#MetaHashCoin é usada para: transações, armazenamento de dados, funções de aplicação. Pode também trocar #MHC para adicionar um endereço público, para listar a sua aplicação no diretório #MetaApp, para adquirir anúncios na rede publicitária #MetaGate e muito mais.',
      'faq-02-07' : 'Quais são as capacidades de velocidade do vosso Blockchain? Como conseguem atingir esse resultado?',
      'faq-02-08' : 'Por favor, consulte o nosso <a href="docs/MetaHash_WhitePaper_EN.pdf" class="link -link-small" target="_blank">Artigo Técnico</a> para saber mais sobre as capacidades do nosso Blockchain.',
      'faq-02-09' : 'É possível minerar a vossa moeda? Há vantagens para mineiros?',
      'faq-02-10' : 'Leia o <a href="docs/MetaHash_WhitePaper_EN.pdf" class="link -link-small" target="_blank">Artigo Técnico</a> para obter mais detalhes sobre mineração.',
      'faq-02-11' : 'Que sistema de prova usam: POW ou POS?',
      'faq-02-12' : '#MetaHash usa um algoritmo de consenso híbrido. Trata-se de um sistema multiPOS que inclui os resultados de votação de nós de rede separados.',


      'faq-03-00' : 'Ronda A da ICO / Ronda B da ICO e compra de #MHC',
      'faq-03-01' : 'Que métodos de pagamento aceitam?',
      'faq-03-02' : 'Apenas aceitamos ETH. Outros ativos digitais devem primeiro ser trocados por ETH.',
      'faq-03-03' : '',
      'faq-03-04' : '',
      'faq-03-05' : 'Posso participar a partir de uma plataforma de câmbio?',
      'faq-03-06' : 'Sim, pode. Mas apenas aceitamos ETH.',
      'faq-03-07' : '',
      'faq-03-08' : '',
      'faq-03-09' : 'Quando termina a Ronda A / Ronda B da ICO?',
      'faq-03-10' : 'A Ronda A da ICO decorre até que seja atingido o montante pretendido. A Ronda B da ICO começa após o lançamento do MVP.',
      'faq-03-11' : 'Quais são os termos especiais da carteira multiativos #MHC?',
      'faq-03-12' : 'A carteira multiativos #MetaGate é um produto de código-fonte aberto. O seu uso é financiado por pagamentos de anúncios apresentados e subscrições de bloqueio de anúncios.',


      'faq-04-00' : '#MetaHashCoin e Perspetivas',
      'faq-04-01' : 'Quais são as diferenças gerais entre #MetaHash e qualquer outro provedor de Blockchain?',
      'faq-04-02' : 'Todos os concorrentes existentes são lentos ou centralizados. A próxima geração de Blockchains deverá ser ágil, totalmente descentralizada e ter também transações baratas. Não existe nenhum projeto (à exceção de #MetaHash) que cubra todos estes requisitos.',
      'faq-04-03' : '#MHC ERC20 é emitida através de Contrato Inteligente ETH?',
      'faq-04-04' : '#MHC é uma moeda independente e separada, que é operada numa cadeia separada. Ainda assim, existem alguns contratos espelho em Ethereum e #MetaHash. Estes contratos espelho permitem o procedimento de tokenização de tokens ERC20 em ambas as direções.',
      'faq-04-05' : 'Qual a oferta total de tokens?',
      'faq-04-06' : '92 000 000 #MHC serão lançadas ao longo de um período de 10 anos. 46 000 000 #MHC serão lançadas no primeiro ano.',
      'faq-04-07' : 'Que plataformas bolsistas irão trocar as #MetaHashCoins?',
      'faq-04-08' : 'A disponibilidade de moeda em plataformas bolsistas será anunciada através dos canais públicos oficiais de #MetaHash. Não estamos autorizados a divulgar antecipadamente esta informação.',
      'faq-04-09' : 'Qual será o preço inicial da #MHC após a ICO quando atingir o mercado aberto? E após um ano?',
      'faq-04-10' : 'O custo da #MetaHashCoin é determinado pelas necessidades do mercado. #MHC é usada para pagar os seguintes serviços: transações, armazenamento de dados, funcionamento de aplicações, etc. Estes fatores irão influenciar o custo da #MHC.',
      'faq-04-11' : 'Quando começa/termina a venda de tokens?',
      'faq-04-12' : 'Planeamos concluir a Ronda A da ICO até final de 2018. A Ronda B da ICO iniciará oficialmente no quarto trimestre de 2018 ou no 1T de 2019.',


      'faq-05-00' : 'Processo de Venda #MHC',
      'faq-05-01' : 'Há um limite mínimo para participar em #MetaHash?',
      'faq-05-02' : 'Não definimos nenhum limite mínimo. Poderá adquirir tantos tokens quantos quiser.',
      'faq-05-03' : 'Quando é que os tokens serão disponibilizados aos participantes?',
      'faq-05-04' : 'Serão fornecidas moedas TestNet #MetaHash ou as suas substitutas ERC20 quando a Ronda B da ICO for concluída.',
      'faq-05-05' : 'O que farão com as moedas não vendidas?',
      'faq-05-06' : 'Todos os ativos não vendidos irão permanecer na Empresa #MetaHash.',
      'faq-05-07' : 'Eu transferi 0,07 ETH para a minha carteira #MetaHash. Quantos tokens irei receber?',
      'faq-05-08' : 'Pode usar a nossa calculadora interna.',
      'faq-05-09' : 'Como posso comprar #MHC se não tiver ativos de criptomoeda.',
      'faq-05-10' : 'Não pode: tem de converter o seu dinheiro em ETH ou BTC. Pode usar qualquer plataforma bolsista que quiser.',



      'faq-06-00' : 'Outras Questões',
      'faq-06-01' : 'Sou um cidadão Chinês ou Coreano, é legal participar na venda coletiva de ICO #MetaHash?',
      'faq-06-02' : 'Todas as nacionalidades exceto: Estados Unidos, Singapura, República Socialista do Vietname, República Popular da China ou residentes de um país em que embargos ou sanções Americanas estejam em vigor, nomeadamente Irão, Coreia do Norte, Síria, Sudão ou Cuba. Mais informações nos nossos Termos de Venda de Tokens.',
      'faq-06-03' : 'Então em suma, o que é #TraceChain?',
      'faq-06-04' : '#TraceChain é a próxima geração de sistemas Blockchain. A solução é baseada num algoritmo de encaminhamento autónomo com autoaprendizagem. Começa o seu funcionamento a uma velocidade de 50 000 transações por segundo (velocidade básica de um canal de 100 Mb/s) e aumenta adicionando números razoáveis de canais de alta velocidade. Estes canais formam o núcleo da rede #MetaHash e tornam o seu funcionamento estável.',
      'faq-06-05' : 'Hard cap / soft cap?',
      'faq-06-06' : 'O soft cap é atingido através dos Fundadores e da Ronda Privada. O hard cap não está determinado.',
      'faq-06-07' : 'Eu depositei 0,0067769 BTC/ETH, quando serão convertidos em tokens #MHC?',
      'faq-06-08' : "Os tokens são entregues após terem sido recebidas seis confirmações na rede Ethereum e nos nós #MetaChains. Normalmente, damos 6 horas para validar as transações das redes ETH e BTC. Não se preocupe se não receber as suas moedas em 6 horas. Envie-nos um relatório e iremos resolver o seu problema. O seu depósito é uma transação em si. Se a transação foi realizada, as suas moedas ser-lhe-ão enviadas.",
      'faq-06-09' : 'Quais são as datas oficiais da Ronda Privada, das Rondas A/B da ICO e restantes?',
      'faq-06-10' : 'As datas oficiais dos períodos de Ronda A e Ronda B da ICO ainda não estão definidos. Serão anunciadas em breve através dos nossos canais públicos. Mantenha-se atento e será o primeiro a saber.',
      'faq-06-11' : 'A #MetaHash é uma bifurcação de BTC ou ETH?',
      'faq-06-12' : '#MetaHash não é uma bifurcação. É um provedor de blockchain independente que é muito mais rápido e mais seguro.',


      'support-01' : 'Tem alguma questão? Contacte-nos!',
      'support-02' : 'Submeter',
      'support-03' : 'User question',
      'support-04' : 'Insira o seu nome',
      'support-05' : 'Insira o seu e-mail',
      'support-06' : 'A sua pergunta',


      'prefooter-01' : 'Entre na corrida!',
      'prefooter-02' : '#MetaHashTeam',
      'prefooter-03' : '<a href="#private-round" class="btn -default">Comprar #MHC<i class="icon icon_link"></i></a>',
      'prefooter-04' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Transferir Artigo Técnico<i class="icon icon_dowload"></i></a>',
      'prefooter-05' : '<a href="docs/MetaHash_OnePager_PT.pdf" target="_blank" class="btn -download">Transferir Sumário<i class="icon icon_dowload"></i></a>',
      'prefooter-06' : 'Participe da Ronda A da ICO',
      'prefooter-07' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Artigo Técnico</a>',
      'prefooter-08' : '<a href="docs/MetaHash_OnePager_PT.pdf" target="_blank" class="btn -download float-right">Sumário</a>',


      'footer-01' : 'O que é #MetaHash?',
      'footer-02' : 'Comprar #MetaHashCoin (#MHC)',
      'footer-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -footer-link">Artigo Técnico</a>',
      'footer-04' : '<a href="docs/MetaHash_OnePager_PT.pdf" target="_blank" class="link -footer-link">Sumário</a>',
      'footer-05' : 'FAQ',
      'footer-06' : '<a href="docs/MetaHash_TermsOfUse_EN.pdf" target="_blank" class="link -footer-link">Termos de Utilização</a>',
      'footer-07' : '<a href="docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank" class="link -footer-link">Política de Privacidade</a>',
      'footer-08' : '<a href="docs/MetaHash_AntiSpam_EN.pdf" target="_blank" class="link -footer-link">Política Anti-Spam</a>',
      'footer-09' : 'Acordo de Consultor',
      'footer-10' : '<a href="docs/MetaHash_RiskDisclosureStatement_EN.pdf" target="_blank" class="link -footer-link">Acordo de Divulgação de Risco</a>',
      'footer-11' : 'Redes sociais e serviços de mensagens',
      'footer-12' : 'Fóruns',
      'footer-13' : 'Feedback em <a href="mailto:hello@metahash.org" class="link -link-small">hello@metahash.org</a>',
      'footer-14' : 'Suporte em <a href="mailto:support@metahash.org" class="link -link-small">support@metahash.org</a>',
      'footer-15' : 'Questões de imprensa <a href="mailto:support@metahash.org" class="link -link-small">press@metahash.org</a>',
      'footer-16' : 'Gabinete de imprensa <a class="link -link-small">+7 926 671-67-08</a>',
	  'copyright' : 'Copyright © 2017-2018 #MetaHash. Todos os Direitos Reservados',

      'mobile-menu-01' : '<a href="#whatis" class="link -link-white">O que é #MetaHash?</a>',
      'mobile-menu-02' : '<a href="#private-round" class="link -link-white">Comprar #MetaHashCoin (#MHC)</a>',
      'mobile-menu-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -link-white">Transferir Artigo Técnico</a>',
      'mobile-menu-04' : '<a href="docs/MetaHash_OnePager_PT.pdf" target="_blank" class="link -link-white">Transferir Sumário</a>',
      'mobile-menu-05' : '<a href="#faq" class="link -link-white">F.A.Q.</a>',
      'mobile-menu-06' : '<a href="#support" class="link -link-white">Suporte</a>',
      'mobile-menu-07' : '<a href="#support" class="link -link-white">Contactos</a>',
	 
	  'new-mobile-menu-01' : '<a href="#whatis" class="link -link-white --offcan">O que é #MetaHash?</a>',
	  'new-mobile-menu-02' : '<a href="#tracechain" class="link -link-white --offcan">#TraceChain</a>',
	  'new-mobile-menu-03' : '<a href="#metaapps" class="link -link-white --offcan">#MetaApps</a>',
	  'new-mobile-menu-04' : '<a href="#metagate" class="link -link-white --offcan">#MetaGate</a>',
	  'new-mobile-menu-05' : '<a href="#timemap" class="link -link-white --offcan">Roadmap</a>',
	  'new-mobile-menu-06' : '<a href="#advisors-and-consultants" class="link -link-white --offcan">Advisors & Consultants</a>',
	  'new-mobile-menu-07' : '<a href="#teambanner" class="link -link-white --offcan">The Team</a>',
	  'new-mobile-menu-08' : '<a href="#ico" class="link -link-white --offcan">Ronda A da ICO</a>',
	  'new-mobile-menu-09' : '<a href="#faq" class="link -link-white --offcan">F.A.Q.</a>',
	  'new-mobile-menu-10' : '<a href="#support" class="link -link-white --offcan">Contacte-nos</a>',

      'promo-soc-01' : '<a href="https://t.me/metahash_ENG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
      'promo-soc-02' : '<a href="https://www.facebook.com/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
      'promo-soc-03' : '<a href="https://vk.com/metahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
      'promo-soc-04' : '<a href="https://twitter.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
      'promo-soc-05' : '<a href="https://instagram.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
      'promo-soc-06' : '<a href="https://www.youtube.com/channel/UCIkBIrd1q7JkLLj43KgG8zA" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">youtube.com</span><span class="icon -icon-big icon_youtube"></span></a>',
      'promo-soc-07' : '<a href="#" class="link-soc -tooltype"><span class="soc-tooltype">ID:MetaHash</span><span class="icon -icon-big icon_wechat"></span></a>',
      'promo-soc-08' : '<a href="https://open.kakao.com/o/gY5dUgG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">talk.com</span><span class="icon -icon-big icon_talk"></span></a>',
      'promo-soc-09' : '<a href="https://github.com/metahashorg" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
      'promo-soc-10' : '<a href="https://www.reddit.com/user/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">reddit.com</span><span class="icon -icon-big icon_reddit"></span></a>',
      'promo-soc-11' : '<a href="https://www.linkedin.com/company/27209614/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">in.com</span><span class="icon -icon-big icon_in"></span></a>',
      'promo-soc-12' : '<a href="https://medium.com/@themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">medium.com</span><span class="icon -icon-big icon_medium"></span></a>',
      'promo-soc-13' : '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitsmedia"></span></a>',
      'promo-soc-14' : '<a href="https://bitcointalk.org/index.php?action=profile;u=1253602" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',


      'promo-soc-mobile-01' : '<a href="https://t.me/metahash_ENG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
      'promo-soc-mobile-02' : '<a href="https://www.facebook.com/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
      'promo-soc-mobile-03' : '<a href="https://vk.com/metahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
      'promo-soc-mobile-04' : '<a href="https://twitter.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
      'promo-soc-mobile-05' : '<a href="https://instagram.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
      'promo-soc-mobile-06' : '<a href="https://github.com/metahashorg" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
      'promo-soc-mobile-07' : '<a href="https://www.linkedin.com/company/27209614/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">in.com</span><span class="icon -icon-big icon_in"></span></a>',
      'promo-soc-mobile-08' : '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="link-soc"><span class="icon -icon-big --icon-forum icon_bitsmedia" target="_blank"></span></a>',
      'promo-soc-mobile-09' : '<a href="https://bitcointalk.org/index.php?action=profile;u=1253602" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',

      'tg_button' : '<a href="https://t.me/metahash_ENG" target="_blank"><img class="telega-svg" style="margin-bottom: 40px;" src="img/telegram.svg" alt=""></a>',



      'private-close-01' : 'A Ronda Privada está fechada',
      'private-close-02' : 'Foi concluída após ter sido subscrita 20x mais do que o montante oferecido.',
      'private-close-03' : 'Queremos agradecer a todos os participantes e convidar todos a juntarem-se a nós para a Ronda A da ICO.',
      'private-close-04' : 'Ronda A da ICO',
      'private-close-05' : 'mês programado de início',
      'private-close-06' : 'Ronda A da ICO em breve',
      'private-close-07' : 'não perca o início, registe-se já<br class="mobile-br"> para participar ou juntar-se à nossa equipa',
      'private-close-08' : 'Registar já <i class="icon icon_link"></i>',
      'private-close-09' : 'Fique a par:',
      'private-close-10' : 'Características da Ronda A:',
      'private-close-11' : '<b class="mob-bold">9 200 000 #MHC</b> serão distribuídas durante a Ronda A da ICO',
      'private-close-12' : 'O valor da #MHC para a Ronda A da ICO é de  <b class="mob-bold">0,0125 ETH</b>',
      'private-close-13' : 'As encomendas <b class="mob-bold">inferiores a 50 ETH</b> (12 500 #MHC) são realizadas a partir de uma reserva geral limitada renovada a cada 4 horas. <b class="mob-bold">São realizadas por ordem de entrada</b>',
      'private-close-14' : 'Para manter espaço para pequenos compradores, <b class="mob-bold">as encomendas superiores a 50 ETH</b> são realizadas instantaneamente a partir de uma reserva separada.',
      'private-close-15' : '04/2018',
      'private-close-16' : 'Insira o seu e-mail',
      'private-close-17' : 'pode ser alterado de acordo com<br> o Artigo Técnico', 
      // 'private-close-18' : '<input id="private-close__terms-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__terms-check">I agree to </label><a href="docs/MetaHash_TermsOfUse_EN.pdf" target="_blank">Terms of Use</a>',
      // 'private-close-19' : '<input id="private-close__policy-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__policy-check">I agree to </label><a href="docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank">Privacy Policy</a> ',
      

      'private-close-18' : 'Eu aceito ',
      'private-close-19' : 'Eu aceito ',
      'private-close-25' : '<a href="docs/MetaHash_TermsOfUse_EN.pdf"  target="_blank">Termos de Utilização</a>',
      'private-close-26' : '<a href="docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank">Política de Privacidade</a>',



      'private-close-20' : 'Application submitted',
      'private-close-21' : ', thank you for your interest in <b>#MetaHash</b> project. We will keep you informed about the <b>ICO Round A Start date</b>.',
      'private-close-22' : 'Dont miss a thing!',
      'private-close-23' : '<a href="https://t.me/metahash_ENG" target="_blank"  class="private-close__modal-content_tg-link" >Join our Telegram Channel<br> and stay updated</a>',
      'private-close-24' : '<a href="https://t.me/metahash_ENG" target="_blank" class="support-window__social-block_soc-link support-window__social-block_soc-link_tg"><img class="support-window__social-block_soc-img" src="img/popup/sub-tg.png" alt=""><span class="flag"><img class="support-window__social-block_flag-img" src="img/icons/flag-eng.png"></span></a>',


};