"use strict";

window.arrLang = window.arrLang || {};
window.arrLang["ru"] = {
  
      'nav-link-01' : 'Что такое #MetaHash',
      'nav-link-02' : 'Купить #MHC',
      'nav-link-03' : '<a href="https://static.metahash.org/docs/MetaHash_WhitePaper_RU.pdf" target="_blank" class="download-white-paper link -link-white"><img src="img/icon_file.svg" class="icon_file"> White Paper</a>',
      'nav-link-04' : '<a href="https://static.metahash.org/docs/MetaHash_OnePager_RU.pdf" target="_blank" class="download-one-pager link -link-white"><img src="img/icon_file.svg" class="icon_file"> One-Pager</a>',
      'nav-link-05' : 'Вопросы',
      'nav-link-06' : 'Поддержка',
      'nav-link-07' : 'Напишите нам',

      'promo-nav-heading' : 'Репозитории metahash',
      'promo-nav-link-1' : 'Основные',
      'promo-nav-link-2' : 'Сервисы MetaHash',
      'promo-nav-link-3' : 'Скрипты и приложения, позволяющие сгенерировать адрес и провести транзакцию в сети Metahash',
      'promo-nav-link-4' : 'Библиотеки по генерации уникальных идентификационных иконок для любого Metahash-адреса',
      'promo-nav-link-5' : 'О сети Metahash',
      'promo-nav-link-6' : 'Примеры использования библиотеки v8',
      'promo-nav-link-7' : 'Другие',
      'promo-nav-download' : '<a href="https://github.com/metahashorg/YellowPaper/raw/master/MetaHash_YellowPaper_EN.pdf">Скачать Yellow Paper</a>',


      'promo-content-description-1-1' : 'Содержит исходный код кошелька MetaHash на языке С++,<br/>a так же релизы приложения кошелька под различные операционные системы: <br><a href="https://github.com/metahashorg/metagate/releases">https://github.com/metahashorg/metagate/releases</a>',
      'promo-content-description-1-2' : 'Подробнее о кошельке MetaHash на вики-странице:<br><a href="https://github.com/metahashorg/MetaHash/wiki/MetaHash-Wallet">https://github.com/metahashorg/MetaHash/wiki/MetaHash-Wallet</a>',
      'promo-content-description-2-1' : 'Репозиторий содержит драйвер PHP7 для поддержки нескольких баз данных,<br>в настоящее время поддерживается только Redis DB',
      'promo-content-description-3-1' : 'Исходный код драйвера для PHP cо всем функционалом по генерации кошелька,<br>использует библиотеку из репо cpplib_open_ssl_decor на языке С++',
      'promo-content-description-3-2' : 'Библиотека со всем функционалом по генерации кошелька,<br>написанная на языке C++',
      'promo-content-description-3-3' : 'На языке Python',
      'promo-content-description-3-4' : 'Подробнее на вики-странице<br><a href="https://github.com/metahashorg/MetaHash/wiki/Address-Bash-example">https://github.com/metahashorg/MetaHash/wiki/Address-Bash-example</a>',
      'promo-content-description-3-5' : 'Shell-скрипты<br>Подробнее на вики-странице <br><a href="https://github.com/metahashorg/MetaHash/wiki/Address-Python-example">https://github.com/metahashorg/MetaHash/wiki/Address-Python-example</a>',
      'promo-content-description-3-6' : 'API для генерации адреса и совершения транзакции на языке PHP',
      'promo-content-description-3-7' : 'На языке С++',
      'promo-content-description-3-8' : 'Репозиторий пока пуст',
      'promo-content-description-3-9' : 'Поддерживает тот же функционал по генерации адреса и проверке<br>подписи на языке PHP',
      'promo-content-description-4-1' : 'На языке Python',
      'promo-content-description-4-2' : 'Подробнее на вики-странице<br><a href="https://github.com/metahashorg/MetaHash/wiki/Python-iconhash">https://github.com/metahashorg/MetaHash/wiki/Python-iconhash</a>',
      'promo-content-description-4-3' : 'На языке JavaScript',
      'promo-content-description-4-4' : 'Подробнее на вики-странице<br><a href="https://github.com/metahashorg/MetaHash/wiki/JavaScript-iconhash">https://github.com/metahashorg/MetaHash/wiki/JavaScript-iconhash</a>',
      'promo-content-description-5-1' : 'Репозиторий содержит код данного сайта',
      'promo-content-description-5-2' : 'Вики-страницы основных репозиториев<br><a href="https://github.com/metahashorg/MetaHash/wiki">https://github.com/metahashorg/MetaHash/wiki</a>',
      'promo-content-description-5-3' : 'Репозиторий, содержащий YellowPaper сети MetaHash',
      'promo-content-description-6-1' : 'Репозиторий содержит примеры решения ряда задач на языке С++<br>с использованием библиотеки v8',
      'promo-content-description-6-2' : 'Репозиторий используется для сохранения результата компиляции<br>и выполнения контрактов на v8-сервере. Язык JavaScript',
      'promo-content-description-7-1' : 'Язык HTML',
      'promo-content-description-7-2' : 'Язык PHP',
      'promo-content-description-7-3' : 'Язык Python. Репозиторий пока пуст',

      'promo-content-heading-1' : 'Основные',
      'promo-content-heading-2' : 'Сервисы<br/>MetaHash',
      'promo-content-heading-3' : 'Скрипты и приложения, позволяющие<br/>сгенерировать адрес и провести<br/>транзакцию в сети Metahash',
      'promo-content-heading-4' : 'Библиотеки по генерации уникальных<br/>идентификационных иконок<br/>для любого Metahash-адреса',
      'promo-content-heading-5' : 'О сети<br/>Metahash',
      'promo-content-heading-6' : 'Примеры использования<br/>библиотеки v8',
      'promo-content-heading-7' : 'Другие',

      'promo-01' : 'быстрая',
      'promo-02' : 'время транзакции <b>до 3 секунд</b> скорость свыше 50.000 TPS',
      'promo-03' : 'безопасная',
      'promo-04' : '<b>5 алгоритмов консенсуса</b> для верификации',
      'promo-05' : 'децентрализованная',
      'promo-06' : 'каждый участник может <b>создавать узлы для транзакций</b> в сети #MetaHash',


      'descr-01' : 'на базе Blockchain 2.0',
      'descr-02' : '<span class="cripto-title -title-part01">крипто</span><span class="cripto-title -title-part02">валюта</span>',
      'descr-03' : 'and decentralized ecosystem',
      'descr-04' : 'на базе Blockchain 2.0',


      'promo-appint-01' : '<span class="part-name">для&nbsp;</span>хранения',
      'promo-appint-03' : 'любой информации в Blockchain с <b>крипто-защитой 4k</b> и <b>multi-signature</b>',
      'promo-appint-04' : '<a href="#private-round" class="btn -default">ICO Round A<i class="icon icon_link"></i></a>',
      'promo-appint-05' : 'транзакций<span class="part-name">&nbsp;</span>',
      'promo-appint-06' : 'со скоростью <b>до 3 секунд</b> внутри сети #MetaHash и за ее пределами',
      'promo-appint-07' : '<a href="docs/MetaHash_WhitePaper_RU.pdf" target="_blank" class="download-white-paper btn -download">Скачать White Paper<i class="icon icon_dowload"></i></a>',
      'promo-appint-08' : 'обмена<span class="part-name">&nbsp;любого актива</span>',
      'promo-appint-10' : '<b>всех цифровых активов</b> в кошельке #MetaGate, использования <b>токена ERC20</b> во всех обменных сервисах',
      'promo-appint-11' : '<a href="docs/MetaHash_OnePager_RU.pdf" target="_blank" class="download-one-pager btn -download">Скачать One-Pager<i class="icon icon_dowload"></i></a>',
      'promo-appint-12' : '<a href="#private-round" class="btn -default -mega" >ICO Round A</a>',
      'promo-appint-13' : '<a href="docs/MetaHash_WhitePaper_RU.pdf" target="_blank" class="download-white-paper btn -download">White Paper</a>',
      'promo-appint-14' : '<a href="docs/MetaHash_OnePager_RU.pdf" target="_blank" class="download-one-pager btn -download float-right">One-Pager</a>',
      'promo-appint-15' : 'Download #MetaGate client',

      'whatis-01' : 'Что такое #MetaHash',
      'whatis-02' : '#MetaHash — сеть нового поколения на основе технологии Blockchain 2.0 для обмена цифровыми активами и платформа для создания и управления децентрализованными приложениями и сервисами, работающими в реальном времени',
      'whatis-03' : '4 компонента: ',
      'whatis-04' : '#TraceChain',
      'whatis-05' : 'Самый быстрый и безопасный Blockchain',
      'whatis-06' : '<b>Более 5 миллиардов</b> транзакций в сутки, время подтверждения каждой транзакции <b>до 3 секунд</b>',
      'whatis-07' : 'Подробнее о #TraceChain',
      'whatis-08' : '#MetaApps',
      'whatis-09' : 'Новое поколение Smart Contracts',
      'whatis-10' : 'Децентрализованные приложения, которые работают <b<real-time</b> как веб-сервисы и пишутся <b>на любом языке программирования</b>, включая Solidity, PHP, C++ и другие',
      'whatis-11' : 'Подробнее о #MetaApps',
      'whatis-12' : '#MetaGate',
      'whatis-13' : 'Децентрализованный Internet',
      'whatis-14' : 'Каталог <b>децентрализованных приложений</b> и кошелек обмена, который не грузит ваш компьютер',
      'whatis-15' : 'Подробнее о #MetaGate',
      'whatis-16' : '#MetaHashCoin',
      'whatis-17' : 'средство обмена сети #MetaHash',
      'whatis-18' : '<b>#MetaHashCoin</b> используется для обеспечения надежности сети, обмена услугами и регуляции ее самофинансирования и развития',
      'whatis-19' : 'Подробнее о #MHC',


      'tracechain-01' : '#TraceChain',
      'tracechain-02' : 'Быстрый и безопасный Blockchain 2.0',
      'tracechain-03' : 'свыше',
      'tracechain-04' : '100.000',
      'tracechain-05' : 'транзакций в секунду на каждом узле',
      'tracechain-06' : '<a href="docs/MetaHash_WhitePaper_RU.pdf" target="_blank" class="download-white-paper btn -download lang" >Скачать White Paper<i class="icon icon_dowload"></i></a>',
      'tracechain-07' : 'подтверждение транзакции',
      'tracechain-08' : 'транзакций в сутки',
      'tracechain-09' : 'ступеней консенсуса для верификации',
      'tracechain-10' : 'якоря блоков #MetaHash <span class="blue">в сетях Bitcoin и Ethereum</span>',
      'tracechain-11' : '<img class="tracechain-svg -ru" src="img/graphical/tracechaine-ru.svg" alt="">',


      'speed-work-01' : 'Беспрецедентная скорость работы и децентрализованность сети #TraceChain делают #MetaHash флагманом Blockchain',
      'speed-work-02' : 'Проведение любых объeмов транзакций в сети <b>#MetaHash</b>',
      'speed-work-03' : 'Стоимость транзакции ниже, чем в любом классическом Blockchain',
      'speed-work-04' : 'Адекватная стоимость хранения информации в <b>#TraceChain</b> для децентрализованных проектов',
      'speed-work-05' : 'Любой актив может быть токенизирован в <b>#MetaHashCoin</b> и свободно обращаться в сетях #MetaHash, Ethereum и др.',


      'speeds-01' : 'Как мы достигли таких скоростей?',
      'speeds-02' : 'Транзакции сходятся от внешнего радиуса к ядру сети по оптимальному пути.',
      'speeds-03' : 'Каждое звено подтверждает транзакцию на пути к ядру сети.',
      'speeds-04' : 'Ядро сети из самых быстрых узлов синхронизирует полученные транзакции между собой.',
      'speeds-05' : 'Ядро возвращает балансы кошельков в сеть, которая верифицирует правильность расчетов.',
      'speeds-06' : 'Бэкап данных уходит в классический Blockchain, верифицируя целостность сети.',
      'speeds-07' : 'Якоря (hash от самой длинной цепочки блоков) сохраняются в сетях Bitcoin, Ethereum и др.',
      'speeds-08' : 'Повредить или изменить информацию, хранящуюся в #MetaHash, невозможно. Для этого необходимо провести успешную атаку как на сеть #MetaHash, так и на сети Bitcoin, Ethereum и другие.',
      'speeds-09' : 'Подробная техническая информация доступна в White Paper',
      'speeds-10' : '<a href="docs/MetaHash_WhitePaper_RU.pdf" target="_blank" class="download-white-paper btn -download">Скачать White Paper<i class="icon icon_dowload"></i></a>',


      'metaapps-01' : '#MetaApps',
      'metaapps-02' : 'Облачный сервис для smart-приложений, работающих в режиме real-time',
      'metaapps-03' : '#MetaApps — это эволюционная замена Smart Contracts, которая  позволяет децентрализовать любой сервис. Полноценные программы, которые могут существовать вечно и не принадлежать никому. Они работают именно так, как заложено в их коде, и неподвластны влиянию людей.',
      'metaapps-04' : 'Преимущества #MetaApps',
      'metaapps-05' : 'Работают в real-time',
      'metaapps-06' : 'Так же быстро, как обычные веб-сервисы и программы',
      'metaapps-07' : 'Любой дизайн GUI',
      'metaapps-08' : 'Внешне могут выглядеть как абсолютно обычные программы или сайты',
      'metaapps-09' : 'Защита от вмешательств',
      'metaapps-10' : 'Никто не может изменить работу приложения в обход правил обновления',
      'metaapps-11' : 'Образ программы и операционной системы загружается в сеть и автоматически запускается на множестве машин в сети.',
      'metaapps-12' : 'Создаются на любом языке программирования, включая C++, PHP, Solidity и прочие.',
      'metaapps-13' : 'Полностью поддерживают функционал Smart Contracts и могут работать с любым Blockchain и просто данными из интернета.',


      'metagate-01' : '#MetaGate',
      'metagate-02' : 'Врата в децентрализованный интернет',
      'metagate-03' : '#MetaGate — программа с открытым исходным кодом, поэтому все разработчики могут встраивать части ее кода в свои приложения и браузеры.',
      'metagate-04' : 'Мультивалютный криптокошелек',
      'metagate-05' : 'Кошелек может работать в «light режиме», не скачивая себе Blockchain целиком.  Данные приходят из разных источников децентрализованной сети и проверяются пользователем. Приватные ключи от всех используемых Blockchain будут храниться только у пользователя.',
      'metagate-06' : 'Каталог приложений',
      'metagate-07' : 'Каталог децентрализованных приложений и браузер для работы с ними. Любое децентрализованное приложение, построенное на #MetaHash, может быть доступно не только по стандартному интернет домену, но и через #MetaGate или выделено в отдельную программу.',
      'metagate-08' : '<a href="docs/MetaHash_WhitePaper_RU.pdf" target="_blank" class="download-white-paper btn -download">Скачать White Paper<i class="icon icon_dowload"></i></a>',
	  'metagate-download-button' : 'Скачать #Metahash',

      'metahashcoin-01' : '#MetaHashCoin (#MHC)',
      'metahashcoin-02' : 'Финансовая модель сети #MetaHash',
      'metahashcoin-03' : '#MetaHash — самофинансируемая система с саморазвитием, заложенным в ее генетический код.',
      'metahashcoin-04' : '#MetaHashCoin используется для оплаты:',
      'metahashcoin-05' : 'Транзакций',
      'metahashcoin-06' : 'Мгновенные и надежные транзакции любых активов по адекватной фиксированной цене.',
      'metahashcoin-07' : 'Хранения данных',
      'metahashcoin-08' : 'Для приложений, которым нужно хранить данные, но не хватает скорости и объема данных в обычных Blockchain-системах.',
      'metahashcoin-09' : 'Работы приложений',
      'metahashcoin-10' : 'Любое децентрализованное приложение или Smart Contract требует ресурсов для размещения, включая саму сеть <b>#MetaHash</b>.',
      'metahashcoin-11' : 'Других сервисов',
      'metahashcoin-12' : 'Оплата публичных адресов, листинга в <b>#MetaApps</b>, рекламы в <b>#MetaGate</b> и других.',
      'metahashcoin-13' : '<a href="#private-round" class="btn -default btn-mobile">Купить #MHC<i class="icon icon_link"></i></a>',


      'minig-01' : 'Ресурсы для майнинга (forging) #MHC',
      'minig-02' : 'Серверы',
      'minig-03' : 'Используются для работы сети транзакций, а свободные ресурсы — для работы децентрализованных приложений.',
      'minig-04' : 'Кошельки #MetaGate',
      'minig-05' : 'В режиме Full nodes используются как хранилище данных и Torrent nodes.',
      'minig-06' : '#MetaHashCoins',
      'minig-07' : 'Укрепляют силу консенсуса по гибридной модели голосования компонентов PoW + PoS.',
      'minig-08' : '#MHC, полученные от продажи услуг, используются для:',
      'minig-09' : 'обучения разработчиков, строящих свои проекты на <b>#MetaHash</b>',
      'minig-10' : 'улучшения качества проекта',
      'minig-11' : 'рекламы для увеличения популярности #MetaHash',
      'minig-12' : 'оплаты владельцам <b>#MetaHashCoins</b> за поддержку консенсуса',
      'minig-13' : 'оплаты владельцам серверов и компьютеров',


      'compare-01' : 'Преимущества #MetaHash',
      'compare-02' : 'Мы не нашли ни одного проекта, который сейчас работает над созданием полностью децентрализованной и синхронизированной цепи, способной быстро обрабатывать необходимый для мира объем данных, поэтому сделали проект #MetaHash.',
      'compare-03' : 'Сравнительная таблица основных Blockchain-систем',
      'compare-04' : 'Подтвер&shy;ждение транзакции',
      'compare-05' : 'Транзакций в секунду (TPS)',
      'compare-06' : 'Уровень децентра&shy;лизации',
      'compare-07' : 'Bitcoin',
      'compare-08' : '10 минут',
      'compare-09' : 'до 12',
      'compare-10' : 'высокий',
      'compare-11' : 'Ethereum',
      'compare-12' : '15 секунд',
      'compare-13' : 'до 30',
      'compare-14' : 'высокий',
      'compare-15' : 'Plasma',
      'compare-16' : '15 секунд',
      'compare-17' : 'до 30',
      'compare-18' : 'высокий',
      'compare-19' : 'EOS',
      'compare-20' : '5 секунд',
      'compare-21' : 'от 1.000 до миллионов',
      'compare-22' : 'мини&shy;мальный',
      'compare-23' : '#MetaHash',
      'compare-24' : 'до 3 секунд',
      'compare-25' : 'от 50.000 до миллионов',
      'compare-26' : 'высокий',
      'compare-27' : '<a href="docs/MetaHash_WhitePaper_RU.pdf" target="_blank" class="download-white-paper btn -download">Скачать White Paper<i class="icon icon_dowload"></i></a>',


      'timemap-01' : 'Roadmap',
      'timemap-02' : 'В основу технологической части проекта легли наработки компании AdSniper в сфере рекламных технологий, созданные в 2012-2017 годах.',
      'timemap-03' : "Когда мы получили массу запросов от разных компаний на применение Blockchain-технологий, то пришли к пониманию, что существующие решения не удовлетворяют требованиям к подобного типа системам. Поэтому в 2016 году мы начали разработку собственного протокола #TraceChain.",
      'timemap-04' : 'В 2017 году мы создали Alpha и Beta-версии протокола #TraceChain и объединили усилия с сильнейшими компаниями и людьми в областях международного маркетинга и Business development.',
      'timemap-05' : '2012-2016',
      'timemap-06' : 'Сетевая библиотека приема сигналов, работающая на C++ и способная принимать и отдавать одновременно более 100.000 запросов в секунду на один недорогой стандартный сервер',
      'timemap-07' : 'Сетевая библиотека синхронизации сигналов внутри кластера, управляющая гигантскими потоками данных между машинами кластера.',
      'timemap-08' : 'Система машинного обучения, принимающая решения за 40 миллисекунд об ответе на сигнал с учетом мультифакторных взаимосвязей.',
      'timemap-09' : 'Собственный аналог Hadoop подобных систем на C++ для распределенной обработки больших данных.',
      'timemap-11' : '2017',
      'timemap-12' : 'Создание протокола #TraceChain (Alpha version)',
      'timemap-13' : 'Создание протокола #TraceChain (Beta version) ',
      'timemap-14' : 'Присоединение команды <b>AdNow</b> ',
      'timemap-15' : 'Присоединение команды <b>Agranovsky IT</b> ',
      'timemap-16' : 'Формирование команды <b>Business development</b>',
      'timemap-17' : 'Формирование <b>Operational Team</b>',
      'timemap-18' : '2018',


      'timemap-19' : 'Официальный запуск <b>сайта #MetaHash</b>',
      'timemap-20' : 'Старт строительства офиса Operational Team',
      'timemap-21' : 'Присоединение экспертов и консультантов (Advisors)',
      'timemap-22' : 'Разработка #MetaGate (v.1.0). Мультивалютный кошелек с возможностью перевода #MetaHashCoins между кошельками.',
      'timemap-23' : 'Разработка #TraceChain (v.1.0). Приватный, распределенный между серверами TestNet',
      'timemap-23a': 'Разработка #TraceChain (v.2.0). API для скачивания данных',
      'timemap-24' : 'Разработка #MetaICO (v.1.0). Интерфейс проведения ICO на платформе #MetaICO с приемом средств из разных Blockchains (bitcoin & ethereum) и начисление токенов в сети #MetaHash и multichain-переводами, включая ERC20 в сети Ethereum',
      'timemap-25' : 'Разработка #MetaChains (v.1.0). Конвертация #MetaHashCoins в ERC20 и вывод их в сеть Ethereum, чтобы обладатель #MHC мог самостоятельно выбирать, в какой из сетей их использовать и автоматическая конвертация токенов ERC20 в #MetaHashCoins',
      'timemap-26' : 'Разработка #MetaApps (v.1.0). Платформа приложений',
      'timemap-27' : 'API для скачивания данных TestNet',

      'timemap-28' : '<b>Открытие офиса Operational Team</b>',
      'timemap-29' : '<b>Запланированный старт ICO Round A</b>',
      'timemap-30' : 'Разработка #MetaChains (v.2.0). API с балансами и историей переводов по кошелькам разных Blockchains. Децентрализованное приложение с информацией о транзакциях в сетях Ethereum и Bitcoin для работы с Blockchain Interoperability в #MetaApps',
      'timemap-31' : 'Релиз <b>#MetaGate (v.2.0)</b>. Мессенджер с публичными нотификациями и зашифрованными сообщениями между кошельками',
      'timemap-32' : 'Релиз <b>#TraceChain (v.3.0)</b>. Пиринговые узлы, подключаемые к TestNet для установки на любые сервера',
      'timemap-33' : '#TraceChain (v.4.0). Cервис тестирования производительности ядра сети на 1.000.000+ транзакций в секунду',
      'timemap-34' : '#MetaICO (v.2.0). Интерфейс создания токенов внутри сети #MetaHash',
      'timemap-35' : 'Релиз #MetaICO (v.3.0). Платформа для проведения ICO проектов на #MetaHash',
      'timemap-36' : '#TraceChain (v.4.0). Функции голосования в сети #MetaHash',
      'timemap-37' : '#TraceChain (v.5.0). AI, управляющая маршрутизацией сигналов между узлами для обеспечения максимальной скорости создания блоков и пропускной способности сети #MetaHash, а также 100 тестовых узлов для тестирования взаимодействия между узлами сети в разных географических локациях',


      'timemap-38' : '#MetaICO (v.4.0). Релиз приложения #MetaToken и токенизация эфира, ERC20 токенов, биткоина в токенах #MetaHash для их использования в сети #MetaHash',
      'timemap-39' : '#TraceChain (v.6.0). #MetaStorage для работы децентрализованных приложений',
      'timemap-40' : '#MetaApps (v.2.0). Платформа для приема к размещению сторонних децентрализованных приложений #MetaApps',
      'timemap-41' : '#MetaGate (v.3.0). Финальный релиз, кошелек #MetaGate для Mac/Win/Unix/Android/iOS с каталогом #MetaApps',


      'timemap-42' : '<b>#TraceChain (v.7.0). Начало форджинга</b>',
	  'timemap-43' : 'ICO Round B или возможное заключение договора о листинге с криптобиржей, созданной и регулируемой в соотвествии с требованиями законодательства',
      'timemap-44' : 'Оглашение дальнейшего плана работ',


      'timemap-45' : 'Обширные тесты безопасности',
      'timemap-46' : 'По завершении тестов релиз исходного кода',
      'timemap-47' : '<b>Старт полностью децентрализованной системы</b>',
      
      'timemap-100' : 'Показать больше',
	  'timemap-101' : 'Скрыть события',
	  'timemap-102' : 'Другие события',


      'teambanner-01' : 'Команда',
      'teambanner-02' : '#MetaHash — проект с открытой структурой команды, в которую принимаются люди и компании.',
      'teambanner-03' : 'Если вы считаете, что можете помочь проекту и хотите присоединиться к команде, <a class="team-write" href="mailto:hello@metahash.org">напишите нам</a>.',
      'teambanner-04' : '<a href="#private-round" class="btn -default">ICO Round A<i class="icon icon_link"></i></a>',
      'teambanner-05' : 'Если вы считаете, что можете помочь проекту и хотите присоединиться к команде, <a href="mailto:hello@metahash.org">напишите нам</a>',
      'teambanner-06' : 'ICO Round A',
      'teambanner-07' : '<img src="img/graphical/People_RU@3x.svg" alt="">',


      'team-hidden-01' : 'Имена остальных сотрудников компании не указаны в интересах проекта',

      'team-dev-01' : 'Глеб Никитин',
      'team-dev-02' : 'Олег Романенко',
      'team-dev-03' : 'CSA, Архитектор real-time сервисов AdSniper и в прошлом системный аналитик системы онлайн-банкинга АльфаБанк. Создатель высоконагруженной сетевой библиотеки, способной выдерживать более миллиона запросов в секунду.',
      'team-dev-04' : 'Михаил Заруцкий',
      'team-dev-05' : 'CTO, Руководитель команд по машинному обучению, обработке больших данных и real-time сервисов. Создатель системы машинного обучения Razoom, способной в режиме реального времени обрабатывать миллионы запросов, используя комбинированные расчеты нейросетей и других методов машинного обучения.',
      'team-dev-06' : 'Сергей Райлян',
      'team-dev-07' : 'CIO, планирует и организовывает стыковку десятков различных систем и интерфейсов, составляющих технологический стек AdSniper',
      'team-dev-08' : '29 сотрудников AdSniper <i class="icon icon_link"></i>',
      'team-dev-09' : 'Последние 10 лет создает высоконагруженные рекламные сети. В багаже компании собственный обработчик Big data , обслуживающий петабайты данных, собственные быстрые NoSQL и SQL базы данных, системы искусственного интеллекта и C++ библиотеки для высоконагруженных сетевых сервисов, обрабатывающие запросы на рекламу от всего интернета.',
      'team-key-staff' : 'Ключевые сотрудники',


      'team-mark-01' : 'Владимир Башкин',
      'team-mark-02' : 'Рекламная сеть с более чем миллиардом показов в день. Одна из сильнейших команд в мире по покупке рекламы во всех рекламных сетях, обладающая своим штатом переводчиков и специалистов по рекламе на локальных рынках.',
      'team-mark-03' : '89 сотрудников AdNow <i class="icon icon_link"></i>',
      'team-mark-04' : 'Артем Кравченко',
      'team-mark-05' : 'Event Director - PR-директор. Организатор международных digital-конференций AdDays Digital Events. Event-директор в партнёрской сети Bitcomo',
      'team-mark-06' : 'Дарья Баранова',
      'team-mark-07' : 'Affiliate Director - Publisher Sales Director в AdNow. Руководит московским офисом компании',
      'team-mark-08' : 'Pham Thành Trung',
      'team-mark-09' : 'Head of Advertiser’s Department - Руководитель Sales-департамента в Юго-Восточной Азии в AdNow',


      'team-fin-01' : 'Антон Аграновский',
      'team-fin-02' : 'Agranovsky IT - инвестиционная компания, финансирует IT-стартапы и сопровождает рост компаний от идеи до IPO. Основатель Антон Аграновский — инвестор, эксперт, лидер мнений в области создания и развития IT-компаний. Член совета директоров Plastic Media, SMX Communications. В 2008-2017 годах — основатель, президент Destiny Development, одной из первых игровых компаний на российском интернет-рынке, известной как своими собственными разработками, так и локализациями. <br />&nbsp;<br /><a href="https://goo.gl/fJVjfK" class="link -link-small" target="_blank">Forbes magazine contributor</a>',
      'team-fin-03' : '11 сотрудников Agranovsky IT <i class="icon icon_link"></i>',
      'team-fin-04' : 'Геннадий Якунин',
      'team-fin-05' : 'CEO - Постановка бухгалтерского учета в холдинговых компаниях. Опыт управленческой работы в IT и игровых секторах более 10 лет',
      'team-fin-06' : 'Светлана Руденок',
      'team-fin-07' : 'Deputy CEO - Опыт в оценке рисков, аудирование новых и действующих проектов в игровых и IT секторах более 10 лет',
      'team-fin-08' : 'Андрей Коростелев',
      'team-fin-09' : 'CFO - Опыт финансового сопровождения в игровых и IT проектах более 10 лет. Активный участник социальных и благотворительных проектов',


      'team-oper-01' : 'Дмитрий Ушаков',
      'team-oper-02' : '<span style="color:#ffffff;">COO, General PM</span><br/>Более 11 лет опыта операционного управления многопользовательскими проектами в Game Insight и других IT-стартапах',
      'team-oper-03' : 'Михаил Иванов',
      'team-oper-04' : '<span style="color:#ffffff;">Art Director</span><br/>Более 16 лет опыта в графическом и продуктовом дизайне. Работал над проектами для компаний РОСНАНО, Sony, Canon, Nikon и других',
      'team-oper-05' : 'Джибо Фан',
      'team-oper-06' : '<span style="color:#ffffff;">Asia BD Partner</span><br/>Основатель игровой платформы GAME.RU, а также издателя INFIPLAY',
      'team-oper-07' : 'Александр Жигаренко',
      'team-oper-08' : '<span style="color:#ffffff;">CBDO Russia, CIS</span><br/>Более 10 лет опыта издания, управления и развития в компании Destiny.Games и индустрии компьютерных игр',
      'team-oper-09' : 'Евгения Сигачева',
      'team-oper-10' : '<span style="color:#ffffff;">Public Affairs Partner</span><br/>Более 18 лет работы в области IT и инноваций, международного маркетинга и PR. Евгения входит в международную команду всемирно известного робота Софии, является CEO&Founder проекта IHEART Platform.',
      'team-oper-11' : 'Андрей Акимов',
      'team-oper-12' : '<span style="color:#ffffff;">Chief Communication Officer</span><br/>Более 15 лет в маркетинговых коммуникациях индустрии игр, развлечений и IT. Руководил отделами PR и маркетинга компаний My.com, Mail.Ru Group, Game Insight и других',
      'team-oper-00' : '17 сотрудников Operational Team <i class="icon icon_link"></i>',


      'legal-title' : 'Legal Department',
    //  'legal-02' : 'Анастасия Пичугина',
    //   'legal-03' : 'ANP Law Managing Partner <a href="https://www.facebook.com/people/Anastasia-Pichugina/1520204010" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
    //  'legal-04' : 'Екатерина Мызникова',
    //  'legal-05' : 'Senior Lawyer - Глава практики Blockchain-проектов. В настоящее время успешно сопровождает несколько ICO проектов, является участником и спикером профильных конференций, вебинаров.',
    //  'legal-06' : 'Максим Мехряков',
    //  'legal-07' : 'Senior Lawyer - Руководитель штата юристов, специализирующихся на правовом сопровождении коммерческих и инвестиционных сделок.',
    //  'legal-08' : 'Анна Шевченко',
    //  'legal-09' : 'Lawyer - Юридическая поддержка для российских и иностранных компаний в сфере интеллектуальной собственности полного спектра, включая регистрацию товарных знаков и патентов.',
    //  'legal-10' : 'Мы прекрасно разбираемся как в российском, так и в международном законодательстве. Наши юристы получали образование в лучших российских и иностранных учебных заведениях. Управлявляющий партнер Анастасия обладает уникальным опытом и знаниями в российском и иностранном праве, является доверенным юридическим представителем нескольких иностранных компаний из IT, FMCG рынка. Анастасия успешно представляла иностранные компании в российских судах.',
    //  'legal-11' : '<a href="docs/MetaHash_LegalOpinion_RU.pdf" target="_blank">Скачать юридический анализ #MetaHashCoin<i class="icon icon_link"></i></a>',
	  
	  'legal-more' : 'Подробнее',
	  'legal-less' : 'Свернуть',
	  'legal-17' : 'Андрей Миронов <a href="http://www.linkedin.com/in/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a> <a href="https://www.facebook.com/" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
	  'legal-18' : 'Chief of Legal Department',
	  'legal-19' : 'Выпускник МГИМО 2000, межународно-правовой факультет. Юридическая практика в сфере новых технологий, медиа и интеллектуальной собственности более 15 лет.',
	  'legal-19a' : 'Работал в Студии Артемия Лебедева, Одноклассниках, русском офисе Myspace, на каналах MTV, Discovery, Amedia и онлайн-кинотеатре Amediateka. Помогал развитию издательству ЭКСМО, телеканалам Fox. Эксперт Российской ассоциации электронных коммуникаций (РАЭК).<br>Второе образование: психолог-консультант',
	  'legal-20' : 'Мария Аграновская',
	  'legal-21' : 'Chief Legal Coordinator',
	  'legal-22' : 'Адвокат, юрист-международник со стажем более 20 лет. Начала работать с регулированием криптовалют в 2010 году.',
	  'legal-22a' : 'МГИМО МИД РФ (Международное право), училась в Германии и Голландии.  8,5 лет вела мультисемейный офис. Работала над различными вопросами - трансграничные сделки, инвестиции, управление активами, структурирование сделок и холдингов во многих юрисдикциях, слияния и поглощения, международное налогообложение и другое. Области: финтех, финансы, телеком, банковская деятельность, энергетика, фармацевтика, недвижимость и другие. 1007: создание Адвокатской коллегии ГРАД (управляющий партнер, 30+ российских и иностранных юристов). Существенную часть времени занимается проектами, связанными с технологией блокчейн, проведением ИСО и аналогичными вопросами, регулирование трейдинга, финансовой деятельности и фондов. Языки: английский, немецкий, французский, итальянский, испанский.',
	  'legal-23' : 'Катя Фишер',
	  'legal-24' : 'Partner, Principal at The Law Office of Katya Yoffe PLLC',
	  'legal-25' : 'Катя Йоффе (Фишер) - адвокат, специализирующийся на общем корпоративном праве, международных сделках и бизнес-иммиграции.',
	  'legal-25a' : 'Катя представляет различные известные компании и стартапы, занимающиеся бизнесом в Соединенных Штатах, а также знаменитостей и частных лиц. Катя была выбрана Супер Юристами в качестве "восходящей звезды" в 2014, 2015, 2016, 2017 и 2018 годах.<br>Катя является выпускником Нью-Йоркского университета, школы права им. Бенджамина Н. Кардозо и бывшим научным сотрудником Howard M. Squadron по международному праву и политике в области средств массовой информации в Оксфордском университете и центре глобальных коммуникационных исследований Пенсильванского университета. Она допущена к практике в Нью-Йорке и Налоговом Суде Соединенных Штатов.',
	  'legal-26' : 'Анастасия Пичугина',
	  'legal-27' : 'ANP Law Managing Partner ',
	  'legal-28' : 'Глава практики Blockchain-проектов. В настоящее время успешно сопровождает несколько ICO проектов, является участником и спикером профильных конференций, вебинаров.',
	  'legal-29' : 'Екатерина Мызникова',
	  'legal-30' : 'Senior Lawyer',
	  'legal-31' : 'Head of the practice of Blockchain projects. Successfully accompanies several ICO projects, a participant and speaker of profile conferences, webinars.',
	  'legal-32' : 'International Legal Support',
	  'legal-33' : 'Даниэль Г. Виола',
	  'legal-34' : 'Partner, Head of Regulatory and Compliance Group at Sadis & Goldberg LLP',
	  'legal-35' : 'Oliver Ciric',
	  'legal-36' : 'Partner at TA Advisory',
	  'legal-37' : 'Даниэль Г. Виола является партнером <span class="ilegal-white">ТОО «Садис и Голдберг»</span> и руководителем их Группы по регулированию и соответствию требований.  Он структурирует и организует брокеров, инвестиционных консультантов',
	  'legal-37a' : ', фонды и регулярно консультирует специалистов по инвестициям в нормативных и корпоративных вопросах.  Г-н Виола активно работает в BlockChain и виртуальных валютных вертикалях (Virtual Currency verticals) с 2014 года. Он также является Основателем вебинаров Crypto Asset, конференций Blockchain Shift и выступает в качестве члена консультативного совета для нескольких ICO.  Г-н Виола также выполнял функции старшего экзаменатора по вопросам соблюдения требований в <span class="ilegal-white">Северо-восточном региональном отделении SEC</span>, где он работал с 1992 по 1996 год. За время своего пребывания в SEC г-н Виола работал над несколькими проектами по проверке соответствия и обеспечительными действиями, связанными с проверками зарегистрированных  инвестиционных консультантов, обеспечивающих соблюдение федеральных законов и законов о государственных ценных бумагах.  Опыт г-на Виолы включает финансовую отчетность, эффективную рекламу и обзоры документов раскрытия информации, а также анализ инвестиционных консультантов и проблем хедж-фондов, возникающих в соответствии с законами ERISA и «Blue Sky».  В конце 2006 года г-н Виола основал свою собственную юридическую фирму и в конечном итоге объединил ее в юридическую практику Садиса и Голдберга.',
	  'legal-38' : 'Опыт работы в области международной юриспруденции более 20-ти лет. Окончил Бостонский юридический университет в 2006 году по специальности банковское и финансовое право, а также Женевский университет права в 1998  году, специальность “Лицензия и право”.',
	  'legal-38a' : 'Предыдущий опыт работы: Nationale Suisse Assurances, Matile Brosset Stickel Stickel-Cicurel & Gianninazzi, Poncet Turrettini Amaudruz Neyroud & Partners, <span class="ilegal-white">Akin Gump Strauss Hauer & Feld LLP</span> (previously Hogan & Hartson LLP). С июня 2017 является Партнером в <span class="ilegal-white">TA Advisory</span>. Оказывает юридическую поддержку для блокчейн проектов, а также консультирует в вопросах сотрудничества <span class="ilegal-white">с FINMA.</span>.<br> Языки: Немецкий, Английский, Французский, Португальский, Русский, Сербский.',
	  'legal-39' : '<span class="ilegal-white-02">KPMG AG, Switzerland,</span> served as advisor to #MetaHash in the evaluation of the Swiss regulatory, tax and legal aspects in respect of the Initial Coin offering (ICO)',
	  'legal-40' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">Download White Paper<i class="icon icon_dowload"></i></a>',
	  'legal-41' : 'Martin Hess',
      'legal-42' : 'Partner at Wenger & Vieli AG',
	  'legal-43' : 'Martin Hess specializes in financial services and capital markets law, FinTech and the digitization of financial services. He is recognized by the Swiss Stock Exchange as an issuer representative. Martin Hess advises Swiss and foreign clients and represents them vis-à-vis supervisory authorities and in court.',
	  'legal-43a' : 'He is involved in the legal design of trading venues for digital assets, payment systems and securities settlement systems as well as central counterparties. He advises and represents clients on Initial Coin Offerings / Token Generating Events. Since 2001 Partner at Wenger & Vieli Ltd',
  

      'legal-14' : 'Мария Аграновская',
      'legal-15' : 'Chief Legal Coordinator <a href="https://www.facebook.com/magranovskaya" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a> <a href="https://www.linkedin.com/in/maria-agranovskaya-151334/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
      'legal-16' : '<span>Адвокат, юрист-международник со стажем более 20 лет. Начала работать с регулированием криптовалют в 2010 году.МГИМО МИД РФ (Международное право), училась в Германии и Голландии. 8,5 лет вела мультисемейный офис. Работала над различными вопросами - трансграничные сделки, инвестиции, управление активами, структурирование сделок и холдингов во многих юрисдикциях, слияния и поглощения, международное налогообложение и другое.</span><span>Области: финтех, финансы, телеком, банковская деятельность, энергетика, фармацевтика, недвижимость и другие.</span><span>2007: создание Адвокатской коллегии ГРАД (управляющий партнер, 30+ российских и иностранных юристов).</span><span>Существенную часть времени занимается проектами, связанными с технологией блокчейн, проведением ИСО и аналогичными вопросами, регулирование трейдинга, финансовой деятельности и фондов.</span><span>Языки: английский, немецкий, французский, итальянский, испанский.</span>',



      'private-01' : 'Private Round',
      'private-form' : '<input type="hidden" name="form_subject" value="Заявка на участие в Private Round">',
      'private-03' : 'дней',
      'private-04' : 'До окончания раунда осталось',
      'private-05' : 'Private Round',
      'private-06' : 'Цель Private Round — верификация идеи до публичного запуска',
      'private-07' : 'Мы хотим видеть среди участников Private Round экспертов, которые  готовы принять участие в обсуждении проекта до его публичного запуска и, возможно, присоединиться к команде #MetaHash.',
      'private-08' : '#MetaHash в обязательном порядке информирует всех участников Private Round об их правах и условиях участия.',
      'private-09' : 'Участники Private Round смогут принять решение: остаться в проекте после ICO .',
      'private-10' : 'Отправьте заявку на участие в Private Round',
      'private-11' : 'Нам важна не сумма, а ваша экспертиза. Мы хотим, чтобы в Private Round приняли участие эксперты из разных областей.',
      'private-12' : 'Дополнительные способы связи, ваша экспертиза в криптовалютах. Готовы ли вы принимать участие в обсуждении проекта?',
      'private-13' : 'Отправить заявку <i class="icon icon_link"></i>',
      'private-14' : 'Пользовательское соглашение',
      'private-15' : 'политика конфиденциальности',
      'private-16' : 'Условия Private Round:',
      'private-17' : 'Хотите принять участие в Private Round или присоединиться к команде #MetaHash?',
      'private-18' : 'Участие в Private Round публичное — имя или компания участника будут опубликованы',
      'private-19' : 'Объем Private Round - <b>1.840 ETH</b>',
      'private-20' : 'Цена #MHC - <b>0,001 ETH</b> ',
      'private-21' : 'Объема Private Round не хватит на удовлетворение заявок всех желающих',
      'private-22' : 'Оставлять заявки на участие можно до окончания Private Round',
      'private-23' : 'В конце Private Round текущая команда #MetaHash примет решение о квотах для каждого из желающих принять участие',
      'private-24' : 'После завершения Private Round и распределения задач между текущими и новыми участниками команды начнется ICO Round A',
      'private-25' : 'Заявка на участие в Private Round',
      'private-26' : 'Введите Ваше имя',
      'private-27' : 'Введите Ваш Email',
      'private-28' : 'Желаемый объем участия (ETH)',
      'private-29' : 'Дополнительная информация о Вас',


      'timer-day-1' : 'день',
      'timer-day-2' : 'дня',
      'timer-day-3' : 'дней',
      'timer-hour-1' : 'час',
      'timer-hour-2' : 'часа',
      'timer-hour-3' : 'часов',
      'timer-minute-1' : 'минута',
      'timer-minute-2' : 'минуты',
      'timer-minute-3' : 'минут',
      'timer-second-1' : 'секунда',
      'timer-second-2' : 'секунды',
      'timer-second-3' : 'секунд',



	'form-sent-01' : 'Спасибо!',
	'form-sent-02' : 'Информация успешно отправлена.',


      'faq-01' : 'Вопросы и ответы',
      'faq-02-00' : 'Общие вопросы о проекте #MetaHash',
      'faq-02-01' : 'Какова юридическая структура организации и страна регистрации?',
      'faq-02-02' : 'В данный момент идет процедура регистрации в Швейцарии. Процесс требует согласования с госорганами швейцарских кантонов.',
      'faq-02-03' : 'Где можно увидеть MVP и Open Code продукта?',
      'faq-02-04' : 'На сегодня запущен централизованный #TraceChain и кошелек с открытым исходным кодом. Исходные коды #TraceChain будут выпущены после завершения публичного тестирования хакерами и получения патента, сеть станет полностью децентрализованной.',
      'faq-02-05' : 'Какова основная роль проекта, и для чего нужен #MetaHashCoin?',
      'faq-02-06' : '#MetaHashCoin используется для оплаты: транзакций, хранения данных, работы приложений, публичных адресов, листинга в #MetaApps, рекламы в #MetaGate и других',
      'faq-02-07' : 'Какая скорость транзакций вашего Blockchain? Open Code? Как вы добились этой скорости?',
      'faq-02-08' : 'Пожалуйста, ознакомьтесь с соответствующим разделом <a href="docs/MetaHash_WhitePaper_RU.pdf" class="download-white-paper link -link-small" target="_blank">White Paper</a>',
      'faq-02-09' : 'На каких условиях майнится данная криптовалюта? Есть ли какие-то специальные условия для майнеров?',
      'faq-02-10' : 'Подробную схему майнинга читайте в <a href="docs/MetaHash_WhitePaper_RU.pdf" class="download-white-paper link -link-small" target="_blank">White Paper</a>.',
      'faq-02-11' : 'Какая система работы данного Blockchain, POW или POS?',
      'faq-02-12' : 'Алгоритм консенсуса гибридный. #MetaHash - это multiPOS с учетом голосов отдельных узлов сети.',


      'faq-03-00' : 'Вопросы об условиях проведения ICO Round A / Round B и приобретению #MHC',
      'faq-03-01' : 'Какие способы оплаты вы принимаете?',
      'faq-03-02' : 'Мы принимаем только ETH (Ethereum). Остальные валюты сначала конвертируются в Ethereum.',
      'faq-03-03' : '',
      'faq-03-04' : '',
      'faq-03-05' : 'Могу ли я с Биржи перевести вам криптовалюту?',
      'faq-03-06' : 'Конечно. Но мы принимаем только ETH.',
      'faq-03-07' : '',
      'faq-03-08' : '',
      'faq-03-09' : 'Когда заканчиваются ICO Round A / Round B?',
      'faq-03-10' : 'ICO Round A идет до полной продажи всего раунда. ICO Round B стартует после выпуска готового продукта.',
      'faq-03-11' : 'Что ещё за условия кошелька #MHC',
      'faq-03-12' : '#MetaGate - продукт с открытым исходным кодом. Его использование финансируется рекламой и оплатами за отсутствие рекламы.',


      'faq-04-00' : 'Вопросы о #MHC и перспективы роста',
      'faq-04-01' : 'Каково различие Между #MetaHash и его конкурентами?',
      'faq-04-02' : 'Мы будем готовить ответ о каждом отдельном конкуренте. В целом конкуренты или централизованные, или медленные (ниже 1000 транзакций в секунду). А smart-приложений, работающих в real-time на данный момент никто не делает.',
      'faq-04-03' : '#MHC - это токен ERC20  и эмитирован посредством Smart Contract Ethereum?',
      'faq-04-04' : '#MetaHashCoin - самостоятельная монета в отдельном чейне. Но существуют зеркальные контракты в Ethereum и #MetaHash, позволяющие обменивать  #MetaHashCoin на токен ERC20 в Ethereum и обратно.',
      'faq-04-05' : 'Каков общий объем эмиссии #MHC?',
      'faq-04-06' : '92 000 000 #MHC будет выпущено в обращение в течение 10 лет. 46 000 000 #MHC будет выпущено в обращение в первый год.',
      'faq-04-07' : 'Где и когда можно будет обменять #MHC? На каких биржах будет выведена ваша монета?',
      'faq-04-08' : 'Появление #MetaHashCoin на конкретной бирже будет анонсировано по всем публичным каналам. До факта выхода информация конфиденциальна.',
      'faq-04-09' : 'Какова будет начальная цена #MetaHashCoin после окончания ICO и появления #MHC на рынке?',
      'faq-04-10' : 'Цена #MetaHashCoin определяется рынком. Основная ценность #MetaHashCoin в том, что он используется для процедуры форджинга и оплаты транзакций и хранения данных, а так же для работы приложений.',
      'faq-04-11' : 'Когда начнется/закончится продажа токенов?',
      'faq-04-12' : 'Мы планируем, что этап ICO Round A завершится до конца 2018 года, а ICO Round B начнется в конце 2018 - начале 2019',


      'faq-05-00' : 'Организационные вопросы приобретения #MHC',
      'faq-05-01' : 'Есть ли минимальный лимит на приобретение #MetaHash?',
      'faq-05-02' : 'Вы можете приобрести столько #MetaHashCoins, сколько вам нужно. У нас нет ограничений по минимальной сумме.',
      'faq-05-03' : 'Когда токены #MHC будут выданы?',
      'faq-05-04' : 'TestNet #MetaHashCoin или их замена в ERC20 выдаются и могут быть использованы сразу.',
      'faq-05-05' : 'Что будет с монетами, которые не продадутся в ходе всех раундов продаж?',
      'faq-05-06' : 'Все непроданные активы будут оставлены #MetaHash Company',
      'faq-05-07' : 'Я перевел 0.07 ETH на кошелек #MetaHash. Сколько токенов я получу?',
      'faq-05-08' : 'Воспользуйтесь нашим специальным калькулятором, чтобы получить расчет получаемых #MHC ',
      'faq-05-09' : 'Как купить #MHС токены не имея криптовалюты?',
      'faq-05-10' : 'В любом случае, необходимо обменять фиатные средства на цифровые активы ETH. Воспользуйтесь услугами криптовалютных бирж или платёжных систем.',


      'faq-06-00' : 'Прочие вопросы',
      'faq-06-01' : 'Я гражданин Китая, Кореи или США, это законно участвовать в ICO #MetaHash?',
      'faq-06-02' : 'В ICO #MetaHash могут принять участие граждане всех стран, кроме: США, Сингапур, Вьетнам, КНР,  а также стран с  эмбарго и санкциями США, такие как Иран, КНДР, Сирия, Судан, Куба. Подробнее в Условиях продажи Токенов.',
      'faq-06-03' : 'Что такое #TraceChain?',
      'faq-06-04' : '#TraceChain - это эволюционная альтернатива Blockchain-системам. Решение проблемы скорости строится на автоматическом самообучающемся алгоритме маршрутизации сигналов по сети. Начиная работу на скорости 50 000 транзакций в секунду (пропускная способность 100 мегабитного канала) она растет по мере добавления в сеть достаточного количества узлов с более высокой пропускной способностью, формируя ядро основной сети и стабилизируя надежность дополнительных дата-сетей, нужных для работы приложений.',
      'faq-06-05' : 'Ограничения HardCap / SoftCap?',
      'faq-06-06' : 'SoftCap достигнут за счет раунда основателей и Private Round. HardCap нет - его определяет рынок.',
      'faq-06-07' : 'Я внес XX BTC/ETH, когда они сконвертируются в #MHC?',
      'faq-06-08' : 'После того, как получены 6 подтверждений от сети Ethereum и подтверждения от узлов, на которых стоит #MetaChains. Если после перевода прошло 6 часов, а транзакция еще не обработана - не волнуйтесь, напишите нам и мы решим проблему. Факт вашего перевода - это транзакция в Blockchain. Если она есть - вы получите начисление.',
      'faq-06-09' : 'Где найти даты предварительной продажи, ICO и другие этапы?',
      'faq-06-10' : 'Официальные даты запуска этапов ICO Round A и ICO Round B пока не определены. Мы обьявим о проведении раундов по всем нашим публичным каналам. Подпишитесь на наши обновления, чтобы первым получать актуальные новости.',
      'faq-06-11' : 'Ваш проект - это Fork?',
      'faq-06-12' : '#MetaHash не является форком ни одной из сетей. Для #MetaHash разработан собственный протокол #TraceChain',


      'support-01' : 'Остались вопросы? Напишите нам!',
      'support-02' : 'Отправить вопрос',
      'support-03' : 'Вопрос от пользователя',
      'support-04' : 'Введите Ваше имя',
      'support-05' : 'Введите Ваш E-mail',
      'support-06' : 'Ваш вопрос',


      'prefooter-02' : '#MetaHashTeam',
      'prefooter-03' : '<a href="#private-round" class="btn -default">Купить #MHC<i class="icon icon_link"></i></a>',
      'prefooter-04' : '<a href="docs/MetaHash_WhitePaper_RU.pdf" target="_blank" class="download-white-paper btn -download">Скачать White Paper<i class="icon icon_dowload"></i></a>',
      'prefooter-05' : '<a href="docs/MetaHash_OnePager_RU.pdf" target="_blank" class="download-one-pager btn -download">Скачать One-Pager<i class="icon icon_dowload"></i></a>',
      'prefooter-06' : 'Принять участие в ICO Round A',
      'prefooter-07' : '<a href="docs/MetaHash_WhitePaper_RU.pdf" target="_blank" class="download-white-paper btn -download">White Paper</a>',
      'prefooter-08' : '<a href="docs/MetaHash_OnePager_RU.pdf" target="_blank" class="download-one-pager btn -download float-right">One-Pager</a>',


      'footer-01' : 'Что такое #MetaHash',
      'footer-02' : 'Купить #MetaHashCoin (#MHC)',
      'footer-03' : '<a href="https://static.metahash.org/docs/MetaHash_WhitePaper_RU.pdf" target="_blank" class="download-white-paper link -footer-link">White Paper</a>',
      'footer-04' : '<a href="https://static.metahash.org/docs/MetaHash_OnePager_RU.pdf" target="_blank" class="download-one-pager link -footer-link">One-Pager</a>',
      'footer-05' : 'Вопросы и ответы',
      'footer-06' : '<a href="https://static.metahash.org/docs/MetaHash_TermsOfUse_EN.pdf" target="_blank" class="link -footer-link">Пользовательское соглашение</a>',
      'footer-07' : '<a href="https://static.metahash.org/docs/MetaHash_PrivacyPolicy_RU.pdf" target="_blank" class="link -footer-link">Политика конфиденциальности</a>',
      'footer-08' : '<a href="https://static.metahash.org/docs/MetaHash_AntiSpam_EN.pdf" target="_blank" class="link -footer-link">Политика Anti-Spam</a>',
      'footer-09' : 'Advisor Agreement',
      'footer-10' : '<a href="https://static.metahash.org/docs/MetaHash_RiskDisclosureStatement_EN.pdf" target="_blank" class="link -footer-link">Risk Disclosure Agreement</a>',
      'footer-11' : 'Соцсети и мессенджеры',
      'footer-12' : 'Форумы',
      'footer-13' : 'Обратная связь <a href="mailto:hello@metahash.org" class="link -link-small">hello@metahash.org</a>',
      'footer-14' : 'Служба поддержки <a href="mailto:support@metahash.org" class="link -link-small">support@metahash.org</a>',
      'footer-15' : 'E-mail для прессы <a href="mailto:support@metahash.org" class="link -link-small">press@metahash.org</a>',
      'footer-16' : 'Телефон для прессы <a class="link -link-small">+7 926 671-67-08</a>',


      'mobile-menu-01' : '<a href="#whatis" class="link -link-white">Что такое #MetaHash</a>',
      'mobile-menu-02' : '<a href="#private-round" class="link -link-white">Купить #MetaHashCoin</a>',
      'mobile-menu-03' : '<a href="docs/MetaHash_WhitePaper_RU.pdf" target="_blank" class="download-white-paper link -link-white">Скачать White Paper</a>',
      'mobile-menu-04' : '<a href="docs/MetaHash_OnePager_RU.pdf" target="_blank" class="download-one-pager link -link-white">Скачать One-Pager</a>',
      'mobile-menu-05' : '<a href="#faq" class="link -link-white">Вопросы и ответы</a>',
      'mobile-menu-06' : '<a href="#support" class="link -link-white">Поддержка</a>',
      'mobile-menu-07' : '<a href="#support" class="link -link-white">Контакты</a>',
	  
	  'new-mobile-menu-01' : '<a href="#whatis" class="link -link-white --offcan">Что такое #MetaHash?</a>',
	  'new-mobile-menu-02' : '<a href="#tracechain" class="link -link-white --offcan">#TraceChain</a>',
	  'new-mobile-menu-03' : '<a href="#metaapps" class="link -link-white --offcan">#MetaApps</a>',
	  'new-mobile-menu-04' : '<a href="#metagate" class="link -link-white --offcan">#MetaGate</a>',
	  'new-mobile-menu-05' : '<a href="#timemap" class="link -link-white --offcan">Roadmap</a>',
	  'new-mobile-menu-06' : '<a href="#advisors-and-consultants" class="link -link-white --offcan">Advisors & Consultants</a>',
	  'new-mobile-menu-07' : '<a href="#teambanner" class="link -link-white --offcan">Команда</a>',
	  'new-mobile-menu-08' : '<a href="#ico" class="link -link-white --offcan">ICO Round A</a>',
	  'new-mobile-menu-09' : '<a href="#faq" class="link -link-white --offcan">Вопросы и ответы</a>',
	  'new-mobile-menu-10' : '<a href="#support" class="link -link-white --offcan">Напишите нам</a>',


      'promo-soc-01' : '<a href="https://t.me/metahash_rus" class="footer-social-button link-soc -tooltype" data-event="org_tg" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
      'promo-soc-02' : '<a href="https://www.facebook.com/MetaHashRu/" class="footer-social-button link-soc -tooltype" data-event="org_fb" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
      'promo-soc-03' : '<a href="https://vk.com/metahash" class="footer-social-button link-soc -tooltype" data-event="org_vk" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
      'promo-soc-04' : '<a href="https://twitter.com/MetaHashRU" class="footer-social-button link-soc -tooltype" data-event="org_twitter" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
      'promo-soc-05' : '<a href="https://instagram.com/themetahash" class="footer-social-button link-soc -tooltype" data-event="org_instagram" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
      'promo-soc-06' : '<a href="https://www.youtube.com/channel/UCIkBIrd1q7JkLLj43KgG8zA" class="footer-social-button link-soc -tooltype" data-event="org_youtube" target="_blank"><span class="soc-tooltype">youtube.com</span><span class="icon -icon-big icon_youtube"></span></a>',
      'promo-soc-07' : '<a href="#" class="footer-social-button link-soc -tooltype" data-event="org_wechat"><span class="soc-tooltype">ID:MetaHash</span><span class="icon -icon-big icon_wechat"></span></a>',
      'promo-soc-08' : '<a href="https://open.kakao.com/o/gY5dUgG" class="footer-social-button link-soc -tooltype" data-event="org_kakao" target="_blank"><span class="soc-tooltype">talk.com</span><span class="icon -icon-big icon_talk"></span></a>',
      'promo-soc-09' : '<a href="https://github.com/metahashorg" class="footer-social-button link-soc -tooltype" data-event="org_github" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
      'promo-soc-10' : '<a href="https://www.reddit.com/user/MetaHash/" class="footer-social-button link-soc -tooltype" data-event="org_reddit" target="_blank"><span class="soc-tooltype">reddit.com</span><span class="icon -icon-big icon_reddit"></span></a>',
      'promo-soc-11' : '<a href="https://www.linkedin.com/company/27209614/" class="footer-social-button link-soc -tooltype" data-event="org_linkedin" target="_blank"><span class="soc-tooltype">linkedin.com</span><span class="icon -icon-big icon_in"></span></a>',
      'promo-soc-12' : '<a href="https://medium.com/@metahashru" class="footer-social-button link-soc -tooltype" data-event="org_medium" target="_blank"><span class="soc-tooltype">medium.com</span><span class="icon -icon-big icon_medium"></span></a>',
      'promo-soc-13' : '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="footer-social-button link-soc" data-event="org_bitsmedia" target="_blank"><span class="icon -icon-big --icon-forum icon_bitsmedia"></span></a>',
      'promo-soc-14' : '<a href="https://bitcointalk.org/index.php?action=profile;u=1189183" class="footer-social-button link-soc" data-event="org_bitcointalk" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',


      'promo-soc-mobile-01' : '<a href="https://t.me/metahash_rus" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
      'promo-soc-mobile-02' : '<a href="https://www.facebook.com/MetaHashRu/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
      'promo-soc-mobile-03' : '<a href="https://vk.com/metahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
      'promo-soc-mobile-04' : '<a href="https://twitter.com/MetaHashRU" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
      'promo-soc-mobile-05' : '<a href="https://instagram.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
      'promo-soc-mobile-06' : '<a href="https://github.com/metahashorg" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
      'promo-soc-mobile-07' : '<a href="https://www.linkedin.com/company/27209614/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">linkedin.com</span><span class="icon -icon-big icon_in"></span></a>',
      'promo-soc-mobile-08' : '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitsmedia" target="_blank"></span></a>',
      'promo-soc-mobile-09' : '<a href="https://bitcointalk.org/index.php?action=profile;u=1189183" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',
      'promo-soc-mobile-10' : '<a href="https://www.youtube.com/channel/UCIkBIrd1q7JkLLj43KgG8zA" class="link-soc" target="_blank"><span class="icon -icon-big icon_youtube"></span></a>',
      'promo-soc-mobile-11' : '<a href="https://medium.com/@metahashru" class="link-soc" target="_blank"><span class="icon -icon-big icon_medium"></span></a>',




      'tg_button' : '<a href="https://t.me/metahash_rus" class="footer-social-button" data-event="org_tg" target="_blank"><img class="telega-svg" style="margin-bottom: 40px;" src="img/telegram.svg" alt=""></a>',








      'private-close-01' : 'Private Round завершен',
      'private-close-02' : 'Сумма заявок превысила доступный объем более чем в 20 раз',
      'private-close-03' : 'Мы благодарим всех участников и приглашаем желающих присоединиться к проекту на этапе ICO Round A.',
      'private-close-04' : 'ICO Round A',
      'private-close-05' : 'Запланированная дата',
      'private-close-06' : 'ICO Round A уже скоро',
      'private-close-07' : 'Не пропустите старт,<br class="mobile-br"> оставьте заявку на участие и присоединитесь к проекту',
      'private-close-08' : 'Подписаться <i class="icon icon_link"></i>',
      'private-close-09' : 'Следите за нами:',
      'private-close-10' : 'Правила ICO Round A:',
      'private-close-11' : 'В ходе ICO Round A будет распределено <b class="mob-bold">9,200,000 #MHC</b>',
      'private-close-12' : 'Стоимость #MHC на этапе ICO Round A составляет <b class="mob-bold">0.0125 ETH</b>',
      'private-close-13' : 'Заявки <b class="mob-bold">менее 50 ETH</b> (4,000 #MHC) реализуются <b class="mob-bold">в порядке живой очереди</b> из ограниченного объема, который восполняется  <b class="mob-bold">каждые 4 часа</b>',
      'private-close-14' : 'Чтобы не блокировать очередь небольших и средних заявок <b class="mob-bold">суммы свыше 50 ETH реализуются вне очереди из отдельного резерва</b>',
      'private-close-15' : '04/2018',
      'private-close-16' : 'введите e-mail',
      'private-close-17' : 'в соответствии с White Paper<br> может измениться',
      // 'private-close-18' : '<input id="private-close__terms-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__terms-check">Соглашаюсь с </label><a href="docs/MetaHash_TermsOfUse_EN.pdf" target="_blank">Terms of Use</a>',
      // 'private-close-19' : '<input id="private-close__policy-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__policy-check">Соглашаюсь с </label><a href="docs/MetaHash_PrivacyPolicy_RU.pdf" target="_blank">Privacy Policy</a> ',

      'private-close-18' : 'Соглашаюсь с ',
      'private-close-19' : 'Соглашаюсь с ',

      'private-close-25' : '<a href="docs/MetaHash_TermsOfUse_EN.pdf"  target="_blank">Terms of Use</a>',
      'private-close-26' : '<a href="docs/MetaHash_PrivacyPolicy_RU.pdf" target="_blank">Privacy Policy</a>',




      'private-close-20' : 'Заявка отправлена',
      'private-close-21' : ', благодарим вас за интерес к проекту <b>#MetaHash</b>  Мы сообщим вам <b>о дате ICO Round A</b>.',
      'private-close-22' : 'Не пропустите важное!',

      'private-close-23' : '<a href="https://t.me/metahash_rus" target="_blank"  class="private-close__modal-content_tg-link" >Присоединяйтесь к нашему<br> Телеграм-каналу</a>',
      'private-close-24' : '<a href="https://t.me/metahash_rus" target="_blank" class="support-window__social-block_soc-link support-window__social-block_soc-link_tg"><img class="support-window__social-block_soc-img" src="img/popup/sub-tg.png" alt=""><span class="flag"><img class="support-window__social-block_flag-img" src="img/icons/flag-rus.png"></span></a>',






      

        'modal-sub-name' : 'Владислав',
        'modal-sub-metalang' : '#MetaHash<br class="mobile-br"> Russian (Russia)',
        'modal-sub-subtit' : 'Подпишитесь на новостной дайджест #MetaHash<br class="mobile-br"> о криптовалютах, майнинге и технологии блокчейн',
        'modal-sub-subbtn' : 'Подписаться',
        'modal-sub-talk' : '<a class="sub-hr-text" href="https://t.me/metahash_rus" target="_blank"><b>Мы говорим на русском!</b><br> Присоединяйтесь к нашему чату в Telegram и не стесняйтесь задавать любые вопросы команде #MetaHash </a>',
        'modal-sub-tw' : '<a href="https://twitter.com/MetaHashRU" class="sub-hr-text" target="_blank">Следите за нашими новостями и развитием проекта в Twitter</a>',
        'modal-sub-img' : '<img src="img/popup/support_people/EN and RU - Vladislav.png" class="" alt="">',
        'modal-sub-soc-tg' : '<a href="https://t.me/metahash_rus" target="_blank" class="support-window__social-block_soc-link support-window__social-block_soc-link_tg"><img class="support-window__social-block_soc-img" src="img/popup/sub-tg.png" alt=""><span class="flag"><img class="support-window__social-block_flag-img" src="img/icons/flag-rus.png"></span></a>',
        'modal-sub-soc-tw' : '<a href="https://twitter.com/MetaHashRU" target="_blank" class="support-window__social-block_soc-link support-window__social-block_soc-link_tw"><img class="support-window__social-block_soc-img" src="img/popup/sub-tw.png" alt=""><span class="flag"><img class="support-window__social-block_flag-img" src="img/icons/flag-rus.png"></span>',
        'modal-sub-enter' : '<input type="text" class="modal__sub-inp" placeholder="Введите e-mail">',


        



        'attention-01' : '<span class="mobtext">Обратите внимание!</span> После многочисленных консультаций с юристами и подготовки документов для регуляторов SEC и FINMA, командой проекта были приняты следующие решения:',
        'attention-03' : '1. Переименовать раунды ICO на ICO Round A и ICO Round B;',
        'attention-04' : '2. Пересмотреть финансовые условия двух ожидаемых раундов ICO для увеличения конкурентоспособности проекта относительно проектов с необоснованно завышенной капиатализацией;',
        'attention-05' : '3. Изменить диаграмму распределения сборов для соблюдения правил FINMA, где команда заменена на Авторов и объединена с Советниками (Advisors) проекта. Авторские отчисления распространяются за пределы обоих раундов ICO;',
        'attention-06' : '4. Открыть в апреле запись на тестирование TestNet #TraceChain и скачивание рабочего клиента #MetaGate до старта ICO Round A, чтобы рабочий продукт был доступен <span>до начала crowdsale.</span>',
        'attention-07' : '<span class="mobtext">C подробностями можно</span> ознакомиться в White Paper проекта',
        'attention-08' : '<a href="docs/MetaHash_WhitePaper_RU.pdf" target="_blank" class="download-white-paper btn -download">Скачать White Paper<i class="icon icon_dowload"></i></a>'

};

