"use strict";

window.arrLang = window.arrLang || {};
window.arrLang["ar"] = {
  
      'nav-link-01' : 'ما هي شبكة MetaHash#؟',
      'nav-link-02' : 'شراء MHC#',
      'nav-link-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -link-white"><img src="img/icon_file.svg" class="icon_file"> الورقة البيضاء</a>',
      'nav-link-04' : '<a href="docs/MetaHash_OnePager_AR.pdf" target="_blank" class="link -link-white"><img src="img/icon_file.svg" class="icon_file"> المنشور المكون من صفحة واحدة</a>',
      'nav-link-05' : 'الأسئلة المتداولة',
      'nav-link-06' : 'الدعم',
	  'nav-link-07' : 'اتصل بنا',


      'promo-01' : 'سريعة',
      'promo-02' : 'معدل التحقق من الصحة أقل من 3 ثوان والأداء أكثر من 50000 معاملة في الثانية',
      'promo-03' : 'آمنة',
      'promo-04' : 'محمية بواسطة 5 خوارزميات متوافقة متنوعة',
      'promo-05' : 'لامركزية',
      'promo-06' : 'يمكن لأي شخص إضافة عُقد المعاملة إلى شبكة MetaHash#',


      'descr-01' : 'قائمة على تكنولوجيا البلوكتشين 2.0',
      'descr-02' : '<span class="cripto-title -title-part01">العملات</span><span class="cripto-title -title-part02">المشفرة</span>',
      'descr-03' : 'and decentralized ecosystem',
      'descr-04' : 'قائمة على تكنولوجيا البلوكتشين 2.0',


      'promo-appint-01' : '<span class="part-name">لتخزين</span>',
      'promo-appint-03' : 'أي معلومات في البلوكتشين مع حماية تشفير بمعدل 4 كيلو بود وتوقيع متعدد',
      'promo-appint-04' : '<a href="#private-round" class="btn -default">جولة العرض الأولي للعملة أ<i class="icon icon_link"></i></a>',
      'promo-appint-05' : 'المعاملات<span class="part-name">&nbsp;</span>',
      'promo-appint-06' : 'تستغرق حتى 3 ثوان للموافقة داخل شبكة MetaHash# وخارجها',
      'promo-appint-07' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">تنزيل الورقة البيضاء<i class="icon icon_dowload"></i></a>',
      'promo-appint-08' : '<span class="part-name">ل أيّ أصل</span>',
      'promo-appint-10' : 'تستخدم جميع الأصول الرقمية في محفظة MetaGate# العملة الرمزية ERC20 في جميع خدمات التبادل',
      'promo-appint-11' : '<a href="docs/MetaHash_OnePager_AR.pdf" target="_blank" class="btn -download">تنزيل المنشـور المكون من صفحة واحدة<i class="icon icon_dowload"></i></a>',
      'promo-appint-12' : '<a href="#private-round" class="btn -default -mega" >جولة العرض الأولي للعملة أ</a>',
      'promo-appint-13' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">الورقة البيضاء</a>',
      'promo-appint-14' : '<a href="docs/MetaHash_OnePager_AR.pdf" target="_blank" class="btn -download float-right">المنشور المكون من صفحة واحدة</a>',
      'promo-appint-15' : 'Download #MetaGate client',

      'whatis-01' : 'ما هي شبكة MetaHash#؟',
      'whatis-02' : 'MetaHash#هي شبكة الجيل القادم القائمة على تكنولوجيا البلوكتشين 2.0 لتبادل الأصول الرقمية بالإضافة إلى أنها منصة لإنشاء التطبيقات وإدارتها وتوفير خدمات لامركزية فورية',
      'whatis-03' : 'يحتوي النظام على أربعة مكونات:',
      'whatis-04' : '#TraceChain',
      'whatis-05' : 'أسرع بلوكتشين والأكثر أمانًا',
      'whatis-06' : 'أكثر من خمسة مليارات معاملة في اليوم الواحد، لا تستغـرق سوى ثلاث ثوانٍ للتحقق من صحة المعاملة',
      'whatis-07' : 'معلومات حول TraceChain#',
      'whatis-08' : '#MetaApps',
      'whatis-09' : 'جيل جديد من العقود الذكية',
      'whatis-10' : 'تطبيقات لامركزية فورية يتم تشغيلها مثل خدمات الويب العادية ويمكن تطويرها بمساعدة أي لغة برمجة بما في ذلك ++C وPHP وSolidity وغيرها',
      'whatis-11' : 'معلومات حول #MetaApps',
      'whatis-12' : '#MetaGate',
      'whatis-13' : 'إنترنت لامركزي',
      'whatis-14' : 'دليل للتطبيقات اللامركزية ومحفظة متعددة الأصول لا يمثلا حملاً زائدًا على جهاز الكمبيوتر',
      'whatis-15' : 'معلومات حول MetaGate#',
      'whatis-16' : '#MetaHashCoin',
      'whatis-17' : 'أصول تبادل شبكة MetaHash#',
      'whatis-18' : 'اعتادت <b>MetaHashCoin#</b> على ضمان موثوقية الشبكة وخدمات التبادل وتنظم التمويل الذاتي والتنمية',
      'whatis-19' : 'معلومات حول MHC#',


      'tracechain-01' : '#TraceChain',
      'tracechain-02' : 'تكنولوجيا البلوكتشين 2.0 السريعة الآمنة',
      'tracechain-03' : 'أكثر من',
      'tracechain-04' : '100,000',
      'tracechain-05' : 'معاملة في الثانية في كل عُقدة',
      'tracechain-06' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download lang" >تنزيل الورقة البيضاء<i class="icon icon_dowload"></i></a>',
 //   'tracechain-07' : 'to approve a transaction',
 //   'tracechain-08' : 'transactions per day',
 //   'tracechain-09' : 'stages of consensus for verification',
 //   'tracechain-10' : '#MetaHash block anchors <span class="blue">in Bitcoin and Ethereum networks</span>',
      'tracechain-11' : '<img class="tracechain-svg" src="img/graphical/tracechain-ar.svg" alt="">',


      'speed-work-01' : 'تمتاز شبكة #TraceChain بسرعة لم يسبق لها مثيل ولامركزية تجعل MetaHash# هي الرائدة في عالم البلوكتشين',
      'speed-work-02' : 'أكمل أي مبلغ من المعاملات في شبكة <b>MetaHash#</b>',
      'speed-work-03' : 'تكلفة المعاملة أقل من أي بلوكتشين عادية',
      'speed-work-04' : 'تكلفة تخزين البيانات معقولة مع <b>TraceChain#</b> للمشاريع اللامركزية',
      'speed-work-05' : 'أي أصول يمكن ترميزها في <b>MetaHashCoin#</b> ليتم توزيعها في شبكة <b>MetaHash#</b> وإيثريوم وشبكات أخرى',


      'speeds-01' : 'كيف تمكّنا من تحقيق هذه السرعة؟',
      'speeds-02' : 'تبدأ المعاملات في المحيط الخارجي ثم تدخل في الشبكة الأساسية عبر أسرع طريق.',
      'speeds-03' : 'تتم الموافقة على المعاملة في كل مرحلة حتى تصل إلى الشبكة الأساسية.',
      'speeds-04' : 'تعمل أسرع عُقد للشبكة الأساسية على مزامنة المعاملات فيما بينها.',
      'speeds-05' : 'تُرجع الشبكة الأساسية رصيد المحفظة إلى الشبكة والتي تتحقق بدورها من صحة الحسابات.',
      'speeds-06' : 'تذهب بيانات النسخ الاحتياطي إلى البلوكتشين التقليدية للتحقق من سلامة الشبكة.',
      'speeds-07' : 'رموز الإرساء (تجزئة من أطول كتلة) يتم تخزينها على شبكة بيتكوين وإيثريوم وغيرهما من الشبكات.',
      'speeds-08' : 'لا يمكنك إتلاف المعلومات المخزنة في MetaHash# أو تعديلها. لتتمكن من القيام بذلك، يتوجب عليك مهاجمة شبكة MetaHash# بنجاح وكذلك شبكة بيتكوين وإيثريوم وغيرهما من الشبكات.',
      'speeds-09' : 'لمزيد من التفاصيل الفنية، راجع الورقة البيضاء',
      'speeds-10' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">تنزيل الورقة البيضاء<i class="icon icon_dowload"></i></a>',


      'metaapps-01' : '#MetaApps',
      'metaapps-02' : 'الخدمات السحابية للتطبيقات الذكية الفورية',
      'metaapps-03' : 'MetaApps# هي تطور للعقود الذكية، ويمكن استخدامه لجعل أي خدمة لامركزية. تُعد هذه البرامج مستقلة ويمكن أن تستمر إلى الأبد وليست مملوكة لأي شخص، كما أنها تعمل تمامًا كما لو كانت برنامج ولا يمكن العبث بها من قِبل أيّ أطراف خارجية.',
      'metaapps-04' : 'مزايا MetaApps#',
      'metaapps-05' : 'تشغيل في الوقت الحقيقي',
      'metaapps-06' : 'تعمل بنفس سرعة خدمات الويب والتطبيقات العادية',
      'metaapps-07' : 'تصميم مماثل لتصميم أي واجهة مستخدم رسومية',
      'metaapps-08' : 'يمكن أن تبدو مثل التطبيقات أو صفحات الويب العادية',
      'metaapps-09' : 'الأمان',
      'metaapps-10' : "لا يمكن لأحد تغيير نهج التطبيق بتجاوز قواعد التحديث",
      'metaapps-11' : 'يتم تحميل صورة البرنامج ونظام التشغيل على الشبكة ثم يبدأ تلقائيًا على العديد من أجهزة الكمبيوتر.',
      'metaapps-12' : 'تم إنشاؤه بأي لغة برمجة بما في ذلك بما في ذلك بما في ذلك ++C وPHP وSolidity وغيرها.',
      'metaapps-13' : 'الدعم الكامل لميزة العقود الذكية، ويمكن أن تعمل مع أي بلوكتشين أو مع البيانات القادمة من الإنترنت فقط.',


      'metagate-01' : '#MetaGate',
      'metagate-02' : 'بوابة الإنترنت اللامركزي',
      'metagate-03' : 'MetaGate# هو برنامج مفتوح المصدر، لذلك يمكن لجميع المطورين تضمين أجزاء من شفرته في تطبيقاتهم ومتصفحاتهم.',
      'metagate-04' : 'محفظة متعددة الأصول',
      'metagate-05' : 'المحفظة تدعم "الوضع الخفيف" دون تحميل البلوكتشين بأكملها، وتأتي البيانات من مصادر مختلفة للشبكة اللامركزية ويفحصها المستخدم. المستخدم فقط هو من يمكنه تخزين مفاتيح خاصة من جميع البلوكتشين المستخدمة.',
      'metagate-06' : 'كتالوج ال طبيقات',
      'metagate-07' : 'كتالوج للتطبيقات اللامركزية والمتصفح للعمل معهم. يمكن الوصول لأي تطبيق لامركزي قائم على <b>MetaHash#</b> ليس فقط من خلال نطاق الإنترنت القياسي ولكن أيضًا عن طريق <b>MetaGate#</b> أو التوزيع على برنامج منفصل.',
      'metagate-08' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">تنزيل الورقة البيضاء<i class="icon icon_dowload"></i></a>',
	  'metagate-download-button' : 'Download #Metahash',

      'metahashcoin-01' : 'MetaHashCoin# (‏MHC#)',
      'metahashcoin-02' : 'النموذج المالي لنظام MetaHash#',
      'metahashcoin-03' : 'MetaHash# هو نظام تمويل ذاتي مقترن بعملية تنمية ذاتية متضمنة في شفرته الوراثية.',
      'metahashcoin-04' : 'يُستخدم MetaHashCoin# لدفع:',
      'metahashcoin-05' : 'المعاملات',
      'metahashcoin-06' : 'معاملات فورية وموثوق بها لأي نوع أصول بسعر ثابت ومعقول.',
      'metahashcoin-07' : 'تخزين البيانات',
      'metahashcoin-08' : 'للتطبيقات التي تحتاج إلى تخزين بيانات، ولكنها تفتقر إلى السرعة وحجم البيانات في أنظمة البلوكتشين التقليدية.',
      'metahashcoin-09' : 'تشغيل التطبيق',
      'metahashcoin-10' : 'يتطلب أي تطبيق لامركزي أو عقد ذكي موارد للنشر، بما في ذلك شبكة <b>MetaHash#</b> نفسها.',
      'metahashcoin-11' : 'خدمات أخرى',
      'metahashcoin-12' : 'الدفع لعناوين عامة والإدراج في <b>MetaApps#</b> والإعلان في <b>MetaGate#</b> وغيرها من المصادر.',
      'metahashcoin-13' : '<a href="#private-round" class="btn -default btn-mobile">شراء MHC#<i class="icon icon_link"></i></a>',


      'minig-01' : 'التعدين/النسخ لعملة MHC#',
      'minig-02' : 'الخوادم',
      'minig-03' : 'تُستخدم لتشغيل شبكة المعاملات والموارد الحرة المستخدمة لتشغيل التطبيقات اللامركزية.',
      'minig-04' : 'مَحافِظ #MetaGate',
      'minig-05' : 'تُستخدم العُقد في الوضع الكامل كتخزين للبيانات وعُقد التورنت.',
      'minig-06' : 'MetaHashCoins#',
      'minig-07' : 'تعزيز أمان التوافق على نموذج التصويت المختلط لمكونات إثبات العمل (PoW) + إثبات الحصة (PoS).',
      'minig-08' : 'تُستخدم MHC# الواردة من بيع الخدمات في:',
      'minig-09' : 'تدريب المطورين الذين يُنشئون مشاريعهم على MetaHash#',
      'minig-10' : 'تحسين جودة المشروع',
      'minig-11' : 'ترقية MetaHash#',
      'minig-12' : 'الدفع لأصحاب MetaHashCoins# لتحقيق دعم متوافق',
      'minig-13' : 'الدفع لأصحاب الخوادم وأجهزة الكمبيوتر',


      'compare-00' : 'المشروع',
	  'compare-01' : 'مزايا MetaHash#',
      'compare-02' : 'بعد أن فشلنا في العثور على أي مشاريع تعمل بناءً على إنشاء دائرة لامركزية تمامًا وتكون متزامنة ولديها القدرة على معالجة كمية البيانات اللازمة للعالم أجمع بسرعة كبيرة، قررنا عمل MetaHash#.',
      'compare-03' : 'جدول للمقارنة بين أنظمة البلوكتشين الأساسية',
      'compare-04' : 'وقت الموافقة<br />على المعاملة',
      'compare-05' : 'عدد المعاملات في الثانية',
      'compare-06' : 'مستوى اللا<br />ركزية',
      'compare-07' : 'بيتكوين',
      'compare-08' : '10 دقائق',
      'compare-09' : 'حتى 12',
      'compare-10' : 'مرتفع',
      'compare-11' : 'Ethereum',
      'compare-12' : '15 ثوان',
      'compare-13' : 'حتى 30',
      'compare-14' : 'مرتفع',
  //    'compare-15' : 'Plasma',
  //    'compare-16' : '15 seconds',
  //    'compare-17' : 'up to 30',
  //    'compare-18' : 'high',
      'compare-19' : 'EOS',
      'compare-20' : '5 ثوان',
      'compare-21' : 'من 1000 حتى ملايين',
      'compare-22' : 'أدنى حد',
      'compare-23' : 'MetaHash#',
      'compare-24' : 'حتى 3 ثوان',
      'compare-25' : 'من 50,000 حتى ملايين',
      'compare-26' : 'مرتفع',
      'compare-27' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">تنزيل الورقة البيضاء<i class="icon icon_dowload"></i></a>',


      'timemap-01' : 'خطة العمل',
      'timemap-02' : 'استند الجزء التقني من المشروع إلى إنجازات AdSniper، المنشأة عام 2012 حتى عام 2017 في مجال تقنيات الإعلان.',
      'timemap-03' : "لقد تلقينا الكثير من الطلبات من شركات مختلفة لتطبيق تقنية البلوكتشين وتوصلنا لنتيجة مُسلّم بها وهي أن التقنيات الحالية لا يمكن أن تُلبي احتياجات مثل هذه الأنواع من الأنظمة. لذلك بدأنا في تطوير بروتوكول TraceChain# الخاص بنا في في عام 2016.",
      'timemap-04' : 'في عام 2017، أنشأنا إصدارات ألفا وبيتا من بروتوكول TraceChain# وتضافرت جهودنا مع أقوى الشركات والأفراد في مجالات التسويق الدولي وتطوير الأعمال.',
      'timemap-05' : '2012-2016',
      'timemap-06' : 'A network library for receiving signals, working on C++ and capable of simultaneously receiving and sending more than 100,000 requests per second to one inexpensive standard server',
      'timemap-07' : 'A network library for synchronizing signals within a cluster that manages gigantic data flows between cluster machines.',
      'timemap-08' : 'A machine learning system that decides in 40 milliseconds to respond to a signal taking into account multifactorial interrelationships.',
      'timemap-09' : 'Own analogue of Hadoop’s for similar systems in C ++ for distributed processing of large data.',
      'timemap-11' : '2017',
      'timemap-12' : 'Development of #TraceChain protocol (Alpha version)',
      'timemap-13' : 'Development of #TraceChain protocol (Beta version)',
      'timemap-14' : '<b>AdNow</b> team joins us',
      'timemap-15' : '<b>Agranovsky IT</b> team joins us',
      'timemap-16' : 'Formation of <b>Business Development team</b>',
      'timemap-17' : 'Formation of <b>Operational Team</b>',
      'timemap-18' : '2018',


      'timemap-19' : '#MetaHash website official launch',
      'timemap-20' : 'Start of the Operational Team office construction',
      'timemap-21' : 'Onboarding of experts and advisors',
      'timemap-22' : 'Development of #MetaGate (v.1.0). Multi-asset wallet featuring the ability to transfer #MetaHashCoins between wallets on multiple servers that stores data on transactions between crypto wallets.',
      'timemap-23' : 'Development of #TraceChain (v.1.0)',
      'timemap-23a': 'Development of #TraceChain (v.2.0). #TraceChain data download API',
      'timemap-24' : 'Development of #MetaICO (v.1.0). The ICO interface on the #MetaHash platform that accepts assets from various blockchains (Bitcoin and Ethereum), distributes tokens in the #MetaHash network and carries out multichain transactions, including ERC20 in the Ethereum network',
      'timemap-25' : 'Development of #MetaChains (v.1.0). Converting #MetaHashCoins to ERC20 and withdrawing them to the Ethereum network so that #MHC holders can choose which network to use and automatically convert ERC20 tokens into #MetaHashCoins',

      'timemap-26' : 'Development of #MetaApps (v.1.0). Application Platform',
      'timemap-27' : 'Testnet data download API',
      'timemap-28' : 'Opening of the Operational Team office',


      'timemap-29' : 'ICO Round A scheduled start',
      'timemap-30' : 'Development of #MetaChains (v.2.0). API featuring transaction history and balance  of wallets associated with different blockchain platforms. Decentralized application containing information about transactions in the Ethereum and Bitcoin networks which is necessary to provide blockchain interoperability in #MetaApps',
      'timemap-31' : 'Release of <b>#MetaGate (v.2.0)</b>. Encrypted messenger for public notifications and messaging between wallets',
      'timemap-32' : 'Release of <b>#TraceChain (v.3.0)</b>. Peer nodes that connect to TestNet to be installed on any server',
      'timemap-33' : '#TraceChain (v.4.0). Network core performance testing service (1,000,000+ transactions per second)',
      'timemap-34' : '#MetaICO (v.2.0). Interface for creating tokens inside the network #MetaHash',
      'timemap-35' : '#MetaICO (v.3.0). Release of ICO project platform at #MetaHash.',
      'timemap-36' : '#TraceChain (v.4.0). Voting functions in the #MetaHash network',
      'timemap-37' : '#TraceChain (v.5.0). AI managing the routing of signals between nodes for providing maximum speed of #MetaHash block creation and bandwidth and 100 test nodes in different geographical locations for testing node interaction',

      'timemap-38' : '#MetaICO (v.4.0). Release of the #MetaToken application, tokenization of ETH, ERC20, Bitcoin to #MetaHashCoin for use in the #MetaHash network',
      'timemap-39' : '#TraceChain (v.6.0). #MetaStorage, service for decentralized applications',
      'timemap-40' : '#MetaApps (v.2.0). The platform for self-deployment of third-party decentralized applications',
      'timemap-41' : '#MetaGate (v.3.0). Final release of #MetaGate wallet for Mac/Win/Unix/Android/iOS with #MetaApps catalogue',


      'timemap-42' : '<b>#TraceChain (v.7.0). Start of forging </b>',
      'timemap-43' : '<b>بداية جولة العرض الأولي للعملة (ب) أو إبرام اتفاق التسجيل  في بورصة العملات المشفرة التي تخضع للتنظيم والضبط على النحو الواجب</b>',
      'timemap-44' : 'إعلان خطة أخرى',


      'timemap-45' : 'اختبار أمني مكثف',
      'timemap-46' : 'إصدار شفرة المصدر عند الانتهاء من الاختبار',
      'timemap-47' : 'إطلاق نظام لامركزي بالكامل',
      
      'timemap-100' : 'قراءة المزيد',
	  'timemap-101' : 'إخفاء الأحداث',
	  'timemap-102' : 'أحداث أخرى',


      'teambanner-01' : 'فريقنا',
      'teambanner-02' : 'MetaHash# عبارة عن مشروع منظم يضم فريق متفتح ويرحب بجميع الأفراد والشركات.',
      'teambanner-03' : 'إذا كنت تعتقد أنه بإمكانك المساعدة وتريد الانضمام إلى الفريق، الرجاء <a class="team-write" href="mailto:hello@metahash.org">الاتصـال بنا</a>.',
      'teambanner-04' : '<a href="#private-round" class="btn -default">جولة العرض الأولي للعملة أ<i class="icon icon_link"></i></a>',
      'teambanner-05' : 'إذا كنت تعتقد أنه بإمكانك المساعدة وتريد الانضمام إلى الفريق، الرجاء <a href="mailto:hello@metahash.org">الاتصـال بنا</a>.',
      'teambanner-06' : 'جولة العرض الأولي للعملة أ',
      'teambanner-07' : '<img src="img/graphical/People_AR@3x.svg" alt="">',

      'team-hidden-01' : 'لمصلحة المشروع ، يتم الكشف عن أسماء بقية أعضاء الفريق.',

      'team-dev-00' : 'المطوِّر:',
	  'team-dev-01' : 'هيثم الشربيني',
	  'team-dev-01a' : 'عضو مؤسس، شريك، كبير مسؤولي المخاطر <a href="http://www.facebook.com/glebnikitin" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="https://www.linkedin.com/in/glebnikitin/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
      'team-dev-02' : 'رامي محسن',
      'team-dev-03' : 'كبير المستشارين المعتمدين، مهندس الخدمات الفورية في AdSniper ومحلل نظام AlfaBank المصرفي عبر الإنترنت ومُنشئ مكتبة شبكة الحِمل العال القادرة على خدمة أكثر من مليون طلب في الثانية الواحدة على عُقدة واحدة.',
      'team-dev-04' : 'مايكل جورج',
      'team-dev-05' : 'كبير موظفي التكنولوجيا، رئيس وحدة الذكاء الاصطناعي والتي تشمل كم ضخم من البيانات وتضم فرق الخدمات الفورية بهدف تقديم ذكاء اصطناعي قادر على التعامل مع الملايين من الطلبات الفورية التي تجمع بين حسابات الشبكات العصبية وخوارزميات التعلم الآلي الأخرى.',
      'team-dev-06' : 'سراج الدين محمد',
      'team-dev-07' : "كبير موظفي المعلومات، يخطط وينسق تنفيذ العشرات من التقنيات والواجهات المختلفة التي تُشكّل تسلسل تكنولوجيا AdSniper.",
      'team-dev-08' : '29 موظفًا في AdSniper <i class="icon icon_link"></i>',
      'team-dev-09' : "على مدى السنوات العشر الماضية، أنشأت الشركة شبكات إعلانية محملة تحميلاً عاليًا. إلى جانب أن الشركة تمتلك معالج بيانات كبير خاص بها يتضمن توفير خدمة بيتابايت للبيانات وقواعد بيانات NoSQL سريعة وقواعد بياناتSQL وأنظمة للذكاء الاصطناعي ومكتبات ++C وذلك لتوفير الخدمات الإعلانية بشكل قوي للغاية وكذلك لمعالجة طلبات الإعلانات من شبكة الإنترنت بأكملها.",
      'team-key-staff' : 'الفريق الأساسي',


      'team-mark-00' : 'التسويق',
	  'team-mark-01' : 'فايز عبد العزيز',
	  'team-mark-01a' : 'الرئيس التنفيذي لشركة AdNow، رئيس مسؤولي التسويق <a href="http://www.facebook.com/vladimir.bashkin" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="http://www.linkedin.com/in/vladimir-bashkin-18877678/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
      'team-mark-02' : 'تضم الشبكة الإعلانية أكثر من مليار مرة ظهور في اليوم وتُعد واحدة من أقوى الفرق في العالم لشراء الإعلانات عبر جميع الشبكات الإعلانية بالتعاون مع فريق من المترجمين والمتخصصين في الإعلانات في الأسواق المحلية.',
      'team-mark-03' : '89 موظفًا في AdNow <i class="icon icon_link"></i>',
      'team-mark-04' : 'عمر محسن',
      'team-mark-05' : 'مدير المناسبات - مدير العلاقات العامة الرئيس التنفيذي لمناسبات AdDays الرقمية. مدير المناسبات في شبكة Bitcomo التابعة',
      'team-mark-06' : 'فتحي فايز',
      'team-mark-07' : 'مدير تابع - مدير مبيعات النشر في AdNow. المدير التنفيذي لمكتب القاهرة',
      'team-mark-08' : 'فارس الطحان',
      'team-mark-09' : "رئيس قسم الإعلانات - رئيس قسم المبيعات في AdNow بأفريقيا. مدير المبيعات وتطوير الأعمال فيAdNow",


      'team-fin-00' : 'تطوير الأعمال',
	  'team-fin-01' : 'محمد منصور',
	  'team-fin-01a' : 'عضو مؤسس، شريك، الرئيس التنفيذي لتطوير الأعمال <a href="https://www.facebook.com/aagranovsky" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="https://www.linkedin.com/in/anton-agranovsky-57427a15a/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
      'team-fin-02' : 'Agranovsky IT - شركة استثمارية تستثمر في شركات تكنولوجيا المعلومات الناشئة وترعى نموالشركة من الفكرة وصولاً إلى الاكتتاب العام. المؤسس أنطون أجرونوفسكي هو مستثمر خبير، وهو المستشار الرائد في مجال إنشاء وتطوير شركات تكنولوجيا المعلومات. عضو مجلس إدارة Media Planet وXMA. من 2008 وحتى 2017 - مؤسس ورئيس Destination Development، وهي واحدة من أوائل شركات الألعاب الرائدة في سوق الإنترنت المصري المشهورة بأعمال التطوير والتوطين الخاصة بها.<br />&nbsp;<br /><a href="https://goo.gl/fJVjfK" class="link -link-small" target="_blank">مشارك في مجلة الفوربس</a>',
      'team-fin-03' : '11 موظفًا في Agranovsky IT <i class="icon icon_link"></i>',
      'team-fin-04' : 'يونس الجندي',
      'team-fin-05' : 'الرئيس التنفيذي - تنظيم المحاسبة في الشركات القابضة. أكثر من 10 أعوام من الخبرة في مجال تكنولوجيا المعلومات ومشاريع الألعاب',
      'team-fin-06' : 'محمد سعيد',
      'team-fin-07' : 'نائب الرئيس التنفيذي - خبير في تقييم المخاطر، أكثر من 10 أعوام من الخبرة في مراجعة المشاريع الجديدة والنشطة في تكنولوجيا المعلومات وصناعات الألعاب',
      'team-fin-08' : 'كريم ذكي',
      'team-fin-09' : 'المدير المالي - أكثر من 10 أعوام من الخبرة في مجال تكنولوجيا المعلومات ومشاريع الألعاب. داعم نشط للمشاريع الاجتماعية والخيرية',


      'team-oper-00t' : 'الفريق التشغيلي',
	  'team-oper-01' : 'نعيم حامد',
      'team-oper-02' : 'أكثر من 11 عاما من الخبرة في الإدارة التشغيلية للمشاريع متعددة المستخدمين في Game Lightوغيرها من شركات تكنولوجيا المعلومات الناشئة.',
      'team-oper-03' : 'محمود متولي',
      'team-oper-04' : 'مدير الفنون، أكثر من 16 عامًا من الخبرة في مجال التصميم البصري وتصميم المنتجات. عَمِل في مشاريع لشركات RUSNANO وSony وCanon وNikon وغيرها من الشركات',
      'team-oper-05' : 'أحمد شاهين',
      'team-oper-06' : 'الرئيس التنفيذي لتطوير الأعمال في أفريقيا والشرق الأوسط وشمال أفريقيا - مؤسس منصة الألعاب Game.MA وناشر لعبة INFINITY',
      'team-oper-07' : 'سيد عبد الفتاح',
      'team-oper-08' : 'الرئيس التنفيذي لتطوير الأعمال في روسيا ورابطة الدول المستقلة - أكثر من 10 أعوام من الخبرة في النشر والتشغيل وتطوير الأعمال خبرة في Destiny.Games وفي صناعة الألعاب',
      'team-oper-09' : 'يوجينيا سيغاتشيفا',
      'team-oper-10' : 'شريك الشؤون العامة -أكثر من 18 عامًا في التسويق الدولي والعلاقات العامة، وكذلك تكنولوجيا المعلومات والابتكارات. تعتبر فايزة جزءًا من الفريق الدولي المسؤول عن الروبوت" صوفيا" المعروفة جيدًا والرئيس التنفيذي ومؤسسة منصة IHEART.',
      'team-oper-11' : 'Andrey Akimov',
      'team-oper-12' : '<span style="color:#ffffff;">Chief Communication Officer</span><br/>More than 15 years in marketing and PR in gaming, entertainment, and IT business. Former head of PR and marketing at My.com, Mail.Ru Group, Game Insight, and other companies.',
      'team-oper-00' : '17 موظفًا في الفريق التشغيلي <i class="icon icon_link"></i>',


      //'legal-01' : 'الدعم القانوني',
      //'legal-02' : 'أمل الهواري',
      //'legal-03' : 'شريك اداري في مكتب أنيس للاستشارات القانونية <a href="https://www.facebook.com/people/Anastasia-Pichugina/1520204010" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
      //'legal-04' : 'علا صديق',
      //'legal-05' : 'كبيرة محامين - رئيسة ممارس لمشاريع البلوكتشين. رافقت نجاح العديد من مشاريع العرض الأولي للعملة، وهي الشريك والمتحدث في المؤتمرات والندوات عبر الإنترنت.',
      //'legal-06' : 'حسن يونس',
      //'legal-07' : 'كبير محامين - رئيس ممارس للأنشطة التجارية في مكتب أنيس للاستشارات القانونية المتخصصة في الدعم القانوني للمعاملات التجارية والاستثمارية.',
      //'legal-08' : 'آية البدري',
      //'legal-09' : 'محامية - دعم قانوني للشركات المصرية والأجنبية في مجال حقوق الملكية الفكرية، بما في ذلك تسجيل العلامات التجارية وبراءات الاختراع.',
      //'legal-10a' : 'مكتب أنيس للاستشارات القانونية ومكتب العدالة',
	  //'legal-10' : 'خبراء في القانون الدولي والمصري. تخرج محامونا من أرقى كليات الحقوق داخل مصر وخارجها. أمل، الشريك الإداري لديها خبرة فريدة من نوعها ومعرفة غير مسبوقة في القانون المصري والدولي، وهي ممثل قانوني موثوق لعدة شركات أجنبية تعمل في تكنولوجيا المعلومات والسلع الاستهلاكية سريعة التداول. تمثل أمل الشركات الأجنبية أمام المحاكم المصرية بنجاح.',
      //'legal-11' : '<a href="docs/MetaHash_LegalOpinion_EN.pdf" target="_blank">تنزيل الرأي القانوني #MetaHashCoin<i class="icon icon_link"></i></a>',
	  'legal-title' : 'Legal Department',

    //'legal-14' : 'Maria Agranovskaya',
    //'legal-15' : 'Chief Legal Coordinator <a href="https://www.facebook.com/magranovskaya" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a> <a href="https://www.linkedin.com/in/maria-agranovskaya-151334/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
    //'legal-16' : '<span>Attorney at Law with 20+ years of experience. Started working with cryptocurrency issues back in 2010. MGIMO MID of Russia (International Law), studied in Germany and Holland. 8,5 years - running a multifamily office, worked on various cross-border transactions, investments, asset management, deal and corporate structuring in various jurisdictions, M&A, international taxation and other matters.</span><span>Areas: fintech, finance, telecom, banking, energy, pharmaceuticals, real estate and other sectors.</span><span>2007: setup of GRAD Attorney Bar (managing partner,  30+ Russian and foreign lawyers)</span><span>Substantially engaged in blockchain technology, ICO (TGE) related projects, trading and finance regulations, funds and financial activity.</span><span>Speaks English, German, French, Italian, </span>',
	 
	  'legal-more' : 'قراءة المزيد',
	  'legal-less' : 'إخفاء الأحداث',
	  'legal-17' : 'Andrey Mironov <a href="http://www.linkedin.com/in/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a> <a href="https://www.facebook.com/" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
	  'legal-18' : 'Chief of Legal Department',
	  'legal-19' : 'Graduated MGIMO in 2000 at the international law faculty. Legal practice in the field of new technologies, media and intellectual property for more than 15 years.',
	  'legal-19a' : 'He worked at the Art. Lebedev Studio, Odnoklassniki, the Russian office of Myspace, on the channels MTV, Discovery, Amedia and the online cinema Amediateka. Helped to develop the EKSMO publishing house, the Fox TV channel. Expert at the Russian Association of Electronic Communications (RAEC).<br>Secondary Education: Consultant Psychologist',
	  'legal-20' : 'Maria Agranovskaya',
	  'legal-21' : 'Chief Legal Coordinator',
	  'legal-22' : 'Attorney at Law with 20+ years of experience. Started working with cryptocurrency issues back in 2010.',
	  'legal-22a' : 'MGIMO MID of Russia (International Law), studied in Germany and Holland. 8,5 years - running a multifamily office, worked on various cross-border transactions, investments, asset management, deal and corporate structuring in various jurisdictions, M&A, international taxation and other matters. Areas: fintech, finance, telecom, banking, energy, pharmaceuticals, real estate and other sectors. 2007: setup of GRAD Attorney Bar (managing partner,  30+ Russian and foreign lawyers). Substantially engaged in blockchain technology, ICO (TGE) related projects, trading and finance regulations, funds and financial activity. Speaks English, German, French, Italian,  Spanish.',
	  'legal-23' : 'Katya Fisher',
	  'legal-24' : 'Partner, Principal at The Law Office of Katya Yoffe PLLC',
	  'legal-25' : 'Katya Yoffe (née Fisher) is an attorney focusing on general corporate law, cross-border transactions and business immigration.',
	  'legal-25a' : 'Katya represents various prominent companies and startups doing business in the United States as well as celebrity and HNW individuals. Katya has been selected to Super Lawyers as a “Rising Star” in 2014, 2015, 2016, 2017 and 2018. <br>Katya is a graduate of New York University, the Benjamin N. Cardozo School of Law and a former Howard M. Squadron Fellow in International Media Law & Policy at the University of Oxford and Center for Global Communication Studies, University of Pennsylvania. She is admitted to practice in New York and before the United States Tax Court.',
	  'legal-26' : 'Anastasia Pichugina',
	  'legal-27' : 'ANP Law Managing Partner ',
	  'legal-28' : 'Managing partner Anastasia has a unique experience and knowledge in Russian and foreign law, is a trusted legal representative of several foreign companies.',
	  'legal-29' : 'علا صديق',
	  'legal-30' : ' عبر الإنترنت',
	  'legal-31' : 'كبيرة محامين - رئيسة ممارس لمشاريع البلوكتشين. رافقت نجاح العديد من مشاريع العرض الأولي للعملة، وهي الشريك والمتحدث في المؤتمرات والند',
	  'legal-32' : 'International Legal Support',
	  'legal-33' : 'Daniel G. Viola',
	  'legal-34' : 'Partner, Head of Regulatory and Compliance Group at Sadis & Goldberg LLP',
	  'legal-35' : 'Oliver Ciric',
	  'legal-36' : 'Partner at TA Advisory',
	  'legal-37' : 'Daniel G. Viola is a partner of <span class="ilegal-white">Sadis & Goldberg LLP</span> and the Head of its Regulatory and Compliance Group.  Mr. Viola has been active in the Blockchain and Virtual Currency verticals since 2014. He also served as a Senior Compliance Examiner for the <span class="ilegal-white">Northeast Regional Office of the SEC,</span> where he worked from 1992 through 1996',
	  'legal-37a' : 'During his tenure at the SEC, Mr. Viola worked on several compliance inspection projects and enforcement actions involving examinations of registered investment advisers, ensuring compliance with federal and state securities laws. Mr. Viola’s examination experience includes financial statement, performance advertising, and disclosure document reviews, as well as, analysis of investment adviser and hedge fund issues arising under ERISA and blue-sky laws. In late 2006 Mr.  Viola founded his own law firm and eventually merged it into Sadis & Goldberg’s law practice.',
	  'legal-38' : 'Experience in international jurisprudence for more than 20 years. Oliver graduated from Boston University of Law in 2006, majoring in banking and finance law, and the Geneva University of Law in 1998, specializing in "License and Law". Previous work experience:  Nationale Suisse Assurances, Matile Brosset Stickel-Cicurel & Gianninazzi, Poncet Turrettini Amaudruz Neyroud & Partners, <span class="ilegal-white">Akin Gump Strauss Hauer & Feld LLP</span> (formerly Hogan & Hartson LLP).',
	  'legal-38a' : 'Since June 2017 he has been a partner at <span class="ilegal-white">TA Advisory</span>. Mr. Ciric provides legal support for blockchain projects, and also advises on cooperation <span class="ilegal-white">with FINMA.</span><br>Languages: German, English, French, Portuguese, Russian, Serbian.',
	  'legal-39' : '<span class="ilegal-white-02">KPMG AG, Switzerland,</span> served as exclusive legal advisor to #MetaHash and its management in the evaluation of regulatory, tax and legal aspects in respect of the White Paper, which is released in preparation of a Coin offering (ICO)',
	  'legal-40' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">الورقة البيضاء<i class="icon icon_dowload"></i></a>',
	  'legal-41' : 'Martin Hess',
      'legal-42' : 'Partner at Wenger & Vieli AG',
	  'legal-43' : 'Martin Hess specializes in financial services and capital markets law, FinTech and the digitization of financial services. He is recognized by the Swiss Stock Exchange as an issuer representative. Martin Hess advises Swiss and foreign clients and represents them vis-à-vis supervisory authorities and in court.',
	  'legal-43a' : 'He is involved in the legal design of trading venues for digital assets, payment systems and securities settlement systems as well as central counterparties. He advises and represents clients on Initial Coin Offerings / Token Generating Events. Since 2001 Partner at Wenger & Vieli Ltd',
	

   //   'private-01' : 'Private Round',
   //   'private-form' : '<input type="hidden" name="form_subject" value="Private Round Application">',
   //   'private-03' : 'days',
   //   'private-04' : 'Private Round ends in',
   //   'private-05' : 'Private Round',
   //   'private-06' : 'The purpose of the Private Round is to verify the idea before the public launch',
   //   'private-07' : 'We hope to meet experts who are ready to participate in the discussion of the project before its public launch and, possibly, join the #MetaHashTeam.',
   //   'private-08' : '#MetaHash undertakes to inform all Private Round participants about terms of participation, their rights and obligations in connection with participation.',
   //   'private-09' : 'Private Round participants will be able to decide whether to remain in the project after the ICO.',
   //   'private-10' : 'Send an application to participate in the Private Round',
   //   'private-11' : 'We are not interested in the amount, but rather in your expertise. We want experts from different fields to participate in the Private Round.',
   //   'private-12' : 'Describe your expertise in cryptocurrencies. Are you ready to participate in discussion about the project?',
   //   'private-13' : 'Apply <i class="icon icon_link"></i>',
   //   'private-14' : 'Terms of Use',
   //   'private-15' : 'Privacy Policy',
   //   'private-16' : 'Private Round terms:',
   //   'private-17' : 'Do you want to participate in the Private Round or join the #MetaHashTeam?',
   //   'private-18' : 'Participation in the Private Round is public - the name or company name of the participant will be published',
   //   'private-19' : 'Private Round volume - <b>1,840 ETH</b>',
   //   'private-20' : 'The value of the #MHC - <b>0.001 ETH</b>',
   //   'private-21' : 'The volume of the Private Round is not enough to satisfy the requests of all comers',
   //   'private-22' : 'You can fill the application form before the end of the Private Round',
   //   'private-23' : 'At the end of the Private Round, the current #MetaHash team will decide on quotas for each of those wishing to participate',
   //   'private-24' : 'After the completion of the Private Round and the distribution of tasks between the current and new team members, the Pre-ICO will start',
   //   'private-25' : 'Private Round Application',
        'private-26' : 'أدخل الاسم',
        'private-27' : 'أدخل البريد الإلكتروني',
   //   'private-28' : 'Desired amount of participation (ETH)',
   //   'private-29' : 'Additional information about yourself',


   //   'timer-day-1' : 'days',
   //   'timer-day-2' : 'days',
   //   'timer-day-3' : 'days',
   //   'timer-hour-1' : 'hour',
   //   'timer-hour-2' : 'hours',
   //   'timer-hour-3' : 'hours',
   //   'timer-minute-1' : 'minute',
   //   'timer-minute-2' : 'minutes',
   //   'timer-minute-3' : 'minutes',
   //   'timer-second-1' : 'second',
   //   'timer-second-2' : 'seconds',
   //   'timer-second-3' : 'seconds',


    'form-sent-01' : 'شكرًا لك!',
    'form-sent-02' : 'تم تسجيل بياناتك بنجاح.',


      'faq-01' : 'الأسئلة المتداولة',
      'faq-02-00' : 'حول MetaHash#',
      'faq-02-01' : 'هل أنت كيان قانوني؟',
      'faq-02-02' : 'بدأت عملية تسجيل الكيانات القانونية في مصر. وعادة ما يستغرق الأمر وقتًا طويلاً للتوصل إلى اتفاق مع الحكومة المصرية.',
      'faq-02-03' : 'أين يمكنني فحص البرنامج متعدد السرعات MVP وشفرة المصدر المفتوح في MetaHash#؟',
      'faq-02-04' : 'تعمل شبكة TraceChain# المركزية حاليًا بمحفظة متعددة الأصول. سيتم إصدار شفرات المصدر لبروتوكول TraceChain# بعد إصدار برنامج الأمن العام ضد القراصنة والحصول على البراءة.',
      'faq-02-05' : 'ما هو الهدف العام من المنتج نفسه والعملة الرمزية؟',
      'faq-02-06' : 'يُستخدم MetaHashCoin# لتبادل المعاملات وتخزين البيانات ووظائف التطبيق. يمكنك أيضًا تبادل MHC# لإضافة عنوان عام لإدراج تطبيقك في دليل MetaApp# لشراء الإعلانات في الشبكة الإعلانية MetaGate# وغير ذلك الكثير من المميزات.',
      'faq-02-07' : 'ما هي قدرات سرعة البلوكتشين الخاصة بك؟ كيف يمكنك الوصول إلى مثل هذه النتيجة؟',
      'faq-02-08' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" class="link -link-small" target="_blank">الورقة البيضاء</a>حول قدرات البلوكتشين لدينا، يرجى مراجعة الورقة البيضاء.',
      'faq-02-09' : 'هل عملتك قابلة للتعدين؟ هل هناك أي فوائد للمُعدّنين؟',
      'faq-02-10' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" class="link -link-small" target="_blank">الورقة البيضاء</a>صيل حول التعدين، اقرأ الورقة البيضاء.',
      'faq-02-11' : 'ما نظام الإثبات الذي تستخدمه إثبات العمل (PoW) أو إثبات الحصة (PoS)؟',
      'faq-02-12' : 'يستخدم MetaHash# خوارزمية متوافقة مختلطة. يشمل هذا النظام متعدد لإثبات الحصة (POS) نتائج التصويت من عُقد خاصة بشبكة منفصلة.',


      'faq-03-00' : 'جولات العر ض الأولي للعملة (أ)/(ب) وشراء MHC#',
      'faq-03-01' : 'ما هي طرق الدفع التي تقبلونها؟',
      'faq-03-02' : 'نقبل إيثريوم فقط. يجب تبادل الأصول الرقمية الأخرى بإيثريوم أولاً.',
      'faq-03-03' : '',
      'faq-03-04' : '',
      'faq-03-05' : 'هل يمكنني المشاركة من منصة التبادل؟',
      'faq-03-06' : 'نعم، يمكنك. ولكننا نقبل إيثريوم فقط.',
      'faq-03-07' : '',
      'faq-03-08' : '',
      'faq-03-09' : 'متى تنتهي جولات العرض الأولي للعملة (أ)/(ب)؟',
      'faq-03-10' : 'تستمر جولة العرض الأولي للعملة (أ) حتى يتم الوصول إلى المبلغ المستهدف. تبدأ جولة العرض الأولي للعملة ب بعد إصدار المنتج الفعال الأساسي',
      'faq-03-11' : 'ما هي الشروط الخاصة بالمحفظة متعددة الأصول في MHC#؟',
      'faq-03-12' : 'محفظة MetaGate# متعددة الأصول هي منتج ذو شفرة مفتوحة المصدر. يتم تمويل استخدامه من أموال الإعلانات المعروضة واشتراكات منع الإعلانات',


      'faq-04-00' : 'MetaHashCoin# والعملاء المتوقعون',
      'faq-04-01' : 'ما هي الاختلافات العامة بين MetaHash# وأي موفر بلوكتشين آخر؟',
      'faq-04-02' : 'جميع المنافسين الحاليين إما بطيئين أو يتعاملون بنظام مركزي. يجب أن يكون الجيل القادم من البلوكتشين سريع ولامركزي تماما ويحتوي على معاملات رخيصة أيضًا. لا يوجد أي مشروع حالي (باستثناء MetaHash#) يوفر جميع هذه المتطلبات.',
      'faq-04-03' : 'هل يتم استخراج ERC20 ‏‏MHC#‏ على الرغم من العقد الذكي للإيثريوم؟',
      'faq-04-04' : '#MHC هي عملة منفصلة مستقلة يتم تشغيلها في سلسلة منفصلة. ومع ذلك، توجد بعض العقود المتطابقة في إيثريوم وMetaHash#. تسمح هذه العقود المتطابقة بترميز إجراء العملات الرمزية ERC20 في كلا الاتجاهين.',
      'faq-04-05' : 'ما هو إجمالي الإمدادات في العملات الرمزية؟',
      'faq-04-06' : 'سيتم إصدار ‏92,000,000‏ MHC# على مدى 10 سنوات. سيتم إصدار ‏92,000,000‏ MHC# في السنة الأولى.',
      'faq-04-07' : 'ما هي منصات التبادل التي ستتداول MetaHashCoins#؟',
      'faq-04-08' : 'سيتم الإعلان عن توافر العملة على منصات التبادل من خلال جميع قنوات MetaHash# الرسمية العامة. غير مسموح لنا بمشاركة هذه المعلومات مسبقًا.',
      'faq-04-09' : 'كم سيكون السعر المبدئي للعملة الرمزية MHC# بعد العرض الأولي للعملة بمجرد وصوله إلى السوق المفتوحة؟ وهل سيكون ذلك بعد سنة واحدة؟',
      'faq-04-10' : 'يتم تحديد تكلفة MetaHashCoin# وفق متطلبات السوق. تُستخدم MHC# لدفع الخدمات التالية: المعاملات وتخزين البيانات وتشغيل التطبيق وهكذا. ستؤثر هذه العوامل على تكلفة MHC#.',
      'faq-04-11' : 'متى يبدأ/ ينتهي بيع العملة الرمزية؟',
      'faq-04-12' : 'نحن نخطط لإنهاء جولة العرض الأولي للعملة (أ) في نهاية عام 2018. وسيبدأ الإصدار الرسمي لجولة العرض الأولي للعملة (ب) في الربع الأخير من عام 2018 أو في الربع الأول من عام 2019.',


      'faq-05-00' : 'عملية بيع MHC#',
      'faq-05-01' : 'هل هناك حد أدنى للمشاركة في MetaHash#؟',
      'faq-05-02' : 'نحن لا نضع أيّ حد أدنى. يمكنك أن تمتلك أي عدد تريده من العملات الرمزية.',
      'faq-05-03' : 'متى سيتم تقديم العملات الرمزية المميزة للمشاركين؟',
      'faq-05-04' : 'يتم توفير عملات MetaHash TestNet#  أو بديلها ERC20 عند الانتهاء من جولة العرض الأولي للعملة (ب)',
      'faq-05-05' : 'ماذا ستفعل بالعملات غير المباعة؟',
      'faq-05-06' : 'ستبقى جميع الأصول غير المباعة في شركة MetaHash#',
      'faq-05-07' : 'نقلت 0.07 إيثريوم إلى محفظتي في MetaHash#. كم عدد العملات الرمزية التي سأحصل عليها؟',
      'faq-05-08' : 'يمكنك استخدام الآلة الحاسبة الداخلية لدينا.',
      'faq-05-09' : 'كيف يمكنني شراء MHC# إذا لم يكن لدي أي أصول من العملات المشفرة؟',
      'faq-05-10' : 'لا يمكنك: عليك تحويل أموالك إلى إيثريوم أو بيتكوين. يمكنك استخدام أي منصة تبادل تشاء.',



      'faq-06-00' : 'أسئلة أخرى',
      'faq-06-01' : 'أنا مواطن صيني أو كوري، هل من القانوني المشاركة في التمويل الجماعي في العرض الأولي للعملة الخاص بـ MetaHash#؟',
      'faq-06-02' : 'مسموح لكل الجنسيات باستثناء: الولايات المتحدة الأمريكية وسنغافورة وجمهورية فيتنام الاشتراكية وجمهورية الصين الشعبية أو أن تكون مقيمًا في بلد يتم فرض الحظر والعقوبات الأمريكية فيه وهم إيران أو كوريا الشمالية أو سوريا أو السودان أو كوبا. مزيد من المعلومات حول الشروط الخاصة بنا لبيع العملات الرمزية.',
      'faq-06-03' : 'إذن باختصار، ما هو TraceChain#؟',
      'faq-06-04' : 'TraceChain# هو الجيل القادم من أنظمة البلوكتشين. وهو حل يقوم على خوارزمية توجيه مستقلة وذاتية المعالجة. يبدأ تشغيلها بسرعة 50,000 عملية في الثانية الواحدة (السرعة الأساسية من 100 ميجابايت للقناة) ويزيد بإضافة عدد معقول من القنوات عالية السرعة. هذه القنوات تشكل أساس شبكة MetaHash# ومصدر استقرارها.',
      'faq-06-05' : 'ما هو الحد الأقصى للتمويل/الحد الأدنى للتمويل؟',
      'faq-06-06' : 'يتم الوصول إلى الحد الأدنى للتمويل من خلال المؤسسين وإجراء الجولة الخاصة. الحد الأقصى للتمويل غير محدد',
      'faq-06-07' : 'أودعت 0.0067769 بيتكوين / إيثريوم، متى سيتم تحويلها إلى العملات الرمزية MHC#؟',
      'faq-06-08' : "يتم توفير العملات الرمزية لك بعد تلقي ستة تأكيدات على شبكة إثريوم وعُقـد MetaChains#. عادة ما يستغرق الأمر 6 ساعات للتحقق من صحة المعاملات من شبكات إيثريوم و بيتكوين. لذا، من فضلك لا تقلق إذا كنت لم تتلق العملات الخاصة بك في غضون 6 ساعات. أرسل إلينا تقريرًا وسنقوم بحل مشكلتك. إيداعك هو معاملة في حد ذاته. إذا حدثت المعاملة، فستُرسل إليك العملات.",
      'faq-06-09' : 'ما هي التواريخ الرسمية للجولة الخاصة وجولات العرض الأولي للعملة (أ)/(ب) وما إلى ذلك؟',
      'faq-06-10' : 'لم يتم بعد تحديد التواريخ الرسمية لفترات جولة العرض الأولي للعملة (أ) وجولة العرض الأولي للعملة (ب). سيتم الإعلان عنها من خلال قنواتنا العامة قريبًا. لا داعي للقلق، ستكونون أول من يعرف.',
      'faq-06-11' : 'هل تُعد MetaHash# فوركس بيتكوين أم إيثريوم؟',
      'faq-06-12' : 'MetaHash# لا تُعد فوركس إنها موفر بلوكتشين مستقل ولذلك هي أسرع بكثير وأكثر أمانًا.',


      'support-01' : 'هل لديك أية أسئلة؟ اتصل بنا!',
      'support-02' : 'تقديم',
      'support-03' : 'User question',
      'support-04' : 'أدخل الاسم',
      'support-05' : 'أدخل البريد الإلكتروني',
      'support-06' : 'السؤال',


      'prefooter-01' : 'انضم إلينا!',
      'prefooter-02' : 'فريق MetaHash#',
      'prefooter-03' : '<a href="#private-round" class="btn -default">شراء MHC#<i class="icon icon_link"></i></a>',
      'prefooter-04' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">تنزيل الورقة البيضاء<i class="icon icon_dowload"></i></a>',
      'prefooter-05' : '<a href="docs/MetaHash_OnePager_AR.pdf" target="_blank" class="btn -download">تنزيل المنشـور المكون من صفحة واحدة<i class="icon icon_dowload"></i></a>',
      'prefooter-06' : 'شارك في جولة ICO',
      'prefooter-07' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">الورقة البيضاء</a>',
      'prefooter-08' : '<a href="docs/MetaHash_OnePager_AR.pdf" target="_blank" class="btn -download float-right">المنشور المكون من صفحة واحدة</a>',


      'footer-01' : 'ما هي MetaHash#؟',
      'footer-02' : 'شراء MetaHashCoin# (‏MHC#)',
      'footer-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -footer-link">الورقة البيضاء</a>',
      'footer-04' : '<a href="docs/MetaHash_OnePager_AR.pdf" target="_blank" class="link -footer-link">المنشور المكون من صفحة واحدة</a>',
      'footer-05' : 'الأسئلة المتداولة',
      'footer-06' : '<a href="docs/MetaHash_TermsOfUse_EN.pdf" target="_blank" class="link -footer-link">شروط الاستخدام</a>',
      'footer-07' : '<a href="docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank" class="link -footer-link">سياسة الخصوصية</a>',
      'footer-08' : '<a href="docs/MetaHash_AntiSpam_EN.pdf" target="_blank" class="link -footer-link">سياسة مكافحة البريد الإلكتروني العشوائي</a>',
      'footer-09' : 'اتفاقية الاستشارات',
      'footer-10' : '<a href="docs/MetaHash_RiskDisclosureStatement_EN.pdf" target="_blank" class="link -footer-link">اتفاقية الإفصاح عن المخاطر</a>',
      'footer-11' : 'شبكات التواصل الاجتماعي والرسائل',
      'footer-12' : 'المنتديات',
      'footer-13' : 'الملاحظات على <a href="mailto:hello@metahash.org" class="link -link-small">hello@metahash.org</a>',
      'footer-14' : 'الدعم على <a href="mailto:support@metahash.org" class="link -link-small">support@metahash.org</a>',
      'footer-15' : 'الاستفسارات الصحفية <a href="mailto:support@metahash.org" class="link -link-small">press@metahash.org</a>',
      'footer-16' : 'مكتب الصحافة <a class="link -link-small">+7 926 671-67-08</a>',
	  'copyright' : 'حقوق الطبع والنشر © 2017-2018 MetaHash#. جميع الحقوق محفوظة',

      'mobile-menu-01' : '<a href="#whatis" class="link -link-white">ما هي MetaHash#؟</a>',
      'mobile-menu-02' : '<a href="#private-round" class="link -link-white">شراء MetaHashCoin# (‏MHC#)</a>',
      'mobile-menu-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -link-white">تنزيل الورقة البيضاء</a>',
      'mobile-menu-04' : '<a href="docs/MetaHash_OnePager_AR.pdf" target="_blank" class="link -link-white">تنزيل المنشـور المكون من صفحة واحدة</a>',
      'mobile-menu-05' : '<a href="#faq" class="link -link-white">الأسئلة المتداولة</a>',
      'mobile-menu-06' : '<a href="#support" class="link -link-white">الدعم</a>',
      'mobile-menu-07' : '<a href="#support" class="link -link-white">جهات الاتصال</a>',

	  'new-mobile-menu-01' : '<a href="#whatis" class="link -link-white --offcan">ما هي MetaHash#؟</a>',
	  'new-mobile-menu-02' : '<a href="#tracechain" class="link -link-white --offcan">#TraceChain</a>',
	  'new-mobile-menu-03' : '<a href="#metaapps" class="link -link-white --offcan">#MetaApps</a>',
	  'new-mobile-menu-04' : '<a href="#metagate" class="link -link-white --offcan">#MetaGate</a>',
	  'new-mobile-menu-05' : '<a href="#timemap" class="link -link-white --offcan">Roadmap</a>',
	  'new-mobile-menu-06' : '<a href="#advisors-and-consultants" class="link -link-white --offcan">Advisors & Consultants</a>',
	  'new-mobile-menu-07' : '<a href="#teambanner" class="link -link-white --offcan">The Team</a>',
	  'new-mobile-menu-08' : '<a href="#ico" class="link -link-white --offcan">جولة العرض الأولي للعملة (أ)</a>',
	  'new-mobile-menu-09' : '<a href="#faq" class="link -link-white --offcan">الأسئلة المتداولة</a>',
	  'new-mobile-menu-10' : '<a href="#support" class="link -link-white --offcan">اتصل بنا</a>',

      'promo-soc-01' : '<a href="https://t.me/metahash_ENG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
      'promo-soc-02' : '<a href="https://www.facebook.com/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
      'promo-soc-03' : '<a href="https://vk.com/metahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
      'promo-soc-04' : '<a href="https://twitter.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
      'promo-soc-05' : '<a href="https://instagram.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
      'promo-soc-06' : '<a href="https://www.youtube.com/channel/UCIkBIrd1q7JkLLj43KgG8zA" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">youtube.com</span><span class="icon -icon-big icon_youtube"></span></a>',
      'promo-soc-07' : '<a href="#" class="link-soc -tooltype"><span class="soc-tooltype">ID:MetaHash</span><span class="icon -icon-big icon_wechat"></span></a>',
      'promo-soc-08' : '<a href="https://open.kakao.com/o/gY5dUgG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">talk.com</span><span class="icon -icon-big icon_talk"></span></a>',
      'promo-soc-09' : '<a href="https://github.com/metahashorg" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
      'promo-soc-10' : '<a href="https://www.reddit.com/user/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">reddit.com</span><span class="icon -icon-big icon_reddit"></span></a>',
      'promo-soc-11' : '<a href="https://www.linkedin.com/company/27209614/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">in.com</span><span class="icon -icon-big icon_in"></span></a>',
      'promo-soc-12' : '<a href="https://medium.com/@themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">medium.com</span><span class="icon -icon-big icon_medium"></span></a>',
      'promo-soc-13' : '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitsmedia"></span></a>',
      'promo-soc-14' : '<a href="https://bitcointalk.org/index.php?action=profile;u=1253602" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',


      'promo-soc-mobile-01' : '<a href="https://t.me/metahash_ENG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
      'promo-soc-mobile-02' : '<a href="https://www.facebook.com/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
      'promo-soc-mobile-03' : '<a href="https://vk.com/metahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
      'promo-soc-mobile-04' : '<a href="https://twitter.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
      'promo-soc-mobile-05' : '<a href="https://instagram.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
      'promo-soc-mobile-06' : '<a href="https://github.com/metahashorg" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
      'promo-soc-mobile-07' : '<a href="https://www.linkedin.com/company/27209614/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">in.com</span><span class="icon -icon-big icon_in"></span></a>',
      'promo-soc-mobile-08' : '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="link-soc"><span class="icon -icon-big --icon-forum icon_bitsmedia" target="_blank"></span></a>',
      'promo-soc-mobile-09' : '<a href="https://bitcointalk.org/index.php?action=profile;u=1253602" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',

      'tg_button' : '<a href="https://t.me/metahash_ENG" target="_blank"><img class="telega-svg" style="margin-bottom: 40px;" src="img/telegram.svg" alt=""></a>',



      'private-close-01' : 'تم إغلاق الجولة الخاصة',
      'private-close-02' : 'انتهت بعدما زاد عدد المشتركين فيها عن أكـثر من 20 ضعفًا.',
      'private-close-03' : 'يسعدنا أن نتقدم بخالص الشكر لجميع المشاركين وندعو الجميع للانضمام إلينا لجولة العرض الأولي للعملة (أ).',
      'private-close-04' : 'تبدأ جولة العرض الأولي للعملة أ',
      'private-close-05' : 'الشهر المقرر للبدء',
      'private-close-06' : 'بداية جولة العرض الأولي للعملة (أ) قريبًا',
      'private-close-07' : 'لا تفوت البداية، تقدّم الآن',
      'private-close-08' : 'تقدّم الآن <i class="icon icon_link"></i>',
      'private-close-09' : 'تابعنا من خلال:',
      'private-close-10' : 'ميزات جولة العرض الأولي للعملة (أ):',
      'private-close-11' : '<b class="mob-bold">سيتم توزيع 9,200,000 MHC#</b> خلال جولة العرض الأولي للعملة (أ)',
      'private-close-12' : 'قيمة MHC# لجولة العرض الأولي للعملة (أ) تبلغ 0.0125 إثيريوم',
      'private-close-13' : 'يتم تقديم الطلبات التي تقل عن 50 إيثريوم (12500 MHC#) من مجموعة عامة محدود<b class="mob-bold">ة تجدد كل 4 ساعات. الأولوية حسب الأسبقية</b>',
      'private-close-14' : 'يتم تقديم الطلبات التي تزيد عن 50 إيثريوم من مجموعة منفصلة مخصصة بشكل فوري لترك مساحة للمشترين الصغار',
      'private-close-15' : '18 أبريل',
      'private-close-16' : 'أدخل البريد الإلكتروني',
      'private-close-17' : 'يمكن أن يتغير وفقًا للورقة البيضاء', 
      // 'private-close-18' : '<input id="private-close__terms-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__terms-check">I agree to </label><a href="docs/MetaHash_TermsOfUse_EN.pdf" target="_blank">Terms of Use</a>',
      // 'private-close-19' : '<input id="private-close__policy-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__policy-check">I agree to </label><a href="docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank">Privacy Policy</a> ',
      

      'private-close-18' : 'أوافق على ',
      'private-close-19' : 'أوافق على ',
      'private-close-25' : '<a href="docs/MetaHash_TermsOfUse_EN.pdf"  target="_blank">شروط الاستخدام</a>',
      'private-close-26' : '<a href="docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank">سياسة الخصوصية</a>',



      'private-close-20' : 'Application submitted',
      'private-close-21' : ', thank you for your interest in <b>#MetaHash</b> project. We will keep you informed about the <b>ICO Round A Start date</b>.',
      'private-close-22' : 'Dont miss a thing!',
      'private-close-23' : '<a href="https://t.me/metahash_ENG" target="_blank"  class="private-close__modal-content_tg-link" >Join our Telegram Channel<br> and stay updated</a>',
      'private-close-24' : '<a href="https://t.me/metahash_ENG" target="_blank" class="support-window__social-block_soc-link support-window__social-block_soc-link_tg"><img class="support-window__social-block_soc-img" src="img/popup/sub-tg.png" alt=""><span class="flag"><img class="support-window__social-block_flag-img" src="img/icons/flag-eng.png"></span></a>',



      
};

