"use strict";

window.arrLang = window.arrLang || {};

window.arrLang["cn"] = {

      'nav-link-01' : '#MetaHash是什么？',
      'nav-link-02' : '购买 #MHC',
      'nav-link-03' : '<a href="docs/MetaHash_WhitePaper_CN.pdf" target="_blank" class="link -link-white"><img src="img/icon_file.svg" class="icon_file"> 白皮书</a>',
      'nav-link-04' : '<a href="docs/MetaHash_OnePager_CN.pdf" target="_blank" class="link -link-white"><img src="img/icon_file.svg" class="icon_file"> 单页程序</a>',
      'nav-link-05' : '常见问题',
      'nav-link-06' : '支持',
	  'nav-link-07' : '联系我们',


      'promo-01' : '快速',
      'promo-02' : '验证时间低于3秒。性能超过50,000 TPS',
      'promo-03' : '安全',
      'promo-04' : '5种共识算法提供保护',
      'promo-05' : '去中心化式',
      'promo-06' : '任何人均可在#MetaHash网络内添加交易节点',


      'descr-01' : '基于区块链2.0',
      'descr-02' : '<span class="cripto-title -title-part01 --eng">虚拟</span><span class="cripto-title -title-part02 --eng">货币</span>',
      'descr-03' : 'and decentralized ecosystem',
      'descr-04' : '基于区块链2.0',


      'promo-appint-01' : '<span class="part-name">&nbsp;</span>储存',
      'promo-appint-03' : '区块链内的任何信息均进行4k加密保护和多重签名',
      'promo-appint-04' : '<a href="#private-round" class="btn -default">ICO A轮<i class="icon icon_link"></i></a>',
      'promo-appint-05' : '交易<span class="part-name">&nbsp;</span>',
      'promo-appint-06' : '#MetaHash网络内外部确认最多只需3秒',
      'promo-appint-07' : '<a href="docs/MetaHash_WhitePaper_CN.pdf" target="_blank" class="btn -download">下载白皮书<i class="icon icon_dowload"></i></a>',
      'promo-appint-08' : '任意资产交换<span class="part-name">&nbsp;</span>',
      'promo-appint-10' : '#MetaGate钱包内的任何数字资产在全部的交换服务中均使用ERC20令牌',
      'promo-appint-11' : '<a href="docs/MetaHash_OnePager_CN.pdf" target="_blank" class="btn -download">下载单页程序<i class="icon icon_dowload"></i></a>',
      'promo-appint-12' : '<a href="#private-round" class="btn -default -mega" >ICO A轮</a>',
      'promo-appint-13' : '<a href="docs/MetaHash_WhitePaper_CN.pdf" target="_blank" class="btn -download">白皮书</a>',
      'promo-appint-14' : '<a href="docs/MetaHash_OnePager_CN.pdf" target="_blank" class="btn -download float-right">单页程序</a>',
      'promo-appint-15' : 'Download #MetaGate client',

      'whatis-01' : '#MetaHash是什么？',
      'whatis-02' : '#MetaHash是以区块链2.0数字化资产共享技术为基础的新一代网络，能够作为平台实时创建和管理去中心化的应用和服务。',
      'whatis-03' : '系统的四大组成部分:',
      'whatis-04' : '#TraceChain',
      'whatis-05' : '最快速最安全的区块链',
      'whatis-06' : '每日交易量超过50亿，交易验证时间不超过3秒',
      'whatis-07' : '关于#TraceChain',
      'whatis-08' : '#MetaApps',
      'whatis-09' : '新一代的智能合约',
      'whatis-10' : '去中心化式实时应用，操作方式类似于普通网络服务，使用各种编程语言开发，包括C++、PHP、Solidity 等',
      'whatis-11' : '关于#MetaApps',
      'whatis-12' : '#MetaGate',
      'whatis-13' : '去中心化式网络',
      'whatis-14' : "去中心化式应用目录和不会导致电脑过载的多资产钱包",
      'whatis-15' : '关于#MetaGate',
      'whatis-16' : '#MetaHashCoin',
      'whatis-17' : '#MetaHash网络交换资产',
      'whatis-18' : '#MetaHashCoin(#MHC)用于保证网络的可靠性，交换服务并对其自筹资金和发展进行管理',
      'whatis-19' : '关于#MHC',


      'tracechain-01' : '#TraceChain',
      'tracechain-02' : '快速而安全的区块链2.0',
      'tracechain-03' : '超过',
      'tracechain-04' : '100,000',
      'tracechain-05' : '每个节点每秒交易',
      'tracechain-06' : '<a href="docs/MetaHash_WhitePaper_CN.pdf" target="_blank" class="btn -download lang" >下载白皮书<i class="icon icon_dowload"></i></a>',
    //  'tracechain-07' : 'to approve a transaction',
    //  'tracechain-08' : 'transactions per day',
    //  'tracechain-09' : 'stages of consensus for verification',
    //  'tracechain-10' : '#MetaHash block anchors <span class="blue">in Bitcoin and Ethereum networks</span>',
      'tracechain-11' : '<img class="tracechain-svg" src="img/graphical/tracechain-cn.svg" alt="">',


      'speed-work-01' : '史无前例的速度和去中心化的#TraceChain网络使#MetaHash成为区块链的旗舰',
      'speed-work-02' : '在#MetaHash网络内完成任意数量的交易',
      'speed-work-03' : '交易成本低于任何常规区块链',
      'speed-work-04' : '#TraceChain能够实现去中心化项目的合理数据存储成本',
      'speed-work-05' : '任何资产均可在 #MetaHashCoin内实现语法分析，从而实现在#MetaHash、Ethereum和其他网络内流通',


      'speeds-01' : '如何实现如此迅速？',
      'speeds-02' : '交易在外半径开始，然后通过最快速路径进入核心网络。',
      'speeds-03' : '每个阶段均会批准在进入核心的交易。',
      'speeds-04' : '核心网络的最快速节点实现相互之间的交易同步。',
      'speeds-05' : '核心网络将钱包的平衡返回至网络，通过网络确认计算的准确性。',
      'speeds-06' : '备份数据进入经典的区块链，验证网络的完整性。',
      'speeds-07' : '锚点（来自最长供应链的哈希）储存在比特币、以太坊和其他网络上。',
      'speeds-08' : '存储在#MetaHash内的信息无法被损坏或者修改。如需修改，则必须成功攻击#MetaHash网络，以及比特币、Ethereum和其他网络。',
      'speeds-09' : '如需了解更多技术信息，请查看我们的白皮书',
      'speeds-10' : '<a href="docs/MetaHash_WhitePaper_CN.pdf" target="_blank" class="btn -download">下载白皮书<i class="icon icon_dowload"></i></a>',


      'metaapps-01' : '#MetaApps',
      'metaapps-02' : '针对智能实时应用提供云服务',
      'metaapps-03' : '#MetaApps是智能合约的升级，能够对任何服务进行去中心化化。这些独立的编程能够永远存在，而不属于任何人。他们将会按照编程精准工作，而不会受到第三方的影响。',
      'metaapps-04' : '#MetaApps优势',
      'metaapps-05' : '实时运行',
      'metaapps-06' : '与常规网络服务和应用同样快速',
      'metaapps-07' : '任何GUI设计',
      'metaapps-08' : '能够看起来就像普通的应用或者网页',
      'metaapps-09' : '安全',
      'metaapps-10' : '没有人能够绕过更新规则来改变应用的行为',
      'metaapps-11' : '编程以及系统的图片上传至网络并能够在多个电脑上自动启动。',
      'metaapps-12' : '使用包括C++、PHP、Solidity 等编程语言制作。',
      'metaapps-13' : '全面支持智能合约功能，能够适应来自任何区块链或网络的任何数据。',


      'metagate-01' : '#MetaGate',
      'metagate-02' : '去中心化式网络的网关',
      'metagate-03' : '#MetaGate是开源项目，所以全部的开发者都可以将其部分代码嵌入到他们的应用或者浏览器。',
      'metagate-04' : '多资产钱包',
      'metagate-05' : '钱包支持轻量模式，无需下载全部区块链。数字来自去中心化网络的不同来源，并由用户检查。所有已使用的来自全部区块链的私人密钥将只会由用户储存。',
      'metagate-06' : '应用目录',
      'metagate-07' : '去中心化式应用以及能够与之匹配的浏览器的目录。任何基于#MetaHash的去中心化式应用均可以访问，不只是标准应用域名，还可以通过#MetaGate或者被分配至独立程序。',
      'metagate-08' : '<a href="docs/MetaHash_WhitePaper_CN.pdf" target="_blank" class="btn -download">下载白皮书<i class="icon icon_dowload"></i></a>',
	  'metagate-download-button' : 'Download #Metahash',

      'metahashcoin-01' : '#MetaHashCoin (#MHC)',
      'metahashcoin-02' : '#MetaHash 财务模式',
      'metahashcoin-03' : '#MetaHash是一种在其基因代码中嵌入自我发展过程的自筹资金系统。',
      'metahashcoin-04' : '#MetaHashCoin用于支付：',
      'metahashcoin-05' : '交易',
      'metahashcoin-06' : '以合理的固定价格即时和可靠地交易任何资产。',
      'metahashcoin-07' : '数据储存',
      'metahashcoin-08' : '适用于需要储存数据，但是缺少传统区块链系统中的速度和数据量的应用。',
      'metahashcoin-09' : '应用操作',
      'metahashcoin-10' : '任何去中心化化应用或者智能合约需要资源才能进行部署，包括#MetaHash网络本身。',
      'metahashcoin-11' : '其他服务',
      'metahashcoin-12' : '用于列在#MetaApps，以及在#MetaGate和其他资源内公共地址的支付。',
      'metahashcoin-13' : '<a href="#private-round" class="btn -default btn-mobile">购买#MHC<i class="icon icon_link"></i></a>',


      'minig-01' : '#MHC的挖掘和锻造',
      'minig-02' : '服务器',
      'minig-03' : '用于交易网络、用于去中心化化应用操作所使用的免费资源。',
      'minig-04' : '#MetaGate钱包',
      'minig-05' : '在完整模式中，节点主要用于数据储存以及Torrent节点。',
      'minig-06' : '#MetaHashCoins',
      'minig-07' : '提高对于PoW+ PoS组件混合投票模型共识的安全性。',
      'minig-08' : '来自服务销售的#MHC主要用于：',
      'minig-09' : '培训以#MetaHash为基础建设项目的开发者',
      'minig-10' : '提高项目质量',
      'minig-11' : '推广#MetaHash',
      'minig-12' : '向#MetaHashCoins的所有者付款以获得共同支持',
      'minig-13' : '向服务器和计算机所有者支付',


      'compare-01' : '#MetaHash优势',
      'compare-02' : '在搜索能够制作去中心化式和同步电路，从而能够处理这个世界所需数据量的项目，但是最终失败之后，我们决定制作#MetaHash。',
      'compare-03' : '主要区块链系统的对比表',
      'compare-04' : '交易批准时间',
      'compare-05' : '每秒交易数（TPS）',
      'compare-06' : '去中心化程度',
      'compare-07' : '比特币',
      'compare-08' : '10分钟',
      'compare-09' : '最高12',
      'compare-10' : '高',
      'compare-11' : 'Ethereum',
      'compare-12' : '15秒',
      'compare-13' : '最高30',
      'compare-14' : '高',
    //  'compare-15' : 'Plasma',
    //  'compare-16' : '15 seconds',
    //  'compare-17' : 'up to 30',
    //  'compare-18' : 'high',
      'compare-19' : 'EOS',
      'compare-20' : '5秒',
      'compare-21' : '从1,000到数百万',
      'compare-22' : '最低',
      'compare-23' : '#MetaHash',
      'compare-24' : '最高3秒',
      'compare-25' : '从50,000到数百万',
      'compare-26' : '高',
      'compare-27' : '<a href="docs/MetaHash_WhitePaper_CN.pdf" target="_blank" class="btn -download">下载白皮书<i class="icon icon_dowload"></i></a>',


      'timemap-01' : '路线图',
      'timemap-02' : '这一项目的技术部分是以AdSniper的成绩为基础，创立于2012年至2017年，集中在广告技术领域。',
      'timemap-03' : '我们收到了来自很多公司对于区块链技术应用的请求，了解到当前技术不能满足这一类系统的要求。因此，在2016年，我们开始研发我们自己的协议 #TraceChain。',
      'timemap-04' : '2017年，我们推出了#TraceChain协议的alpha和beta版本，并与国际营销和企业发展领域最强大的企业和人员联手。',
      'timemap-05' : '2012-2016',
      'timemap-06' : 'A network library for receiving signals, working on C++ and capable of simultaneously receiving and sending more than 100,000 requests per second to one inexpensive standard server',
      'timemap-07' : 'A network library for synchronizing signals within a cluster that manages gigantic data flows between cluster machines.',
      'timemap-08' : 'A machine learning system that decides in 40 milliseconds to respond to a signal taking into account multifactorial interrelationships.',
      'timemap-09' : 'Own analogue of Hadoop’s for similar systems in C ++ for distributed processing of large data.',
      'timemap-11' : '2017',
      'timemap-12' : 'Development of #TraceChain protocol (Alpha version)',
      'timemap-13' : 'Development of #TraceChain protocol (Beta version)',
      'timemap-14' : '<b>AdNow</b> team joins us',
      'timemap-15' : '<b>Agranovsky IT</b> team joins us',
      'timemap-16' : 'Formation of <b>Business Development team</b>',
      'timemap-17' : 'Formation of <b>Operational Team</b>',
      'timemap-18' : '2018',


      'timemap-19' : '#MetaHash website official launch',
      'timemap-20' : 'Start of the Operational Team office construction',
      'timemap-21' : 'Onboarding of experts and advisors',
      'timemap-22' : 'Development of #MetaGate (v.1.0). Multi-asset wallet featuring the ability to transfer #MetaHashCoins between wallets on multiple servers that stores data on transactions between crypto wallets.',
      'timemap-23' : 'Development of #TraceChain (v.1.0)',
      'timemap-23a': 'Development of #TraceChain (v.2.0). #TraceChain data download API',
      'timemap-24' : 'Development of #MetaICO (v.1.0). The ICO interface on the #MetaHash platform that accepts assets from various blockchains (Bitcoin and Ethereum), distributes tokens in the #MetaHash network and carries out multichain transactions, including ERC20 in the Ethereum network',
      'timemap-25' : 'Development of #MetaChains (v.1.0). Converting #MetaHashCoins to ERC20 and withdrawing them to the Ethereum network so that #MHC holders can choose which network to use and automatically convert ERC20 tokens into #MetaHashCoins',

      'timemap-26' : 'Development of #MetaApps (v.1.0). Application Platform',
      'timemap-27' : 'Testnet data download API',
      'timemap-28' : 'Opening of the Operational Team office',


      'timemap-29' : 'ICO Round A scheduled start',
      'timemap-30' : 'Development of #MetaChains (v.2.0). API featuring transaction history and balance  of wallets associated with different blockchain platforms. Decentralized application containing information about transactions in the Ethereum and Bitcoin networks which is necessary to provide blockchain interoperability in #MetaApps',
      'timemap-31' : 'Release of <b>#MetaGate (v.2.0)</b>. Encrypted messenger for public notifications and messaging between wallets',
      'timemap-32' : 'Release of <b>#TraceChain (v.3.0)</b>. Peer nodes that connect to TestNet to be installed on any server',
      'timemap-33' : '#TraceChain (v.4.0). Network core performance testing service (1,000,000+ transactions per second)',
      'timemap-34' : '#MetaICO (v.2.0). Interface for creating tokens inside the network #MetaHash',
      'timemap-35' : '#MetaICO (v.3.0). Release of ICO project platform at #MetaHash.',
      'timemap-36' : '#TraceChain (v.4.0). Voting functions in the #MetaHash network',
      'timemap-37' : '#TraceChain (v.5.0). AI managing the routing of signals between nodes for providing maximum speed of #MetaHash block creation and bandwidth and 100 test nodes in different geographical locations for testing node interaction',

      'timemap-38' : '#MetaICO (v.4.0). Release of the #MetaToken application, tokenization of ETH, ERC20, Bitcoin to #MetaHashCoin for use in the #MetaHash network',
      'timemap-39' : '#TraceChain (v.6.0). #MetaStorage, service for decentralized applications',
      'timemap-40' : '#MetaApps (v.2.0). The platform for self-deployment of third-party decentralized applications',
      'timemap-41' : '#MetaGate (v.3.0). Final release of #MetaGate wallet for Mac/Win/Unix/Android/iOS with #MetaApps catalogue',


      'timemap-42' : '<b>#TraceChain (v.7.0). Start of forging </b>',
      'timemap-43' : 'ICO B轮开始或者经过恰当安排并规范的加密交易的上市协议总结',
      'timemap-44' : '宣布进一步规划',


      'timemap-45' : '大量的安全测试',
      'timemap-46' : '源代码在测试完成后发布',
      'timemap-47' : '完全去中心化系统的推出',
      
      'timemap-100' : '显示更多',
	  'timemap-101' : '隐藏活动',
	  'timemap-102' : '其他活动',

      'teambanner-01' : '我们的团队',
      'teambanner-02' : '#MetaHash是一个开放结构的团队，欢迎所有的个人和企业。',
      'teambanner-03' : '如果您觉得可以提供帮助，希望加入我们团队，请<a class="team-write" href="mailto:hello@metahash.org">联系我们</a>。',
      'teambanner-04' : '<a href="#private-round" class="btn -default">ICO A轮<i class="icon icon_link"></i></a>',
      'teambanner-05' : '如果您觉得可以提供帮助，希望加入我们团队，请<a class="team-write" href="mailto:hello@metahash.org">联系我们</a>。',
      'teambanner-06' : 'ICO A轮',
      'teambanner-07' : '<img src="img/graphical/People_CN@3x.svg" alt="">',

      'team-hidden-01' : '为了项目的利益，该团队的其他成员的名字会被公布',

      'team-dev-01' : 'Gleb Nikitin',
      'team-dev-02' : 'Oleg Romanenko',
      'team-dev-03' : 'CSA，AdSniper实时服务架构师，AlfaBank在线银行系统分析师。能够在1个节点每秒处理超过1百万请求的高负荷网络库的创始人。',
      'team-dev-04' : 'Mikhail Zarutskiy',
      'team-dev-05' : 'CTO，AI、大数据和实时服务团队负责人，打造了能够将神经网络计算和其他机器学习算法相结合，实时处理数以百万计请求的Razoom AI。',
      'team-dev-06' : 'Sergey Raylyan',
      'team-dev-07' : 'CIO，规划和调整来自AdSniper技术堆栈的不同技术和界面的实施。',
      'team-dev-08' : '29名员工 AdSniper <i class="icon icon_link"></i>',
      'team-dev-09' : '在过去的十年中，该公司创建了高负载的广告网络。公司自有的大数据处理器，将服务PB级数据，快速NoSQL和SQL数据库、人工智能系统以及C++库进行整合，打造高度繁忙的广告服务，处理来自整个网络的广告请求。',
      'team-key-staff' : '核心成员',


      'team-mark-01' : 'Vladimir Bashkin',
      'team-mark-02' : '一个每天拥有10次展示的广告网络，是全球在全部广告网络购买广告的最具实力的团队之一，员工包括翻译员和广告专员，在本地市场任职。',
      'team-mark-03' : '89名员工 AdNow <i class="icon icon_link"></i>',
      'team-mark-04' : 'Artem Kravchenko',
      'team-mark-05' : '活动总监 - 公共关系总监。 AdDays数字活动首席执行官。Bitcomo网盟活动总监',
      'team-mark-06' : 'Daria Baranova',
      'team-mark-07' : '联盟总监 - AdNow经销商销售总监。莫斯科办公室董事。',
      'team-mark-08' : 'Pham Thành Trung',
      'team-mark-09' : '广告商部门负责人，AdNow亚洲区销售部门负责人。AdNow销售和业务发展经理',


      'team-fin-01' : 'Anton Agranovsky',
      'team-fin-02' : 'Agranovsky IT - 投资公司，投资IT初创公司，陪伴公司从起步成长，直至上市。创始人 Anton Agronovsky 是IT公司组建和发展领域的投资人、专家和意见领袖。还是Plastic Media以及SMX Communications的董事会成员。在2008-2017年间，担任Destiny Development公司的创始人兼总裁，公司是俄罗斯互联网市场最早的游戏公司之一，因独立研发和本地化而知名。 <br />&nbsp;<br /><a href="https://goo.gl/fJVjfK" class="link -link-small" target="_blank">福布斯杂志捐助人</a>',
      'team-fin-03' : '11名员工  Agranovsky IT <i class="icon icon_link"></i>',
      'team-fin-04' : 'Gennady Yakunin',
      'team-fin-05' : '首席执行官 - 控股公司会计业务。在IT和游戏项目拥有超过10年的经验',
      'team-fin-06' : 'Svetlana Rudenok',
      'team-fin-07' : '代理首席执行官 - 风险评估专家，在IT和游戏行业新项目和活跃项目的审计方面拥有超过10年的经验',
      'team-fin-08' : 'Andrey Korostelev',
      'team-fin-09' : 'CFO - 在IT和游戏项目拥有超过10年的财务管理经验，是社交和慈善项目的积极支持者',


      'team-oper-01' : 'Dmitry Ushakov',
      'team-oper-02' : '<span style="color:#ffffff;">COO - 项目总经理</span><br />Game Sight和其他IT初创公司多用户项目运营管理领域拥有超过11年的经验',
      'team-oper-03' : 'Michaił Iwanow',
      'team-oper-04' : '<span style="color:#ffffff;">艺术总监</span><br/>在视觉和产品设计方面拥有超过16年的经验。在RUSNANO、索尼、佳能、尼康等其他公司负责多个项目',
      'team-oper-05' : 'Zhibo Fan',
      'team-oper-06' : '<span style="color:#ffffff;">亚洲区商务合伙人</span><br/>Game.ru 游戏平台的创始人，以及INFIPLAY游戏发行商',
      'team-oper-07' : 'Alexander Zhigarenko',
      'team-oper-08' : '<span style="color:#ffffff;">俄罗斯CBDO，CIS</span><br/>在Destiny.Games公司以及游戏行业拥有超过10年的出版，运营和业务开发经验',
      'team-oper-09' : 'Eugenia Sigacheva',
      'team-oper-10' : '<span style="color:#ffffff;">公共事务合作伙伴</span><br/>在国际营销和公共关系领域，以及IT和创新成果方面拥有超过18年的经验，Eugenia 是机器人Sophia背后的知名国际团队以及IHEART平台的CEO和创始人。',
      'team-oper-11' : 'Andrey Akimov',
      'team-oper-12' : '<span style="color:#ffffff;">Chief Communication Officer</span><br/>More than 15 years in marketing and PR in gaming, entertainment, and IT business. Former head of PR and marketing at My.com, Mail.Ru Group, Game Insight, and other companies.',
      'team-oper-00' : '17名员工 运营团队 <i class="icon icon_link"></i>',


      //'legal-01' : '法律支持',
      //'legal-02' : 'Anastasia Pichugina',
      //'legal-03' : 'ANP法律管理合作伙伴 <a href="https://www.facebook.com/people/Anastasia-Pichugina/1520204010" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
      //'legal-04' : 'Ekaterina Myznikova',
      //'legal-05' : '资深律师 - 区块链项目律师事务所总监。成功领导多个ICO项目，是多次大会的参与者和主讲人。',
      //'legal-06' : 'Maxim Mekhriakov',
      //'legal-07' : '资深律师 - ANP律师事务所商业事务总监，主攻商业和投资交易的法律支持。',
      //'legal-08' : 'Anna Shevchenko',
      //'legal-09' : '律师 - 知识产权领域俄国和外资公司的法律支持，包括商标和专利的注册。',
      //'legal-10' : '国际法和俄罗斯法律的专家。我们的律师们均毕业于俄国和海外的知名法律院校。管理合作伙伴Anastasia在俄国和海外法律方面拥有独特的经验和知识，是多个IT、FMCG领域外资公司值得信任的法律代表。Anastasia成功在俄国法庭成功代表了多家俄国公司。',
      //'legal-11' : '<a href="docs/MetaHash_LegalOpinion_EN.pdf" target="_blank">下载法律意见<i class="icon icon_link"></i></a>',
      //'legal-title' : 'Legal Department',

    //'legal-14' : 'Maria Agranovskaya',
    //'legal-15' : 'Chief Legal Coordinator <a href="https://www.facebook.com/magranovskaya" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a> <a href="https://www.linkedin.com/in/maria-agranovskaya-151334/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
    //'legal-16' : '<span>Attorney at Law with 20+ years of experience. Started working with cryptocurrency issues back in 2010. MGIMO MID of Russia (International Law), studied in Germany and Holland. 8,5 years - running a multifamily office, worked on various cross-border transactions, investments, asset management, deal and corporate structuring in various jurisdictions, M&A, international taxation and other matters.</span><span>Areas: fintech, finance, telecom, banking, energy, pharmaceuticals, real estate and other sectors.</span><span>2007: setup of GRAD Attorney Bar (managing partner,  30+ Russian and foreign lawyers)</span><span>Substantially engaged in blockchain technology, ICO (TGE) related projects, trading and finance regulations, funds and financial activity.</span><span>Speaks English, German, French, Italian, </span>',
	 
	  'legal-more' : '阅读更多',
	  'legal-less' : '隐藏活动',
	  'legal-17' : 'Andrey Mironov <a href="http://www.linkedin.com/in/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a> <a href="https://www.facebook.com/" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
	  'legal-18' : 'Chief of Legal Department',
	  'legal-19' : 'Graduated MGIMO in 2000 at the international law faculty. Legal practice in the field of new technologies, media and intellectual property for more than 15 years.',
	  'legal-19a' : 'He worked at the Art. Lebedev Studio, Odnoklassniki, the Russian office of Myspace, on the channels MTV, Discovery, Amedia and the online cinema Amediateka. Helped to develop the EKSMO publishing house, the Fox TV channel. Expert at the Russian Association of Electronic Communications (RAEC).<br>Secondary Education: Consultant Psychologist',
	  'legal-20' : 'Maria Agranovskaya',
	  'legal-21' : 'Chief Legal Coordinator',
	  'legal-22' : 'Attorney at Law with 20+ years of experience. Started working with cryptocurrency issues back in 2010.',
	  'legal-22a' : 'MGIMO MID of Russia (International Law), studied in Germany and Holland. 8,5 years - running a multifamily office, worked on various cross-border transactions, investments, asset management, deal and corporate structuring in various jurisdictions, M&A, international taxation and other matters. Areas: fintech, finance, telecom, banking, energy, pharmaceuticals, real estate and other sectors. 2007: setup of GRAD Attorney Bar (managing partner,  30+ Russian and foreign lawyers). Substantially engaged in blockchain technology, ICO (TGE) related projects, trading and finance regulations, funds and financial activity. Speaks English, German, French, Italian,  Spanish.',
	  'legal-23' : 'Katya Fisher',
	  'legal-24' : 'Partner, Principal at The Law Office of Katya Yoffe PLLC',
	  'legal-25' : 'Katya Yoffe (née Fisher) is an attorney focusing on general corporate law, cross-border transactions and business immigration.',
	  'legal-25a' : 'Katya represents various prominent companies and startups doing business in the United States as well as celebrity and HNW individuals. Katya has been selected to Super Lawyers as a “Rising Star” in 2014, 2015, 2016, 2017 and 2018. <br>Katya is a graduate of New York University, the Benjamin N. Cardozo School of Law and a former Howard M. Squadron Fellow in International Media Law & Policy at the University of Oxford and Center for Global Communication Studies, University of Pennsylvania. She is admitted to practice in New York and before the United States Tax Court.',
	  'legal-26' : 'Anastasia Pichugina',
	  'legal-27' : 'ANP Law Managing Partner ',
	  'legal-28' : 'Managing partner Anastasia has a unique experience and knowledge in Russian and foreign law, is a trusted legal representative of several foreign companies.',
	  'legal-29' : 'Ekaterina Myznikova',
	  'legal-30' : '资深律师',
	  'legal-31' : '区块链项目律师事务所总监。成功领导多个ICO项目，是多次大会的参与者和主讲人。',
	  'legal-32' : 'International Legal Support',
	  'legal-33' : 'Daniel G. Viola',
	  'legal-34' : 'Partner, Head of Regulatory and Compliance Group at Sadis & Goldberg LLP',
	  'legal-35' : 'Oliver Ciric',
	  'legal-36' : 'Partner at TA Advisory',
	  'legal-37' : 'Daniel G. Viola is a partner of <span class="ilegal-white">Sadis & Goldberg LLP</span> and the Head of its Regulatory and Compliance Group.  Mr. Viola has been active in the Blockchain and Virtual Currency verticals since 2014. He also served as a Senior Compliance Examiner for the <span class="ilegal-white">Northeast Regional Office of the SEC,</span> where he worked from 1992 through 1996',
	  'legal-37a' : 'During his tenure at the SEC, Mr. Viola worked on several compliance inspection projects and enforcement actions involving examinations of registered investment advisers, ensuring compliance with federal and state securities laws. Mr. Viola’s examination experience includes financial statement, performance advertising, and disclosure document reviews, as well as, analysis of investment adviser and hedge fund issues arising under ERISA and blue-sky laws. In late 2006 Mr.  Viola founded his own law firm and eventually merged it into Sadis & Goldberg’s law practice.',
	  'legal-38' : 'Experience in international jurisprudence for more than 20 years. Oliver graduated from Boston University of Law in 2006, majoring in banking and finance law, and the Geneva University of Law in 1998, specializing in "License and Law". Previous work experience:  Nationale Suisse Assurances, Matile Brosset Stickel-Cicurel & Gianninazzi, Poncet Turrettini Amaudruz Neyroud & Partners, <span class="ilegal-white">Akin Gump Strauss Hauer & Feld LLP</span> (formerly Hogan & Hartson LLP).',
	  'legal-38a' : 'Since June 2017 he has been a partner at <span class="ilegal-white">TA Advisory</span>. Mr. Ciric provides legal support for blockchain projects, and also advises on cooperation <span class="ilegal-white">with FINMA.</span><br>Languages: German, English, French, Portuguese, Russian, Serbian.',
	  'legal-39' : '<span class="ilegal-white-02">KPMG AG, Switzerland,</span> served as exclusive legal advisor to #MetaHash and its management in the evaluation of regulatory, tax and legal aspects in respect of the White Paper, which is released in preparation of a Coin offering (ICO)',
	  'legal-40' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">ICO A轮<i class="icon icon_dowload"></i></a>',
	  'legal-41' : 'Martin Hess',
      'legal-42' : 'Partner at Wenger & Vieli AG',
	  'legal-43' : 'Martin Hess specializes in financial services and capital markets law, FinTech and the digitization of financial services. He is recognized by the Swiss Stock Exchange as an issuer representative. Martin Hess advises Swiss and foreign clients and represents them vis-à-vis supervisory authorities and in court.',
	  'legal-43a' : 'He is involved in the legal design of trading venues for digital assets, payment systems and securities settlement systems as well as central counterparties. He advises and represents clients on Initial Coin Offerings / Token Generating Events. Since 2001 Partner at Wenger & Vieli Ltd',


      'private-01' : 'Private Round',
      'private-form' : '<input type="hidden" name="form_subject" value="Private Round Application">',
      'private-03' : 'days',
      'private-04' : 'Private Round ends in',
      'private-05' : 'Private Round',
      'private-06' : 'The purpose of the Private Round is to verify the idea before the public launch',
      'private-07' : 'We hope to meet experts who are ready to participate in the discussion of the project before its public launch and, possibly, join the #MetaHashTeam.',
      'private-08' : '#MetaHash undertakes to inform all Private Round participants about terms of participation, their rights and obligations in connection with participation.',
      'private-09' : 'Private Round participants will be able to decide whether to remain in the project after the ICO.',
      'private-10' : 'Send an application to participate in the Private Round',
      'private-11' : 'We are not interested in the amount, but rather in your expertise. We want experts from different fields to participate in the Private Round.',
      'private-12' : 'Describe your expertise in cryptocurrencies. Are you ready to participate in discussion about the project?',
      'private-13' : 'Apply <i class="icon icon_link"></i>',
      'private-14' : 'Terms of Use',
      'private-15' : 'Privacy Policy',
      'private-16' : 'Private Round terms:',
      'private-17' : 'Do you want to participate in the Private Round or join the #MetaHashTeam?',
      'private-18' : 'Participation in the Private Round is public - the name or company name of the participant will be published',
      'private-19' : 'Private Round volume - <b>1,840 ETH</b>',
      'private-20' : 'The value of the #MHC - <b>0.001 ETH</b>',
      'private-21' : 'The volume of the Private Round is not enough to satisfy the requests of all comers',
      'private-22' : 'You can fill the application form before the end of the Private Round',
      'private-23' : 'At the end of the Private Round, the current #MetaHash team will decide on quotas for each of those wishing to participate',
      'private-24' : 'After the completion of the Private Round and the distribution of tasks between the current and new team members, the ICO A轮 will start',
      'private-25' : 'Private Round Application',
      'private-26' : 'Enter your name',
      'private-27' : 'Enter your e-mail',
      'private-28' : 'Desired amount of participation (ETH)',
      'private-29' : 'Additional information about yourself',


      'timer-day-1' : 'days',
      'timer-day-2' : 'days',
      'timer-day-3' : 'days',
      'timer-hour-1' : 'hour',
      'timer-hour-2' : 'hours',
      'timer-hour-3' : 'hours',
      'timer-minute-1' : 'minute',
      'timer-minute-2' : 'minutes',
      'timer-minute-3' : 'minutes',
      'timer-second-1' : 'second',
      'timer-second-2' : 'seconds',
      'timer-second-3' : 'seconds',


      'form-sent-01' : '谢谢您',
      'form-sent-02' : '您的信息已经成功提交！',


      'faq-01' : '常见问题',
      'faq-02-00' : '关于#MetaHash',
      'faq-02-01' : '您是否是法律实体？',
      'faq-02-02' : '注册法律实体的流程已经在瑞士启动。在与瑞士政府达成协议之前需要一段时间。',
      'faq-02-03' : '我在哪里能够查看#MetaHash的MVP和开源代码？',
      'faq-02-04' : '#TraceChain去中心化式网络目前主要活跃于多资产钱包。#TraceChain协议的开源代码将会在公共安全黑客赏金计划通过并且获得专利之后发布。',
      'faq-02-05' : '产品本身以及代币的大致目的是什么？',
      'faq-02-06' : '#MetaHashCoin主要用来交换：交易、数据储存、应用功能。您还可以通过交换#MHC添加公共地址，使您的应用列在#MetaApp目录内，在#MetaGate广告网络内购买广告等。',
      'faq-02-07' : '您区块链的速度能力如何？您怎样能达到这样的结果？',
      'faq-02-08' : '请查看我们的白皮书了解更多关于区块链的能力。',
      'faq-02-09' : '您的货币可以挖掘吗？采矿人员有何好处？',
      'faq-02-10' : '请阅读白皮书了解更多关于挖矿的信息',
      'faq-02-11' : '您使用的是哪种凭证系统，POW还是POS？',
      'faq-02-12' : '#MetaHash使用的是混合共识算法，这是一个多POS系统，包括来自不同网络节点的投票结果。',


      'faq-03-00' : 'ICO A轮 / ICO B轮并购买#MHC',
      'faq-03-01' : '您所接受的支付方式是什么？',
      'faq-03-02' : '我们只接受ETH，其他类型的数字资产必须要首先交换成为ETH。',
      'faq-03-03' : '',
      'faq-03-04' : '',
      'faq-03-05' : '我能够通过交易平台参与吗？',
      'faq-03-06' : '是的，您可以，但是我们只接受ETH。',
      'faq-03-07' : '',
      'faq-03-08' : '',
      'faq-03-09' : 'ICO A轮 / ICO B轮将在什么时候结束?',
      'faq-03-10' : 'ICO A轮会一直持续到目标金额筹集完毕。ICO B轮将于发行MVP之后再开始',
      'faq-03-11' : '#MHC多资产钱包有何独特条款？',
      'faq-03-12' : '#MetaGate多资产钱包是一个开源代码产品，主要由所展示广告的费用以及广告拦截功能订阅的费用提供资金支持',


      'faq-04-00' : '#MetaHashCoin和愿景',
      'faq-04-01' : '#MetaHash和任何其他区块链供应商之间的一般区别在哪里？',
      'faq-04-02' : '所有当前的竞争对手要么较慢，要么比较集中。下一代的区块链必须快速，能够彻底去中心化并能够实现廉价的交易。除了#MetaHash之外，当前还没有项目能够满足上述所有需求。',
      'faq-04-03' : 'ETH 智能合约是否会发出#MHC ERC20？',
      'faq-04-04' : '#MHC是单独和独立的货币，能够在独立的链内操作。然而，在Ethereum和#MetaHash内一些镜面合约依然存在。这些镜面合约允许ERC20令牌的双向令牌化程序。',
      'faq-04-05' : '令牌的总供应量是多少？',
      'faq-04-06' : '在10年期内，将会发布9,200万#MHC，在第一年将会发布4,600万#MHC。',
      'faq-04-07' : '#MetaHashCoin的交易平台有哪些？',
      'faq-04-08' : '货币在交易平台的供应量将会在#MetaHash公共渠道内通过官方发布。我们禁止关于此类信息的提前共享。',
      'faq-04-09' : '一旦能够实现公共市场，ICO之后#MHC的初始价格将是多少？一年之后呢？',
      'faq-04-10' : '#MetaHashCoin的成本是由市场必要性决定。#MHC主要用来支付下述服务：交易、数据储存、应用功能等。这些因素将影响#MHC的成本。',
      'faq-04-11' : '令牌销售的起始时间将为何时？',
      'faq-04-12' : '我们计划在2018年底前完成ICO A轮。官方的ICO B轮将于2018年第4季度或2019年第一季度开始。',


      'faq-05-00' : '#MHC销售流程',
      'faq-05-01' : '参与#MetaHash是否有最低限制？',
      'faq-05-02' : '我们不设定任何最低限制。您可以拥有任意数量的令牌。',
      'faq-05-03' : '令牌将会在何时提供给参与者？',
      'faq-05-04' : '网络测试的#MetaHash币或他们的ERC20代币将在ICO B轮结束时为大家发放',
      'faq-05-05' : '您将如何处理未销售的货币？',
      'faq-05-06' : '所有未销售的资产依然将会停留在#MetaHash公司',
      'faq-05-07' : '如果我转移0.07ETH至我的#MetaHash钱包，我将获得多少令牌？',
      'faq-05-08' : '您可以使用我们的内部计算器。',
      'faq-05-09' : '如果我没有任何虚拟货币资产，我如何才能购买#MHC？',
      'faq-05-10' : '您不能，您必须将您的钱币转换成ETH或BTC。您可以选择您中意的任何平台。',



      'faq-06-00' : '其他问题',
      'faq-06-01' : '中国人或韩国人是否可以合法参与#MetaHash ICO 众筹?',
      'faq-06-02' : '除了下述国家之外的任何国家：美国，新加坡，越南、中国以及任何美国禁止通商或者禁止交易国家的公民，即伊朗、朝鲜、叙利亚、或古巴。更多信息请查看我们的令牌销售条款。',
      'faq-06-03' : '所以，简而言之，什么是#TraceChain？',
      'faq-06-04' : '#TraceChain？是新一代的区块链系统。这一解决方案以自动的自我学习路径算法为基础。起始功能为每秒50,000个交易（基本速度为100 Mb/s渠道），并能够通过增加高速渠道的数量提高。这些渠道是#MetaHash网络的核心，能够保持工作的稳定。',
      'faq-06-05' : '硬帽/软帽？',
      'faq-06-06' : '软帽通过创始人以及私人股权融资实现，硬帽则尚未确定。',
      'faq-06-07' : '我存了0.0067769个BTC/ETH，何时才能转化为#MHC令牌？',
      'faq-06-08' : '令牌将会在Ethereum网络六项确认以及#MetaChain节点接收到之后向您提供。我们通常给予您六个小时，对来自ETH和BTC网络的交易进行验证。如果您在六个小时之内未收到任何货币，请勿担心。向我们发送报告，我们将解决您的问题，您的定金本身就是一项交易。如果交易发生，我们将向您发送货币。',
      'faq-06-09' : '私人融资、ICO A/B轮等等的官方日期是什么?',
      'faq-06-10' : 'ICO A轮和ICO B轮的官方日期尚未确定，我们将很快通过公共频道向大家宣布。请继续关注，你很可能是第一个知道的人哦。',
      'faq-06-11' : '#MetaHash是BTC还是ETH分支？',
      'faq-06-12' : '#MetaHash并非是分支。这是一个更加快速和安全的独立区块链供应商。',


      'support-01' : '有何疑问？联系我们',
      'support-02' : '提交',
      'support-03' : 'User question',
      'support-04' : '输入您的名字',
      'support-05' : '输入您的邮箱',
      'support-06' : '您的问题',


      'prefooter-01' : '加入我们',
      'prefooter-02' : '#MetaHashTeam',
      'prefooter-03' : '<a href="#private-round" class="btn -default">购买#MHC<i class="icon icon_link"></i></a>',
      'prefooter-04' : '<a href="docs/MetaHash_WhitePaper_CN.pdf" target="_blank" class="btn -download">下载白皮书<i class="icon icon_dowload"></i></a>',
      'prefooter-05' : '<a href="docs/MetaHash_OnePager_CN.pdf" target="_blank" class="btn -download">下载单页程序<i class="icon icon_dowload"></i></a>',
      'prefooter-06' : 'Take part in ICO A轮',
      'prefooter-07' : '<a href="docs/MetaHash_WhitePaper_CN.pdf" target="_blank" class="btn -download">下载白皮书</a>',
      'prefooter-08' : '<a href="docs/MetaHash_OnePager_CN.pdf" target="_blank" class="btn -download float-right">下载单页程序</a>',


      'footer-01' : '#MetaHash是什么？',
      'footer-02' : '购买 #MetaHashCoin（#MHC）',
      'footer-03' : '<a href="docs/MetaHash_WhitePaper_CN.pdf" target="_blank" class="link -footer-link">白皮书</a>',
      'footer-04' : '<a href="docs/MetaHash_OnePager_CN.pdf" target="_blank" class="link -footer-link">单页程序</a>',
      'footer-05' : '常见问题',
      'footer-06' : '<a href="docs/MetaHash_TermsOfUse_CN.pdf" target="_blank" class="link -footer-link">使用条款</a>',
      'footer-07' : '<a href="docs/MetaHash_PrivacyPolicy_CN.pdf" target="_blank" class="link -footer-link">隐私政策</a>',
      'footer-08' : '<a href="docs/MetaHash_AntiSpam_EN.pdf" target="_blank" class="link -footer-link">反作弊政策</a>',
      'footer-09' : '咨询协议',
      'footer-10' : '<a href="docs/MetaHash_RiskDisclosureStatement_EN.pdf" target="_blank" class="link -footer-link">风险披露协议</a>',
      'footer-11' : '社交网络和通讯',
      'footer-12' : '论坛',
      'footer-13' : '反馈邮箱：<a href="mailto:hello@metahash.org" class="link -link-small">hello@metahash.org</a>',
      'footer-14' : '支持邮箱：<a href="mailto:support@metahash.org" class="link -link-small">support@metahash.org</a>',


      'mobile-menu-01' : '<a href="#whatis" class="link -link-white">#MetaHash是什么？</a>',
      'mobile-menu-02' : '<a href="#private-round" class="link -link-white">购买 #MetaHashCoin（#MHC）</a>',
      'mobile-menu-03' : '<a href="docs/MetaHash_WhitePaper_CN.pdf" target="_blank" class="link -link-white">下载白皮书</a>',
      'mobile-menu-04' : '<a href="docs/MetaHash_OnePager_CN.pdf" target="_blank" class="link -link-white">下载单页程序</a>',
      'mobile-menu-05' : '<a href="#faq" class="link -link-white">单页程序</a>',
      'mobile-menu-06' : '<a href="#support" class="link -link-white">支持</a>',
      'mobile-menu-07' : '<a href="#support" class="link -link-white">联系方式</a>',
	  
	  'new-mobile-menu-01' : '<a href="#whatis" class="link -link-white --offcan">#MetaHash是什么？</a>',
	  'new-mobile-menu-02' : '<a href="#tracechain" class="link -link-white --offcan">#TraceChain</a>',
	  'new-mobile-menu-03' : '<a href="#metaapps" class="link -link-white --offcan">#MetaApps</a>',
	  'new-mobile-menu-04' : '<a href="#metagate" class="link -link-white --offcan">#MetaGate</a>',
	  'new-mobile-menu-05' : '<a href="#timemap" class="link -link-white --offcan">Roadmap</a>',
	  'new-mobile-menu-06' : '<a href="#advisors-and-consultants" class="link -link-white --offcan">Advisors & Consultants</a>',
	  'new-mobile-menu-07' : '<a href="#teambanner" class="link -link-white --offcan">The Team</a>',
	  'new-mobile-menu-08' : '<a href="#ico" class="link -link-white --offcan">ICO A轮</a>',
	  'new-mobile-menu-09' : '<a href="#faq" class="link -link-white --offcan">单页程序</a>',
	  'new-mobile-menu-10' : '<a href="#support" class="link -link-white --offcan">联系我们</a>',

      'promo-soc-01' : '<a href="https://t.me/metahash_ENG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
      'promo-soc-02' : '<a href="https://www.facebook.com/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
      'promo-soc-03' : '<a href="https://vk.com/metahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
      'promo-soc-04' : '<a href="https://twitter.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
      'promo-soc-05' : '<a href="https://instagram.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
      'promo-soc-06' : '<a href="https://www.youtube.com/channel/UCIkBIrd1q7JkLLj43KgG8zA" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">youtube.com</span><span class="icon -icon-big icon_youtube"></span></a>',
      'promo-soc-07' : '<a href="#" class="link-soc -tooltype"><span class="soc-tooltype">ID:MetaHash</span><span class="icon -icon-big icon_wechat"></span></a>',
      'promo-soc-08' : '<a href="https://open.kakao.com/o/gY5dUgG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">talk.com</span><span class="icon -icon-big icon_talk"></span></a>',
      'promo-soc-09' : '<a href="https://github.com/metahashorg" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
      'promo-soc-10' : '<a href="https://www.reddit.com/user/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">reddit.com</span><span class="icon -icon-big icon_reddit"></span></a>',
      'promo-soc-11' : '<a href="https://www.linkedin.com/company/27209614/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">in.com</span><span class="icon -icon-big icon_in"></span></a>',
      'promo-soc-12' : '<a href="https://medium.com/@themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">medium.com</span><span class="icon -icon-big icon_medium"></span></a>',
      'promo-soc-13' : '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitsmedia"></span></a>',
      'promo-soc-14' : '<a href="https://bitcointalk.org/index.php?action=profile;u=1253602" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',


      'promo-soc-mobile-01' : '<a href="https://t.me/metahash_ENG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
      'promo-soc-mobile-02' : '<a href="https://www.facebook.com/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
      'promo-soc-mobile-03' : '<a href="https://vk.com/metahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
      'promo-soc-mobile-04' : '<a href="https://twitter.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
      'promo-soc-mobile-05' : '<a href="https://instagram.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
      'promo-soc-mobile-06' : '<a href="https://github.com/metahashorg" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
      'promo-soc-mobile-07' : '<a href="https://www.linkedin.com/company/27209614/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">in.com</span><span class="icon -icon-big icon_in"></span></a>',
      'promo-soc-mobile-08' : '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="link-soc"><span class="icon -icon-big --icon-forum icon_bitsmedia" target="_blank"></span></a>',
      'promo-soc-mobile-09' : '<a href="https://bitcointalk.org/index.php?action=profile;u=1253602" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',

      'tg_button' : '<a href="https://t.me/metahash_ENG" target="_blank"><img class="telega-svg" style="margin-bottom: 40px;" src="img/telegram.svg" alt=""></a>',



      'private-close-01' : '私募轮已经结束',
      'private-close-02' : '订阅人数超过预期的20倍以上。',
      'private-close-03' : '我们要感谢所有的参与者，并邀请所有人加入我们的ICO A轮。',
      'private-close-04' : 'ICO A轮',
      'private-close-05' : '计划开始月份',
      'private-close-06' : 'ICO A轮即将到来',
      'private-close-07' : '不要错过，现在申请<br class="mobile-br"> 来参与或者加入我们的团队',
      'private-close-08' : '现在申请 <i class="icon icon_link"></i>',
      'private-close-09' : '随时关注我们：',
      'private-close-10' : 'ICO A轮的特点:',
      'private-close-11' : '在ICO A轮中，我们将会分配<b class="mob-bold">920万 #MHC</b>',
      'private-close-12' : 'ICO A轮的MHC价值为<b class="mob-bold">0.0125 ETH</b>',
      'private-close-13' : '低于50ETH（12,500 #MHC）的订单将会从每四小时更新一次的常规限量池内注入。先到先到',
      'private-close-14' : '为了保证小型买家的空间，超过50 ETH的订单将会立即从单独保留的预留池内注入',
      'private-close-15' : '04/2018',
      'private-close-16' : '输入您的电子邮箱',
      'private-close-17' : '可通过白皮书变更', 
      // 'private-close-18' : '<input id="private-close__terms-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__terms-check">I agree to </label><a href="docs/MetaHash_TermsOfUse_CN.pdf" target="_blank">Terms of Use</a>',
      // 'private-close-19' : '<input id="private-close__policy-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__policy-check">I agree to </label><a href="docs/MetaHash_PrivacyPolicy_CN.pdf" target="_blank">Privacy Policy</a> ',
      

      'private-close-18' : '我同意 ',
      'private-close-19' : '我同意 ',
      'private-close-25' : '<a href="docs/MetaHash_TermsOfUse_CN.pdf"  target="_blank">使用条款</a>',
      'private-close-26' : '<a href="docs/MetaHash_PrivacyPolicy_CN.pdf" target="_blank">隐私政策 </a>',



      'private-close-20' : 'Application submitted',
      'private-close-21' : ', thank you for your interest in <b>#MetaHash</b> project. We will keep you informed about the <b>ICO A轮 start date</b>.',
      'private-close-22' : 'Dont miss a thing!',
      'private-close-23' : '<a href="https://t.me/metahash_ENG" target="_blank"  class="private-close__modal-content_tg-link" >Join our Telegram Channel<br> and stay updated</a>',
      'private-close-24' : '<a href="https://t.me/metahash_ENG" target="_blank" class="support-window__social-block_soc-link support-window__social-block_soc-link_tg"><img class="support-window__social-block_soc-img" src="img/popup/sub-tg.png" alt=""><span class="flag"><img class="support-window__social-block_flag-img" src="img/icons/flag-eng.png"></span></a>',


};
