window.arrLang = window.arrLang || {};
window.arrLang["ms"] = {
   'nav-link-01' : 'Apakah #MetaHash?',
      'nav-link-02' : 'Beli #MHC',
      'nav-link-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -link-white"><img src="img/icon_file.svg" class="icon_file"> Kertas Putih</a>',
      'nav-link-04' : '<a href="docs/MetaHash_OnePager_MS.pdf" target="_blank" class="link -link-white"><img src="img/icon_file.svg" class="icon_file"> Helaian Tunggal </a>',
      'nav-link-05' : 'SOALAN LAZIM',
      'nav-link-06' : 'Sokongan',
	  'nav-link-07' : 'Hubungi kami',

      'promo-01' : 'pantas',
      'promo-02' : 'kadar pengesahan di <b>bawah 3 saat</b>. Prestasi adalah <b>lebih daripada 50,000 TPS</b>',
      'promo-03' : 'selamat',
      'promo-04' : 'dilindungi oleh <b>5 algoritma konsensus yang berbeza</b>',
      'promo-05' : 'desentralisasi',
      'promo-06' : '<b>sesiapa sahaja boleh menambah nod transaksi</b> ke rangkaian #MetaHash',


      'descr-01' : 'berasaskan kepada Blockchain 2.0',
      'descr-02' : '<span class="cripto-title -title-part01 --eng">matawang</span> <span class="cripto-title -title-part02 --eng">kripto</span>',
      'descr-03' : 'and decentralized ecosystem',
      'descr-04' : 'berasaskan kepada Blockchain 2.0',


      'promo-appint-01' : '<span class="part-name">untuk&nbsp;</span>penyimpanan',
      'promo-appint-03' : 'bagi sebarang maklumat dalam Blockchain dengan <b>perlindungan kripto 4k</b> dan <b>pelbagai tandatangan</b>',
      'promo-appint-04' : '<a href="#private-round" class="btn -default">Pusingan A ICO Bermula<i class="icon icon_link"></i></a>',
      'promo-appint-05' : 'transaksi<span class="part-name">&nbsp;</span>',
      'promo-appint-06' : '<b>sehingga 3 saat untuk diluluskan</b> di dalam rangkaian #MetaHash dan di luarnya',
      'promo-appint-07' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Muat turun Kertas Putih<i class="icon icon_dowload"></i></a>',
      'promo-appint-08' : 'pertukaran<span class="part-name">&nbsp;bagi sebarang aset</span>',
      'promo-appint-10' : '<b>semua aset digital</b> dalam dompet #MetaGate menggunakan  <b>token ERC20</b> dalam semua perkhidmatan pertukaran',
      'promo-appint-11' : '<a href="docs/MetaHash_OnePager_MS.pdf" target="_blank" class="btn -download">Muat turun Helaian Tunggal<i class="icon icon_dowload"></i></a>',
      'promo-appint-12' : '<a href="#private-round" class="btn -default -mega" >Pusingan A ICO Bermula</a>',
      'promo-appint-13' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Kertas Putih</a>',
      'promo-appint-14' : '<a href="docs/MetaHash_OnePager_MS.pdf" target="_blank" class="btn -download float-right">Helaian Tunggal</a>',
      'promo-appint-15' : 'Download #MetaGate client',

      'whatis-01' : 'Apakah #MetaHash?',
      'whatis-02' : '#MetaHash adalah suatu rangkaian generasi akan datang yang berdasarkan kepada teknologi Blockchain 2.0 untuk berkongsi aset digital dan suatu platform untuk mencipta serta mengurus aplikasi serta perkhidmatan desentralisasi secara masa nyata',
      'whatis-03' : 'Empat komponen sistem:',
      'whatis-04' : '#TraceChain',
      'whatis-05' : 'Blockchain yang paling pantas dan paling selamat',
      'whatis-06' : 'Lebih daripada <b>lima bilion transaksi sehari</b>, tidak lebih daripada tiga saat untuk mengesahkan transaksi',
      'whatis-07' : 'Mengenai #TraceChain',
      'whatis-08' : '#MetaApps',
      'whatis-09' : 'Generasi baharu Kontrak Pintar',
      'whatis-10' : '<b>Aplikasi masa nyata desentralisasi</b> yang dikendalikan seperti perkhidmatan web biasa dan dibangunkan dengan bantuan mana-mana bahasa pengaturcaraan termasuk C ++, PHP, Solidity dan lain-lain.',
      'whatis-11' : 'Mengenai #MetaApps',
      'whatis-12' : '#MetaGate',
      'whatis-13' : 'Internet Desentralisasi',
      'whatis-14' : 'Direktori aplikasi desentralisasi dan <b>dompet pelbagai aset</b> yang tidak akan membebankan komputer anda',
      'whatis-15' : 'Mengenai #MetaGate',
      'whatis-16' : '#MetaHashCoin',
      'whatis-17' : 'Aset pertukaran rangkaian #MetaHash',
      'whatis-18' : '<b>#MetaHashCoin</b> digunakan untuk memastikan kebolehpercayaan rangkaian, perkhidmatan pertukaran dan mengawal pembiayaannya sendiri serta pembangunan',
      'whatis-19' : 'Mengenai #MHC',


      'tracechain-01' : '#TraceChain',
      'tracechain-02' : 'Blockchain 2.0 yang pantas dan selamat',
      'tracechain-03' : 'LEBIH DARIPADA',
      'tracechain-04' : '100,000',
      'tracechain-05' : 'transaksi setiap saat pada setiap nod',
      'tracechain-06' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download lang" >Muat turun Kertas Putih<i class="icon icon_dowload"></i></a>',
       //   'tracechain-07' : 'to approve a transaction',
       //   'tracechain-08' : 'transactions per day',
       //   'tracechain-09' : 'stages of consensus for verification',
       //   'tracechain-10' : '#MetaHash block anchors <span class="blue">in Bitcoin and Ethereum networks</span>',
      'tracechain-11' : '<img class="tracechain-svg" src="img/graphical/tracechain-ms.svg" alt="">',


      'speed-work-01' : 'Kelajuan yang tidak pernah berlaku sebelumnya dan desentralisasi rangkaian #TraceChain membuatkan #MetaHash menjadi kemegahan Blockchain',
      'speed-work-02' : 'Lengkapkan mana-mana jumlah transaksi dalam rangkaian <b>#MetaHash</b>',
      'speed-work-03' : 'Kos transaksi adalah lebih rendah daripada mana-mana Blockchain biasa',
      'speed-work-04' : 'Kos penyimpanan data yang munasabah dengan <b>#TraceChain</b> untuk projek desentralisasi',
      'speed-work-05' : 'Sebarang aset boleh diberikan kepada <b>#MetaHashCoin</b> untuk diedarkan dalam <b>#MetaHash</b>, Ethereum dan rangkaian lain',


      'speeds-01' : 'Bagaimanakah kami dapat mencapai kepantasan sedemikian?',
      'speeds-02' : 'Transaksi bermula pada radius luar dan kemudian masuk ke rangkaian teras dengan menggunakan laluan terpantas.',
      'speeds-03' : 'Setiap peringkat meluluskan transaksi dalam perjalanannya ke teras.',
      'speeds-04' : 'Nod terpantas bagi rangkaian teras menyegerakkan transaksi antara mereka.',
      'speeds-05' : 'Rangkaian teras mengembalikan keseimbangan dompet ke rangkaian, yang mengesahkan ketepatan perhitungan.',
      'speeds-06' : 'Data sandaran akan masuk ke Blockchain klasik, mengesahkan integriti rangkaian.',
      'speeds-07' : 'Sauh (cincangan daripada blok terpanjang) disimpan pada Bitcoin, Ethereum dan rangkaian lain.',
      'speeds-08' : 'Anda tidak boleh merosakkan atau mengubah suai maklumat yang disimpan dalam #MetaHash. Untuk berbuat demikian, adalah perlu untuk menyerang rangkaian #MetaHash serta Bitcoin, Ethereum dan rangkaian lain.',
      'speeds-09' : 'Semak Kertas Putih kami untuk butiran lebih teknikal',
      'speeds-10' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Muat turun Kertas Putih<i class="icon icon_dowload"></i></a>',


      'metaapps-01' : '#MetaApps',
      'metaapps-02' : 'Perkhidmatan awan untuk aplikasi masa nyata pintar',
      'metaapps-03' : '#MetaApps adalah evolusi kepada Kontrak Pintar dan boleh digunakan untuk desentralisasi mana-mana perkhidmatan. Ini adalah program bebas yang boleh wujud selama-lamanya dan tidak menjadi milik sesiapapun. Ia berfungsi dengan tepat seperti yang diprogramkan dan tidak boleh diganggu oleh pihak ketiga.',
      'metaapps-04' : 'Kelebihan #MetaApps',
      'metaapps-05' : 'Dilaksanakan dalam masa nyata',
      'metaapps-06' : 'Sepantas perkhidmatan dan aplikasi web biasa',
      'metaapps-07' : 'Sebarang reka bentuk GUI',
      'metaapps-08' : 'Boleh kelihatan seperti aplikasi biasa atau halaman web',
      'metaapps-09' : 'Keselamatan',
      'metaapps-10' : "Tiada siapa yang boleh mengubah tingkah laku aplikasi bagi memintas peraturan pengemaskinian",
      'metaapps-11' : 'Imej sistem program dan pengoperasian dimuat naik ke rangkaian dan bermula secara automatik pada kebanyakan komputer.',
      'metaapps-12' : 'Dicipta dalam sebarang bahasa pengaturcaraan termasuk C++, PHP, Solidity dan lain-lain.',
      'metaapps-13' : 'Sokongan penuh untuk kefungsian Kontrak Pintar, boleh berfungsi dengan mana-mana Blockchain atau hanya data daripada internet.',


      'metagate-01' : '#MetaGate',
      'metagate-02' : 'Get laluan ke internet desentralisasi',
      'metagate-03' : '#MetaGate adalah program sumber terbuka, oleh itu semua pembangun boleh memasukkan bahagian kodnya ke dalam aplikasi dan pelayar mereka.',
      'metagate-04' : 'Dompet pelbagai aset',
      'metagate-05' : 'Dompet menyokong "mod ringan" tanpa memuat turun keseluruhan Blockchain. Data datang dari pelbagai sumber rangkaian desentralisasi dan diperiksa oleh pengguna. Kunci peribadi dari semua Blockchains yang digunakan akan disimpan hanya oleh pengguna.',
      'metagate-06' : 'Katalog aplikasi',
      'metagate-07' : 'Katalog bagi aplikasi desentralisasi dan pelayar untuk bekerja dengannya. Mana-mana aplikasi desentralisasi yang dibina melalui <b>#MetaHash</b> boleh diakses, bukan sahaja melalui domain internet standard, tetapi juga melalui <b>#MetaGate</b> atau diperuntukkan kepada program berasingan.',
      'metagate-08' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Muat turun Kertas Putih<i class="icon icon_dowload"></i></a>',
	  'metagate-download-button' : 'Download #Metahash',

      'metahashcoin-01' : '#MetaHashCoin (#MHC)',
      'metahashcoin-02' : 'Model kewangan #MetaHash',
      'metahashcoin-03' : '#MetaHash adalah suatu sistem pembiayaan sendiri dengan proses pembangunan sendiri yang tertanam dalam kod genetiknya.',
      'metahashcoin-04' : '#MetaHashCoin digunakan untuk pembayaran:',
      'metahashcoin-05' : 'Transaksi',
      'metahashcoin-06' : 'Transaksi segera dan boleh dipercayai bagi sebarang aset pada harga tetap yang munasabah.',
      'metahashcoin-07' : 'Penyimpanan data',
      'metahashcoin-08' : 'Untuk aplikasi yang perlu menyimpan data, tetapi kekurangan kelajuan dan jumlah data dalam sistem Blockchain konvensional.',
      'metahashcoin-09' : 'Pengoperasian aplikasi',
      'metahashcoin-10' : 'Mana-mana aplikasi desentralisasi atau Kontrak Pintar memerlukan sumber untuk digunakan, termasuk rangkaian <b>#MetaHash</b> itu sendiri.',
      'metahashcoin-11' : 'Perkhidmatan lain',
      'metahashcoin-12' : 'Pembayaran untuk alamat awam, penyenaraian dalam <b>#MetaApps</b>, pengiklanan di <b>#MetaGate</b> dan sumber lain.',
      'metahashcoin-13' : '<a href="#private-round" class="btn -default btn-mobile">Beli #MHC<i class="icon icon_link"></i></a>',


      'minig-01' : 'Perlombongan / penempaan #MHC',
      'minig-02' : 'Pelayan',
      'minig-03' : 'Digunakan untuk pengendalian rangkaian transaksi, sumber percuma digunakan untuk pengendalian aplikasi desentralisasi.',
      'minig-04' : 'Dompet #MetaGate ',
      'minig-05' : 'Dalam mod Penuh, nod digunakan sebagai penyimpanan data dan Nod Torrent.',
      'minig-06' : '#MetaHashCoins',
      'minig-07' : 'Memperkuat keselamatan konsensus mengenai model pengundian hibrid untuk komponen PoW + PoS.',
      'minig-08' : '#MHC yang diterima daripada jualan perkhidmatan digunakan untuk:',
      'minig-09' : 'melatih para pembangun yang membina projek mereka di #MetaHash',
      'minig-10' : 'penambahbaikan kualiti projek',
      'minig-11' : 'promosi #MetaHash',
      'minig-12' : 'pembayaran kepada pemilik #MetaHashCoins untuk sokongan konsensus',
      'minig-13' : 'pembayaran kepada pemilik pelayan dan komputer',


      'compare-00' : 'Projek',
	  'compare-01' : 'Kelebihan #MetaHash',
      'compare-02' : 'Selepas mencari dan gagal menjumpai sebarang projek yang berfungsi untuk mewujudkan litar desentralisasi penuh dan disegerakkan yang mampu untuk memproses dengan cepat jumlah data yang diperlukan untuk dunia, kami memutuskan untuk menghasilkan #MetaHash.',
      'compare-03' : 'Jadual perbandingan bagi sistem Blockchain utama',
      'compare-04' : 'Masa kelulusan<br />transaksi',
      'compare-05' : 'Transaksi sesaat (TPS)',
      'compare-06' : 'Tahap<br />desentralisasi',
      'compare-07' : 'Bitcoin',
      'compare-08' : '10 minit',
      'compare-09' : 'sehingga 12',
      'compare-10' : 'tinggi',
      'compare-11' : 'Ethereum',
      'compare-12' : '15 saat',
      'compare-13' : 'sehingga 30 ',
      'compare-14' : 'tinggi',
        //    'compare-15' : 'Plasma',
        //    'compare-16' : '15 seconds',
        //    'compare-17' : 'up to 30',
        //    'compare-18' : 'high',
      'compare-19' : 'EOS',
      'compare-20' : '5 saat',
      'compare-21' : 'dari 1,000 kepada jutaan',
      'compare-22' : 'minimum',
      'compare-23' : '#MetaHash',
      'compare-24' : 'sehingga 3 saat',
      'compare-25' : 'dari 50,000 kepada jutaan',
      'compare-26' : 'tinggi',
      'compare-27' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Muat turun Kertas Putih<i class="icon icon_dowload"></i></a>',


      'timemap-01' : 'Peta jalan',
      'timemap-02' : 'Bahagian teknikal projek adalah berdasarkan kepada pencapaian AdSniper, dihasilkan pada tahun 2012 hingga 2017 dalam bidang teknologi pengiklanan.',
      'timemap-03' : "Kami menerima banyak permintaan daripada syarikat yang berlainan untuk aplikasi teknologi Blockchain dan kemudian memahami bahawa teknologi semasa tidak dapat memenuhi permintaan untuk jenis sistem sedemikian. Jadi pada tahun 2016 kami telah mula membangunkan protokol kami sendiri iaitu #TraceChain.",
      'timemap-04' : 'Pada tahun 2017, kami telah mencipta versi alfa dan beta bagi protokol #TraceChain dan bergabung tenaga dengan syarikat dan orang terkuat dalam bidang pemasaran antarabangsa dan pembangunan perniagaan.',
      'timemap-05' : '2012-2016',
      'timemap-06' : 'A network library for receiving signals, working on C++ and capable of simultaneously receiving and sending more than 100,000 requests per second to one inexpensive standard server',
      'timemap-07' : 'A network library for synchronizing signals within a cluster that manages gigantic data flows between cluster machines.',
      'timemap-08' : 'A machine learning system that decides in 40 milliseconds to respond to a signal taking into account multifactorial interrelationships.',
      'timemap-09' : 'Own analogue of Hadoop’s for similar systems in C ++ for distributed processing of large data.',
      'timemap-11' : '2017',
      'timemap-12' : 'Development of #TraceChain protocol (Alpha version)',
      'timemap-13' : 'Development of #TraceChain protocol (Beta version)',
      'timemap-14' : '<b>AdNow</b> team joins us',
      'timemap-15' : '<b>Agranovsky IT</b> team joins us',
      'timemap-16' : 'Formation of <b>Business Development team</b>',
      'timemap-17' : 'Formation of <b>Operational Team</b>',
      'timemap-18' : '2018',


      'timemap-19' : '#MetaHash website official launch',
      'timemap-20' : 'Start of the Operational Team office construction',
      'timemap-21' : 'Onboarding of experts and advisors',
      'timemap-22' : 'Development of #MetaGate (v.1.0). Multi-asset wallet featuring the ability to transfer #MetaHashCoins between wallets on multiple servers that stores data on transactions between crypto wallets.',
      'timemap-23' : 'Development of #TraceChain (v.1.0)',
      'timemap-23a': 'Development of #TraceChain (v.2.0). #TraceChain data download API',
      'timemap-24' : 'Development of #MetaICO (v.1.0). The ICO interface on the #MetaHash platform that accepts assets from various blockchains (Bitcoin and Ethereum), distributes tokens in the #MetaHash network and carries out multichain transactions, including ERC20 in the Ethereum network',
      'timemap-25' : 'Development of #MetaChains (v.1.0). Converting #MetaHashCoins to ERC20 and withdrawing them to the Ethereum network so that #MHC holders can choose which network to use and automatically convert ERC20 tokens into #MetaHashCoins',

      'timemap-26' : 'Development of #MetaApps (v.1.0). Application Platform',
      'timemap-27' : 'Testnet data download API',
      'timemap-28' : 'Opening of the Operational Team office',


      'timemap-29' : 'ICO Round A scheduled start',
      'timemap-30' : 'Development of #MetaChains (v.2.0). API featuring transaction history and balance  of wallets associated with different blockchain platforms. Decentralized application containing information about transactions in the Ethereum and Bitcoin networks which is necessary to provide blockchain interoperability in #MetaApps',
      'timemap-31' : 'Release of <b>#MetaGate (v.2.0)</b>. Encrypted messenger for public notifications and messaging between wallets',
      'timemap-32' : 'Release of <b>#TraceChain (v.3.0)</b>. Peer nodes that connect to TestNet to be installed on any server',
      'timemap-33' : '#TraceChain (v.4.0). Network core performance testing service (1,000,000+ transactions per second)',
      'timemap-34' : '#MetaICO (v.2.0). Interface for creating tokens inside the network #MetaHash',
      'timemap-35' : '#MetaICO (v.3.0). Release of ICO project platform at #MetaHash.',
      'timemap-36' : '#TraceChain (v.4.0). Voting functions in the #MetaHash network',
      'timemap-37' : '#TraceChain (v.5.0). AI managing the routing of signals between nodes for providing maximum speed of #MetaHash block creation and bandwidth and 100 test nodes in different geographical locations for testing node interaction',

      'timemap-38' : '#MetaICO (v.4.0). Release of the #MetaToken application, tokenization of ETH, ERC20, Bitcoin to #MetaHashCoin for use in the #MetaHash network',
      'timemap-39' : '#TraceChain (v.6.0). #MetaStorage, service for decentralized applications',
      'timemap-40' : '#MetaApps (v.2.0). The platform for self-deployment of third-party decentralized applications',
      'timemap-41' : '#MetaGate (v.3.0). Final release of #MetaGate wallet for Mac/Win/Unix/Android/iOS with #MetaApps catalogue',


      'timemap-42' : '<b>#TraceChain (v.7.0). Start of forging </b>',
      'timemap-43' : '<b>Pusingan B ICO bermula atau berakhirnya Perjanjian Penyenaraian dengan bursa kripto yang diatur dan dikawal selia sewajarnya</b>',
      'timemap-44' : 'Pengumuman rancangan selanjutnya',


      'timemap-45' : 'Pengujian keselamatan yang meluas',
      'timemap-46' : 'Kod sumber akan didedahkan setelah selesai ujiannya',
      'timemap-47' : 'Pelancaran sistem yang disentralisasi sepenuhnya',
      
      'timemap-100' : 'Baca lebih lanjut',
	  'timemap-101' : 'Sembunyi Peristiwa',
	  'timemap-102' : 'Peristiwa lain',


      'teambanner-01' : 'Pasukan kami',
      'teambanner-02' : '#MetaHash adalah projek berstruktur bagi pasukan terbuka, yang mengalu-alukan semua orang dan syarikat.',
      'teambanner-03' : 'Jika anda percaya anda boleh membantu dan ingin menyertai pasukan, sila <a class="team-write" href="mailto:hello@metahash.org">hubungi kami</a>.',
      'teambanner-04' : '<a href="#private-round" class="btn -default">Pusingan A ICO Bermula<i class="icon icon_link"></i></a>',
      'teambanner-05' : 'Jika anda percaya anda boleh membantu dan ingin menyertai pasukan, sila <a href="mailto:hello@metahash.org">hubungi kami</a>.',
      'teambanner-06' : 'Pusingan A ICO Bermula',
      'teambanner-07' : '<img src="img/graphical/People_MS@3x.svg" alt="">',

      'team-hidden-01' : 'Bagi kepentingan projek, nama-nama bagi ahli pasukan yang lain tidak dinyatakan',

      'team-dev-00' : 'Pembangunan',
	  'team-dev-01' : 'Gleb Nikitin',
	  'team-dev-01a' : 'Pengasas Bersama, Rakan Kongsi, CRO',
      'team-dev-02' : 'Oleg Romanenko',
      'team-dev-03' : 'CSA, Arkitek bagi perkhidmatan masa nyata di AdSniper dan penganalisis sistem bagi sistem perbankan atas talian AlfaBank. Pencipta perpustakaan rangkaian beban tinggi yang mampu melayani lebih dari 1 juta permintaan sesaat pada 1 nod.',
      'team-dev-04' : 'Mikhail Zarutskiy',
      'team-dev-05' : 'CTO, Ketua AI, Big Data dan pasukan perkhidmatan masa nyata yang menghasilkan Razoom AI yang mampu mengendalikan jutaan permintaan dalam masa nyata menggabungkan pengiraan rangkaian neural dengan algoritma pembelajaran mesin yang lain.',
      'team-dev-06' : 'Sergey Raylyan',
      'team-dev-07' : "CIO, merancang dan menyelaraskan pelaksanaan berpuluh-puluh teknologi dan antaramuka berbeza yang membentuk susunan teknologi AdSniper.",
      'team-dev-08' : '29 orang kakitangan <i class="icon icon_link"></i>',
      'team-dev-09' : "Sepanjang 10 tahun yang lalu, syarikat ini telah mencipta rangkaian pengiklanan yang amat berbeban tinggi. Pemproses data yang besar dari syarikat itu sendiri menggabungkan penservisan data petabyte, pangkalan data NoSQL dan SQL yang pantas, sistem kepintaran buatan dan perpustakaan C ++ untuk perkhidmatan pengiklanan yang amat berbeban tinggi, memproses permintaan untuk pengiklanan daripada seluruh internet.",
      'team-key-staff' : 'Kakitangan utama',


      'team-mark-00' : 'Pemasaran',
	  'team-mark-01' : 'Vladimir Bashkin',
	  'team-mark-01a' : 'CEO AdNow <a href="http://www.facebook.com/vladimir.bashkin" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="http://www.linkedin.com/in/vladimir-bashkin-18877678/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
      'team-mark-02' : 'Rangkaian pengiklanan dengan lebih daripada satu bilion impresi setiap hari. Salah satu pasukan terkuat di dunia untuk membeli pengiklanan di semua rangkaian pengiklanan dengan kakitangan penterjemah dan pakar pengiklanannya sendiri di pasaran tempatan.',
      'team-mark-03' : '89 orang kakitangan AdNow <i class="icon icon_link"></i>',
      'team-mark-04' : 'Artem Kravchenko',
      'team-mark-05' : 'Pengarah Acara - Pengarah Perhubungan Awam. CEO AdDays Digital Events. Pengarah Acara dalam Rangkaian Gabungan Bitcomo',
      'team-mark-06' : 'Daria Baranova',
      'team-mark-07' : 'Pengarah Gabungan - Pengarah Jualan Penerbitan AdNow. Pengarah Urusan Pejabat Moscow',
      'team-mark-08' : 'Pham Thành Trung',
      'team-mark-09' : "Ketua Jabatan Pengiklanan - Ketua Jabatan Jualan di AdNow Rantau Asia. Pengurus Pembangunan Jualan dan Perniagaan AdNow",


      'team-fin-00' : 'Pembangunan Perniagaan',
	  'team-fin-01' : 'Anton Agranovsky',
	  'team-fin-01a' : 'Pengasas Bersama, Rakan Kongsi, CBDO <a href="https://www.facebook.com/aagranovsky" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a><a href="https://www.linkedin.com/in/anton-agranovsky-57427a15a/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
      'team-fin-02' : 'Agranovsky IT - syarikat pelaburan, melabur dalam syarikat permulaan IT dan mengiringi pertumbuhan syarikat daripada idea kepada IPO. Pengasasnya, Anton Agronovsky adalah seorang pelabur, pakar, pemimpin pendapat dalam bidang penubuhan dan pengembangan perusahaan IT. Ahli Lembaga dalam Media Plastik dan Komunikasi SMX. Pada tahun 2008-2017 - menjadi pengasas dan presiden Destiny Development, salah satu syarikat permainan pertama di pasaran internet Rusia yang dikenali untuk pembangunan dan penyetempatan sendiri.<br />&nbsp;<br /><a href="https://goo.gl/fJVjfK" class="link -link-small" target="_blank">Penyumbang kepada majalah Forbes</a>',
      'team-fin-03' : '11 orang kakitangan Agranovsky IT <i class="icon icon_link"></i>',
      'team-fin-04' : 'Gennady Yakunin',
      'team-fin-05' : 'CEO - Mengorganisasi perakaunan dalam syarikat pegangan. Lebih daripada 10 tahun pengalaman dalam projek IT dan permainan',
      'team-fin-06' : 'Svetlana Rudenok',
      'team-fin-07' : 'Timbalan CEO - Pakar dalam penilaian risiko, lebih daripada 10 tahun pengalaman dalam mengaudit projek baharu dan aktif dalam industri IT dan permainan',
      'team-fin-08' : 'Andrey Korostelev',
      'team-fin-09' : 'CFO - Lebih daripada 10 tahun pengalaman dalam pengurusan kewangan IT dan projek permainan. Penyokong aktif dalam projek sosial dan amal',


      'team-oper-00t' : 'Pasukan Operasi',
	  'team-oper-01' : 'Dmitry Ushakov',
      'team-oper-02' : '<span style="color:#ffffff;">COO, Pengurus Projek Besar</span><br/>Lebih 11 tahun pengalaman dalam pengurusan operasi bagi projek berbilang pengguna untuk Game Insight dan syarikat permulaan IT yang lain',
      'team-oper-03' : 'Michaił Iwanow',
      'team-oper-04' : '<span style="color:#ffffff;">Pengarah Kesenian</span><br/>dengan lebih daripada 16 tahun pengalaman dalam reka bentuk visual dan produk. Pernah mengendalikan projek untuk RUSNANO, Sony, Canon, Nikon dan syarikat lain',
      'team-oper-05' : 'Zhibo Fan',
      'team-oper-06' : '<span style="color:#ffffff;">CBDO Asia, MENA</span><br/>Pengasas platform permainan Game.ru dan penerbit permainan INFIPLAY',
      'team-oper-07' : 'Alexander Zhigarenko',
      'team-oper-08' : '<span style="color:#ffffff;">CBDO Russia, CIS</span><br/>Lebih daripada 10 tahun pengalaman dalam penerbitan, pengoperasian dan pembangunan perniagaan untuk Destiny.Games dan dalam industri permainan',
      'team-oper-09' : 'Eugenia Sigacheva',
      'team-oper-10' : '<span style="color:#ffffff;">Rakan Kongsi Hal Ehwal Awam</span><br/>Lebih daripada 18 tahun pengalaman dalam bidang Pemasaran & PR antarabangsa, juga dalam bidang IT & Inovasi. Eugenia adalah sebahagian daripada pasukan antarabangsa bagi robot terkenal Sophia dan merupakan CEO& Pengasas Platform IHEART.',
      'team-oper-11' : 'Andrey Akimov',
      'team-oper-12' : '<span style="color:#ffffff;">Chief Communication Officer</span><br/>More than 15 years in marketing and PR in gaming, entertainment, and IT business. Former head of PR and marketing at My.com, Mail.Ru Group, Game Insight, and other companies.',
      'team-oper-00' : '17 orang kakitangan Pasukan Operasi <i class="icon icon_link"></i>',


     // 'legal-01' : 'Sokongan Perundangan',
     // 'legal-02' : 'Anastasia Pichugina',
     // 'legal-03' : 'Rakan Kongsi Pengurusan Perundangan ANP <a href="https://www.facebook.com/people/Anastasia-Pichugina/1520204010" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
     // 'legal-04' : 'Ekaterina Myznikova',
     // 'legal-05' : 'Peguam Kanan - Ketua amalan bagi projek Blockchain. Mengiringi dengan berjayanya beberapa projek ICO, seorang peserta dan penceramah persidangan profil, webinar.',
     // 'legal-06' : 'Maxim Mekhriakov',
     // 'legal-07' : 'Peguam Kanan - Ketua Amalan Komersial dalam Undang-undang ANP yang mengkhusus dalam sokongan undang-undang bagi transaksi perdagangan dan pelaburan.',
     // 'legal-08' : 'Anna Shevchenko',
     // 'legal-09' : 'Peguam - Sokongan undang-undang untuk syarikat Rusia dan syarikat asing dalam bidang hak harta intelektual, termasuk pendaftaran cap dagang dan paten.',
     // 'legal-10a' : 'Firma Perundangan ANP',
	 // 'legal-10' : 'Pakar dalam undang-undang Antarabangsa dan Rusia. Para peguam kami menamatkan pengajian daripada sekolah undang-undang yang paling berprestij di Rusia dan di luar negara. Rakan kongsi pengurusan, Anastasia mempunyai pengalaman dan pengetahuan yang unik dalam undang-undang Rusia dan asing, merupakan wakil perundangan yang sah bagi beberapa syarikat asing daripada pasaran IT, FMCG. Anastasia dengan berjayanya telah mewakili syarikat asing di mahkamah Rusia.',
     // 'legal-11' : '<a href="docs/MetaHash_LegalOpinion_EN.pdf" target="_blank">Muat turun Pendapat Perundangan #MetaHashCoin<i class="icon icon_link"></i></a>',
      'legal-title' : 'Legal Department',

    //'legal-14' : 'Maria Agranovskaya',
    //'legal-15' : 'Chief Legal Coordinator <a href="https://www.facebook.com/magranovskaya" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a> <a href="https://www.linkedin.com/in/maria-agranovskaya-151334/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a>',
    //'legal-16' : '<span>Attorney at Law with 20+ years of experience. Started working with cryptocurrency issues back in 2010. MGIMO MID of Russia (International Law), studied in Germany and Holland. 8,5 years - running a multifamily office, worked on various cross-border transactions, investments, asset management, deal and corporate structuring in various jurisdictions, M&A, international taxation and other matters.</span><span>Areas: fintech, finance, telecom, banking, energy, pharmaceuticals, real estate and other sectors.</span><span>2007: setup of GRAD Attorney Bar (managing partner,  30+ Russian and foreign lawyers)</span><span>Substantially engaged in blockchain technology, ICO (TGE) related projects, trading and finance regulations, funds and financial activity.</span><span>Speaks English, German, French, Italian, </span>',
	 
	  'legal-more' : 'Baca lebih lanjut',
	  'legal-less' : 'Sembunyi Peristiwa',
	  'legal-17' : 'Andrey Mironov <a href="http://www.linkedin.com/in/" class="link-soc" target="_blank"><span class="icon -icon-small icon_in"></span></a> <a href="https://www.facebook.com/" class="link-soc" target="_blank"><span class="icon -icon-small icon_fb"></span></a>',
	  'legal-18' : 'Chief of Legal Department',
	  'legal-19' : 'Graduated MGIMO in 2000 at the international law faculty. Legal practice in the field of new technologies, media and intellectual property for more than 15 years.',
	  'legal-19a' : 'He worked at the Art. Lebedev Studio, Odnoklassniki, the Russian office of Myspace, on the channels MTV, Discovery, Amedia and the online cinema Amediateka. Helped to develop the EKSMO publishing house, the Fox TV channel. Expert at the Russian Association of Electronic Communications (RAEC).<br>Secondary Education: Consultant Psychologist',
	  'legal-20' : 'Maria Agranovskaya',
	  'legal-21' : 'Chief Legal Coordinator',
	  'legal-22' : 'Attorney at Law with 20+ years of experience. Started working with cryptocurrency issues back in 2010.',
	  'legal-22a' : 'MGIMO MID of Russia (International Law), studied in Germany and Holland. 8,5 years - running a multifamily office, worked on various cross-border transactions, investments, asset management, deal and corporate structuring in various jurisdictions, M&A, international taxation and other matters. Areas: fintech, finance, telecom, banking, energy, pharmaceuticals, real estate and other sectors. 2007: setup of GRAD Attorney Bar (managing partner,  30+ Russian and foreign lawyers). Substantially engaged in blockchain technology, ICO (TGE) related projects, trading and finance regulations, funds and financial activity. Speaks English, German, French, Italian,  Spanish.',
	  'legal-23' : 'Katya Fisher',
	  'legal-24' : 'Partner, Principal at The Law Office of Katya Yoffe PLLC',
	  'legal-25' : 'Katya Yoffe (née Fisher) is an attorney focusing on general corporate law, cross-border transactions and business immigration.',
	  'legal-25a' : 'Katya represents various prominent companies and startups doing business in the United States as well as celebrity and HNW individuals. Katya has been selected to Super Lawyers as a “Rising Star” in 2014, 2015, 2016, 2017 and 2018. <br>Katya is a graduate of New York University, the Benjamin N. Cardozo School of Law and a former Howard M. Squadron Fellow in International Media Law & Policy at the University of Oxford and Center for Global Communication Studies, University of Pennsylvania. She is admitted to practice in New York and before the United States Tax Court.',
	  'legal-26' : 'Anastasia Pichugina',
	  'legal-27' : 'ANP Law Managing Partner ',
	  'legal-28' : 'Managing partner Anastasia has a unique experience and knowledge in Russian and foreign law, is a trusted legal representative of several foreign companies.',
	  'legal-29' : 'Ekaterina Myznikova',
	  'legal-30' : 'Peguam Kanan',
	  'legal-31' : 'Ketua amalan bagi projek Blockchain. Mengiringi dengan berjayanya beberapa projek ICO, seorang peserta dan penceramah persidangan profil, webinar.',
	  'legal-32' : 'International Legal Support',
	  'legal-33' : 'Daniel G. Viola',
	  'legal-34' : 'Partner, Head of Regulatory and Compliance Group at Sadis & Goldberg LLP',
	  'legal-35' : 'Oliver Ciric',
	  'legal-36' : 'Partner at TA Advisory',
	  'legal-37' : 'Daniel G. Viola is a partner of <span class="ilegal-white">Sadis & Goldberg LLP</span> and the Head of its Regulatory and Compliance Group.  Mr. Viola has been active in the Blockchain and Virtual Currency verticals since 2014. He also served as a Senior Compliance Examiner for the <span class="ilegal-white">Northeast Regional Office of the SEC,</span> where he worked from 1992 through 1996',
	  'legal-37a' : 'During his tenure at the SEC, Mr. Viola worked on several compliance inspection projects and enforcement actions involving examinations of registered investment advisers, ensuring compliance with federal and state securities laws. Mr. Viola’s examination experience includes financial statement, performance advertising, and disclosure document reviews, as well as, analysis of investment adviser and hedge fund issues arising under ERISA and blue-sky laws. In late 2006 Mr.  Viola founded his own law firm and eventually merged it into Sadis & Goldberg’s law practice.',
	  'legal-38' : 'Experience in international jurisprudence for more than 20 years. Oliver graduated from Boston University of Law in 2006, majoring in banking and finance law, and the Geneva University of Law in 1998, specializing in "License and Law". Previous work experience:  Nationale Suisse Assurances, Matile Brosset Stickel-Cicurel & Gianninazzi, Poncet Turrettini Amaudruz Neyroud & Partners, <span class="ilegal-white">Akin Gump Strauss Hauer & Feld LLP</span> (formerly Hogan & Hartson LLP).',
	  'legal-38a' : 'Since June 2017 he has been a partner at <span class="ilegal-white">TA Advisory</span>. Mr. Ciric provides legal support for blockchain projects, and also advises on cooperation <span class="ilegal-white">with FINMA.</span><br>Languages: German, English, French, Portuguese, Russian, Serbian.',
	  'legal-39' : '<span class="ilegal-white-02">KPMG AG, Switzerland,</span> served as exclusive legal advisor to #MetaHash and its management in the evaluation of regulatory, tax and legal aspects in respect of the White Paper, which is released in preparation of a Coin offering (ICO)',
	  'legal-40' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="download-white-paper btn -download">Kertas Putih<i class="icon icon_dowload"></i></a>',
	  'legal-41' : 'Martin Hess',
      'legal-42' : 'Partner at Wenger & Vieli AG',
	  'legal-43' : 'Martin Hess specializes in financial services and capital markets law, FinTech and the digitization of financial services. He is recognized by the Swiss Stock Exchange as an issuer representative. Martin Hess advises Swiss and foreign clients and represents them vis-à-vis supervisory authorities and in court.',
	  'legal-43a' : 'He is involved in the legal design of trading venues for digital assets, payment systems and securities settlement systems as well as central counterparties. He advises and represents clients on Initial Coin Offerings / Token Generating Events. Since 2001 Partner at Wenger & Vieli Ltd',


         //   'private-01' : 'Private Round',
         //   'private-form' : '<input type="hidden" name="form_subject" value="Private Round Application">',
         //   'private-03' : 'days',
         //   'private-04' : 'Private Round ends in',
         //   'private-05' : 'Private Round',
         //   'private-06' : 'The purpose of the Private Round is to verify the idea before the public launch',
         //   'private-07' : 'We hope to meet experts who are ready to participate in the discussion of the project before its public launch and, possibly, join the #MetaHashTeam.',
         //   'private-08' : '#MetaHash undertakes to inform all Private Round participants about terms of participation, their rights and obligations in connection with participation.',
         //   'private-09' : 'Private Round participants will be able to decide whether to remain in the project after the ICO.',
         //   'private-10' : 'Send an application to participate in the Private Round',
         //   'private-11' : 'We are not interested in the amount, but rather in your expertise. We want experts from different fields to participate in the Private Round.',
         //   'private-12' : 'Describe your expertise in cryptocurrencies. Are you ready to participate in discussion about the project?',
         //   'private-13' : 'Apply <i class="icon icon_link"></i>',
         //   'private-14' : 'Terms of Use',
         //   'private-15' : 'Privacy Policy',
         //   'private-16' : 'Private Round terms:',
         //   'private-17' : 'Do you want to participate in the Private Round or join the #MetaHashTeam?',
         //   'private-18' : 'Participation in the Private Round is public - the name or company name of the participant will be published',
         //   'private-19' : 'Private Round volume - <b>1,840 ETH</b>',
         //   'private-20' : 'The value of the #MHC - <b>0.001 ETH</b>',
         //   'private-21' : 'The volume of the Private Round is not enough to satisfy the requests of all comers',
         //   'private-22' : 'You can fill the application form before the end of the Private Round',
         //   'private-23' : 'At the end of the Private Round, the current #MetaHash team will decide on quotas for each of those wishing to participate',
         //   'private-24' : 'After the completion of the Private Round and the distribution of tasks between the current and new team members, the Pre-ICO will start',
         //   'private-25' : 'Private Round Application',
              'private-26' : 'Masukkan nama anda',
              'private-27' : 'Masukkan e-mel anda',
         //   'private-28' : 'Desired amount of participation (ETH)',
         //   'private-29' : 'Additional information about yourself',


         //   'timer-day-1' : 'days',
         //   'timer-day-2' : 'days',
         //   'timer-day-3' : 'days',
         //   'timer-hour-1' : 'hour',
         //   'timer-hour-2' : 'hours',
         //   'timer-hour-3' : 'hours',
         //   'timer-minute-1' : 'minute',
         //   'timer-minute-2' : 'minutes',
         //   'timer-minute-3' : 'minutes',
         //   'timer-second-1' : 'second',
         //   'timer-second-2' : 'seconds',
         //   'timer-second-3' : 'seconds',


      'form-sent-01' : 'Terima kasih!',
      'form-sent-02' : 'Maklumat anda telah berjaya diserahkan.',


      'faq-01' : 'Soalan Lazim',
      'faq-02-00' : 'Mengenai #MetaHash',
      'faq-02-01' : 'Adakah anda entiti yang sah?',
      'faq-02-02' : 'Proses mendaftarkan entiti yang sah telah dimulakan di Switzerland. Ia secara umumnya memerlukan masa untuk mencapai persetujuan dengan kerajaan Switzerland.',
      'faq-02-03' : 'Di mana saya boleh meneliti MVP dan kod Sumber Terbuka #MetaHash?',
      'faq-02-04' : 'Rangkaian terpusat #TraceChain kini sedang aktif dengan dompet pelbagai aset. Kod sumber protokol #TraceChain akan dikeluarkan selepas program ganjaran keselamatan awam untuk penggodam telah diluluskan dan paten diperolehi.',
      'faq-02-05' : 'Apakah matlamat umum produk itu sendiri dan tokennya?',
      'faq-02-06' : '#MetaHashCoin digunakan sebagai pertukaran untuk: transaksi, penyimpanan data, fungsi aplikasi. Anda juga boleh menukarkan #MHC untuk menambah alamat awam, untuk membuatkan aplikasi anda disenaraikan dalam direktori #MetaApp, untuk membeli iklan dalam rangkaian iklan #MetaGate dan banyak lagi.',
      'faq-02-07' : 'Apakah kapasiti kelajuan Blockchain anda? Bagaimana anda dapat mencapai keputusan tersebut?',
      'faq-02-08' : 'Sila semak <a href="docs/MetaHash_WhitePaper_EN.pdf" class="link -link-small" target="_blank">Kertas Putih</a> kami untuk mengetahui lebih lanjut mengenai kapasiti Blockchain kami.',
      'faq-02-09' : 'Adakah duit syiling anda boleh dilombong? Adakah terdapat manfaat untuk pelombong?',
      'faq-02-10' : 'Baca <a href="docs/MetaHash_WhitePaper_EN.pdf" class="link -link-small" target="_blank">Kertas Putih</a> untuk maklumat lanjut mengenai perlombongan.',
      'faq-02-11' : 'Apakah sistem bukti yang anda gunakan, POW atau POS?',
      'faq-02-12' : '#MetaHash menggunakan algoritma konsensus hibrid. Ini merupakan sistem multiPOS yang termasuk keputusan undian daripada nod rangkaian berasingan.',


      'faq-03-00' : 'Pusingan A / Pusingan B ICO dan pembelian #MHC',
      'faq-03-01' : 'Apakah kaedah pembayaran yang anda terima?',
      'faq-03-02' : 'Kami hanya menerima ETH sahaja. Aset digital lain perlu ditukar kepada ETH terlebih dahulu.',
      'faq-03-03' : '',
      'faq-03-04' : '',
      'faq-03-05' : 'Bolehkah saya mengambil bahagian daripada platform pertukaran?',
      'faq-03-06' : 'Ya, anda boleh. Tetapi kami hanya menerima ETH sahaja.',
      'faq-03-07' : '',
      'faq-03-08' : '',
      'faq-03-09' : 'Bilakah Pusingan A / Pusingan B ICO tamat?',
      'faq-03-10' : 'Pusingan A ICO berlangsung sehingga jumlah yang disasarkan dicapai. Pusingan B ICO bermula selepas MVP dilepaskan',
      'faq-03-11' : 'Apakah terma khas untuk dompet pelbagai aset #MHC?',
      'faq-03-12' : 'Dompet pelbagai aset #MetaGate adalah produk kod sumber terbuka. Penggunaannya adalah dibiayai daripada pembayaran untuk iklan yang dipaparkan dan langganan untuk sekatan iklan',


      'faq-04-00' : '#MetaHashCoin dan Prospek',
      'faq-04-01' : 'Apakah perbezaan umum di antara #MetaHash dan mana-mana penyedia Blockchain yang lain?',
      'faq-04-02' : 'Semua pesaing sedia ada sama ada perlahan atau berpusat. Generasi Blockchain berikutnya perlu pantas, desentralisasi sepenuhnya dan mempunyai transaksi yang murah juga. Tidak terdapat projek sedia ada (kecuali #MetaHash) yang merangkumi semua keperluan ini.',
      'faq-04-03' : 'Adakah #MHC ERC20 dikeluarkan melalui Kontrak Pintar ETH?',
      'faq-04-04' : '#MHC adalah duit syiling bebas berasingan yang dikendalikan dalam rantai berasingan. Walau bagaimanapun, terdapat beberapa kontrak cermin dalam Ethereum dan #MetaHash yang wujud. Kontrak cermin ini membenarkan prosedur penokenan ERC20 untuk kedua-dua arah.',
      'faq-04-05' : 'Apakah jumlah bekalan dalam token?',
      'faq-04-06' : '92,000,000 #MHC akan dikeluarkan dalam tempoh 10 tahun. 46,000,000 #MHC akan dikeluarkan pada tahun pertama.',
      'faq-04-07' : 'Platform pertukaran apakah yang akan menperdagangkan #MetaHashCoins?',
      'faq-04-08' : 'Ketersediaan duit syiling di platform pertukaran akan diumumkan melalui semua saluran awam #MetaHash yang rasmi. Kami tidak dibenarkan untuk berkongsi maklumat sedemikian terlebih dahulu.',
      'faq-04-09' : 'Apakah yang akan menjadi harga permulaan #MHC selepas ICO sebaik sahaja ia mencapai pasaran terbuka? Dan selepas satu tahun?',
      'faq-04-10' : 'Kos #MetaHashCoin adalah ditentukan oleh keperluan pasaran. #MHC digunakan untuk membayar perkhidmatan berikut: transaksi, penyimpanan data, fungsi aplikasi dan sebagainya. Faktor-faktor ini akan mempengaruhi kos #MHC.',
      'faq-04-11' : 'Bilakah penjualan token akan bermula/berakhir?',
      'faq-04-12' : 'Kami merancang untuk menamatkan Pusingan A ICO menjelang akhir tahun 2018. Pusingan B ICO rasmi akan bermula pada Q4 tahun 2018 atau pada Q1 tahun 2019.',


      'faq-05-00' : 'Proses Penjualan #MHC',
      'faq-05-01' : 'Adakah terdapat had minumum untuk menyertai #MetaHash?',
      'faq-05-02' : 'Kami tidak menetapkan sebarang had minimum. Anda boleh memiliki sebanyak mana token yang anda mahukan.',
      'faq-05-03' : 'Bilakah token diberikan kepada peserta?',
      'faq-05-04' : 'Syiling #MetaHash TestNet atau pengganti ERC20 disediakan apabila Pusingan B ICO ditamatkan',
      'faq-05-05' : 'Apa yang akan anda lakukan dengan duit syiling yang tidak terjual?',
      'faq-05-06' : 'Semua aset yang tidak terjual akan kekal di Syarikat #MetaHash',
      'faq-05-07' : 'Saya telah memindahkan 0.07 ETH ke dompet #MetaHash saya. Berapa banyak token yang akan saya terima?',
      'faq-05-08' : 'Anda boleh menggunakan kalkulator dalaman kami.',
      'faq-05-09' : 'Bagaimana saya boleh membeli #MHC jika saya tidak mempunyai aset matawang kripto?',
      'faq-05-10' : 'Anda tidak boleh: anda perlu menukar wang anda ke ETH atau BTC. Anda boleh menggunakan mana-mana platform pertukaran yang anda suka.',



      'faq-06-00' : 'Soalan Lain',
      'faq-06-01' : 'Saya adalah warganegara Cina atau Korea, adakah sah untuk menyertai jualan orang ramai #MetaHash ICO?',
      'faq-06-02' : 'Setiap kewarganegaraan kecuali: Amerika Syarikat, Singapura, Republik Sosialis Vietnam, Republik Rakyat China atau pemastautin di negara di mana embargo dan sekatan Amerika berkuatkuasa, iaitu Iran, Korea Utara, Syria, Sudan, atau Cuba. Maklumat lanjut di dalam Terma Penjualan Token kami.',
      'faq-06-03' : 'Jadi secara ringkas, apakah #TraceChain?',
      'faq-06-04' : '#TraceChain adalah sistem Blockchain untuk generasi seterusnya. Penyelesaiannya adalah berdasarkan kepada algoritma penghalaan belajar sendiri yang berautonomi. Ia mula berfungsi pada kelajuan 50,000 transaksi sesaat (kelajuan asas bagi saluran 100 Mb/s) dan meningkat dengan menambah bilangan saluran berkelajuan tinggi yang munasabah. Saluran ini membentuk teras rangkaian #MetaHash dan menjadikan kerjanya stabil.',
      'faq-06-05' : '"Hard cap" / "soft cap"?',
      'faq-06-06' : '"Soft cap" dicapai melalui Pusingan Pengasas dan Pusingan Persendirian. "Hard cap" tidak ditentukan.',
      'faq-06-07' : 'Saya telah mendepositkan 0.0067769 BTC/ETH, bilakah ia akan ditukar menjadi token #MHC?',
      'faq-06-08' : "Token akan diberikan kepada anda selepas enam pengesahan pada rangkaian Ethereum dan nod #MetaChains diterima. Kami biasanya memberikan 6 jam untuk mengesahkan transaksi daripada rangkaian ETH dan BTC. Jangan risau jika anda tidak menerima duit syiling anda dalam masa 6 jam. Hantarkan laporan kepada kami dan kami akan selesaikan masalah anda. Deposit anda adalah transaksi itu sendiri. Sekiranya transaksi telah berlaku, duit syiling akan dihantar kepada anda.",
      'faq-06-09' : 'Apakah tarikh rasmi Pusingan Persendirian, Pusingan A/B ICO dan sebagainya?',
      'faq-06-10' : 'Tarikh rasmi tempoh Pusingan A ICO dan Pusingan B ICO belum ditentukan lagi. Tarikh tersebut akan diumumkan melalui saluran awam kami tidak lama lagi. Jangan ke mana-mana, dan anda akan menjadi orang pertama yang tahu.',
      'faq-06-11' : 'Adakah #MetaHash suatu garpu ("fork") BTC atau ETH?',
      'faq-06-12' : '#MetaHash bukan sejenis garpu. Ia adalah penyedia blokchain bebas yang lebih pantas dan lebih selamat.',


      'support-01' : 'Ada soalan? Hubungi kami!',
      'support-02' : 'Hantar',
      'support-03' : 'User question',
      'support-04' : 'Masukkan nama anda',
      'support-05' : 'Masukkan e-mel anda',
      'support-06' : 'Soalan anda',


      'prefooter-01' : 'Sertai perjalanan!',
      'prefooter-02' : '#MetaHashTeam',
      'prefooter-03' : '<a href="#private-round" class="btn -default">Beli #MHC<i class="icon icon_link"></i></a>',
      'prefooter-04' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Muat turun Kertas Putih<i class="icon icon_dowload"></i></a>',
      'prefooter-05' : '<a href="docs/MetaHash_OnePager_MS.pdf" target="_blank" class="btn -download">Muat turun Helaian Tunggal<i class="icon icon_dowload"></i></a>',
      'prefooter-06' : 'Mengambil bahagian dalam Pusingan A ICO Bermula',
      'prefooter-07' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="btn -download">Kertas Putih</a>',
      'prefooter-08' : '<a href="docs/MetaHash_OnePager_MS.pdf" target="_blank" class="btn -download float-right">Helaian Tunggal</a>',


      'footer-01' : 'Apakah #MetaHash?',
      'footer-02' : 'Beli #MetaHashCoin (#MHC)',
      'footer-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -footer-link">Kertas Putih</a>',
      'footer-04' : '<a href="docs/MetaHash_OnePager_MS.pdf" target="_blank" class="link -footer-link">Helaian Tunggal</a>',
      'footer-05' : 'Soalan Lazim',
      'footer-06' : '<a href="docs/MetaHash_TermsOfUse_EN.pdf" target="_blank" class="link -footer-link">Terma Penggunaan</a>',
      'footer-07' : '<a href="docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank" class="link -footer-link">Dasar Privasi</a>',
      'footer-08' : '<a href="docs/MetaHash_AntiSpam_EN.pdf" target="_blank" class="link -footer-link">Dasar Anti-Spam</a>',
      'footer-09' : 'Perjanjian Penasihat',
      'footer-10' : '<a href="docs/MetaHash_RiskDisclosureStatement_EN.pdf" target="_blank" class="link -footer-link">Perjanjian Pendedahan Risiko</a>',
      'footer-11' : 'Rangkaian sosial dan mesej',
      'footer-12' : 'Forum',
      'footer-13' : 'Maklum balas di <a href="mailto:hello@metahash.org" class="link -link-small">hello@metahash.org</a>',
      'footer-14' : 'Sokongan di <a href="mailto:support@metahash.org" class="link -link-small">support@metahash.org</a>',
	  'footer-15' : 'Pertanyaan akhbar <a href="mailto:support@metahash.org" class="link -link-small">press@metahash.org</a>',
      'footer-16' : 'Pejabat akhbar <a class="link -link-small">+7 926 671-67-08</a>',	  	  
	  'copyright' : 'Hak Cipta © 2017-2018 #MetaHash. Hak Cipta Terpelihara',


      'mobile-menu-01' : '<a href="#whatis" class="link -link-white">Apakah #MetaHash?</a>',
      'mobile-menu-02' : '<a href="#private-round" class="link -link-white">Beli #MetaHashCoin (#MHC)</a>',
      'mobile-menu-03' : '<a href="docs/MetaHash_WhitePaper_EN.pdf" target="_blank" class="link -link-white">Muat turun Kertas Putih</a>',
      'mobile-menu-04' : '<a href="docs/MetaHash_OnePager_MS.pdf" target="_blank" class="link -link-white">Muat turun Helaian Tunggal</a>',
      'mobile-menu-05' : '<a href="#faq" class="link -link-white">SOALAN LAZIM</a>',
      'mobile-menu-06' : '<a href="#support" class="link -link-white">Sokongan</a>',
      'mobile-menu-07' : '<a href="#support" class="link -link-white">Hubungi</a>',

	  'new-mobile-menu-01' : '<a href="#whatis" class="link -link-white --offcan">Apakah #MetaHash?</a>',
	  'new-mobile-menu-02' : '<a href="#tracechain" class="link -link-white --offcan">#TraceChain</a>',
	  'new-mobile-menu-03' : '<a href="#metaapps" class="link -link-white --offcan">#MetaApps</a>',
	  'new-mobile-menu-04' : '<a href="#metagate" class="link -link-white --offcan">#MetaGate</a>',
	  'new-mobile-menu-05' : '<a href="#timemap" class="link -link-white --offcan">Roadmap</a>',
	  'new-mobile-menu-06' : '<a href="#advisors-and-consultants" class="link -link-white --offcan">Advisors & Consultants</a>',
	  'new-mobile-menu-07' : '<a href="#teambanner" class="link -link-white --offcan">The Team</a>',
	  'new-mobile-menu-08' : '<a href="#ico" class="link -link-white --offcan">Pusingan A ICO</a>',
	  'new-mobile-menu-09' : '<a href="#faq" class="link -link-white --offcan">SOALAN LAZIM</a>',
	  'new-mobile-menu-10' : '<a href="#support" class="link -link-white --offcan">Hubungi kami</a>',


      'promo-soc-01' : '<a href="https://t.me/metahash_ENG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
      'promo-soc-02' : '<a href="https://www.facebook.com/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
      'promo-soc-03' : '<a href="https://vk.com/metahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
      'promo-soc-04' : '<a href="https://twitter.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
      'promo-soc-05' : '<a href="https://instagram.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
      'promo-soc-06' : '<a href="https://www.youtube.com/channel/UCIkBIrd1q7JkLLj43KgG8zA" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">youtube.com</span><span class="icon -icon-big icon_youtube"></span></a>',
      'promo-soc-07' : '<a href="#" class="link-soc -tooltype"><span class="soc-tooltype">ID:MetaHash</span><span class="icon -icon-big icon_wechat"></span></a>',
      'promo-soc-08' : '<a href="https://open.kakao.com/o/gY5dUgG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">talk.com</span><span class="icon -icon-big icon_talk"></span></a>',
      'promo-soc-09' : '<a href="https://github.com/metahashorg" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
      'promo-soc-10' : '<a href="https://www.reddit.com/user/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">reddit.com</span><span class="icon -icon-big icon_reddit"></span></a>',
      'promo-soc-11' : '<a href="https://www.linkedin.com/company/27209614/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">in.com</span><span class="icon -icon-big icon_in"></span></a>',
      'promo-soc-12' : '<a href="https://medium.com/@themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">medium.com</span><span class="icon -icon-big icon_medium"></span></a>',
      'promo-soc-13' : '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitsmedia"></span></a>',
      'promo-soc-14' : '<a href="https://bitcointalk.org/index.php?action=profile;u=1253602" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',


      'promo-soc-mobile-01' : '<a href="https://t.me/metahash_ENG" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">telegram</span><span class="icon -icon-big icon_telegram2"></span></a>',
      'promo-soc-mobile-02' : '<a href="https://www.facebook.com/MetaHash/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">facebook.com</span><span class="icon -icon-big icon_fb"></span></a>',
      'promo-soc-mobile-03' : '<a href="https://vk.com/metahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">vk.com</span><span class="icon -icon-big icon_vk"></span></a>',
      'promo-soc-mobile-04' : '<a href="https://twitter.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">twitter.com</span><span class="icon -icon-big icon_twitter"></span></a>',
      'promo-soc-mobile-05' : '<a href="https://instagram.com/themetahash" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">instagram.com</span><span class="icon -icon-big icon_inst"></span></a>',
      'promo-soc-mobile-06' : '<a href="https://github.com/metahashorg" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">github.com</span><span class="icon -icon-big icon_github"></span></a>',
      'promo-soc-mobile-07' : '<a href="https://www.linkedin.com/company/27209614/" class="link-soc -tooltype" target="_blank"><span class="soc-tooltype">in.com</span><span class="icon -icon-big icon_in"></span></a>',
      'promo-soc-mobile-08' : '<a href="https://forum.bits.media/index.php?/profile/112748-metahash/" class="link-soc"><span class="icon -icon-big --icon-forum icon_bitsmedia" target="_blank"></span></a>',
      'promo-soc-mobile-09' : '<a href="https://bitcointalk.org/index.php?action=profile;u=1253602" class="link-soc" target="_blank"><span class="icon -icon-big --icon-forum icon_bitcointalk"></span></a>',

      'tg_button' : '<a href="https://t.me/metahash_ENG" target="_blank"><img class="telega-svg" style="margin-bottom: 40px;" src="img/telegram.svg" alt=""></a>',



      'private-close-01' : 'Pusingan Persendirian ditutup',
      'private-close-02' : 'Tamat setelah terlebih langgan sebanyak 20x lebih',
      'private-close-03' : 'Kami ingin mengucapkan terima kasih kepada semua peserta dan menjemput semua orang untuk menyertai kami untuk Pusingan A ICO.',
      'private-close-04' : 'Pusingan A ICO',
      'private-close-05' : 'bulan permulaan yang dijadualkan',
      'private-close-06' : 'Pusingan A ICO akan tiba tidak lama lagi',
      'private-close-07' : 'Jangan terlepas permulaannya, mohon sekarang<br class="mobile-br"> untuk mengambil bahagian atau menyertai pasukan kami',
      'private-close-08' : 'Daftar sekarang <i class="icon icon_link"></i>',
      'private-close-09' : 'Ikuti kami:',
      'private-close-10' : 'Ciri-ciri Pusingan A ICO: ',
      'private-close-11' : '<b class="mob-bold">9,200,000 #MHC</b> akan diagihkan semasa Pusingan A ICO',
      'private-close-12' : 'Nilai #MHC untuk Pusingan A ICO adalah <b class="mob-bold">0.0125 ETH</b>',
      'private-close-13' : 'Pesanan <b class="mob-bold">di bawah 50 ETH</b> (12,500 #MHC) diisi daripada kolam terhad umum yang diperbaharui pada setiap 4 jam. <b class="mob-bold">Siapa cepat, dia dapat.</b>',
      'private-close-14' : 'Bagi ruang untuk pembeli kecil-kecilan, <b class="mob-bold">pesanan melebihi 50 ETH</b> diisi daripada kolam simpanan  berasingan dengan serta-merta',
      'private-close-15' : '04/2018',
      'private-close-16' : 'Masukkan e-mel anda',
      'private-close-17' : 'boleh diubah mengikut<br> kepada Kertas Putih', 
      // 'private-close-18' : '<input id="private-close__terms-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__terms-check">I agree to </label><a href="docs/MetaHash_TermsOfUse_EN.pdf" target="_blank">Terms of Use</a>',
      // 'private-close-19' : '<input id="private-close__policy-check" type="checkbox" class="private-close__agree-inp"><label for="private-close__policy-check">I agree to </label><a href="docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank">Privacy Policy</a> ',
      

      'private-close-18' : 'Saya bersetuju untuk ',
      'private-close-19' : 'Saya bersetuju untuk ',
      'private-close-25' : '<a href="docs/MetaHash_TermsOfUse_EN.pdf"  target="_blank">Terma Penggunaan</a>',
      'private-close-26' : '<a href="docs/MetaHash_PrivacyPolicy_EN.pdf" target="_blank">Dasar Privasi</a>',



      'private-close-20' : 'Application submitted',
      'private-close-21' : ', thank you for your interest in <b>#MetaHash</b> project. We will keep you informed about the <b>ICO Round A Start date</b>.',
      'private-close-22' : 'Dont miss a thing!',
      'private-close-23' : '<a href="https://t.me/metahash_ENG" target="_blank"  class="private-close__modal-content_tg-link" >Join our Telegram Channel<br> and stay updated</a>',
      'private-close-24' : '<a href="https://t.me/metahash_ENG" target="_blank" class="support-window__social-block_soc-link support-window__social-block_soc-link_tg"><img class="support-window__social-block_soc-img" src="img/popup/sub-tg.png" alt=""><span class="flag"><img class="support-window__social-block_flag-img" src="img/icons/flag-eng.png"></span></a>',



      
};